### ISSUE TITLE
Custom mime.types ignored on Debian

### ISSUE THREAD

**Issue by michela** [Kludex/uvicorn#1007]
uvicorn ignoring /etc/mime.types on Debian

### To reproduce

Add new mime type to /etc/mime.types

e.g.
text/vtt                                        vtt

Serve test.vtt file  via unicorn

Header shows mime type set to application/octet-stream

-->

### Expected behavior

Headers include
 'Content-Type': 'text/vtt' 

### Actual behavior

Headers include
'Content-Type': 'application/octet-stream'

Testing via python on same host returns correct mime type

```
>>> import mimetypes
>>> mimetypes.guess_type("test.vtt")
('text/vtt', None)
```

**Comment by euri10** [comment]
feel free to reopen with the template filled, thanks
