### ISSUE TITLE
use --uds sock error

### ISSUE THREAD

**Issue by panla** [Kludex/uvicorn#1008]
if this, it is right, Uvicorn running on unix socket ./tmp/p.sock

```bash
uvicorn --uds=./tmp/p.sock asgi:app
```

if this, it`s not right, Uvicorn running on http://127.0.0.1:8000

```bash
uvicorn --uds=./tmp/p.sock  --workers=4 asgi:app
or
uvicorn --uds=./tmp/p.sock  --reload asgi:app
or 
uvicorn --uds=./tmp/p.sock  --log-level=debug asgi:app
```

how to use these params right??

if my issue is error, please close it.

**Comment by euri10** [comment]
duplicates https://github.com/encode/uvicorn/issues/428
