### ISSUE TITLE
uvicorn.run() makes a shell program not killable by CTRL+C

### ISSUE THREAD

**Issue by max-l** [Kludex/uvicorn#1010]
I'm developing a command line tool that hosts a uvicorn server, and it would be very convenient to terminate the process with CTRL+C.

For some reason, launching a sevter causes the program to not properly terminate on CTRL+X.

I need to kill it by sending a "kill -9" to the process in order to free the terminal.

======================= 
I'm using uvicorn as an embeded server within a command line tool, and 
```
INFO:     Started server process [2120330]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
^CINFO:     Shutting down
INFO:     Finished server process [2120330]
```
======================= 

Although the log says the server process is terminated, the programm is still stuck, and needs a kill -9 to terminate

**Comment by soumojit** [comment]
@max-l

If i understand correctly, when you press CTRL+C you want both the process running uvicorn and the process of your command line tool to terminate? 

Could you please clarify what is happening when you are pressing CTRL+X, is the uvicorn process still running or is the uvicorn process terminating but your command line tool is not?

**Comment by jkklapp** [comment]
What signal do you have associated with the shortcut `Ctrl-X`?

The keybindings in my workstation look like

```shell
$ stty -e
...
discard dsusp   eof     eol     eol2    erase   intr    kill    lnext
^O      ^Y      ^D      <undef> <undef> ^?      ^C      ^U      ^V
min     quit    reprint start   status  stop    susp    time    werase
1       ^\      ^R      ^Q      ^T      ^S      ^Z      0       ^W
```
It would be useful to know what signal you're sending with that shortcut @max-l 

From [the manual](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html), `Ctrl-c` sends a `SIGTERM` signal which can be **ignored**.

Is `uvicorn` perhaps ignoring the request to _politely ask a program to terminate_?

**Comment by euri10** [comment]
HI @max-l we have an issue that  is tracking the signals but more in the context of multiprocessing (https://github.com/encode/uvicorn/issues/852), I dont think it's the one you're facing but may find some ideas in the PR that tries to solve it.

In any case without seeing how your main program is calling uvicorn and/or handling signals it's hard to tell if that should be our concern or not, I'd be tempted that it is yours, feel free to repoen with actionable info !
