### ISSUE TITLE
Enable syntax highlighting in code blocks in documentation

### ISSUE THREAD

**Issue by johnthagen** [Kludex/uvicorn#1020]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

I would suggest enabling Code Block Highlighting in the Material for MkDocs configuration: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlight

This would make code blocks such as these easier to read in the docs: 

<img width="800" alt="Screen Shot 2021-04-21 at 10 24 13 AM" src="https://user-images.githubusercontent.com/10340167/115570023-c5588a00-a28b-11eb-9aa0-0c338feaf9c5.png">

**Comment by Kludex** [comment]
I guess... https://github.com/encode/uvicorn/pull/973 ?

**Comment by johnthagen** [comment]
According to the docs, CodeHilite has been superseded. Perhaps that is why the colors are not working.

Perhaps we should try:

```yaml
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
 ```

**Comment by Kludex** [comment]
Could we have avoided this by pinning mkdocs?
