### ISSUE TITLE
Missing user feedback if no ws-library has been installed - with httptools installed

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [Kludex/uvicorn#1022]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

#797 still persists with `httptools` installed in the environment.

### To reproduce

1. ```pip install uvicorn httptools fastapi```
2. Create a simple app
```python
from fastapi import FastAPI, WebSocket

app = FastAPI()

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    ...
``` 
3. Open a web-socket connection.
```js
new WebSocket(`ws://localhost:8000/ws`)
```

### Expected behavior

Proper user feedback if no ws-supported library has been installed.

### Actual behavior

```
INFO:     Started server process [19637]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
WARNING:  Unsupported upgrade request.
^C
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [19637]
```

### Environment

- Running uvicorn (master) with CPython 3.9.0 on Linux
- `uvicorn main:app`

```
fastapi==0.63.0
h11==0.12.0
httptools==0.2.0
```

### Additional context
#926 Fixes #797 for `h11`

**Comment by euri10** [comment]
are you sure you tested on master, it seems to me that the fix has been merged but we did not released it yet ? can you confirm please ?

**Comment by Vibhu-Agarwal** [comment]
@euri10 I can confirm that I've tested it on master.
Here are my test files: https://github.com/Vibhu-Agarwal/uvicorn/tree/test_issue_1022/test_uvicorn_issue_1022

**Comment by euri10** [comment]
funny how the discussion in https://github.com/encode/uvicorn/pull/926 resolved around the fact users would either do one of the 2 things we advertise for installation, which is now clearly not the case I just got it.
