### ISSUE TITLE
Clarify the benefits of Cython-based dependencies

### ISSUE THREAD

**Issue by johnthagen** [Kludex/uvicorn#1025]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

Could some extra wording about *why* a user should use `pip install uvicorn[standard]` as it relates to the Cython-based dependencies? For example, are `uvloop` and `httptools` *faster* than the default pure-Python install? Are they more suitable for production?

I think one or two more sentences here could be very useful for new users. I'm happy to open a PR if someone on the team can provide the correct statement.

**Comment by euri10** [comment]
PR welcomed !

**Comment by johnthagen** [comment]
I'd be happy to submit a PR if one of the maintainers could add some discussion in the issue here. I don't actually know what the answer is yet.

**Comment by euri10** [comment]
It effectively comes down to the parsing that is faster

**Comment by euri10** [comment]
maybe a link to uvloop and / or httptools should suffice
