### ISSUE TITLE
docker-compose+gunicorn+uvicorn keeps booting workers

### ISSUE THREAD

**Issue by dwdewang** [Kludex/uvicorn#1031]
Hi, I use docker-compose to delpoy my application
docker-compose config like the picture
![image](https://user-images.githubusercontent.com/11647289/117235648-b19b4f00-ae59-11eb-89f7-dee1065ea520.png)
If I use uvicorn.workers.UvicornWorker worker class  
when docker-compos up 
gunicorn will keeps bootings workers and never stop
![image](https://user-images.githubusercontent.com/11647289/117235743-e0b1c080-ae59-11eb-87a3-c447a9620a4c.png)
If I replace the worker class to gevent, problem disappear
I have search a lot for the answer, but none work,
thanks for all your helping

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/1031">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/1031/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/1031/pledge.svg">
</picture>
</a>

**Comment by bongster** [comment]
Can i ask something? so with gevent + django asgi is working fine?

**Comment by dwdewang** [comment]
> Can i ask something? so with gevent + django asgi is working fine?

@bongster
gevent + django asgi working fine

problem only appears when I use gunicorn+uvicorn

**Comment by bongster** [comment]
@dewang

which version of `asgiref` are used in your project? 
cuz when i find a hanging issue in asgiref 3.3.0 so i downgrade our asgiref version from 3.3.1 to 3.2.10 and 
i set a worker-tmp-dir argument in my gunicorn. 

after that in my project, i don't got an any problems.

```
gunicorn --bind 0.0.0.0:8001 -w 4 -k uvicorn.workers.UvicornH11Worker --worker-tmp-dir /dev/shm 
```

**Comment by dwdewang** [comment]
> uvicorn.workers.UvicornH11Worker
it doesn't work 
I change asgiref into 3.3.1 version, but problem still happens
my worker class is uvicorn.workers.UvicornWorker not uvicorn.workers.UvicornH11Worker
![image](https://user-images.githubusercontent.com/11647289/117530160-38912880-b00e-11eb-8f9f-140acb18694e.png)
![image](https://user-images.githubusercontent.com/11647289/117530165-3cbd4600-b00e-11eb-8fc4-c929f93fe87b.png)
@bongster

**Comment by dwdewang** [comment]
> @dewang
> 
> which version of `asgiref` are used in your project?
> cuz when i find a hanging issue in asgiref 3.3.0 so i downgrade our asgiref version from 3.3.1 to 3.2.10 and
> i set a worker-tmp-dir argument in my gunicorn.
> 
> after that in my project, i don't got an any problems.
> 
> ```
> gunicorn --bind 0.0.0.0:8001 -w 4 -k uvicorn.workers.UvicornH11Worker --worker-tmp-dir /dev/shm 
> ```

I change asgiref into 3.2.10 version and set a worker-tmp-dir argument, but problem still happens
my worker class is uvicorn.workers.UvicornWorker not uvicorn.workers.UvicornH11Worker
![image](https://user-images.githubusercontent.com/11647289/117530160-38912880-b00e-11eb-8f9f-140acb18694e.png)
![image](https://user-images.githubusercontent.com/11647289/117530351-47c4a600-b00f-11eb-8af8-41fc4d4f7c55.png)

do you run gunicorn in docker-compose?
@bongster

**Comment by bongster** [comment]
@dewang Yes i running gunicorn in my docker-compose. could you possible to used `/dev/shm` value in worker-tmp-dir instead of `/var/proj/tmp` ? 
and then i also set `DJANGO_ALLOW_ASYNC_UNSAFE ` environment in my project.

<img width="1015" alt="Screen Shot 2021-05-08 at 10 48 07 PM" src="https://user-images.githubusercontent.com/2687920/117543440-77939e00-b04f-11eb-9b68-6cf1b6dc633d.png">

**Comment by dewang** [comment]
@bongster could you please tag the correct user @dwdewang . You're using my username and spamming me :unamused:

**Comment by bongster** [comment]
> @bongster could you please tag the correct user @dwdewang . You're using my username and spamming me 😒

@dewang i'm so sorry to bothering you :(

**Comment by dwdewang** [comment]
> @dewang Yes i running gunicorn in my docker-compose. could you possible to used `/dev/shm` value in worker-tmp-dir instead of `/var/proj/tmp` ?
> and then i also set `DJANGO_ALLOW_ASYNC_UNSAFE ` environment in my project.
> 
> <img alt="Screen Shot 2021-05-08 at 10 48 07 PM" width="1015" src="https://user-images.githubusercontent.com/2687920/117543440-77939e00-b04f-11eb-9b68-6cf1b6dc633d.png">

@bongster I set what you said, but problem still appears.
gunicorn still keeps booting wokeres nerver stop

**Comment by dwdewang** [comment]
@bongster  If I use UvicornH11Worker worker class ,problem solve. but my python is Cpython ,not pypy, I need to use UvicornWorker

**Comment by bongster** [comment]
> @bongster If I use UvicornH11Worker worker class ,problem solve. but my python is Cpython ,not pypy, I need to use UvicornWorker

@dwdewang  Then i thought then you need to checking your uvicorn dependency in `UvicornWorker ` what kind of lib do you need to installed for used UvicornWorker.

**Comment by dwdewang** [comment]
> > @bongster If I use UvicornH11Worker worker class ,problem solve. but my python is Cpython ,not pypy, I need to use UvicornWorker
> 
> @dwdewang Then i thought then you need to checking your uvicorn dependency in `UvicornWorker ` what kind of lib do you need to installed for used UvicornWorker.

@bongster 
OK, I will check my environment and installed packages in detail. Thanks!

**Comment by euri10** [comment]
seems similar to this https://github.com/tiangolo/fastapi/issues/253
feel free to reopen if answers there dont help, in current state nothing tells me it's an issue on uvicorn's side

**Comment by fanchunke** [comment]
Hi, I have the same issues  when deploy FastAPI using gunicorn + uvicorn，it keeps booting workers when exceptions raised at startup events.

**main.py**

```python
from fastapi import FastAPI

app = FastAPI()


@app.on_event("startup")
async def startup():
    raise Exception("error")


@app.get("/")
async def hello():
    return {"msg": "hello world"}
```

**gunicorn.conf.py**

```python
import json
import os

worker_class = "uvicorn.workers.UvicornWorker"

host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "8000")
bind_env = os.getenv("BIND", None)
use_loglevel = os.getenv("LOG_LEVEL", "info")
if bind_env:
    use_bind = bind_env
else:
    use_bind = f"{host}:{port}"


accesslog_var = os.getenv("ACCESS_LOG", "-")
use_accesslog = accesslog_var or None
errorlog_var = os.getenv("ERROR_LOG", "-")
use_errorlog = errorlog_var or None
graceful_timeout_str = os.getenv("GRACEFUL_TIMEOUT", "120")
timeout_str = os.getenv("TIMEOUT", "120")
keepalive_str = os.getenv("KEEP_ALIVE", "5")

# Gunicorn config variables
loglevel = use_loglevel
bind = use_bind
errorlog = use_errorlog
accesslog = use_accesslog
graceful_timeout = int(graceful_timeout_str)
timeout = int(timeout_str)
keepalive = int(keepalive_str)

# For debugging and testing
log_data = {
    "loglevel": loglevel,
    "bind": bind,
    "graceful_timeout": graceful_timeout,
    "timeout": timeout,
    "keepalive": keepalive,
    "errorlog": errorlog,
    "accesslog": accesslog,
}
print(json.dumps(log_data))
```

**gunicorn log**

```text
{"loglevel": "info", "bind": "0.0.0.0:8000", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "host": "0.0.0.0", "port": "8000"}
[2021-06-01 21:13:05 +0800] [40946] [INFO] Starting gunicorn 20.0.4
[2021-06-01 21:13:05 +0800] [40946] [INFO] Listening at: http://0.0.0.0:8000 (40946)
[2021-06-01 21:13:05 +0800] [40946] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-06-01 21:13:05 +0800] [40949] [INFO] Booting worker with pid: 40949
[2021-06-01 21:13:05 +0800] [40949] [INFO] Started server process [40949]
[2021-06-01 21:13:05 +0800] [40949] [INFO] Waiting for application startup.
[2021-06-01 21:13:05 +0800] [40949] [ERROR] Traceback (most recent call last):
  File "./envs/test/lib/python3.7/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "./envs/test/lib/python3.7/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "./envs/test/lib/python3.7/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "./app/main.py", line 16, in startup
    raise Exception("error")
Exception: error

[2021-06-01 21:13:05 +0800] [40949] [ERROR] Application startup failed. Exiting.
[2021-06-01 21:13:05 +0800] [40949] [INFO] Worker exiting (pid: 40949)
[2021-06-01 21:13:05 +0800] [40950] [INFO] Booting worker with pid: 40950
[2021-06-01 21:13:06 +0800] [40950] [INFO] Started server process [40950]
[2021-06-01 21:13:06 +0800] [40950] [INFO] Waiting for application startup.
[2021-06-01 21:13:06 +0800] [40950] [ERROR] Traceback (most recent call last):
  File "./envs/test/lib/python3.7/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "./envs/test/lib/python3.7/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "./envs/test/lib/python3.7/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "./app/main.py", line 16, in startup
    raise Exception("error")
Exception: error

[2021-06-01 21:13:06 +0800] [40950] [ERROR] Application startup failed. Exiting.
```

I hope the gunicorn would exit when exceptions raised, but it keeps booting workers. Can someone helps me, thanks?
