### ISSUE TITLE
Add a option to disable watchgod monitor

### ISSUE THREAD

**Issue by mnixry** [Kludex/uvicorn#1032]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

In the `uvicorn [standard]` package, uvicorn relies on watchgod to handle the reload function. 
However, `watchgod` still has many problems in actual situations. Even if the `reload-dirs` option is used, these problems cannot be completely resolved.

## Describe the solution you would like.

I think uvicorn can add an option (for example: `disable-watchgod`) to simply disable watchgod reloading to use statreload, just like what happens when watchgod is not installed

**Comment by synodriver** [comment]
Sounds like a upstream issue.

**Comment by Kludex** [comment]
You didn't describe the problem :sweat_smile: 

> However, watchgod still has many problems in actual situations.

What are the problems?
