### ISSUE TITLE
No poetry version solving for uvicorn if used with click 

### ISSUE THREAD

**Issue by epogrebnyak** [Kludex/uvicorn#1040]
I'm trying to install `uvicorn` with Poetry and I'm getting kind of a circular import error after `poetry add uvicorn`:

```
  Because uvicorn (0.13.4) depends on click (>=7.0.0,<8.0.0)
   and no versions of uvicorn match >0.13.4,<0.14.0, uvicorn (>=0.13.4,<0.14.0) requires click (>=7.0.0,<8.0.0).
  So, because rider depends on both click (^8.0.0) and uvicorn (^0.13.4), version solving failed.
```

**Comment by epogrebnyak** [comment]
Any ideas on how to resolve highly appreciated

**Comment by szeleeteo** [comment]
I've also raised an [issue](https://github.com/encode/uvicorn/issues/1016) earlier requesting to relax to upper bound
and there is also a pending [PR](https://github.com/encode/uvicorn/pull/1033) on this.

**Comment by epogrebnyak** [comment]
@szeleeteo - thank for the PR link on click side! Do you think anything can be done before the PR is merged?

**Comment by euri10** [comment]
closing in favor of #1016
