### ISSUE TITLE
Run uvicorn programmatically with `reload=True` not in if-name-main block print irrelated error message

### ISSUE THREAD

**Issue by TLDay** [Kludex/uvicorn#1045]
### Checklist

- The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When you run uvicorn programmatically, `if __name__ ==  '__main__'` block is required if you put `reload=True` as parameter to `uvicorn.run` function. Or you will got
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [$PID] using watchgod
ERROR:    [Errno 48] Address already in use
```
I checked all tcp ports in __LISTEN__ status, 8000 port is free to use and all processes I can recognize them.(They are not zombie _watchgod_ process or something like that).

Using command like `uvicorn --reload app:app` works perfectly in same project.

Put entry code into if-name-main block solved the problem.

Sorry of my poor English, I'm not a native speaker.😅

### To reproduce

* app.py
```
import fastapi
app = fastapi.FastAPI()
```

* dev.py
```
import uvicorn
uvicorn.run('app:app', reload=True)
```

run `python dev.py` will print error message said `Address already in use`.

### Expected behavior

__Best__:
Put entry code into if-name-main block is not required.

__Good__:
Print error message or other information to indicate the real problem.

Write warning or note in doc.

### Actual behavior

Print irrelated error message `Address already in use`.

### Debugging material

```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [$PID] using watchgod
ERROR:    [Errno 48] Address already in use
```

### Environment

- OS / Python / Uvicorn version: MacOS 11.3.1 / Python 3.9.5 / uvicorn 0.13.4

**Comment by euri10** [comment]
if I do `python dev.py` I have this error which is quite explicit about multiprocessing, since we dont use fork but spawn (see https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

so indeed you have to use the `__main__` block if you want to run uvicorn 
However I'm unable to reproduce your `Address already in use` message, probably a difference in os, can someone on a mac see if he can ?

**Comment by TLDay** [comment]
I tested the demo on my linux server (CentOS 7). Error message is same to yours.
Seems `Address already in use` only occured in MacOS. (Need someone to confirm)
BTW, my Mac is based on Intel CPU. And I can reproduce `Address already in use` message in clean 3.8/3.9 virtual env.

**Comment by euri10** [comment]
so it seems like it's indeed a macos issue, cant personnally help more on this but I agree the message in this case is not helpful at all.
Being not in a position to debug that, I'd say the most sensible thing for us to do is to add a warning in the docs about that : thoughts ?

**Comment by TLDay** [comment]
I think this issue is likely caused by same reason with https://github.com/encode/uvicorn/issues/949.
IMO, write something in doc to point `the proper idiom in the main module` is required while using some options like 'debug/reload' is not a bad thing anyway.

**Comment by euri10** [comment]
> I think this issue is likely caused by same reason with #949.
> IMO, write something in doc to point `the proper idiom in the main module` is required while using some options like 'debug/reload' is not a bad thing anyway.

ok let's close those 2 issues by adding a warning to the docs, fancy sending a PR @TLDay  ?
