### ISSUE TITLE
"ModuleType object is not callable" warnings from 'importer'-imported modules

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [Kludex/uvicorn#1046]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Importer => `ModuleType`
https://github.com/encode/uvicorn/blob/06fedab6c1da9ee2bfc3cee635fc772a9958a9c6/uvicorn/importer.py#L10
This has raised `'ModuleType' object is not callable` warnings all over, in my IDE (PyCharm).

For example:
- https://github.com/encode/uvicorn/blob/06fedab6c1da9ee2bfc3cee635fc772a9958a9c6/uvicorn/config.py#L319
- https://github.com/encode/uvicorn/blob/06fedab6c1da9ee2bfc3cee635fc772a9958a9c6/uvicorn/config.py#L359-L361
<hr>

- Is this a valid issue? 😕
- Should we switch to `Any` as return type annotation?

**Comment by Kludex** [comment]
I guess it's only because of the type hint of the parameter `import_str` and not the return, right? Does PyCharm uses `mypy` underneath? Removing the `ModuleType` from the parameter solves the issue?

Our source code passes `mypy` (with the constrains on `setup.cfg`), so it doesn't look like an issue on `uvicorn`. :thinking:

**Comment by Vibhu-Agarwal** [comment]
> I guess it's only because of the type hint of the parameter `import_str` and not the return, right?

The type hint of the returning object (`-> ModuleType`), Yes.

> Does PyCharm uses `mypy` underneath?

[I don't think so](https://www.jetbrains.com/help/pycharm/type-hinting-in-product.html) (at least, not by default without mypy plugin)
PS. I've got their default installation installed. No mypy plugins.

> Removing the `ModuleType` from the parameter solves the issue?

Changing it to `def import_from_string(import_str: Union[ModuleType, str]) -> Any:` fixes it.

> Our source code passes `mypy` (with the constrains on `setup.cfg`), so it doesn't look like an issue on `uvicorn`. 🤔

Hmm ... maybe `mypy` doesn't cover this 🤷
But the warnings make sense as _modules_ aren't really _callables_ 🤔
