### ISSUE TITLE
community link is broken

### ISSUE THREAD

**Issue by kokosabu** [Kludex/uvicorn#1058]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I tried to access https://discuss.encode.io/c/uvicorn listed in README.md, but was unable to do so.

### To reproduce

1. open the [README](https://github.com/encode/uvicorn)
2. select https://discuss.encode.io/c/uvicorn listed next to Community

### Expected behavior

community page will open.

### Actual behavior

Unable to access the page.

### Environment

- macOS Big Sur 11.4 / Chrome

**Comment by Kludex** [comment]
Thanks for the report @kokosabu :)

We should follow `starlette` (https://github.com/encode/starlette/pull/1185) and remove that link.
