### ISSUE TITLE
Improve performance of "--log-level info"

### ISSUE THREAD

**Issue by almarklein** [Kludex/uvicorn#112]
I just did some benchmarking to compare Uvicorn with other frameworks. Wow it is fast! And it stays being the fastest (compared to what I tested) (by quite a bit) also for more realistic benchmarks.

Anyway, at some point I initially did not set the log level (so it was at INFO), and the performance of the hello-world benchmark dropped by 50%.

Perhaps it makes sense to get good performance by default, so setting the default log level to WARNING? Although I can see the importance of good logging by default :)  In the latter case, perhaps its a bit too much or slow for some reason?

**Comment by lovelydinosaur** [comment]
Good question!

Two things here: One would be speeding up the logging - there oughts to be lots of room for improvement here. We're just using the standard Python logger, and I'd not thought of making any attempts to optimize things there as I was always just using `--log-level error` when benchmarking.

Other frameworks will do the same when benchmarking too, but it makes sense for us to also optimize (at least a little) for the case where you want super high throughput, and *also* need access logs.

The other question is what we should use for the defaults. Perhaps once we've got a `--debug` flag we could instead default to WARN by standard, and INFO with `--debug`. Alternatively, if optimizing the logger makes the difference small enough then we might just stick with INFO by default, and just document logging options (and implications) more fully.

**Comment by RobertoPrevato** [comment]
One thing that worries me more, is that the built-in logging module was designed much before asyncio. I think it's time for Python community to turn page and work on a new implementation of async-friendly logging classes. Something similar to what .NET community did implementing `Microsoft.Extensions.Logging` namespace and its related assemblies. A modern web framework using asyncio, like uvicorn, should say 'good bye' to built-in logging module from Python, imho.

**Comment by funkybob** [comment]
Now I know what I'm doing at the pyconau sprints...

On 6 July 2018 07:05:20 GMT+10:00, Roberto Prevato <notifications@github.com> wrote:
>One thing that worries me more, is that the built-in logging module was
>designed much before asyncio. I think it's time for Python community to
>turn page and work on a new implementation of async-friendly logging
>classes. Something similar to what .NET community did implementing
>`Microsoft.Extensions.Logging` namespace and its related assemblies. A
>modern web framework using asyncio, like uvicorn, should say 'good bye'
>to built-in logging module from Python, imho.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/encode/uvicorn/issues/112#issuecomment-402852298

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lovelydinosaur** [comment]
I did take a look at this, and the outcome wasn't as clear-cut as expected. (Created a logger than wrote the logs on a seperate thread.) I don't have the results to hand, but my initial indication is that micro-benchmarking lots of JSON responses is easily skewed by the additional time in Python-space that the logging incurs.

**Comment by lovelydinosaur** [comment]
I don't think there's anything for us to do here. The defaults are sensible, it's easy to turn off access logging, and if you're really running at high volumes that'll likely be a sensible thing to do since you'll be generating more information that you're able to usefully deal with if you're just logging every single request.
