### ISSUE TITLE
allow uvicorn.run to also accept app-dir kwarg

### ISSUE THREAD

**Issue by PietroPasotti** [Kludex/uvicorn#1126]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [x] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

The issue is: I have a script using uvicorn.run, but I can only run it from a specific cwd, else it will fail with ImportError.

## Describe the solution you would like.

I would like the --app-dir functionality to be available in uvicorn.run() as well.
I.e.: to be able to run a script containing a call to uvicorn.run regardless of the cwd.

## Describe alternatives you considered

Doing it myself, i.e. calling sys.path.insert(0, abs_path_to_my_project_root_folder), but it feels to me that if this functionality is implemented in main() but not in run() (which from reading the code are the same thing) there must be something wrong with the uvicorn code.

## Additional context

https://github.com/encode/uvicorn/issues/549
https://github.com/encode/uvicorn/pull/619
https://github.com/encode/uvicorn/commit/77468df7697ec2f2962e77d7a02e0bc22b6f9c79

My guess is that this commit implemented the behaviour in the wrong place. Instead of 'consuming' the app_dir argument inside main(), it should have been passed down as-is to run() where it will be processed.

(I volunteer to do the job, if we agree that there is a problem)

**Comment by command-tab** [comment]
Yes, please! I just ran into this trying to run uvicorn programmatically, with a simple directory structure like:
```
manage.py          # contains `uvicorn.run(...)`
app/
    __init__.py    # empty
    main.py        # contains `app = FastAPI(...)`
```

My uvicorn invocation is in `manage.py`, and my `app` callable (a FastAPI instance) is in `main.py`, but I can't find any way to specify that the module path that should be loaded is actually `app.main`. Being able to pass `app_dir='app/'` to `uvicorn.run` would then let me specify `main:app` as the module:callable. Right now, that's impossible as far as I can tell.

**Comment by Kludex** [comment]
PR is already created.

Waiting for reviews.

**Comment by HansBrende** [comment]
@command-tab even without this PR, it is not "impossible", you can also easily do the same thing yourself:

```python
sys.path.append('app')  # or possibly something more absolute like os.path.abspath(os.path.join(__file__, '..', 'app'))
uvicorn.run('main:app')
```
