### ISSUE TITLE
ERROR:    Error loading ASGI app. Could not import module "app.main".

### ISSUE THREAD

**Issue by code-n-cry** [Kludex/uvicorn#1141]
I am trying to start a FastAPI app but error that describing in the title is throwing.
Here is the file structure:
![изображение](https://user-images.githubusercontent.com/61789375/127881637-3415242a-ba95-471a-ae30-d002049cfff4.png)
 and that happens when I am trying to start it:
![изображение](https://user-images.githubusercontent.com/61789375/127881758-4232b789-9357-4ae0-9c24-46b0c2d288c4.png)

**Comment by code-n-cry** [comment]
So I was stupid and didn't read some docs, sorry

**Comment by neilrla** [comment]
Please do tell, what were the some docs that you didn't read, so the rest of us can read them too ?
