### ISSUE TITLE
onShutdown not trigger when shutdown Gunicorn process (Uvicorn worker class)

### ISSUE THREAD

**Issue by sapjunior** [Kludex/uvicorn#1169]
### Describe the bug

onShutdown not trigger when shutdown Gunicorn (Uvicorn worker class)

### To reproduce

```
from fastapi import FastAPI


app = FastAPI()

@app.get('test')
async def tester():
    return  'test'

@app.on_event("startup")
async def onStartup():
    print('on startup trigger')

@app.on_event("shutdown")
async def onShutdown():
    print('on shutdown trigger')

```

Running with command "gunicorn -w 4 -k uvicorn.workers.UvicornWorker test:app -b 0.0.0.0"
### Expected behavior

It should print 'on shutdown trigger' when pressing ctrl+c on Gunicorn 

### Actual behavior

On shutdown event is not trigger

### Environment
All packages install from Conda-forge

Gunicorn 20.1.0
Uvicorn 0.15.0
FastAPI 0.68.0
Python 3.9.6

**Comment by Kludex** [comment]
Duplicated #1116
