### ISSUE TITLE
asgi_send does not send proper close code if connection is closed before accept

### ISSUE THREAD

**Issue by JanLana** [Kludex/uvicorn#1181]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

If `websocket.close` is send without websocket.accept (i.e. `self.handshake_started_event.is_set()` is false and `message_type = 'websocket.close'`), the `WebSocketProtocol.asgi_send()` is called: https://github.com/encode/uvicorn/blob/1d9511f0b9dc73867bbbb38f72dbbdcac5478651/uvicorn/protocols/websockets/websockets_impl.py#L240-L248
The code ignores _code_ and _reason_  message keys.

### To reproduce

```
async def websocket_application(scope, receive, send):
    event = await receive()
    assert event['type'] == 'websocket.connect'

    if somethong_is_wrong:
        await send({'type': 'websocket.close', 'code': 1002, 'reason': 'something is wrong'}) 
        return

async def application(scope, receive, send):                                                                                                                                          
    if scope['type'] == 'websocket':                                                                                                                                                
        await websocket_application(scope, receive, send)
    else:
        raise NotImplementedError(f"Unknown scope type {scope['type']}")
```

### Expected behavior

The websocket client get error code 1002 with reason 'something is wrong'

### Actual behavior

The websocket client get error code 1006 with empty reason.

### Environment

- OS / Python / Uvicorn version: `Running uvicorn 0.15.0 with CPython 3.9.6 on Darwin`-

**Comment by aminalaee** [comment]
I did take a look into this, seems like we can't use the same `close` method we use after the handshake is started.
Not really sure, maybe we need another method here but calling the same `close` doesn't work:

https://github.com/aaugustin/websockets/blob/67b19e6e9ac96722a584e35d7e9dc3a2173af6b8/src/websockets/legacy/protocol.py#L724

Because in `websockets` the `transfer_data_task` is not set up yet.

**Comment by Kludex** [comment]
From the ASGI specification:
> If this is sent before the socket is accepted, the server must close the connection with a HTTP 403 error code (Forbidden), and not complete the WebSocket handshake; this may present on some browsers as a different WebSocket error code (such as 1006, Abnormal Closure).
> 
> If this is sent after the socket is accepted, the server must close the socket with the close code passed in the message (or 1000 if none is specified).

Reference: https://asgi.readthedocs.io/en/latest/specs/www.html#close-send-event
