### ISSUE TITLE
[DOCS] Contribution docs page

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1197]
Similar to https://www.python-httpx.org/contributing/ but addapted to uvicorn.

**Comment by LuluNwenyi** [comment]
Hi @Kludex I'd like to work on this but could you elaborate so I could get more context

**Comment by Kludex** [comment]
Hi @LuluNwenyi ! Thanks for the interest!

There are some things on the httpx page that doesn't make sense for us, like the `Development proxy setup` section.
And on the `Releasing` section, we don't have a `__version__.py`, but we change the version on the `__init__.py`.

Besides, on the `Reporting Bugs or Other Issues` section, on httpx is recommended to open a discussion, and there are some labels, but we don't have here, so I guess on uvicorn the idea would be to first discuss on our Gitter server, and if it makes sense, create an issue here.

The page should be called `contributing.md`, and it should be the last on the docs.

**Comment by LuluNwenyi** [comment]
Alright. I can be assigned to this.'d love to give it a go

**Comment by Kludex** [comment]
Go ahead!
