### ISSUE TITLE
Access uvicorn logger?

### ISSUE THREAD

**Issue by openSourcerer9000** [Kludex/uvicorn#1198]
Is there some function which can log something through the uvicorn logger? Thanks

```
INFO:     Started server process [50388]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8080 (Press CTRL+C to quit)
INFO:     ::1:61681 - "GET /12/958/1702.mvt HTTP/1.1" 404 Not Found
```

### Environment
uvicorn version 0.15.0, ran in vscode programmatically through Starlette

**Comment by Kludex** [comment]
I can print here :thinking: What are the issues you're talking about?

You can also use the uvicorn logger with `logger = getLogger("uvicorn.error")`.

**Comment by openSourcerer9000** [comment]
Great thank you, it turned out the frontend just wasn't formatting the GET requests correctly, so the function I was putting the log statements in wasn't actually getting called
