### ISSUE TITLE
hot reload doesnt work when using the Config class to initialize uvicorn server

### ISSUE THREAD

**Issue by nbraun-wolf** [Kludex/uvicorn#1206]
### Describe the bug

Hi, I am trying to set up logging for a uvicorn/fastapi app. I have followed this [blogpost](https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/). I want to enable hot reload for development, but it isn't used, despite unicorn logging at the beginning that it's watching for file changes.

### To reproduce

```python
from uvicorn import Config, Server

if __name__ == '__main__':
    server = Server(
        Config(
            "my_app.app:app",
            host="0.0.0.0",
            log_level=LOG_LEVEL,
            reload=True
        ),
    )
    
    # do some other things
    server.run()
```

### Expected behaviour

hot reload works when using the reload kwarg in the Config class.

### Actual behaviour

Hot reload does not work.

### Environment

```bash
Running uvicorn 0.15.0 with CPython 3.9.7 on Linux
```
****

**Comment by Kludex** [comment]
The `Server` doesn't care about the `reload` parameter. You can check the `uvicorn.run` implementation here: https://github.com/encode/uvicorn/blob/a9993bdf8dc9601f5339654286b92f1e7dd0f224/uvicorn/main.py#L428-L449

As you can see, the `ChangeReload` is in charge of reloading.

If you check your own link:
![image](https://user-images.githubusercontent.com/7353520/135728580-58725123-d0e4-412f-8085-39e92d95046b.png)

![image](https://user-images.githubusercontent.com/7353520/135728687-c33c5cdd-6eb6-47bb-bd28-ae8148aa5a87.png)

**Comment by nbraun-wolf** [comment]
Ok, cool, I will check that out. 

Still it is kind of misleading to type the server with argument Config and type the Config with argument reload if it's not used. Maybe the typing should be different, or the server should respect all arguments of the config class.

**Comment by nbraun-wolf** [comment]
The posted solution also doesn't seem to solve the problem of why it was initialized that way. When the server creates the app from string, the app may do some things. The intent was to override whatever the app does in its initialization. In this case the logging behaviour. I have actually already tried something similar to what was suggested there on my own term, but then the logging is all messed up.

Even if it would work in this case, it may not work another time. I think ultimately it should be possible to perform some operation between creating the app and starting the server.

**Comment by Kludex** [comment]
> some operation

For example?

**Comment by nbraun-wolf** [comment]
> For example?

Hook into the application object to manipulate it.  For example disable its logger. It wouldn't be too bad if we could pass arguments to the factory function, but as it stands there is no way to adjust the application behaviour from outside. Disabling it inside the factory by default isn't good because you can't know how the factory will be called and therefore anticipate what the caller may or may not has configured. The only option would be maybe to create multiple factories.

**Comment by Kludex** [comment]
I see. I think before taking any further step, we'd want to discuss that on [our Gitter server](https://gitter.im/encode/community). Feel free to propose your idea there.

Furthermore, I'm closing this, as the original issue was clarified, and the current discussion is out of scope.

**Comment by pawamoy** [comment]
OK, that was not easy but I found a solution that correctly configures logging while enabling live-reload. It re-uses content from my blog post:

```python
from uvicorn import Config, Server
from uvicorn.supervisors import ChangeReload

class FixedLoggingConfig(Config):
    """Subclass of uvicorn config that re-configures logging."""

    serialize_logs = False

    def configure_logging(self) -> None:  # noqa: D102
        super().configure_logging()
        setup_logging(self.serialize_logs)


def run(host="0.0.0.0", port=8080, log_level=LOG_LEVEL, json_logs=JSON_LOGS, reload=False):  # noqa: S104
    """Run the Uvicorn server.

    Parameters:
        host: The host to bind.
        port: The port to use.
        log_level: The log level.
        json_logs: Whether to serialize logs in JSON.
        reload: Whether to enable live-reload.
    """
    FixedLoggingConfig.serialize_logs = json_logs
    config = FixedLoggingConfig(
        "package.app:app",
        host=host,
        port=port,
        log_level=log_level,
        reload=reload,
    )
    server = Server(config)
    setup_logging(serialize=json_logs)

    if reload:
        sock = config.bind_socket()
        ChangeReload(config, target=server.run, sockets=[sock]).run()
    else:
        server.run()


if __name__ == "__main__":
    run()
```

**Comment by obrua** [comment]
> 

JSON_LOGS What is the content, can you post it?

**Comment by pawamoy** [comment]
It's a boolean, see [the blog post](https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/) (I'll update it soon to include these contents).
