### ISSUE TITLE
Uvicorn not gracefully shutting down in Docker container

### ISSUE THREAD

**Issue by erl987** [Kludex/uvicorn#1215]
# Checklist

- [x]  The bug is reproducible against the latest release and/or master.
- [x]  There are no similar issues or pull requests to fix it yet.

There are several issues regarding the shutdown of uvicorn  (#1160, #853) but not related to what is reported in this issue.

### Bug version:
Latest version: 0.15.0

### Describe the bug

uvicorn is not gracefully shutting down in a Docker container if it is started in **shell mode** of the CMD command. It shuts down gracefully though in **exec mode**.

#### `main.py`:
```
from fastapi import FastAPI

app = FastAPI()

@app.get('/')
def endpoint():
        return {'result': 'ok'}
```

#### `Dockerfile`:
```
FROM python:3.10.0-slim-bullseye

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn

COPY main.py /app

# shell mode **is not** shutting down gracefully
CMD uvicorn main:app --host 0.0.0.0 --port $PORT

# exec mode **is** shutting down gracefully
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

```

Build with: `docker build -t testing/test .`
Run with: `docker run --rm -p 8000:8000 --env PORT=8000 testing/test`

### Expected behavior

It is expected that the Docker container is shutting down immediately gracefully, either by `docker stop container_name` or by Ctrl + C if running the container interactively in the terminal.

### Actual behavior

The Docker container is not stopped gracefully. Using Ctrl + C seems to have no effect. `docker stop` will finally after a longer timeout kill the container hard. If using exec mode, uvicorn behaves correctly.

### Debugging material

Not available.

### Environment

Docker version 20.10.6, build 370c289

### Additional context

The problem with this issue is that it prevents providing the actual port to the container at runtime (as an environment variable). The only working exec mode of the CMD command cannot resolve environment variables. This makes usage of the container on cloud platforms such as Google Cloud Run problematic.

**Comment by Kludex** [comment]
This is not a `uvicorn` issue.

The process is not receiving the signals from docker. Read the article for more info: https://hynek.me/articles/docker-signals/

You can verify yourself with the following as well:

```python
# main.py
while True:
    print("Not a uvicorn issue")
```
```
# Dockerfile
FROM python:3.10.0-slim-bullseye

WORKDIR /app

COPY main.py /app

CMD python main.py
```
