### ISSUE TITLE
Is there a reason for overriding the default asyncio policy on Windows?

### ISSUE THREAD

**Issue by polys** [Kludex/uvicorn#1220]
### Checklist

- [ ] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

While developing on Windows, my app being served by `uvicorn` keeps raising `ValueError: too many file descriptors in select()`, which I understand is related to the suboptimal `asyncio.WindowsSelectorEventLoopPolicy`.

[Python 3.8 changed the default to `ProactorEventLoop` on Windows](https://docs.python.org/3/library/asyncio-policy.html#asyncio.DefaultEventLoopPolicy) but [your code seems to override this](https://github.com/encode/uvicorn/blob/master/uvicorn/loops/asyncio.py#L6-L7).

Is there a reason for this?

## Describe the solution you would like.

Ideally, all the `too many file descriptors in select()` exceptions go away.

## Additional context

This isn't an issue at all when running my app in a Linux container.

**Comment by sekrause** [comment]
Looking at the commit history the `ProactorEventLoop` was disabled to fix issue #529.

It probably wasn't understood that using `SelectorEventLoop` basically makes uvicorn completely useless for scalable applications on Windows because you will be limited to only 512 socket connections: https://docs.python.org/3.10/library/asyncio-platforms.html#windows

So simply disabling the `ProactorEventLoop` (the only scalable event loop on Windows) is generally not a good idea.

**Comment by sekrause** [comment]
@polys For now you can work around this issue by starting uvicorn programmatically in your own loop, for example this will give you a `ProactorEventLoop` in Python >= 3.8:

```python
from asyncio import get_event_loop, new_event_loop
from fastapi import FastAPI
from uvicorn import Config, Server

app = FastAPI()

@app.get("/")
async def read_main():
    return f'Running loop: {get_event_loop()}'

loop = new_event_loop()
config = Config(app=app)
server = Server(config)
loop.run_until_complete(server.serve())
```

However I still think that `uvicorn` should use the `ProactorEventLoop` whenever possible. For example if the `--reload` option is the problem (issue #529), only switch to the `SelectorEventLoop` when `--reload` is enabled on Windows, and issue a warning in the logs that `--reload` should never be used in production on Windows.

**Comment by polys** [comment]
Thanks for the suggestion 😀

In my case, I'm only using Windows for development, so `--reload` is actually quite useful. The app runs in a Linux container in production.

My workaround while on Windows is to use [Hypercorn](https://pypi.org/project/Hypercorn/), which seems to be happier. I've only tried this for a couple of days now but haven't seen any `too many file descriptors in select()` exceptions in situations where `uvicorn` was consistently blowing up.

I'm still very happy to use `uvicorn` in production — just wanted to understand why there's this asyncio override on Windows.


> only switch to the `SelectorEventLoop` when `--reload` is enabled on Windows, and issue a warning in the logs that `--reload` should never be used in production on Windows.

That's a nice suggestion — I hadn't realised that that's the only reason for not using `ProactorEventLoop`.

**Comment by euri10** [comment]
> However I still think that uvicorn should use the ProactorEventLoop whenever possible. For example if the --reload option is the problem (issue #529), only switch to the SelectorEventLoop when --reload is enabled on Windows, and issue a warning in the logs that --reload should never be used in production on Windows.

happy to review a PR for this, should you want to tackle it open a new issue
your explanation as to why we changed the windows default is I think correct even if it was a long time ago >_)

**Comment by speedplane** [comment]
FYI, you need the ProactorEventLoop to run playwright. So anyone using uvicorn with playwright together on windows needs to startup uvicorn with the [instructions above](https://github.com/encode/uvicorn/issues/1220#issuecomment-947920138).
