### ISSUE TITLE
support multi threading

### ISSUE THREAD

**Issue by franklucky001** [Kludex/uvicorn#1232]
Is it possible to use one worker with multiple threads, like `gunicorn's --threads` with `gthread`。

**Comment by Kludex** [comment]
No. That doesn't make sense on the context of Python async applications.

I didn't read this article, but did a very fast look, and maybe it's useful to you: https://towardsdatascience.com/a-better-way-for-asynchronous-programming-asyncio-over-multi-threading-3457d82b3295

**Comment by franklucky001** [comment]
@Kludex It is difficult to share a complex global variable among multiple workers. In general, `redis` is a good solution for variable sharing， but `serialization` and `deserialization` of some complex variables are almost impossible for Python. Do you have any good suggestions for this problem?

**Comment by Kludex** [comment]
I need more info. If you want help with adhoc questions, our [Gitter](https://gitter.im/encode/community) is a better place for it. :kissing:

**Comment by franklucky001** [comment]
@Kludex In `one worker with multiple threads` mode, we can perfectly use global variable sharing between worker threads。For example, my service has two routes: `model training` and `model predict`. I hope that after training, each worker can share the `trained model` to complete the prediction task.

**Comment by Kludex** [comment]
You can store the model in a object storage cloud, SQL or NoSQL database you're using, and make sense for you. Then, assuming that you are concerned with a single model for your application, you can load it in a global variable on each worker.

I'll assume you're using FastAPI:

```python
from fastapi import FastAPI

model = None
app = FastAPI()

@app.post("/predict")
def predict(file: UploadFile = File(...)):
    global model
    if model is None:
        model = load_model()
    return model.predict(file.read())
```
Only the first request will take a little bit more, as it will load the model on the `model` variable, and considering the information that I have in hands, I think it should be enough.

Anyway, you completely ignored my second sentence on my previous message, which I think it was very rude, so I'm locking this conversation.
