### ISSUE TITLE
Dotenv could't be loaded with uvicorn 

### ISSUE THREAD

**Issue by lolio-dev** [Kludex/uvicorn#1236]
Hello,
I make an api with fastapi
When I try to load a db url write in a .env file with:
```py
from dotenv import load_dotenv
import os

load_dotenv(dotenv_path='../../config') # My file is called config because my venv was already called .env
DB_URL = os.getenv('DB_URL')
```
And I try to connect my db when i lauch my server with uvicorn I have an error, however when I launch the file manualy (with python myfile.py) I don't have error. 

With uvicorn, the variable is `None` while with my python interpreter she corresponds to my db url connection

I use python3.8, uvicorn 0.15.0 and python-dotenv 0.19.1
I'm on Ubuntu 20.04

**Comment by Kludex** [comment]
Can you add a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by lolio-dev** [comment]
https://github.com/lolio-dev/dotenv-test 

I have reproduce my probleme but i have also resolve it, if in `router/test.py` I replace '../../config' with only 'config' it's the opposite, i have none in test.py and HELLO WORLD when i lauch uvicorn

**Comment by euri10** [comment]
with all due respect, you better ask this kind of stuff on stackoverflow
