### ISSUE TITLE
Remove pinning of httptools==0.2.* - this blocks wheel usage of httptools on Python 3.10 for uvicorn[standard]

### ISSUE THREAD

**Issue by quantumtec** [Kludex/uvicorn#1242]
In summer, httptools upgraded to version `0.3.*` as a maintainace release (no functional changes), just changing the packaging and wheel building to support Python 3.10, dropping Python 3.5 support, see here: https://github.com/MagicStack/httptools/releases/tag/v0.3.0

Currently, the `uvicorn[standard]` dependencies pin `httptools` at version `0.2.*`:
https://github.com/encode/uvicorn/blob/a7d26bb76c29a9bd12f53b3a73ae5614592cdfb4/setup.py#L59

This prevents `uvicorn[standard]` to use wheels for `httptools `on Python 3.10 (cp310), **often preventing the simple usage of uvicorn[standard] with Python 3.10**, as they are only available on `httptools>=0.3.0`.

**Proposed fix:**
Either use `httptools=0.3.x` or drop the pin (initial reason for pinning?)

**Explanation** 
As the `httptools` upgrade is just a packaging release and Python 3.5 is not supported by `uvicorn `anyways, upgrading the pinning to 0.3.x (or dropping it entirely, after careful consideration) should not introduce any side-effects or breaking changes for the supported user base, but instead enable the simple usage of Python 3.10 without the need to manually build wheels for `httptools` on Python 3.10 during `pip install`

I did not open a pull request yet as I don't know if the pin is intentional and wanted to discuss this first.

**Comment by Kludex** [comment]
PR welcome with `"httptools>=0.2.0,<0.4.0",`. :kissing: 

EDIT: Actually, maybe we want a marker for httptools==0.3.0 and Python 3.10.

**Comment by quantumtec** [comment]
@Kludex I added a PR removing the 0.2 pinning, but setting the 0.4 limit as requested.

Any reasons for adding a specific marker just for Python 3.10? Just to test the rollout? Because in the long term improvements in httptools might happen in the 0.3.x branch and might be relevant not only for Python 3.10.

**Comment by Kludex** [comment]
I meant a marker to `httptools==0.3.*`, the 0 at the end was a mistake.

But I guess your PR is fine :+1:
