### ISSUE TITLE
APSceduler AsyncIOScheduler with Gunicorn and uvicorn workers

### ISSUE THREAD

**Issue by airen1986** [Kludex/uvicorn#1247]
Hi,

We have had uvicorn==0.15.0 with gunicorn==20.1.0 (uvicorn workers) where scheduled jobs were not executing, then we changed uvicorn to uvicorn==0.13.4 and installed its dependencies of uvloop and httptools, then the jobs are getting executed. Is there any bug in uvicorn==0.15.0, or how do I make it work for uvicorn==0.15.0 ?

Thanks

**Comment by euri10** [comment]
Thanks for the report, the issue template is there to help is help you, without more information it's rather complicate to get a sense of what could go wrong.
