### ISSUE TITLE
Allow specifying both `uds` and `host` params

### ISSUE THREAD

**Issue by trondhindenes** [Kludex/uvicorn#1250]
### Checklist
- [x] There are no similar issues or pull requests for this yet.
- [x] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.
We're running uviconr behind nginx in Kubernetes. I'd still like to be able to probe the uvicorn app directly to assert application health. In uwsgi this is easiest done by exposing a http endpoint in addition to the socket used to link nginx and the app.

However, the current implementatino of uvicorn does not allow 
```
        uvicorn.run(
            app, host="0.0.0.0", port=9000, access_log=False, uds=socket, forwarded_allow_ips="*"
        )
```
it seems that `host`/`port` params are ignored if the `uds` parameter is present

## Describe the solution you would like.
make `host`, `port` and `uds` not mutually exclusive

**Comment by lovelydinosaur** [comment]
Thanks for the feedback.

Correct. We don't currently support this.

It's possible that we might reconsider at a future point, but for right now I'd consider Uvicorn to mostly be in feature-pause, so that we prioritise stability and correctness rather than feature additions.

**Comment by jackstar12** [comment]
@tomchristie would you consider this feature by now? I think it should be trivial to implement, assuming that there are no conflicts when they are used together, I'd give it a shot.

**Comment by mikkelam** [comment]
I am also quite interesed in this feature 🙏
