### ISSUE TITLE
No module named 'asgiref.typing' after upgrade from 0.13.3 to 0.15.0

### ISSUE THREAD

**Issue by ekbfh** [Kludex/uvicorn#1253]
Hi!

RHEL7, python3.8 in env, pip 21.3+

I have `uvicorn 0.13.3` installed along with `asgiref 3.3.1`.
After `pip install uvicorn==0.15.0` asgiref stays the same version.
But when `pip install --upgrade uvicorn==0.15.0` dependency resolved more clearly.

Usually I install packages by ansible and don't want to do use `forcereinstall` every time just to be sure if there is a proper version with all dependencies cause it will increase my deploy time.

What are the requirements.txt meaning in this repository?

**Comment by Kludex** [comment]
The requirements.txt are for development, the actual `uvicorn` dependencies are listed in the `setup.py`.

`asgiref` was upgraded to 3.4.0 in the meantime.

**Comment by ekbfh** [comment]
Any idea why pip didn't resolve this dependency in update time?
