### ISSUE TITLE
 File "/opt/conda/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi

### ISSUE THREAD

**Issue by ranyaphat29** [Kludex/uvicorn#1254]
I face the problem like this
 File "/opt/conda/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi

What should i do?

**Comment by Kludex** [comment]
This is not the right place for questions like that. Please refer to our Gitter or Stackoverflow.

Besides, it's a good idea to not ignore the issue template.
