### ISSUE TITLE
Subprocess turns into zombile thread when use limit-max-requests and workers > 1 

### ISSUE THREAD

**Issue by karl-ford** [Kludex/uvicorn#1258]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
When I set limit-max-requests and workers > 1, the subprocesses will turn into zombie threading.

### To reproduce
```shell
uvicorn Server.asgi:application --host 0.0.0.0 --workers 2 --limit-max-requests 1 --port 8000
```
Send 2 requests by browser or postman. 

### Expected behavior
Thread exit.

### Actual behavior
Main Thread still alive while subprocesses turn into zombie thread.

### Debugging material
1. The nomal thread
![1 jpg](https://user-images.githubusercontent.com/7666278/142830939-b616b164-ab4c-40b1-8812-54384f40e144.png)
2. Once total_requests >= limit_max_requests
![2 jpg](https://user-images.githubusercontent.com/7666278/142830953-97aa3d5a-9171-454f-bbe2-68b7c5ece1ee.png)

### Environment
- CentOS 7.8.2003 / Python 3.8.2 / uvicorn 0.15.0
```shell
uvicorn Server.asgi:application --host 0.0.0.0 --workers 2 --limit-max-requests 1 --port 8000
```

### Additional context
Subprocess exits once I kill the main thread

**Comment by diogobaeder** [comment]
The same problem is happening to me. I don't even need to limit to 1 request, if I limit to, say, 3 requests per process, I can already easily reproduce the issue.

**Comment by euri10** [comment]
I read that quickly but I think its a duplicate of #632 which I may have fixed sometimes in a closed PR, need to dig
