### ISSUE TITLE
`--reload-include` doesn't work without watchgod

### ISSUE THREAD

**Issue by truh** [Kludex/uvicorn#1265]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Making changes to a file specified with `--reload-include`
doesn't reload the app if watchgod isn't installed.

### To reproduce

* `uvicorn project:app --reload --reload-include '*.md'`
* Edit a markdown file

### Expected behavior

uvicorn reloads if a file specified by `--reload-include` is modified.

### Actual behavior

uvicorn doesn't reload if a file specified by `--reload-include` is modified when watchgod isn't present.

### Debugging material

https://github.com/encode/uvicorn/blob/master/uvicorn/supervisors/statreload.py#L24 only looks for python files.

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`

```
Running uvicorn 0.15.0 with CPython 3.8.8 on Darwin
```

### Additional context

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/1265">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/1265/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/1265/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
It's mentioned in the documentation: https://www.uvicorn.org/settings/#development

![image](https://user-images.githubusercontent.com/7353520/143233927-54289a0a-3377-44a3-b277-4f1d6aaa5644.png)
