### ISSUE TITLE
Passing `reload_dirs` as a string instead of a list

### ISSUE THREAD

**Issue by euri10** [Kludex/uvicorn#1266]
@Roang-zero1 @euri10 @Kludex this PR introduced a regression and deleted the test for it (`test_reload_dir_is_set()`). Previously you could pass `reload_dirs` a string instead of a list. Now:
```python
Config('myapp:app', reload=True, reload_dirs='src')
```
prints:
```
WARNING:  Provided reload directories ['r', 'c', 's'] did not contain valid directories, watching current working directory.
```
https://github.com/encode/uvicorn/pull/820/files#diff-6982a5e270879281f9182303a9da9776148857b46325afb230e50ef8eb3264c9R294
(Of course, `set` expects an iterable... and strings are iterables of chars.)

_Originally posted by @HansBrende in https://github.com/encode/uvicorn/issues/820#issuecomment-977957988_

**Comment by euri10** [comment]
happy to take a PR on this @HansBrende

**Comment by HansBrende** [comment]
Sure, why not.

**Comment by HansBrende** [comment]
@euri10 PR submitted ^
