### ISSUE TITLE
Headers missing(?) when deployed in reverse proxy mode

### ISSUE THREAD

**Issue by tskamaldeep** [Kludex/uvicorn#1268]
### Describe the bug

I'm sending a request from a Node app with the following details (Bearer token valid for at least 7+ hours from current timestamp):
>>> import httpx
>>> headers = {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjY4MTg1ZmYxLTRlNTEtNGNlOS1hZjFjLTY4OTgxMjIwMzMxNyJ9.eyJUb2tlblR5cGUiOjUsIklzc3VlSW5zdGFudCI6MTYzNzc2OTE1NSwiZXhwIjoxNjM3Nzk3OTU1LCJVc2VySWQiOiJkYTM1YmQyZC1lYmQ5LTQ0ZDItODM4Mi00NTNjYmU2ZGQ5NWEiLCJzaXRlaWQiOjEsInNjcCI6WyJzaWduYXR1cmUiLCJpbXBlcnNvbmF0aW9uIiwiZXh0ZW5kZWQiLCJvcmdhbml6YXRpb25fcmVhZCIsImdyb3VwX3JlYWQiLCJwZXJtaXNzaW9uX3JlYWQiLCJ1c2VyX3JlYWQiLCJ1c2VyX3dyaXRlIiwiYWNjb3VudF9yZWFkIiwiZG9tYWluX3JlYWQiLCJpZGVudGl0eV9wcm92aWRlcl9yZWFkIiwiY2xpY2subWFuYWdlIiwiY2xpY2suc2VuZCIsInNwcmluZ19yZWFkIiwic3ByaW5nX3dyaXRlIl0sImF1ZCI6IjczNTBhYzNhLTFjZDgtNDg2My1hODQxLTg0ZTk4YTc1YjYwZCIsImF6cCI6IjczNTBhYzNhLTFjZDgtNDg2My1hODQxLTg0ZTk4YTc1YjYwZCIsImlzcyI6Imh0dHBzOi8vYWNjb3VudC1kLmRvY3VzaWduLmNvbS8iLCJzdWIiOiJkYTM1YmQyZC1lYmQ5LTQ0ZDItODM4Mi00NTNjYmU2ZGQ5NWEiLCJhdXRoX3RpbWUiOjE2Mzc3NjkwNDAsInB3aWQiOiJhOTZkMWE1Zi1jMTQyLTRkNWItYWIwYi05ZjQ3YzBkNzZiMDQifQ.WrZYzJIUz2bx4jCAdQ4FWZnTDsL8rOXdarE0-9gXOh5sT0mi5xCpLioIFcHaxIiab_UK2iKyefvF7Bj2TZdyqbOWGkV1XPjdQ9H-2AKBLdNhM85DN8EUTmOyv6UIrH9HzCt6l2ldmJu8cl8kolC5TFn31gYLOQKjccqdh6wFPDOjHeXOuvcFYtfKjZJA_hoGOBlWL7JmbgadceLFNfhgqhZ86yXVuiyFW7bkYfBRXHAgJRvNW3xXloGtaIPlutKzVx_zYtG_OE9owUtPJGyHwAZZvggz7numVh8XZvtyOKsn5O3vKwFsYz08Dp9SDCDku30VUCeGK48hHpJpTjJejA', 'Content-Type': 'application/x-www-form-urlencoded'}

>>> url = 'https://api-d.docusign.net/management//Management/v2/organizations'
>>> r = httpx.get(url, headers=headers)
>>> r
<Response [200 OK]>

When uvicorn catches the request, the scope does not seem to have these headers, so I am not in a situation to forward the request to the DocuSign servers in CORS mode. Direct invocation from the app to the servers results in CORS errors due to the selected mode and the declared supported for the selected mode.

Scope received at the server in 'instance' mode (with an __call__ definition):

{'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('192.168.50.101', 8001), 'client': ('192.168.50.101', 57218), 'scheme': 'https', 'method': 'OPTIONS', 'root_path': '', 'path': '/', 'raw_path': b'/', 'query_string': b'url=https://api-d.docusign.net/management/Management/v2/organizations', 'headers': [(b'connection', b'keep-alive'), (b'host', b'192.168.50.101:8001'), (b'cache-control', b'max-age=0'), (b'accept', b'*/*'), (b'access-control-request-method', b'GET'), (b'access-control-request-headers', b'authorization'), (b'origin', b'https://account-d.docusign.com'), (b'user-agent', b'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36'), (b'sec-fetch-mode', b'cors'), (b'sec-fetch-site', b'cross-site'), (b'sec-fetch-dest', b'empty'), (b'accept-encoding', b'gzip'), (b'accept-language', b'en-GB,en-US;q=0.9,en;q=0.8')]} 

How do I have access to the declared headers in uvicorn? Eager for your valued inputs.

### Environment

Running uvicorn 0.15.0 with CPython 3.9.8 on Darwin

**Comment by euri10** [comment]
I'm sorry I dont understand the flow of things here and where uvicorn is involved, can you port an app served by uvicorn that replicates your issue

**Comment by HansBrende** [comment]
@tskamaldeep The scope you've displayed describes a pre-flight `OPTIONS` request, whereas the request you sent was a `GET` request! So of course your header would not be there... it is not the same request as the one you sent. If you're not receiving a follow-up GET request, then you have a CORS issue, not a uvicorn issue.

**Comment by tskamaldeep** [comment]
This was a v good input @HansBrende.
After handling the OPTIONS request, I do have the GET request coming through now with the Auth token. So thank you, let me look to get this request through the uvicorn app server.

Eager to get the task through to completion. Thanks again!
