### ISSUE TITLE
when try to connect with websocket it give a error

### ISSUE THREAD

**Issue by wmtamit** [Kludex/uvicorn#1275]
I use fast api and when i change version on uvicorn 0.13.4 to 0.14.0 then i getting this error
```
lib\site-package\uvicorn\protocols\websockets\websockets_impl.py", line 104, in process_request
    websockets.legacy.handshake.check_request(headers)
AttributeError: module 'websockets' has no attribute 'legacy'
websockets.legacy.handshake.check_request(headers)
AttributeError: module 'websockets' has no attribute 'legacy'
```
i attached the WebSocket initial code I use starlette.endpoints WebSocketEndpoint from starlette.endpoints import WebSocketEndpoint

![image](https://user-images.githubusercontent.com/46313130/144361478-ddd8b03b-9017-4e0c-b85b-c35db36e7205.png)

for more info [check here](https://stackoverflow.com/questions/69479225/fastapi-error-when-trying-to-open-a-websocket-connection-after-updating-uvicorn)

Why I update the version because in old version not supported `--ws-max-size` this so please solve this as soon as possible. 
if possible to increase the size of buffer request in uvicorn == 0.13.4
fastapi==0.63.0 starlette==0.13.6

**Comment by euri10** [comment]
you're probably on websockets 9 and you need version 10

**Comment by wmtamit** [comment]
it's working 
Thanks
