### ISSUE TITLE
Feature request: Timeout option

### ISSUE THREAD

**Issue by caleb15** [Kludex/uvicorn#1276]
### Checklist

- [X] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive. (I brought this up twice in chat but only received one response)

### Is your feature related to a problem? Please describe.

I want to time out long-running requests to prevent a DDOS attack from happening. 

## Describe the solution you would like.

A timeout option to end requests after X seconds.

## Describe alternatives you considered

* Using Gunicorn, but gunicorn is not needed as we already have a process management system in the form of kubernetes. Also we had an issue with using gunicorn.
* Using Nginx, but if nginx ends the connection the request might still keep on running? (Not sure about this one)
* Timing out the connection in our Django codebase. This can probably be done but it would be nice if it was a default feature of uvicorn so everyone else could easily set it as well.

## Additional context

There is precedent for this feature as Uwsgi had this option.

**Comment by Kludex** [comment]
PR is welcome.

It's one of the features needed for 1.0. :)

I'll consider this as a duplicated of #157, even if it's a subset, and I'll close the issue.
