### ISSUE TITLE
workers not popping up when starting server manually

### ISSUE THREAD

**Issue by r-priyam** [Kludex/uvicorn#1284]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Passing `workers=4` in uvicorn config but it's not working

### Steps to reproduce the bug

```py
from __future__ import annotations

import asyncio
from functools import wraps

import typer
from uvicorn import Config, Server

try:
    import uvloop  # type: ignore
except ModuleNotFoundError:
    loop = asyncio.new_event_loop()
else:
    loop = uvloop.new_event_loop()

app = typer.Typer()


def coro(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        return asyncio.run(f(*args, **kwargs))

    return wrapper


@app.command()
@coro
async def runserver(host: str = "127.0.0.1"):
    server_config = Config("app.main:app", host=host, access_log=False, workers=4)
    server = Server(config=server_config)
    await server.serve()


if __name__ == "__main__":
    app()
```

### Expected behavior

4 workers should start

### Actual behavior

Only 1 worker is there

### Environment

Python 3.9.9
Uvicorn 0.15.0

**Comment by Kludex** [comment]
Check our main.py.

**Comment by r-priyam** [comment]
> Check our main.py.

Got it, so have to start workers manually with the help of `MultiProcessing`, Thanks!
