### ISSUE TITLE
Application constructor must be run in a thread.

### ISSUE THREAD

**Issue by JohnDoee** [Kludex/uvicorn#129]
[Daphne does it](https://github.com/django/daphne/blob/master/daphne/server.py#L186) and some parts of Channels require it not to be run in main thread because it'd block.

As far as I can see, that's not the case currently?:
https://github.com/encode/uvicorn/blob/1dfb87bd6452b859b5d112d3baa2d1b160915ba8/uvicorn/protocols/http/h11.py#L202-L205
https://github.com/encode/uvicorn/blob/1dfb87bd6452b859b5d112d3baa2d1b160915ba8/uvicorn/protocols/http/httptools.py#L215-L218

**Comment by lovelydinosaur** [comment]
Thanks for raising this - interesting!
Surprised Daphne does that.
My take would strongly be that I/O should not take place in the application init.

**Comment by lovelydinosaur** [comment]
> some parts of Channels require it not to be run in main thread because it'd block.

Any idea where / examples?

I’d expect all blocking operations to take place during the main ASGI call (even if some of that ends up eventually being within a threadpool)

**Comment by JohnDoee** [comment]
I jumped the gun, it seems like he reverted that decision but never removed the code from Daphne. As per https://github.com/django/daphne/issues/188
