### ISSUE TITLE
process stop after any exception with developing with reload feature

### ISSUE THREAD

**Issue by trim21** [Kludex/uvicorn#1295]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

In 0.15, with `--reload`, If I edit my source file with any exception on startup (most commnly a `SynataxError` triggered by auto save function or some typo), the uvicorn process will wait for next file change and then try to reload it again.

But after I upgrade it to 0.16, the process will exit. Then I'll have to start uvicorn again.

### Steps to reproduce the bug

Install uvicorn==0.16.0

write any working asgi app

start it with reload flag `uvicorn server:app --reload`

edit your server.py with any change with it raise a error when startup

then the uvicorn process exited

### Expected behavior

uvicorn process wait for reload like old behavior

### Actual behavior

uvicorn process exited

### Environment

python3.8
windows

`uvicorn.exe pol.server:app --reload --port 3000`

**Comment by trim21** [comment]
After checking changes between 0.15.0 and 0.16.0, looks like it's expected behavior now? https://github.com/encode/uvicorn/pull/1278

But it brings a realy bad user experience

**Comment by Kludex** [comment]
That PR doesn't change what you described. But I'm aware of the PR you're talking about (I'm on my phone, so I'll not search for it). 

In any case, can you tell me a little bit more about your issue/setup? The way I see it, you were using the bug in your favor.

**Comment by trim21** [comment]
Yes, you are right. It's in #1177.

Personally I think old behavior (`--reload` with "hanging") works well for development usage.

maybe we can have a new flag called `--dev` or some else support hanning on error.

It's common that an being edited app can't startup. With old behavior, I just need to keep editing and test it in browser after uvicorn starts listening.

Otherwise it's more convenient to choose another fs watcher like nodemon or watgod itself and start uvicorn with them, instead of using uvicorn's auto-reload, make this function less useful.

**Comment by Kludex** [comment]
I understand your issue, and I think it's a valid point.

Let's see if we can find a solution that satisfies this issue, and can also don't remove the "close if hanging".

Maybe a timeout? Any ideias?

**Comment by trim21** [comment]
watchgod support executing a function after any fs event.

Add a new flag like `--dev` and add a thin wrapper to dispatch other flag like uvloop and port to `uvicorn.run`

**Comment by trim21** [comment]
Does this should be closed by https://github.com/encode/uvicorn/pull/1313 ?

**Comment by Kludex** [comment]
Yes. Thank you!
