### ISSUE TITLE
Feature Request: allow disabling per-message deflate

### ISSUE THREAD

**Issue by cfal** [Kludex/uvicorn#1298]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

We're experiencing intermittent websocket issues causing the browser to be unable to connect due to `Invalid frame header` and other weird errors. I'm guessing the issue isn't directly due to uvicorn, but turning off per-message deflate seems to fix the problem. Since per-message-deflate is hardcoded as an extension in both websockets and wsproto uvicorn implementations, it would be very helpful if that was configurable. Would a PR to add this configuration field be accepted?

### Environment

Uvicorn 0.15.0, Python 3.9, websockets 10.1

**Comment by euri10** [comment]
> Would a PR to add this configuration field be accepted?

yes ! @cfal
