### ISSUE TITLE
Regression (?) with uvicorn workers

### ISSUE THREAD

**Issue by gabac** [Kludex/uvicorn#1306]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I'm currently upgrading the version of our application and have since encountered a regression while moving from `uvicorn` `0.14.0` to `0.15.0`

I believe this is directly related to following PR: https://github.com/encode/uvicorn/pull/1077

In our application we start a `ZeebeWorker` during the startup of `uvicorn`

```
import logging
import asyncio
from typing import Callable

from fastapi import FastAPI
from app.core.config import settings
from app.workers.zeebe_worker import worker

logger = logging.getLogger(__name__)


def create_start_app_handler(_: FastAPI) -> Callable:

    async def start_app() -> None:
        logging.basicConfig(level=settings.LOGGING_LEVEL)
        logger.info('Triggering events on app start')
        task = asyncio.create_task(worker.work())
        logger.info('created task')
        logger.info(f'created task {task}')

    return start_app
```

With `0.14.0` this worked. Since updating to `0.15.0` I receive immediately following error:

```
2022-01-05 13:17:20.983 CET Waiting for application startup.
2022-01-05 13:17:20.984 CET Triggering events on app start
2022-01-05 13:17:20.984 CET created task
2022-01-05 13:17:20.984 CET created task <Task pending coro=<ZeebeWorker.work() running at /usr/local/lib/python3.7/site-packages/pyzeebe/worker/worker.py:54>>
2022-01-05 13:17:20.984 CET Application startup complete.
2022-01-05 13:17:20.985 CET Task exception was never retrieved future: <Task finished coro=<ZeebeWorker.work() done, defined at /usr/local/lib/python3.7/site-packages/pyzeebe/worker/worker.py:54> exception=RuntimeError('Task <Task pending coro=<JobPoller.poll() running at /usr/local/lib/python3.7/site-packages/pyzeebe/worker/job_poller.py:39> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.7/asyncio/tasks.py:691]> got Future <Task pending coro=<UnaryStreamCall._send_unary_request() running at /usr/local/lib/python3.7/site-packages/grpc/aio/_call.py:559>> attached to a different loop')>
```

My assumption is, that this is related to the PR mentioned above?

Any hints how we may fix this?

### Steps to reproduce the bug

Start application

### Expected behavior

Connection to Zeebe should be established

### Actual behavior

Connection to Zeebe is not established

### Environment

Dockerfile
```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
  cd /usr/local/bin && \
  ln -s /opt/poetry/bin/poetry && \
  poetry config virtualenvs.create false

RUN apt-get update && \
  apt-get install -y --no-install-recommends poppler-utils && \
  apt-get install -y --no-install-recommends tesseract-ocr=4.1.1-2.1 && \
  apt-get install -y --no-install-recommends tesseract-ocr-deu && \
  apt-get install -y --no-install-recommends tesseract-ocr-ita && \
  apt-get install -y --no-install-recommends tesseract-ocr-fra && \
  apt-get install -y --no-install-recommends tesseract-ocr-eng && \
  apt-get install -y --no-install-recommends ffmpeg libsm6 libxext6 && \
  apt-get clean

COPY ./commons /commons

# Copy using poetry.lock* in case it doesn't exist yet
COPY ./pre-processing-service/pyproject.toml ./pre-processing-service/poetry.lock* /app/
RUN poetry install --no-root --no-dev

# NLTK download
COPY ./commons/scripts/nltk_download.py /app/
RUN python /app/nltk_download.py

COPY ./pre-processing-service/app /app/app
COPY ./pre-processing-service/prestart.sh /app/prestart.sh
COPY ./pre-processing-service/start-reload.sh /start-reload.sh
RUN chmod +x /start-reload.sh
```

pyproject.toml
```
[tool.poetry]
name = "pre-processing-service"
version = "0.1.0"
description = "Service to pre-processing documents."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"
fastapi = "^0.70.1"
uvicorn = "^0.15.0"
pyzeebe = "3.0.1"
gunicorn = "^20.1.0"
google-cloud-logger = "^0.2.1"
httpx-auth = "^0.10.0"
httpx = "^0.18.1"
# https://github.com/python-poetry/poetry/issues/3368
commons = { path = "../commons/" }
pdf2image = "^1.16.0"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
opencv-python = "^4.5.2"
numpy = "~1.19.0"
tensorflow = "^2.6.2"

[tool.poetry.dev-dependencies]
yapf = "^0.32.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.yapf]
based_on_style = "google"
```

**Comment by Kludex** [comment]
It doesn't look like related to the PR mentioned.

Do you still have the issue?

**Comment by gabac** [comment]
Yes I do. Could it be an issue how I start an asynchronous worker in an already asynchronous function (`start_app()`)? 
The interesting behavior is though that error only started to aperste with version `0.15.0` which was the only change I did

**Comment by Kludex** [comment]
A couple of months and bumps happened. Is this still relevant @gabac ?

**Comment by Kludex** [comment]
Closing as there was no response from author.

For others coming here, please open a discussion about it, with a minimal reproducible code, so we can speed up the process of finding a solution. :)

**Comment by adamos-kyriakou-wolt** [comment]
I recently faced this issue at work (so a minimal, publicly shareable reproduction of the issue was gonna be very cumbersome to produce) where the combination of async gRPC Python code and uvicorn v0.15.0 and greater was giving me similar errors to the above:

```
Task <Task pending name='starlette.middleware.base.BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro' coro=<BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro() running at /opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/base.py:34> cb=[TaskGroup._spawn.<locals>.task_done() at /opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py:726]> got Future <Task pending name='Task-1564' coro=<InterceptedUnaryUnaryCall._invoke() running at /opt/pysetup/.venv/lib/python3.10/site-packages/grpc/aio/_interceptor.py:592> cb=[InterceptedCall._fire_or_add_pending_done_callbacks()]> attached to a different loop
```

Turns out the issue was caused by:

1. Version [v0.15.0](https://github.com/encode/uvicorn/blob/master/CHANGELOG.md#0150---2021-08-13) (and later) of `uvicorn` changing the way they managed their async event loop:

  > Add Python 3.10-rc.1 support. Now the server uses  `asyncio.run`  which will: start a fresh asyncio event loop, on shutdown cancel any background tasks rather than aborting them,  `aexit`  any remaining async generators, and shutdown the default  `ThreadPoolExecutor` . (1070) 30/07/21  

2. Async [gRPC Python's caveats](https://grpc.github.io/grpc/python/grpc_asyncio.html#caveats) warning that:

> gRPC Async API objects may only be used on the thread on which they were created. AsyncIO doesn’t provide thread safety for most of its APIs.

3. My instantiating the [grpc.aio.secure_channel](https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.secure_channel) and related resources outside of the FastAPI/Starlette event loop (in fact I was instantiating it alongside the `FastAPI()` call.

My understanding is threadbare but I gathered that by instantiating those async resources outside the FastAPI event loop they'd create and attach themselves to their own async loop causing the above issue.

The solution was to instead instantiate those resources within the [FastAPI startup event](https://fastapi.tiangolo.com/advanced/events/) which is guaranteed to run within the same event loop that runs the FastAPI routes.

An alternative solution I came across, but didn't personally test, would be to instantiate those async gRPC resources in a JIT fashion as part of the route code as those are also guaranteed to execute within the same event loop.

I hope this helps whoever may come across this issue in the future 🥰
