### ISSUE TITLE
No `python_requires` defined

### ISSUE THREAD

**Issue by vytas7** [Kludex/uvicorn#1327]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

It seems that no `python_requires` is defined for the `uvicorn` package, which in turn results in the latest version being installed in a Python 3.6 (CI) environment (that subsequently fails).

If `python_requires` were defined to restrict the package to supported versions of the interpreter, I would have got an older version (that supported `py36`) instead.

### Steps to reproduce the bug

In a `py36` environment
```
pip install uvicorn
# Run uvicorn
# ...
```

### Expected behavior

An older version is installed that works.

### Actual behavior

`uvicorn` errors out, says `py36` is unsupported.

### Environment

CPython 3.6

**Comment by Kludex** [comment]
PR welcome to add `python_requires`.

**Comment by vytas7** [comment]
Thanks @Kludex, I'll try to open one later today!
(Although it's obviously too late for the 3.6 case unless you are willing to yank the current version later.)

**Comment by Kludex** [comment]
I don't have the power to yank the current version. We should ask @tomchristie for that, but I'm not sure if it's that necessary.

The recommendation on `zero version` is to pin the package version.

In any case, that line of code will be useful in the future.

**Comment by vytas7** [comment]
@Kludex I've now opened a PR: #1328.
