### ISSUE TITLE
multiprocessing/joblib doesn't work in uvicorn

### ISSUE THREAD

**Issue by qwertyforce** [Kludex/uvicorn#1335]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

app freezes when trying to use multiprocessing.Pool or joblib (https://github.com/joblib/joblib/issues/1250)

### Steps to reproduce the bug

```python
import uvicorn
import multiprocessing
if __name__ == '__main__':
    uvicorn.run('uvicorn_test:app', host='127.0.0.1', port=7777, log_level="info")

def calculate(func, args):
    result = func(*args)
    return '%s says that %s%s = %s' % (
        multiprocessing.current_process().name,
        func.__name__, args, result
        )

def calculatestar(args):
    return calculate(*args)

def mul(a, b):
    return a * b

def plus(a, b):
    return a + b

if __name__ == 'uvicorn_test':
    with multiprocessing.Pool(1) as pool:
        print(pool._processes)
        TASKS = [(mul, (i, 7)) for i in range(10)] + \
                [(plus, (i, 8)) for i in range(10)]
        imap_it = pool.imap(calculatestar, TASKS)
        for x in imap_it:
            print('\t', x)
```

### Expected behavior

print some text

### Actual behavior

app hangs

### Environment

Running uvicorn 0.17.0 with CPython 3.8.10 on Windows
joblib doesnt work on: linux, windows; python 3.7 3.8 3.9

**Comment by Kludex** [comment]
How do I run the example?

**Comment by lovelydinosaur** [comment]
@Kludex - I think our general policy ought to be to push these kinda things into "discussions" first. (Probably?) Do you have permissions to do that ATM?

<img width="333" alt="Screenshot 2022-01-27 at 14 19 43" src="https://user-images.githubusercontent.com/647359/151377256-3ba92827-a5b4-4596-bf4c-b08e56de82d3.png">
