### ISSUE TITLE
`packaging` module missing?

### ISSUE THREAD

**Issue by dantownsend** [Kludex/uvicorn#1358]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When installing the latest version from PyPI (0.17.2) I get an error that `packaging` doesn't exist:

https://github.com/encode/uvicorn/blob/41e339dd953a00d071c8bb5704f4671564f9f6e1/uvicorn/protocols/websockets/wsproto_impl.py#L7

I looked at setup.py, and couldn't find any reference to `packaging`. Presumably it's meant to be this module:

https://pypi.org/project/packaging/

It could just be me - but thought I'd report just in case.

### Steps to reproduce the bug

`pip install uvicorn` - try and run any ASGI app

### Environment

Mac OS, Python 3.10

**Comment by lovelydinosaur** [comment]
Thanks for reporting this @dantownsend - fix incoming in #1359

**Comment by lovelydinosaur** [comment]
Now resolved in 0.17.3 - #1361
