### ISSUE TITLE
unable to quiet tracebacks regarding illegal request lines

### ISSUE THREAD

**Issue by kevr** [Kludex/uvicorn#1364]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When users request against uvicorn with illegal request lines, an exception is raised after an "Invalid HTTP request received." warning is logged. This traceback can be caused by malicious actors and it spams up the logs when repeated.

### Steps to reproduce the bug

Make a request with `\xc3\x83\xe2` in the query string.

### Expected behavior

Smaller sanitized message about the illegal request line or a way to configure traceback logging.

### Actual behavior

A traceback is logged out that shows the illegal request line attempted.

### Debugging material

```
aurweb-fastapi-1  | 08:06:41 WARNING | uvicorn.error: Invalid HTTP request received.
aurweb-fastapi-1  | Traceback (most recent call last):
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
aurweb-fastapi-1  |     event = self.conn.next_event()
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/h11/_connection.py", line 443, in next_event
aurweb-fastapi-1  |     exc._reraise_as_remote_protocol_error()
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
aurweb-fastapi-1  |     raise self
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/h11/_connection.py", line 425, in next_event
aurweb-fastapi-1  |     event = self._extract_next_receive_event()
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
aurweb-fastapi-1  |     event = self._reader(self._receive_buffer)
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/h11/_readers.py", line 72, in maybe_read_from_IDLE_client
aurweb-fastapi-1  |     matches = validate(
aurweb-fastapi-1  |   File "/usr/lib/python3.10/site-packages/h11/_util.py", line 88, in validate
aurweb-fastapi-1  |     raise LocalProtocolError(msg)
aurweb-fastapi-1  | h11._util.RemoteProtocolError: illegal request line: bytearray(b'GET /packages/?k=ore_no_im\xc3\x83\xe2abc HTTP/1.0')
```

### Environment

- OS: Arch Linux
- uvicorn version: `uvicorn 0.15.0 with CPython 3.9.5 on Linux`
- running a FastAPI application

### Additional context

I've tried installing a logging filter in our application to prevent this, but it seems like its being logged out regardless.

**Comment by lovelydinosaur** [comment]
Duplicate of #1296
