### ISSUE TITLE
Support channel layers

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#14]
Allow for unsticky websockets, by supporting channel layers.

* A consumer callable that routes some or all channels to a channel layer.
* A worker that pulls messages off a channel layer.

**Comment by lovelydinosaur** [comment]
Blocked due to no asyncio send on redis channel layer, or indeed in the ASGI spec.

(Aside: twisted has an asyncio bridge now, so a twisted future send would also be sufficient)

**Comment by lovelydinosaur** [comment]
Migrating this issue to https://github.com/encode/uvitools/issues/3

**Comment by japrogramer** [comment]
channels might be moving to asyncio in 2.0
```
01:50 <+andrewgodwin> and the reason we don't use built-in async in channels right now is that we support Python 2.7
01:50 <+andrewgodwin> I am reconsidering this for Channels 2.0
```

**Comment by ChillarAnand** [comment]
Channels are migrated to asyncio. Does uvicorn support django channels 2.0? Does it have multi threading/processing support?

**Comment by lovelydinosaur** [comment]
Yes, it should support being used for channels just fine. Yes there’s multi-process support - use ‘-w 4’ to start 4 processes for example. (Multi threading isn’t a thing here since it’s asyncio tasks for concurrency, not multithreaded)
