### ISSUE TITLE
workers=<NUM>, reload=True does not start the workers

### ISSUE THREAD

**Issue by matgnt** [Kludex/uvicorn#1413]
When starting uvicorn (tested with 0.17.0) with both, `reload=True` AND `wokers=<NUM>`, the workers are NOT started.

The documentation at
https://www.uvicorn.org/settings/#development
should probably mention this at the `--reload` option.

After changing to `reload=False` workers start as expected.

Example:
```
if __name__ == '__main__':
    import uvicorn
    uvicorn.run("my.mod:app", host="0.0.0.0", port=8000, workers=5, reload=True)

```

Especially in cases when the system makes an API call to itself, multiple workers are required! otherwise the system blocks. Therefore, the 2 options should be possible to work together.

**Comment by Kludex** [comment]
This works as expected. Those two arguments are mutually exclusive.

I guess a PR to improve the documentation would be useful, but changing its behavior would be troublesome. I guess we'd need to do a refactor on how we handle our processes (either reloader or workers setup), which I think shouldn't take place after we answer the question: "Should `--workers` be deprecated and further removed, or should we develop it in a way that could have analogous features to gunicorn?".

In any case, this is not a bug, and a PR to improve the docs about the behavior is more than welcome.

**Comment by matgnt** [comment]
As discussed with @euri10 in #1415 
This is the behavior I'm seeing:

```
if __name__ == '__main__':
    import uvicorn
    uvicorn.run("cx.main:app", host="0.0.0.0", port=8000, workers=5, reload=True)
```
![Screenshot from 2022-03-22 10-44-00](https://user-images.githubusercontent.com/198707/159452702-f7479351-aa82-4106-b847-8bdbf8867f85.png)

```
if __name__ == '__main__':
    import uvicorn
    uvicorn.run("cx.main:app", host="0.0.0.0", port=8000, workers=5, reload=False)
```

![Screenshot from 2022-03-22 10-43-22](https://user-images.githubusercontent.com/198707/159452728-f6931509-12d6-4159-b73d-18a3d9646a7b.png)

Difference is `reload=True` vs `reload=False`

**Comment by euri10** [comment]
yes as @Kludex said it's expected, not sure we can do something about it and prevent users from using it both, I'm not aware of such a `click` feature so best thing to do for he moment is update the docs, your PR is welcomed =:)
