### ISSUE TITLE
uvloop closes underlying sockets that were established outside upon end of asyncio.run()

### ISSUE THREAD

**Issue by Programmierus** [Kludex/uvicorn#1414]
Sample:

```python
import asyncio
import socket
import uvloop

b = bytes('{"msg": "test"}', 'utf-8')


async def main_async(sock: socket.socket):
    _, writer = await asyncio.open_unix_connection(sock=sock)
    writer.write(b)
    await writer.drain()


if __name__ == '__main__':
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect('data/sockets/echo_server.sock')
    sock.sendall(b)
    uvloop.install()
    asyncio.run(main_async(sock))  # sock gets wrongly closed on asyncio.run() termination
    sock.sendall(b)  # Exception here OSError: [Errno 9] Bad file descriptor
```

Last line result in exception "OSError: [Errno 9] Bad file descriptor" because sock gets closed right after asyncio.run() terminates. It is wrong behavior, because sock was created outside of asyncio loop and has to be left untouched. The issue doesn't occur using regular asyncio loop.

**Comment by Kludex** [comment]
The name is similar, but you got the wrong repository. This is the one: https://github.com/MagicStack/uvloop .

**Comment by Programmierus** [comment]
> The name is similar, but you got the wrong repository. This is the one: https://github.com/MagicStack/uvloop .

Ouch, please accept my apologizes! Not a wrong name, but a wrong tab :-( Shame on me.

**Comment by Kludex** [comment]
No worries :)
