### ISSUE TITLE
uvicorn adding its own server header to response

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1436]
### Discussed in https://github.com/encode/uvicorn/discussions/1435

<div type='discussions-op-text'>

<sup>Originally posted by **udit-pandey** April  1, 2022</sup>
I have added few headers using [secure package](https://pypi.org/project/secure/) in my fastapi application. I wanted to overwrite the server header(having default value "uvicorn") to something else. All the added headers using secure package are replicated in the responses except the server header which is coming twice(once with value given by me and other with uvicorn) as shown the postman api response below:

![image](https://user-images.githubusercontent.com/18224381/161194376-1ff92c6c-ed3e-41c6-9578-39993ea17179.png)

I run my application using:
`gunicorn -k uvicorn.workers.UvicornWorker ${APP_MODULE} --bind 0.0.0.0:80`

Why is this header being added again by **uvicorn** even though it already exists?</div>

**Comment by udit-pandey** [comment]
> ### Discussed in #1435
> Originally posted by **udit-pandey** April 1, 2022 I have added few headers using [secure package](https://pypi.org/project/secure/) in my fastapi application. I wanted to overwrite the server header(having default value "uvicorn") to something else. All the added headers using secure package are replicated in the responses except the server header which is coming twice(once with value given by me and other with uvicorn) as shown the postman api response below:
> 
> ![image](https://user-images.githubusercontent.com/18224381/161194376-1ff92c6c-ed3e-41c6-9578-39993ea17179.png)
> 
> I run my application using: `gunicorn -k uvicorn.workers.UvicornWorker ${APP_MODULE} --bind 0.0.0.0:80`
> 
> Why is this header being added again by **uvicorn** even though it already exists?

Uvicorn version:0.12.3
Fastapi: 0.70.0

**Comment by Kludex** [comment]
Version 0.12.3... Does that it still happens with the latest version?

**Comment by udit-pandey** [comment]
Yes.

**Comment by Kludex** [comment]
The solution here, as many analogous (considering the arguments that are not passed to Uvicorn from Gunicorn), is to subclass `UvicornWorker`.

Example:
```python
from uvicorn.workers import UvicornWorker

class HeadlessUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {"loop": "auto", "http": "auto", "server_header": False}
```
Then you can use it as, e.g.:
```bash
gunicorn main:app --worker-class=main.HeadlessUvicornWorker --bind=localhost:8001
```

**Comment by TheBubblePopped** [comment]
Out of curiosity @Kludex , how did u know that server_header needed an underscore and suddenly accepts a False value?

**Comment by Kludex** [comment]
I'm not sure if I get the question... What do you mean by "suddenly"?

In any case, the CONFIG_KWARGS keys are the ones `Config` class can accept.
