### ISSUE TITLE
The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.

### ISSUE THREAD

**Issue by tillea** [Kludex/uvicorn#1439]
There was a [bug](https://bugs.debian.org/1008457) reported to Debian which I fixed with this [patch](https://salsa.debian.org/python-team/packages/python-uvicorn/-/blob/debian/master/debian/patches/0004-Fix-asyncio-warnings.patch).  Feel free to take it over, Andreas.

**Comment by Kludex** [comment]
Yeah... Thanks, but this doesn't help. More info on https://github.com/encode/uvicorn/pull/1411.
