### ISSUE TITLE
Add extra package version verification before running it

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1453]
Check the version of packages that are not mandatory.

This causes issues that can have an infinity range of possible exceptions.

**Comment by euri10** [comment]
good idea

**Comment by Kludex** [comment]
Based on all previous PRs, I think the question is:

- Do we want to add `setuptools` as dependency? https://packaging.pypa.io/en/latest/version.html#packaging.version.parse

If yes, then we can easily implement and close this issue. If not, this will never be implemented.

**Comment by Kludex** [comment]
Since I'm not willing to add `setuptools` to our dependencies... Bumping to the latest version is the way to go.
