### ISSUE TITLE
use asyncio.Runner(loop_factory=...) instead of the policy system on 3.11

### ISSUE THREAD

**Issue by graingert** [Kludex/uvicorn#1523]
### Discussed in https://github.com/encode/uvicorn/discussions/1521

<div type='discussions-op-text'>

<sup>Originally posted by **graingert** June 17, 2022</sup>
As part of the GELectomy (removing the per thread global eventloop from `asyncio.get_event_loop()` ) asyncio.runners now provides a policy free way to select the eventloop implementation. uvicorn should use this on 3.11 and consider backporting the implementation for other python versions</div>

**Comment by Kludex** [comment]
@graingert What are your thoughts about this issue? Should we still have it here? 👀

I don't see any reaction to your issues on the CPython GitHub about the `asyncio.Runner`. 🤔

**Comment by graingert** [comment]
It might be better to copy the implementation from python 3.10 `asyncio.runners` and ignore the broken implementation in 3.11

**Comment by Kludex** [comment]
> It might be better to copy the implementation from python 3.10 `asyncio.runners` and ignore the broken implementation in 3.11

Let's go back to the discussion then... This implies far more than what the issue proposes... 🤔
