### ISSUE TITLE
uvicorn 0.17.6 still have high CPU spike and memory keeping increasing issue

### ISSUE THREAD

**Issue by ericazhao-china** [Kludex/uvicorn#1583]
once we upgrade from 0.16.0 to 0.17.6 we still have high CPU spike and memory keeping increasing issue.

Firstly we never use reload and  set  Reload=false, so this is not the root cause for our case led to CPU spike. 

for uvicorn process we start with this : uvicorn src.api.api:app --port 8000 --host 0.0.0.0 --workers 1 --limit-max-requests 1000000 

For CPU spike, It happened occasionally in test and prod env  , generally once new pod is deployed , the cpu usage is starting from  0.17 and then keeping to increasing and then sometimes sharply increased to 15 vcpus (our K8s cluster each of  worker node  has 16 vcpus) , our monitoring chat for the processor of uvicorn as following  

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/65637184/181215894-831f01db-372f-4e98-b069-594b22b21d92.png">

And memory also keep increasing starting from 100M to more than 1G for each pod lifecycle.  
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/65637184/181216318-5e1bb9e5-c49d-4fe5-b607-4793f30ffb81.png">

As we set the limit-max to restart uvicorn  and workaround this high cpu and memory usage issue, after each of restart , cpu and memory back to normal and keep increasing again .

I checked we have OOM issue solved in 0.17.4 , so tried to upgrade to 0.17.6 , both cpu and memory not changed , any idea for this issue ??  Thanks !

**Comment by Kludex** [comment]
The issue template is completely ignored.

Until proven wrong, this is the same as: https://github.com/encode/uvicorn/issues/1564
