### ISSUE TITLE
Django integration

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#16]

**Comment by audiolion** [comment]
Just to understand, is the idea that this will integrate into apistar to give it asgi/async functionality?

**Comment by lovelydinosaur** [comment]
The primary aim is to provide the basis for *any* Python asyncio framework. And yes, I'd like apistar to support that.

There's also a secondary aim of  being used with existing WSGI frameworks, in order to support WebSocket functionality. One thing in particular that would be nice would be for `uvicorn` to be an alternative deployment option to `daphne`.

**Comment by lovelydinosaur** [comment]
Migrating this issue to https://github.com/encode/uvitools/issues/2

**Comment by lovelydinosaur** [comment]
See also https://github.com/encode/uvitools/issues/3 for a more standard channels deployment style. I'd expect that to land first.
