### ISSUE TITLE
Keep alive timeout should trigger for first request too.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#160]

**Comment by Kludex** [comment]
Can you add an explanation, please? I'm willing to give it a try. :) @tomchristie @euri10

**Comment by euri10** [comment]
I've no idea sorry !

**Comment by Kludex** [comment]
@tomchristie When you have time, can you please clarify what do you mean here?

**Comment by lovelydinosaur** [comment]
Complete clarity.
