### ISSUE TITLE
Check if ASGI callable returns None is necessary?

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1601]
I've added the ignore statements as the new mypy version throws those errors, but...

Is this really needed?
https://github.com/encode/uvicorn/blob/4d518b79eb22976fbf6a1f742e774e9206aa3fa0/uvicorn/protocols/http/h11_impl.py#L412-L415

@tomchristie Does `uvicorn` needs to check this? If the result is different than `None`, should we care? :thinking:

_Originally posted by @Kludex in https://github.com/encode/uvicorn/issues/1590#issuecomment-1200895206_

**Comment by lovelydinosaur** [comment]
I don't know - not clear to me what the motivation was now.
Perhaps to guard against trivially incorrect configuration errors? (Uvicorn pointed at the wrong callable?)

**Comment by Kludex** [comment]
Not sure if it's necessary, but no harm there. Just questioning cause `mypy` pointed this out.
