### ISSUE TITLE
Not able to disable ws_ping_timeout and ws_ping_interval.

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [Kludex/uvicorn#1609]
How to disable it?

**Comment by Kludex** [comment]
You can try `--ws-ping-timeout=` (yes, empty). If it doesn't work, you can only do it programmatically, using `ws_ping_timeout=None`.

**Comment by ChaitanyaYeole02** [comment]
Changed ws_ping_timeout=None but nothing happened it is still sending ping pong.
The default value is set to 20 in the library. 


```
DEBUG:    % sending keepalive ping
[keepalive_ping - 1245] % sending keepalive ping
DEBUG:    > PING 3a 21 ee bf [binary, 4 bytes]
[write_frame_sync - 1158] > PING 3a 21 ee bf [binary, 4 bytes]
DEBUG:    < PONG 3a 21 ee bf [binary, 4 bytes]
[read_frame - 1152] < PONG 3a 21 ee bf [binary, 4 bytes]
DEBUG:    < PING '\U00032f06' [text, 4 bytes]
[read_frame - 1152] < PING '\U00032f06' [text, 4 bytes]
DEBUG:    > PONG '\U00032f06' [text, 4 bytes]
[write_frame_sync - 1158] > PONG '\U00032f06' [text, 4 bytes]
```

Also tried this - 
`uvicorn central_system:central_system --log-level="debug" --ws-ping-timeout=`

I got this error
`Error: Invalid value for '--ws-ping-timeout': '' is not a valid float.`


@Kludex

**Comment by Kludex** [comment]
Can you give me a code snippet using `uvicorn.run`, please?

**Comment by ChaitanyaYeole02** [comment]
```
uvicorn.run("central_system:central_system", host="0.0.0.0", port=9000, headers=headers, workers=1,
                log_level="debug", ws_ping_timeout=None)
```

**Comment by Kludex** [comment]
A complete snippet...

**Comment by ChaitanyaYeole02** [comment]
```
central_system = CentralSystem()
central_system.include_router(v16_provisioning_router)

if __name__ == "__main__":
    sub_protocols = f"{Subprotocol.ocpp16}"
    headers = [("Sec-WebSocket-Protocol", sub_protocols)]
    uvicorn.run("central_system:central_system", host="0.0.0.0", port=9000, headers=headers, workers=1,
                log_level="debug", ws_ping_timeout=None)
```

**Comment by Kludex** [comment]
Install `websockets`: `pip install websockets`. We only have `ws_ping_timeout` on the `websockets` implementation.

**Comment by MarlieChiller** [comment]
I think @ChaitanyaYeole02 is indicating that if you specify `None` to the `ws_ping_timeout` and/or `ws_ping_interval` this doesnt disable the feature, it falls back to the uvicorn defaults of 20s for each, as these are the default values specified in `main.py:L479` & `main.py:L480`.

**Comment by sathishvenkataraman** [comment]
Hi, i am getting disconnects at 40 second.  am using ws_ping_timeout = None in uvicorn.  any idea?
