### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#161]
See also #125 and https://github.com/django/daphne/issues/118

Going to punt on this for the moment, in favor of prioritizing other aspects.

**Comment by JohnDoee** [comment]
#125 has a concept of "App latency" but how would you know an application is finished?

I tried using weakref.finalize but garbage collection is way too sporadic.

**Comment by lovelydinosaur** [comment]
@JohnDoee There's a couple of different things we *could* measure...

* Response latency - Measure how long it takes before the application has completely sent the response.
* Task duration - Measure how long the application tasks take to run to completion.

We keep track both `connections` and `tasks` in uvicorn (See `self.connections` and `self.tasks` in each of the two HTTP implementations.)

> I tried using weakref.finalize but garbage collection is way too sporadic.

We use a task callback. https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/h11_impl.py#L264

(We need to keep track of running tasks in order to properly perform graceful restart behavior.)

**Comment by lovelydinosaur** [comment]
Closing as currently out of scope.
My *strong* preference on any metrics would be to deal with them in an ASGI middleware,
and have it be an application-level concern. (I think it's far easier to innovate there, than to have something that's strictly coupled to uvicorn, also it can then be behind whatever user-permissions the application is enforcing.)
