### ISSUE TITLE
Documentation request: show pattern for starting server from Python code

### ISSUE THREAD

**Issue by simonw** [Kludex/uvicorn#162]
At the moment Uvicorn mostly expects to be started from the command line, passing a path to the ASGI app that should be served.

For Datasette, I need to configure and start a Uvicorn server running from my own Python code.

I figured out a pattern for his by digging deep into the internal of both uvicorn and gunicorn, but it would be great if there was a well supported documented pattern for doig this.

For reference, here's how I do this using Sanic at the moment: 
https://github.com/simonw/datasette/blob/b320f58d13e510d51e07187c8a75db856205b88f/datasette/cli.py#L578

**Comment by lovelydinosaur** [comment]
Use `uvicorn.run()` - see https://www.uvicorn.org/#running-programmatically

But yes, needs much better documentation, including the available options.

(I need to overhaul the deployment docs generally, particularly around help folks through sensible configurations of using uvicorn together with gunicorn/supervisor/circus, fronting with nginx etc.etc.)

Other things to keep in mind:

* Using `run()` directly won't give you the debug reloader, unlike `--debug`.
* You'll be running single-process.

Both are things that *could* be addressed.

**Comment by simonw** [comment]
Huh, I'd missed that these were added 26 days ago: https://github.com/encode/uvicorn/commit/07c6c18945ab4f4167118e717e197adce3aee3da#diff-1a523bd9fa0dbf998008b37579210e12

I'm definitely interested in as many options as possible for doing this.

**Comment by lovelydinosaur** [comment]
Tackling this in https://github.com/encode/uvicorn/pull/164

**Comment by lovelydinosaur** [comment]
Closed via #164. See https://www.uvicorn.org/
