### ISSUE TITLE
 Error occurs occasionally when shutdown uvicorn(using Docker and multiple workers)

### ISSUE THREAD

**Issue by tim-chow** [Kludex/uvicorn#1649]
My test code shown below:

% ls
Dockerfile	test.py

```python
# test.py

import uvicorn
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def root():
    return {"hello": "world"}


if __name__ == "__main__":
    uvicorn.run("test:app", host="0.0.0.0", port=8000, workers=10)
```

```Dockerfile
# Dockerfile

FROM python:3.10.7-buster
COPY test.py /
RUN pip install fastapi uvicorn
CMD python /test.py
```

And then build an image in my work directory:

```shell
docker build -t test-uvicorn:20220916 .
```

Start docker container using the command shown below:

```shell
docker run --rm -it  test-uvicorn:20220916
```

**Wait for a moment**, and then press CTRL + C, **Maybe** get outputs like below:

```
INFO:     Finished server process [12]
INFO:     Waiting for application shutdown.
INFO:     Waiting for application shutdown.
INFO:     Waiting for application shutdown.
INFO:     Waiting for application shutdown.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 648, in lifespan
    await receive()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
```

when I repeat these operations many times, The above error will occur occasionally.

**Comment by euri10** [comment]
does it happen without docker ?

**Comment by tim-chow** [comment]
> does it happen without docker ?
It looks all right without docker

**Comment by tim-chow** [comment]
@euri10 It looks all right without docker.

**Comment by Kludex** [comment]
You mean that you are doing CTRL + C multiple times? If that's the case, then it's normal...

**Comment by tim-chow** [comment]
@Kludex I mean that I repeat these operations - [docker run ..., wait for a moment, ..., press CTRL + C] many times. rather than repeating these opertions - docker run, ..., wait for a moment, then only press CTRL + C many times.
