### ISSUE TITLE
after release of 0.19.0 run() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by yt605155624** [Kludex/uvicorn#1719]

**Comment by Kludex** [comment]
Remove the debug argument.

**Comment by Kludex** [comment]
For future reference, the debug parameter was removed without deprecation warning because it was not documented, and there was a 4 years old issue to remove it.

**Comment by TeKett** [comment]
> Remove the debug argument.
Would be great to know how, or where it is in the code, cus i get this when i try to run XL, but dont get it on 1.5.
