### ISSUE TITLE
replacing daphne with uvicorn in django channels

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [Kludex/uvicorn#173]
I got this error below when trying to run uvicorn with django channels. We would like to convert from daphne to uvicorn as we find daphne not suitable for scaling.

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/h11.py", line 170, in run_asgi
    asgi = app(self.scope)
TypeError: 'RedisChannelLayer' object is not callable
```

Uvicorn command used: 
`uvicorn --host 0.0.0.0 --port 8003 --loop asyncio --http h11 project.asgi:channel_layer`

Libraries used:
```
uvicorn==0.2.4
channels==1.1.8
asgi-redis==1.4.3
```

Is it because uvicorn is only compatible with channels 2?

**Comment by lovelydinosaur** [comment]
> Is it because uvicorn is only compatible with channels 2?

Exactly, yes.

The ASGI spec changed significantly with version 2.

**Comment by Dean-Christian-Armada** [comment]
Hi @tomchristie , thanks!
