### ISSUE TITLE
The UVICORN dont start correctly.

### ISSUE THREAD

**Issue by KUASSIISRAEL** [Kludex/uvicorn#1765]
When i start my WEB SERVER UVICORN version 0.19.0 i got this error:

** module 'uvloop' has no attribute 'EventLoopPolicy'**
<img width="1207" alt="Capture d’écran 2022-11-13 à 14 24 40" src="https://user-images.githubusercontent.com/64444325/201526835-4a78ee31-aaed-4849-9b50-3d0dbc090d8b.png">

**Comment by iudeen** [comment]
> The starting point for issues should usually be a discussion...
> 
> https://github.com/encode/uvicorn/discussions
> 
> Possible bugs may be raised as a "Potential Issue" discussion, feature requests may be raised as an "Ideas" discussion. We can then determine if the discussion needs to be escalated into an "Issue" or not.
> 
> This will help us ensure that the "Issues" list properly reflects ongoing or needed work on the project.
> 

Can you please open a [discussion](https://github.com/encode/uvicorn/discussions)?

**Comment by Kludex** [comment]
> > The starting point for issues should usually be a discussion...
> > [encode/uvicorn/discussions](https://github.com/encode/uvicorn/discussions)
> > Possible bugs may be raised as a "Potential Issue" discussion, feature requests may be raised as an "Ideas" discussion. We can then determine if the discussion needs to be escalated into an "Issue" or not.
> > This will help us ensure that the "Issues" list properly reflects ongoing or needed work on the project.
> 
> Can you please open a [discussion](https://github.com/encode/uvicorn/discussions)?

There's no need to suggest that, there's a button on the right to do that "Convert to discussion":
![image](https://user-images.githubusercontent.com/7353520/201609675-7d53e35e-6100-425b-b1b7-9adc20cb7e85.png)
