### ISSUE TITLE
Document Uvicorn as a WSGI & ASGI webserver.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#177]
Given that Uvicorn now has `--wsgi` support, we ought to change the documentation around a bit, and promote it as being suitable for either WSGI or ASGI.

This'll be a more obvious sell once we have HTTP/2 support, but it's probably already a decent alternative to gunicorn/uwsgi/waitress/bjeorn.

**Comment by Kludex** [comment]
@tomchristie Do you still think we should promote Uvicorn as WSGI & ASGI webserver?

**Comment by lovelydinosaur** [comment]
Not sure. I'd be open to switching up the documentation if anyone particularly wants to push for it, but I think it's probably just fine as it is.
