### ISSUE TITLE
Allow application to provide `logger` instance when running uvicorn programmatically

### ISSUE THREAD

**Issue by Gyllsdorff** [Kludex/uvicorn#179]
### Problem:
We have a complicated logging setup with nested logger, custom build handlers which forwards logs to a separate process to make sure logging won't slow down the API:s and other "fun" stuff. I would like to be able to customize which logger Uvicorn is using and have complete controll of the configuration of that logger.

Right now `uvicorn` will always use the root logger and tries to set the root logger configuration, which can cause some issues if `uvicorn.run` is called before the some other piece of code tries to call `logging.basicConfig`.

### Proposed solution:
I can see two different solutions:
1. Add a `logger` parameter to the [`run` method](https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L194). 
   1. If both `log_level` and `logger` is set raise a exception.
   2. If `logger` is not `None` then load the logger using `log_level` [like we do today](https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L223).
2. If `log_level` is a method then use it as the logger. If it is a string, load the logger like today.

My personal opinion is that the first is much better.

I can provide a PR if this sounds like a good idea, @tomchristie.

**Comment by lovelydinosaur** [comment]
Number 1 sounds perfectly reasonable yup. Only consideration is how best to update the docs to reflect that, since it won’t obvious match a command line parameter as the other options do.

**Comment by lovelydinosaur** [comment]
> Right now uvicorn will always use the root logger.

We're using a named logger now, which I think is sufficient to resolve this issue.

**Comment by elyobo** [comment]
@tomchristie I don't think the named logger resolves this issue; see https://github.com/encode/uvicorn/issues/112, because uvicorn constantly calls `logging.basicConfig` it tends to overwrite many changes to the `uvicorn` logger.
