### ISSUE TITLE
HTTP returns "Server disconnected without sending a response" error

### ISSUE THREAD

**Issue by PranathiSG** [Kludex/uvicorn#1792]
Currently I'm performing load test for API in AWS with FastAPI version 0.75, uvicorn version 0.20 and httpx version 0.22. I'm sending 500 requests in 10 seconds. Number of workers in my AWS environment is 10. 

Command to execute my API: "gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --worker-connections 10 main:app'

We have tried by increasing the http timeout of API. httpx.Client(transport=transport, timeout=50), but still error is not getting resolved.

Error Message:
Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=3030931.222841871 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 358, in timeout_keep_alive_handler
    self.conn.send(event)
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/h11/_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/h11/_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/h11/_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/h11/_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

**Comment by Kludex** [comment]
The issue is on the server. I've transferred this to https://github.com/encode/uvicorn/issues/1792.

**Comment by Kludex** [comment]
Same as https://github.com/encode/uvicorn/issues/1637.

I want to solve this, but I was not able to reproduce it.

**Comment by Kludex** [comment]
Any MRE that I can use to reproduce it?

**Comment by moarshy** [comment]
I had the same issue running FastAPI on AWS EKS where I had each pod with 2 workers. The problem was resolved when I used a single worker. Although I didn't further investigate, I think it could have been due to a resource issue.

**Comment by Kludex** [comment]
That's what https://github.com/encode/uvicorn/issues/1637#issuecomment-1321118293 suggests.

But we probably want to improve this error message? :thinking:

**Comment by moarshy** [comment]
ok, I take it back it is happening again for me too. I think the connection breaks after some time. When the job the function has to process is short, everything goes okay but it breaks when it is long.

**Comment by adrienballsonos** [comment]
I am also facing this issue, and I managed to reproduce it by running uvicorn with 4 http workers + FastAPI in a pod on a local k8s cluster. In my case it is apparently triggered when the http worker reaches its memory limit, a simple endpoint like below is enough to trigger the `Empty reply from server` curl error:
```python
    @router.post("/memory/{size}")
    async def memory(size: int):
        huge_list = []
        for i in range(size):
            huge_list.append({f"hello {i}": f"world {i}"})
        return {"status": "ok"}
```

What is confusing is that there is no logs server side when this happens. It's a different story when using uvicorn with a single worker because in that case the pod restarts.

**Comment by Kludex** [comment]
> I am also facing this issue, and I managed to reproduce it by running uvicorn with 4 http workers + FastAPI in a pod on a local k8s cluster. In my case it is apparently triggered when the http worker reaches its memory limit, a simple endpoint like below is enough to trigger the `Empty reply from server` curl error:
> 
> ```python
>     @router.post("/memory/{size}")
>     async def memory(size: int):
>         huge_list = []
>         for i in range(size):
>             huge_list.append({f"hello {i}": f"world {i}"})
>         return {"status": "ok"}
> ```
> 
> What is confusing is that there is no logs server side when this happens. It's a different story when using uvicorn with a single worker because in that case the pod restarts.

This is not an issue, the `uvicorn` process is getting killed by the OS.

If you run `cat /var/log/kern.log` (on Ubuntu), you can see those logs:

```bash
ec 24 11:45:10 kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=docker.scope,mems_allowed=0,task=uvicorn,pid=622954,uid=0
Dec 24 11:45:10 kernel: Memory cgroup out of memory: Killed process 622954 (uvicorn) total-vm:147824kB, anon-rss:99900kB, file-rss:12032kB, shmem-rss:0kB, UID:0 pgtables:348kB oom_score_adj:0
```

And just to be clear, the issue mentioned here is that the server shouldn't be logging what is mentioned in the description. Which I still can't reproduce it.

**Comment by Kludex** [comment]
I'm closing this again, since I can't reproduce it.

If someone finds a way to reproduce it, we can always reopen this.
