### ISSUE TITLE
Bug in website info

### ISSUE THREAD

**Issue by DavidTangye** [Kludex/uvicorn#1798]
Isn't this wrong?

In https://www.uvicorn.org/deployment/:  "Run gunicorn -k uvicorn.workers.UvicornWorker for production."

I pasted it into my system test machine, and got an error. Seems the info for the uvicorn parameter required is mixed up with gunicorn.

**Comment by Kludex** [comment]
Its not wrong, but it's not complete. It's missing the application path.

**Comment by DavidTangye** [comment]
So 'gunicorn' is correct?

**Comment by Kludex** [comment]
Yes: https://www.uvicorn.org/deployment/#gunicorn.
