### ISSUE TITLE
Missing access logging

### ISSUE THREAD

**Issue by freakypie** [Kludex/uvicorn#180]
running `uvicorn --port 7000 asgi:application --debug --log-level debug` spews out debug information, but not access logging. It appears to work, but I don't see anything happening in the console. Am i missing a parameter?

**Comment by lovelydinosaur** [comment]
What version are you running? I believe there was an issue along these lines that got resolved.

**Comment by freakypie** [comment]
uvicorn==0.3.2
python3.6.6

**Comment by freakypie** [comment]
Hey, i just tried against master and nothing there still. I'm using it with django and channels, could the logging config for the site affect the access log of the server?

**Comment by lovelydinosaur** [comment]
Can you reproduce this with a basic hello, world ASGI app?

> I'm using it with django and channels, could the logging config for the site affect the access log of the server?

Perhaps?

**Comment by carltongibson** [comment]
> I'm using it with django and channels

Maybe a stray `disable_exisiting_loggers` (https://docs.djangoproject.com/en/2.1/topics/logging/#configuring-logging)

**Comment by freakypie** [comment]
Yep, that seems to be it. I shot myself in the foot

Would it mess things up to add "uvicorn" to the getLogger  call?

https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L54

**Comment by lovelydinosaur** [comment]
> Would it mess things up to add "uvicorn" to the getLogger call?

Not 100% sure of the implications there but happy to consider PRs.

**Comment by freakypie** [comment]
Here you go:  #181

**Comment by lovelydinosaur** [comment]
We're using named loggers now. `getLogger("uvicorn")`

Thanks for the report!
