### ISSUE TITLE
--reload unaware when process is killed during startup

### ISSUE THREAD

**Issue by sxwebster** [Kludex/uvicorn#1801]
There exists an issue where during the startup phase of the script it can crash silently if the server runs out of memory, originating from a behaviour where the process is killed. This can easily be observed and captured witout using the ```-reload``` switch. When the ```--reload``` switch is in use, however, the ```killed``` response seems to be me missed, and the process appears to be available, without errors, and even reports back the local address and port successfully. 

The port is never opened, the api is unavailable, and the startup sequence that was killed does not restart (this is good behaviour). 

The application thus stays in a hung state where it appears to be working, but isnt. 

To replicate add a pandas dataframe as part of initialisation and fill it with an amount of data that is greater than the memory footprint of the server.    

********* Referenced from a discussion, link below.

What was happening was that when I was using ```-reload``` the memory was being filled during script initialisation and the initialisation process was being killed. The killing of the process seemed to be silent, and the application was still running, looking like it was working. 

When I removed the ```reload``` I was able to see that during initialisation the process was exiting with a "```killed``` message. 

To work out what was happening I ran two SSH sessions side by side. One where I was using ```top``` to monitor memory usage, and the other to initialise and watch FastAPI and Uvicorn output on the CLI. I was able to see memory reaching maximum utilisation with ```top```. 

I hope this helps.

_Originally posted by @sxwebster in https://github.com/encode/uvicorn/discussions/1799#discussioncomment-4347256_

**Comment by Kludex** [comment]
That's correct, but not restrict to startup, this behavior happens after it as well.

We are aware of it, and this is not considered as a bug.

Do you have a proposal here?

**Comment by Kludex** [comment]
Closing this, as there's no bug.

But I'm willing to reopen, if a proposal is given. :pray:
