### ISSUE TITLE
The `reload_delay` setting is invalid when using `WatchFiles`?

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1832]
### Discussed in https://github.com/encode/uvicorn/discussions/1831

<div type='discussions-op-text'>

<sup>Originally posted by **shoucandanghehe** January  4, 2023</sup>
This is my demo code👇
<details><summary>code</summary>

```
import sys
import logging
import uvicorn
from fastapi import FastAPI


app = FastAPI()


logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    stream=sys.stdout,
)

logger = logging.getLogger('uvicorn')

LOG_CONFIG = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'generic',
        }
    },
    'formatters': {
        'generic': {
            'format': '%(asctime)s [%(process)d] [%(levelname)s] %(message)s',
            'datefmt': '[%Y-%m-%d %H:%M:%S]',
            'class': 'logging.Formatter',
        }
    },
    'loggers': {
        'uvicorn': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}


@app.get('/')
def read_root():
    return {'Hello': 'World'}


if __name__ == '__main__':
    uvicorn.run(
        '__main__:app',
        host='0.0.0.0',
        port=8000,
        reload=True,
        reload_delay=120.0,
        log_config=LOG_CONFIG
    )
```
</details>

If I understand correctly, `uvicorn` should reload after 120s of file changes, but actually `uvicorn` seems to start reloading right away. (I can't tell if it's immediately or the default 0.25s)

Here are some logs👇

<details><summary>logs</summary>

```
[2023-01-05 05:03:08] [24864] [INFO] Will watch for changes in these directories: ['D:\\code\\test']
[2023-01-05 05:03:08] [24864] [INFO] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[2023-01-05 05:03:08] [24864] [INFO] Started reloader process [24864] using WatchFiles
[2023-01-05 05:03:09] [11648] [INFO] Started server process [11648]
[2023-01-05 05:03:09] [11648] [INFO] Waiting for application startup.
[2023-01-05 05:03:09] [11648] [INFO] Application startup complete.
[2023-01-05 05:03:19] [24864] [WARNING] WatchFiles detected changes in 'reload_test.py'. Reloading...
[2023-01-05 05:03:19] [34588] [INFO] Started server process [34588]
[2023-01-05 05:03:19] [34588] [INFO] Waiting for application startup.
[2023-01-05 05:03:19] [34588] [INFO] Application startup complete.
```
</details></div>

**Comment by br3ndonland** [comment]
That is my understanding as well - `watchfiles` does not use the `reload_delay` setting. `reload_delay` is only used in one place, in the `uvicorn.supervisors.basereload` module, in `BaseReload().pause()`. `BaseReload().pause()` runs `threading.Event().wait()`.

https://github.com/encode/uvicorn/blob/eec7d22ecc0c8926feb365ac7708918e32725f4f/uvicorn/supervisors/basereload.py#L56-L58

We can see that `class WatchGodReload` runs `pause()`, but `WatchFilesReload` does not.

https://github.com/encode/uvicorn/blob/eec7d22ecc0c8926feb365ac7708918e32725f4f/uvicorn/supervisors/watchgodreload.py#L150-L151

https://github.com/encode/uvicorn/blob/eec7d22ecc0c8926feb365ac7708918e32725f4f/uvicorn/supervisors/watchfilesreload.py#L84-L89

**Comment by Kludex** [comment]
@samuelcolvin do you remember if this was on purpose?

**Comment by shoucandanghehe** [comment]
Have we made any progress?👀

**Comment by Kludex** [comment]
PR welcome to fix this.

**Comment by samuelcolvin** [comment]
sorry not to reply earlier. My instinct is that this is an oversight.

The closest equivilant to `reload_delay` in watchfiles is `debounce` I think, see [here](https://watchfiles.helpmanual.io/api/watch/#watchfiles.watch).

**Comment by aminalaee** [comment]
I have taken a look into this issue and went through watchfiles docs and code.
I might be wrong, but I think Uvicorn `reload-delay` is more similar to Watchfiles `step` than `debounce`. Also trying with `debounce` didn't achieve this but `step` did.

But anyway by  just adding the `pause` this is fixed, Unless we want to specifically use this from watchfiles.
