### ISSUE TITLE
Type of "run" is partially unknown

### ISSUE THREAD

**Issue by AlexanderPodorov** [Kludex/uvicorn#1855]
When using VSCode with `pylance` in "strict" mode:

```python
from uvicorn import run
```
Warning is shown: Type of "run" is partially unknown

**Comment by Kludex** [comment]
Ok... How do we solve it?

**Comment by AlexanderPodorov** [comment]
Honestly... I don't know :-(
I checked it multiple times and the signature looks good.
Found out that:
```python
app: typing.Union["ASGIApplication", typing.Callable, str],
```
where `Callable` is not parametrized, but it looks like it does not resolve this warning.

**Comment by Kludex** [comment]
ah, you need to install asgiref. `pip install asgiref`.

It's because of `ASGIApplication`.

**Comment by AlexanderPodorov** [comment]
Yes, I've already tried it, this was my first guess :-) It did not work.

**Comment by Kludex** [comment]
I've created https://github.com/encode/uvicorn/pull/1863 for this.

**Comment by AlexanderPodorov** [comment]
Very nice, thank you!

**Comment by Kludex** [comment]
I'll be closing this as per https://github.com/encode/uvicorn/pull/1863#issuecomment-1463683747.
