### ISSUE TITLE
Reload options doesn't work when you use uvicorn.Server(config).serve()

### ISSUE THREAD

**Issue by vgulaev** [Kludex/uvicorn#1868]
Looks like forgotten add ChangeReload initialization in serve()
My app:
**main.py**
```
import asyncio
import uvicorn


async def main():
    config = uvicorn.Config(
        "example:app", port=5000, log_level="info", host="0.0.0.0", reload=True
    )
    server = uvicorn.Server(config)
    await server.serve()


if __name__ == "__main__":
    asyncio.run(main())

````
**example.py**
```
async def app(scope, receive, send):
    assert scope["type"] == "http"

    body = f'Received {scope["method"]} request ++++* to {scope["path"]}'
    await send(
        {
            "type": "http.response.start",
            "status": 200,
            "headers": [
                [b"content-type", b"text/plain"],
            ],
        }
    )
    await send(
        {
            "type": "http.response.body",
            "body": body.encode("utf-8"),
        }
    )

```

when use everything works correct:
**main.py**
```
import uvicorn

if __name__ == "__main__":
    uvicorn.run("example:app", port=5000, log_level="info", reload=True, host="0.0.0.0")
```

the only place where ChangeReload exists is in **site-packages/uvicorn/main.py**, sorry for my debug code here
![image](https://user-images.githubusercontent.com/2358096/219000913-266a273c-7153-4179-9cf0-b8cd54305b28.png)

**Comment by Kludex** [comment]
As you pointed yourself, it's intentional.

**Comment by slyapustin** [comment]
@Kludex 
That is worth to be mentioned in the `Running programmatically` section of the documentation:
https://github.com/encode/uvicorn/blob/master/docs/index.md#config-and-server-instances

**Comment by Kludex** [comment]
PR to improve documentation is welcome.

**Comment by slyapustin** [comment]
@Kludex I just created PR #1955

**Comment by declension** [comment]
Came here to say it's not just docs, it's uvicorn logging too, so that might want updating

```
INFO:     Will watch for changes in these directories: ['/home/foo/bar...]
```
