### ISSUE TITLE
Serving static files on Django (Channels)

### ISSUE THREAD

**Issue by ebsaral** [Kludex/uvicorn#193]
Hey there. I am trying to replace Daphne with Uvicorn. Daphne was allowing to serve static files even though it wasn't ideal. 

Now I replaced it, and it works fine right now on staging server, but I am not able to serve static files through Gunicorn with Uvicorn worker. I am on Heroku, so nginx is not an option. I know it would be easier though.

I am using the latest version of everything. Is there any undocumented hack around this? 

I wanted to serve the static files over S3 with django_storage but there are hardcoded static urls in css and js files. This creates complexity. 

Thanks.

**Comment by lovelydinosaur** [comment]
> Daphne was allowing to serve static files even though it wasn't ideal.

I'm not quite sure what you mean - daphne *itself* doesn't have any configuration for serving static files. eg. see https://github.com/django/channels/issues/87

(Although running Django Channels does support it, and you can use either `uvicorn` or `daphne` as the server for running channels. Are you using Channels or some other ASGI framework?)

**Comment by ebsaral** [comment]
@tomchristie excuse my terrible explanation please. I am just new to all this ASGI logic.

I am running Django Channels 2 right now. I was using Django Channels 1.x with Daphne as explained in documentation, and the server was serving static files by adding `route('http.request',  StaticFilesConsumer())` in the channel routing. I am looking for something similar. 

Django Channels 2 should do this automatically in the routing file? 
I see it adds `http->django` by default but I can't access static files. 

The command I am running:
`gunicorn MyApp.asgi:channel_layer -b 0.0.0.0:$PORT -w 2 -k uvicorn.workers.UvicornWorker`

Should I expect Django Channels to serve stating files after running this?

**Comment by ebsaral** [comment]
Or does this require configuration on Django Channels side which is not really related to Uvicorn?

**Comment by lovelydinosaur** [comment]
> Or does this require configuration on Django Channels side which is not really related to Uvicorn?

Exactly, yup.
