### ISSUE TITLE
`middleware/proxy_headers.py`: Inconsistent `x-forwarded-proto` for websockets

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1935]
### Discussed in https://github.com/encode/uvicorn/discussions/1933

<div type='discussions-op-text'>

<sup>Originally posted by **1997cui** April  9, 2023</sup>
Hi,
I recently noticed a potential bug in the `proxy_headers.py` middleware:
 ## The problem 
Upstream reverse proxy (i.e. Caddy or Nginx [Check scheme variable](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_scheme) ) always puts `http` or `https` in `x-forwarded-proto`, even if the request has an `Upgrade header` and is a WebSocket. [This behavior complies with the protocol](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto)

The `proxy_headers.py` passes the value along into the `scope["scheme"]`, even if it is a Websocket. This is not correct. According to the [spec](https://asgi.readthedocs.io/en/latest/specs/www.html#websocket-connection-scope), the scheme should be either `ws` or `wss`. `https` or `http` in `websocket` type cause routing errors.

### app.py
``` python
from quart import Quart, websocket

app = Quart(__name__)

@app.websocket('/test')
async def test():
    await websocket.send('Hello World!')
```

### Caddyfile
```
example.com {
    route /test {
        reverse_proxy http://localhost:5000 {
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Proto {scheme}
        }
    }
}
```

### Run it

 - We accept the upstream proxy header
``` bash
gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 127.0.0.1:5000 --forwarded-allow-ips="*"
```
Result
``` bash
wscat -c "wss://slu.t.cuitian1.com/test"
error: Unexpected server response: 403
```
 - We ignore the upstream header
``` bash
gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 127.0.0.1:5000 --forwarded-allow-ips=""
```
result
``` bash
wscat -c "wss://slu.t.cuitian1.com/test"
Connected (press CTRL+C to quit)
< Hello World!
Disconnected (code: 1000, reason: "")
```
</div>

**Comment by 1997cui** [comment]
I tried to add a pull request #1934 just let please let me know if changes are needed.
