### ISSUE TITLE
logger.level vs logger.getEffectiveLevel() on config load()

### ISSUE THREAD

**Issue by josumoreno-BP** [Kludex/uvicorn#1958]
Hello,

I was wondering why `logger.level` is checked [here](https://github.com/encode/uvicorn/blob/2c0ea0a9b80facd2902634b74987b9165c6018ab/uvicorn/config.py#L507) instead of `logger.getEffectiveLevel()` because at the final stage, the level returned by the `logger.getEffectiveLevel()` is the one that is going to be respected.

So for example, if you set a level INFO for _uvicorn_ logger with a dictConfig (and you don't declare any more loggers) uvicorn will load `MessageLoggerMiddleware`, but in the reality we are not going to see any logs from there because our logger is not going to capture at that level.

So what I think is that on that line, `logger.level` should be changed to `logger.getEffectiveLevel()`. 

I can send a MR if you agree with me.

Sorry if I'm missing something and thanks for taking care of this project.

**Comment by Kludex** [comment]
Can you give an MRE on which the change will benefit you?

**Comment by josumoreno-BP** [comment]
Hey, see here an example:
```
import uvicorn 

async def app(scope, receive, send):
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })

if __name__ == "__main__":
    LOG_CONFIG = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "[%(levelname)s] %(message)s",
            },
        },
        "handlers": {
            "stdout": {
                "level": "NOTSET",
                "class": "logging.StreamHandler",
                "formatter": "simple",
                "stream": "ext://sys.stdout",
            }
        },
        "root": {
            "handlers": ["stdout"],
            "level": "WARNING",
        },
        "loggers": {
            "uvicorn": {
                "handlers": ["stdout"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
    uvicorn.run("main:app", log_config=LOG_CONFIG)
```

I'm setting `uvicorn` logger to log on level `INFO`, so every child logger (`uvicorn.error`, `uvicorn.access`, `uvicorn.asgi`, etc) will use that (unless something specific is declared for them). What this means is that no message logged by `MessageLoggerMiddleware` will be printed to stdout because they are logged at created level TRACE (5).

So the thing is that even having this config, uvicorn will still load the `MessageLoggerMiddleware` because I have not passed explicitly the `log_level` parameter. I think that "the need" of passing the `log_level` parameter along with the `log_config` (or having to declare the child logger levels explicitly in the `log_config`) is an unexpected behavior that leads to execute `MessageLoggerMiddleware` without needing it. 

Checking `getEffectiveLevel()` will return the "real final" level that the logger will log in. So that's why I'm suggesting to change `logger.level` to `logger.getEffectiveLevel()` [here](https://github.com/encode/uvicorn/blob/2c0ea0a9b80facd2902634b74987b9165c6018ab/uvicorn/config.py#L507).

Hope this helps to understand it. If this is still not clear, let me know.

**Comment by Kludex** [comment]
Got it. Thanks. Do you mind creating a PR for it? 🙏
