### ISSUE TITLE
Protocol upgrade request not supported; websocket and install issue

### ISSUE THREAD

**Issue by Judekeyser** [Kludex/uvicorn#1967]
Hello, I've been running an application (framework less!) with GUnicorn and Uvicorn. The set-up goes as the documentation in Uvicorn explains: use the default worker class for GUnicorn, and install Uvicorn using:
```
pip install 'uvicorn[standard]'
```
Everything is actually inside a Docker (which explicitly runs the above line, plus other dependencies) and this is the result of `pip freeze`:
```
anyio==3.6.2
click==8.1.3
gunicorn==20.1.0
h11==0.14.0
httptools==0.5.0
idna==3.4
psycopg==3.1.8
psycopg-c==3.1.8
psycopg-pool==3.1.7
python-dotenv==1.0.0
python-rapidjson==1.10
PyYAML==6.0
sniffio==1.3.0
typing_extensions==4.5.0
uvicorn==0.22.0
uvloop==0.17.0
watchfiles==0.19.0
websockets==11.0.2
```
There is nothing specific in the configuration of GUnicorn (except the worker class `'uvicorn.workers.UvicornWorker'`.

Everything is working really fine and I can use psycopg in asynchronous mode for example. I have no issue when issuing `curl` requests. However, when I attack my server with a Java client, I get those errors:
```
[2023-05-01 15:38:03 +0000] [13] [WARNING] Unsupported upgrade request.
[2023-05-01 15:38:03 +0000] [13] [WARNING] No supported WebSocket library detected. Please use "pip install 'uvicorn[standard]'", or install 'websockets' or 'wsproto' manually.
```

This is confusing me, because that's exactly how I installed the Uvicorn dependency. Moreover, `websockets` clearly is in the pip freeze result. I know the HttpClient of Java can be tweaked to stick to HTTP 1.1, but I haven't done it (actually I don't own the client process). By default, it looks like it tries to upgrade to websocket protocol. If I understand GUnicorn correctly, it should just work out of the box

_Originally posted by @Judekeyser in https://github.com/encode/uvicorn/discussions/1965_

**Comment by Kludex** [comment]
Discussion already exists.
