### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'start_response'

### ISSUE THREAD

**Issue by nihs269** [Kludex/uvicorn#1969]
I have this issue when I run uvicorn with flask api "TypeError: __call__() missing 1 required positional argument: 'start_response'", someone can help me??

**Comment by Kludex** [comment]
Hmm... `uvicorn <app_path> --interface wsgi` maybe?

Please create a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.) if that doesn't solve your issue. Also, please create discussions, and not issues, or use stackoverflow for simple questions.
