### ISSUE TITLE
Combining requests-futures with uvicorn

### ISSUE THREAD

**Issue by Midnighter** [Kludex/uvicorn#197]
I'm trying to use [requests-futures](https://github.com/ross/requests-futures) with uvicorn. Currently, this fails with a `ConnectionError` stemming from urllib3. I can run the below code just fine normally but when I `await` the same coroutine from an API Star request handler there is the mentioned error and I see the following warning:

```
[asyncio] [WARNING] Executing <Task finished coro=<RequestResponseCycle.run_asgi() done, defined at /usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:381> result=None created at /usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:272> took 5.026 seconds
```

Maybe that means the requests are not properly run using a `ThreadPoolExecutor`?

```python
import asyncio

import uvloop
from requests_futures.sessions import FuturesSession


async def make_requests():
    session = FuturesSession(max_workers=1)
    # first request is started in background
    future_one = session.get('http://httpbin.org/get')
    # second requests is started immediately
    future_two = session.get('http://httpbin.org/get?foo=bar')
    # wait for the first request to complete, if it hasn't already
    response_one = future_one.result()
    print('response one status: {0}'.format(response_one.status_code))
    print(response_one.content)
    # wait for the second request to complete, if it hasn't already
    response_two = future_two.result()
    print('response two status: {0}'.format(response_two.status_code))
    print(response_two.content)


asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(make_requests())
finally:
    loop.close()
```

**Comment by lovelydinosaur** [comment]
I think the error your seeing implies that you're running some thread-blocking code inside one of the handlers. (eg https://pymotw.com/3/asyncio/debugging.html)

That's not a uvicorn issue as such. You might want to try to get a simple reproducible example running using either a plain ASGI application, or just using Starlette, in order to try to keep things as simple as possible.

I might be able to help you a little with figuring out where to look, but I'll close the issue as this doesn't appear to be a uvicorn problem. (Also an option: Try running the same code under hypercorn or daphne, and see if you can reproduce)

**Comment by Midnighter** [comment]
Just wanted to confirm here that the above **does** work with a simple `Starlette` as well as `apistar.ASyncApp` run via uvicorn and via gunicorn with `UviCornWorker`. Time to dig deeper.

**Comment by Midnighter** [comment]
And it all turned out to be a [DNS problem with docker-compose](https://github.com/docker/compose/issues/2847) :rage:

**Comment by gogobook** [comment]
I has same issue, thanks @Midnighter . I also think it's DNS problem with docker-compose.

**Comment by Midnighter** [comment]
You can solve it by directly defining the DNS IP in your `docker-compose.yml`. Something like:

```yaml
services:
  web:
    dns:
    - 8.8.8.8
    - 8.8.4.4
```
