### ISSUE TITLE
Running Uvicorn on unix socket

### ISSUE THREAD

**Issue by balazss** [Kludex/uvicorn#200]
I'm having trouble running uvicorn on a unix socket with --uds... How do I use this setting?

I've tried everything I can think of in the command line and in systemd as well...

env/bin/uvicorn appname.asgi:application --uds unix:/run/uvicorn/appname.sock and every other combination I can think of seems to produce a FileNotFoundError: [Errno 2] No such file or directory, but the directory is there...

Am I missing something?

**Comment by lovelydinosaur** [comment]
Uvicorn won't create the UDS file itself. If you're taking this deployment approach then the supervisor process (supervisord/circus/whatever) is responsible for creating the domain socket, and passing that to the uvicorn processes.
