### ISSUE TITLE
Use `httpx` as client on WebSocket tests

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#2012]
The idea would be to eliminate `websockets` client from the test suite, and use what is described here: https://github.com/encode/httpx/issues/304#issuecomment-1325333860

The motivation is to simplify the test suite.

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2012">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2012/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2012/pledge.svg">
</picture>
</a>

**Comment by frnsimoes** [comment]
I'm looking into this.

**Comment by kaypee90** [comment]
@Kludex is the idea to use this kind of implementation https://gist.github.com/tomchristie/3293d5b118b5646ce79cc074976744b0 for the WebSocket tests

**Comment by Kludex** [comment]
Yes. Some tweak is needed to use `app=app`.

**Comment by kaypee90** [comment]
@Kludex  app is passed to the config like this
```
config = Config(
        app=app,
        ws=ws_protocol_cls,
        http=http_protocol_cls,
        lifespan="off",
        port=unused_tcp_port,
    )
```
Which is then passed to run_server `async with run_server(config):`
No sure why you need `app=app` for [this](https://gist.github.com/tomchristie/3293d5b118b5646ce79cc074976744b0)

**Comment by likecodingloveproblems** [comment]
I have opened a [PR](https://github.com/encode/uvicorn/pull/2108) for this issue

**Comment by Kludex** [comment]
Let's continue with the current setup. I thought the test suite would be simplified, but that's not the case.
