### ISSUE TITLE
Add page about encode and sponsors to the documentation

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#2123]
The idea is to have a bit more information about the organization, linking the other encode projects on the documentation.

Also, making sure that our sponsors are visible.

cc @tomchristie (good?)

**Comment by lovelydinosaur** [comment]
Yas.

The challenging part is how we manage it...

**Comment by Kludex** [comment]
I have an idea. I'll present it when I have time. But in short, you can link external markdown pages on mkdocs using a plugin.

**Comment by Kludex** [comment]
Closing this from here, we'll manage this on the [organization repo](https://github.com/encode/.github).
