### ISSUE TITLE
`--reload-include` doesn't work with hidden files e.g. `--reload-include .env`

### ISSUE THREAD

**Issue by michaeloliverx** [Kludex/uvicorn#2166]
### Initial Checks

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
https://github.com/encode/uvicorn/discussions/1705
```

### Description

The `--reload-include` CLI flag doesn't work when specifying a hidden file directly e.g.
```sh
uvicorn src.main:app --reload --reload-include .env
```

### Python, Uvicorn & OS Version

```Text
Running uvicorn 0.23.2 with CPython 3.11.5 on Darwin
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2166">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2166/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2166/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
@michaeloliverx Is this done?

**Comment by adithya04dev** [comment]
its still not reloading after the .env file changes

**Comment by enigma** [comment]
@adithya04dev and who else might be having a similar issue: you need to have `watchfiles` installed for `--reload-include` to work.

eg: `uv run --with watchfiles python -m uvicorn ... --reload-include '.env'`

You'll then see:

```
INFO:     Started reloader process [107] using WatchFiles
INFO:     Started server process [109]
WARNING:  WatchFiles detected changes in '.env'. Reloading...
```


See https://www.uvicorn.org/settings/#reloading-with-watchfiles
