### ISSUE TITLE
[Question] Lifespan Protocol best practices

### ISSUE THREAD

**Issue by leobuskin** [Kludex/uvicorn#220]
The current implementation of ASGI lifespan protocol looks nice, the only question - what's the preferred way to use it? So, an app needs to create a connection pool to 3rd party service on startup and gracefully close it on shutdown. I've implemented lifespan protocol support, but not sure about the best practices to store a context (a reference to the connection pool, for example). The app itself will be instantiated on each request, so global variables? Static class properties?

Would really appreciate any examples / best practices here.

**Comment by lovelydinosaur** [comment]
May as well be globals, or a global instance that you store attributes on yup.

You might also want to take a look at Starlette's `LifetimeHandler` and `LifetimeContext` which could come in handy.

See: https://www.starlette.io/events/

**Comment by leobuskin** [comment]
Great sample, totally forgot about Starlette, thank you!
