### ISSUE TITLE
WebSockets and --max-requests does not reload Workers

### ISSUE THREAD

**Issue by lesc6** [Kludex/uvicorn#2201]
### Initial Checks

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
https://github.com/encode/uvicorn/discussions/2146
```

### Description

If you use independent server for websocket connection, you expect that Worker process will be killed after N requests, but it will never killed it consume more and more memory.
use any ws client to reproduce.

### Example Code

```Python
gunicorn --bind=unix:/tmp/ws.sock --worker-class=uvicorn.workers.UvicornWorker --workers=1 --max-requests=10
```

### Python, Uvicorn & OS Version

```Text
any
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2201">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2201/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2201/pledge.svg">
</picture>
</a>

**Comment by lesc6** [comment]
https://github.com/benoitc/gunicorn/issues/3086

**Comment by fatelei** [comment]
from the code, ws protocol not update `total_requests`, so the max requests is not worked. ws is long connection, so it doesn't have request and response, i think it worked as expected.

**Comment by lesc6** [comment]
a client still has to start the WebSocket handshake process by contacting the server and requesting a WebSocket connection.  The client will send a pretty standard HTTP request with headers that looks like
[https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers](url)
```
GET /chat HTTP/1.1
Host: example.com:8000
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Version: 13
```

**Comment by lesc6** [comment]
the problem is more global, suppose you have a web chat that works only on websockets and you have 10 workers that constantly work without rebooting; they constantly increase memory costs, which leads to complete failure of the application.

**Comment by Kludex** [comment]
> from the code, ws protocol not update `total_requests`, so the max requests is not worked. ws is long connection, so it doesn't have request and response, i think it worked as expected.

Actually, this is it.
