### ISSUE TITLE
scope["server"] and scope["client"] must be a two-item iterable

### ISSUE THREAD

**Issue by gdamjan** [Kludex/uvicorn#223]
According to the [asgi spec](https://asgi.readthedocs.io/en/latest/specs/www.html#connection-scope)
> both scope["server"] and scope["client"]  must be either a two-item iterable of [host, port] or None (the default).

The problems is that in certain configurations, where the socket is a unix domain socket (ex. with gunicorn), transport.get_extra_info("sockname") and "peername" will return a string with the unix domain socket.
https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/httptools_impl.py#L143-L144

This will break any apps correctly assuming scope["server"] and scope["client"] are two items.

**Comment by lovelydinosaur** [comment]
Thanks for reporting this!
