### ISSUE TITLE
Debug not working on run command 

### ISSUE THREAD

**Issue by helioascorreia** [Kludex/uvicorn#231]
I'm trying out a basic example with uvicorn

```
import uvicorn


class App():
    def __init__(self, scope):
        self.scope = scope

    async def __call__(self, receive, send):
        await send({
            'type': 'http.response.start',
            'status': 200,
            'headers': [
                [b'content-type', b'text/plain'],
            ]
        })
        await send({
            'type': 'http.response.body',
            'body': b'Hello, world!',
        })
```
Running in terminal with the command `uvicorn --port 5000 --debug  main:App` it's ok, but adding the following code on the file the auto reloading doesn't work.

```
if __name__ == '__main__':
    uvicorn.run(App, host="127.0.0.1", port=5000, log_level="info", debug=True)
```

Am I doing something wrong?

**Comment by lovelydinosaur** [comment]
Auto-reloading isn’t supported when running programmatically.

**Comment by helioascorreia** [comment]
Oh ok, I saw the example of Starlette that runes programmatically. So what is the best approach to run it in development and have auto reloading?

**Comment by lovelydinosaur** [comment]
`uvicorn example:App —debug`

**Comment by helioascorreia** [comment]
Ok, thanks for the help
