### ISSUE TITLE
what's the relationship between "log_config" in     uvicorn.run('main:app', host="127.0.0.1", port=8051, log_config="log.ini")  and logging.getLogger(__name__)?

### ISSUE THREAD

**Issue by sanwei111** [Kludex/uvicorn#2365]
### Initial Checks

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
hello,sir.
i wtite a log.ini,pass it for the para of log_config in  uvicorn.run('main:app', host="127.0.0.1", port=8051, log_config="log.ini").

besides, i initializes class of logger by：self._logger = logging.getLogger(__name__) in some file.

i found that the log generated by self._logger can be found in the log file defined by "log_config".

so,question is:
 1. why?
 2. how can i output some dynamic log to the log file formally?
```

### Description

111111111111111111

### Example Code

```Python
111111111111111
```

### Python, Uvicorn & OS Version

```Text
1111111111111111
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2365">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2365/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2365/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Please create a discussion.
