### ISSUE TITLE
Having a Hard Time Replacing Default Server Header

### ISSUE THREAD

**Issue by Jitsusama** [Kludex/uvicorn#243]
Hello;

I'm using uvicorn to front-end an ASGI application of mine and I'm loving it! There is only one slight marring of the beautiful steed which is uvicorn; I have been unable to find a means whereby I can over-ride the sending of the `Server: uvicorn` header on all outbound responses.

When using HTTP1.1 as the transport protocol, I see in the _uvicorn.protocols.http.h11_impl_ module a `_get_default_headers` function. I can see that this in turn gets called by `H11Protocol#tick`, which overrides whatever value that the global `DEFAULT_HEADERS` variable holds, which in turn is what gets augmented to the headers of every outbound request in the `RequestResponseCycle#send` method.

Is there a strong reason for this? If not, is there any desire with the existing devs to enable this to be disabled/changed? Or, is there a desired approach that someone else should take if they would wish to introduce a PR that would change this behaviour?

**Comment by lovelydinosaur** [comment]
I think we should support a `-h/--header` interface to allow developers to explicitly set particular headers (and to override the default "Server" one)

Should all be much cleaner to do since https://github.com/encode/uvicorn/pull/302

**Comment by Jitsusama** [comment]
@tomchristie; that sounds wonderful! Would you also supply an API method/parameter to do this?

**Comment by lovelydinosaur** [comment]
Yup - it'd be available as part of the `Config`

**Comment by antirais** [comment]
In the meantime, this [gist](https://gist.github.com/antirais/17f5d5c1b7b5ee7a1150bbea1dd9a802) will demonstrate how to monkey patch response headers.

**Comment by Jitsusama** [comment]
Hey @antirais; I had thought about over-riding that method, but it makes me feel uncomfortable, given how intrinsic it is to the inner-workings of uvicorn. I feel like messing with that will require constant vigilance as the upstream changes.

**Comment by antirais** [comment]
> I feel like messing with that will require constant vigilance as the upstream changes.

That is true, it's not perfect. Hopefully this issue will be resolved quickly and there is no need to maintain the monkey patch for too long.

**Comment by lovelydinosaur** [comment]
If anyone wants to take a crack at a pull request adding `headers` to the config, and command line options that'd be most welcome!

**Comment by Jitsusama** [comment]
Hey @tomchristie; I'm taking a look now. Should tests for this go in `tests/protocols/test_http.py`? I can't find any other place that really makes sense.

**Comment by Jitsusama** [comment]
Actually, looking closer at how you test, it looks like you perform more integration/functional tests. I'd be tempted to create a test module named `test_custom_default_headers`, but I'm not sure what directory it would best fit in.

**Comment by lovelydinosaur** [comment]
Welcome to start by issuing a PR without a test case, as a starting point.

**Comment by Jitsusama** [comment]
K, I'll probably throw tests in first, 'cause that's how I roll, but I'll understand if they get moved/substantially changed afterwards.

**Comment by Jitsusama** [comment]
Alright, I cut a PR. Who needs sleep when you can hack on OSS code, eh? 😆

**Comment by Jitsusama** [comment]
PR has been merged which resolves this issue.
