### ISSUE TITLE
Mach9

### ISSUE THREAD

**Issue by 38elements** [Kludex/uvicorn#25]
I forked Sanic and created [Mach9](https://github.com/silver-castle/mach9).
Mach9 is a web application framework based on ASGI.
Mach9 can be integrated [Uvicorn](https://github.com/silver-castle/mach9-cookbook/blob/master/uvicorn.md).

**Comment by lovelydinosaur** [comment]
Neat! Might be worth having the app.__call__ be the entry point, as that'd be more typical. Could also be worth pursuing a pull request to sanic itself? Any particular points of note in what you needed to change to implement this?

**Comment by 38elements** [comment]
Thank you for your reply.
I will make entry point to app.\_\_call\_\_().
Mach9 have only Http response and Http request stream.
Sanic has Http response, Http request stream, Http response stream and WebSocket.
Mach9 does not have Http response stream and WebSocket.
Since Mach9 become slow for big change, I think it is not merged.
I do not send pull request.
I will add other ASGI feature to Mach9.

I changed Request, Protocol, Response and Request Handler for ASGI.
In Sanic, request is generated and request body is got in protocol.
In Mach9, request is generated and request body is got in request handler.

**Comment by lovelydinosaur** [comment]
Cool, thanks for letting us know about this. If we end up having a section with frameworks that support the messaging interface then we'll add Mach9 there. Nice work!
