### ISSUE TITLE
Exit without close process pool, then produce many zombie processes

### ISSUE THREAD

**Issue by weaming** [Kludex/uvicorn#256]
## How to produce:

1. Add a long-running task in background using `multiprocessing.Pool.apply_async()`
2. `Ctrl-C` to interrupt the uvicorn
3. Run `htop` you will see the process with `S`tatus `Z`

## Advice
After catch signal, uvicorn should call `gc.collect()` which will call my class's `__del__` method.

**Comment by lovelydinosaur** [comment]
> After catch signal, uvicorn should call gc.collect() which will call my class's __del__ method.

Okay, I'd happily accept a pull request adding that.

However, also important to note that you probably ought to be using the  ASGI `lifespan` messages in order to properly manage long-lived resource startup/shutdown.
