### ISSUE TITLE
Configure workers

### ISSUE THREAD

**Issue by ferndot** [Kludex/uvicorn#266]
It would be great if the gunicorn workers could support uvicorn's config options.

I would like to run a Django Channels project using them, but cannot do so at this time because the `disable_lifespan` option from #262 cannot be set.

**Comment by lovelydinosaur** [comment]
Yeah indeed, that’d be nice. Thoughts on how best to approach that would be most welcome.

**Comment by lovelydinosaur** [comment]
Related: Have we dug into whichever part of the ASGI ecosystem doesn’t yet support lifespan?
Is it channels? It’d be great to get that up to speed too.

**Comment by ferndot** [comment]
I believe it is channels since they do not have any mention of lifespan in their docs or code. I opened an issue: https://github.com/django/channels/issues/1216

**Comment by lovelydinosaur** [comment]
We provide (undocumented) support for this now...

```python
class CustomWorker(UvicornWorker):
    CONFIG_KWARGS = {...}
```

I guess I'll leave the ticket open until we've documented this.

**Comment by kubami** [comment]
Is the custom class with `CONFIG_KWARGS` still the best option (ha!)?

I see there is an `--env-file` parameter, but I am not sure if it's possible to pass it to `uvicorn` from `gunicorn`.

For completeness there is a ticket for `lifespan` protocol in Django now as well: https://code.djangoproject.com/ticket/31508

**Comment by thomasmodeneis** [comment]
bump

**Comment by Kludex** [comment]
> bump

?

**Comment by beruic** [comment]
Since Django won't support lifespan as per https://code.djangoproject.com/ticket/31508, can we reopen this?

If nothing else, at least to document it.

**Comment by beruic** [comment]
I take that back. This beliongs in https://github.com/Kludex/uvicorn-worker
