### ISSUE TITLE
NameError: name 'Config' is not defined

### ISSUE THREAD

**Issue by yamnikov-oleg** [Kludex/uvicorn#282]
Can't start `gunicorn` with `uvicorn.workers.UvicornWorker` worker:

```
Task exception was never retrieved
future: <Task finished coro=<UvicornWorker.create_servers() done, defined at /usr/local/lib/python3.7/site-packages/uvicorn/workers.py:107> exception=NameError("name 'Config' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 109, in create_servers
    config = Config(
 NameError: name 'Config' is not defined
```

Apparently introduced in [this commit](https://github.com/encode/uvicorn/commit/3b2ab797cf77816e05780bda2de29cc6070b9d1f) 4 hours ago. You deploy so fast! :)

**Comment by lovelydinosaur** [comment]
Should now be resolved in 0.3.28, just deployed.
We don't have any test coverage over the gunicorn worker class at the moment - that needs fixing.
