### ISSUE TITLE
Use invoke instead of bash scripts?

### ISSUE THREAD

**Issue by almarklein** [Kludex/uvicorn#297]
I cannot run the scripts (e.g. `scripts/lint`) on Windows. How would you feel about using `invoke` for this? The idea is that you create a `task.py` in the root directory (example [here](https://github.com/almarklein/asgish/blob/master/tasks.py)) where you define "commands" as functions. Then you just run `invoke test`, `invoke lint`, etc.

Edit: this is not urgent, and no more than a suggestion :)

**Comment by lovelydinosaur** [comment]
Possibly, yes. Tho I guess the more minimal version of that would be: convert all the scripts into python.

I think I'd consider this kind of thing on the basis of an example pull request, but otherwise not treat it as an open issue.
