### ISSUE TITLE
Sanic compatibility?

### ISSUE THREAD

**Issue by hashgupta** [Kludex/uvicorn#3]
Is this software compatible with sanic, or does sanic need asgi interface to work with this?

**Comment by lovelydinosaur** [comment]
I'll be following that up, here: https://github.com/channelcat/sanic/issues/761#issuecomment-306891018

Right now there's still some work to do on thrashing out the interface. I'll be making some more concrete proposals to folks in the near future.

**Comment by tomchristie** [comment]
s/fine//

**Comment by lovelydinosaur** [comment]
Going to close this off for now. Yes at some point the intent will be to promote an ASGI-based interface, both for asyncio frameworks, and for websocket support in non-asyncio frameworks.

**Comment by jstriebel** [comment]
If someone else comes here: The current discussion takes place in https://github.com/huge-success/sanic/pull/1475
