### ISSUE TITLE
pure uvicorn vs uvicorn workers for gunicorn

### ISSUE THREAD

**Issue by unittolabs** [Kludex/uvicorn#303]
Hey, guys!

It can be a noob question, but it's really interesting for me.
Why I should use gunicorn with the uvicorn workers instead of using pure uvicorn?
Which features we don't have in uvicorn, but is too good for production?

**Comment by lovelydinosaur** [comment]
So: Gunicorn will give you multiple worker processes, as well as monitoring and restarting any crashed processes. We might start to have some of those things built directly into Uvicorn at some point, but for now if you want multiple processes you need to use Gunicorn or some other process manager such as circus.

**Comment by unittolabs** [comment]
@tomchristie but if I use docker swarm or kubernets as the main way to scaling my app and the single process will ok for me, I can use uvicorn instead of gunicorn, correct?

tnx for your answer!

**Comment by lovelydinosaur** [comment]
Possibly yes. I’ve not used either, so I couldn’t say for sure if you’d be getting more efficient resource usage by having multi-process-per-container.

**Comment by jacobsvante** [comment]
@tomchristie I think that you should recommend running pure uvicorn in production when using container orchestrators such as Kubernetes and set the number of containers (processes) there instead. Kubernetes (and probably its competitors) has options to automatically scale containers up and down depending on CPU and memory usage, thus minimizing the resource usage.

**Comment by lovelydinosaur** [comment]
@jmagnusson - Yes I think we'll end up going that way.

**Comment by shuvozula** [comment]
It'll be nice if the [documentation](https://www.uvicorn.org/#running-with-gunicorn) is updated to use Uvicorn in Swarm/Kubernetes environments. Thanks!

**Comment by trallnag** [comment]
@jmagnusson This also works better with Prometheus instrumentation since you don't have to rely on the not-perfect multiprocessing functionality of the Prometheus client. Just to add to your comment in case someone comes across this

**Comment by yackx** [comment]
This is an old, closed issue but this comment may help future visitors. We run a large Starlette monolith on Google Cloud k8s with the following command:

```
CMD ["gunicorn", "-w", "1", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "app:app"]
```

We changed to

```
CMD ["uvicorn", "--host", "0.0.0.0", "app:app"]
```

When the changed rolled to different production environments, pods started to "freeze". We had to manually recycle them (k8s itself would not do it). We did not perform a post-mortem, we simply reverted back to the original.

Maybe we did something wrong, or it's just something particular with our setup but beware.

**Comment by rushilsrivastava** [comment]
> When the changed rolled to different production environments, pods started to "freeze".

Adding a warning for future visitors as well. We run on Google Cloud Run, and after switching to using Uvicorn from Gunicorn, we started seeing intermittent CPU spikes like below:

![Container CPU utilization](https://user-images.githubusercontent.com/11495473/153702603-548d3dc3-25d8-4a36-967c-41b901458459.png)

Switching back to Gunicorn alleviated all these problems, while handling the same concurrency. This seems to be contrary to the [suggested strategy](https://fastapi.tiangolo.com/deployment/docker/#one-process-per-container) on the FastAPI docs. It's possible we've done something wrong as well, but figured I would add this experience here.

**Comment by adriangb** [comment]
This is interesting. I don't think there's anything about using pure uvicorn that would cause issues vs. Gunicorn. Are you using Uvicorn workers or just a single process?

**Comment by rushilsrivastava** [comment]
> Are you using Uvicorn workers or just a single process?

I was using a single process in both Uvicorn and Gunicorn. Could probably extract more performance from Gunicorn if I used workers though.

**Comment by adriangb** [comment]
Tricky if you're on Cloud Run with 1 CPU though. I haven't used Cloud Run but in Kubernetes if you set use 2 workers with 1CPU as a resource limit, and if you ever hit full CPU usage on your workers (unlikely unless you're doing ML, but likely if you are) you could go over your resource limits and your pod will can get killed.

But I think I'm going to try Cloud Run and play around with this, good learning experience

**Comment by Dannynis** [comment]
Any update on this ? As im trying to understand which method is preferred, I found myself quite lost... also from my experience the kubernetes auto scalers are not as good as the kernel scheduler so it's not the best solution.. which brings us to uvicorn workers vs gunicorn workers

**Comment by yashpct2807** [comment]
I have the same question, which method is suitable when we use uvicorn over kebernetes? In my experience, I am using single uvicorn having autoscaling aks pods. I have not tried using guvicorn. However I would like to know the difference in terms of performance.

**Comment by harshag** [comment]
> > When the changed rolled to different production environments, pods started to "freeze".
> 
> Adding a warning for future visitors as well. We run on Google Cloud Run, and after switching to using Uvicorn from Gunicorn, we started seeing intermittent CPU spikes like below:
> 
> ![Container CPU utilization](https://user-images.githubusercontent.com/11495473/153702603-548d3dc3-25d8-4a36-967c-41b901458459.png)
> 
> Switching back to Gunicorn alleviated all these problems, while handling the same concurrency. This seems to be contrary to the [suggested strategy](https://fastapi.tiangolo.com/deployment/docker/#one-process-per-container) on the FastAPI docs. It's possible we've done something wrong as well, but figured I would add this experience here.

We ran into same issue, switched to uvcorn workers within guincorn to handle async better but soon ran into multiple spikes in CPU which was never the case with just gunicorn. Used same number of workers.
Using Flask framework on Python v3.10, if thats of any help

**Comment by adriangb** [comment]
> > > When the changed rolled to different production environments, pods started to "freeze".
> > 
> > 
> > Adding a warning for future visitors as well. We run on Google Cloud Run, and after switching to using Uvicorn from Gunicorn, we started seeing intermittent CPU spikes like below:
> > ![Container CPU utilization](https://user-images.githubusercontent.com/11495473/153702603-548d3dc3-25d8-4a36-967c-41b901458459.png)
> > Switching back to Gunicorn alleviated all these problems, while handling the same concurrency. This seems to be contrary to the [suggested strategy](https://fastapi.tiangolo.com/deployment/docker/#one-process-per-container) on the FastAPI docs. It's possible we've done something wrong as well, but figured I would add this experience here.
> 
> We ran into same issue, switched to uvcorn workers within guincorn to handle async better but soon ran into multiple spikes in CPU which was never the case with just gunicorn. Used same number of workers. Using Flask framework on Python v3.10, if thats of any help

My recommendation is to _not_ use workers at all. Just use a single process / thread and scale via Google Cloud Run.
