### ISSUE TITLE
Add websocket max size

### ISSUE THREAD

**Issue by divad** [Kludex/uvicorn#306]
Uvicorn does not appear to support setting a web socket max message size. 

Without such an option an attacker can overwhelm the memory of an application running within Uvicorn (a denial of service). 

Other frameworks such as aiohttp, tornado and Sanic have max message size options. Hypercorn also has a max message size:

https://gitlab.com/pgjones/hypercorn/blob/master/hypercorn/config.py#L55

It is discussed/documented here: https://pgjones.gitlab.io/hypercorn/dos_mitigations.html#large-websocket-message

Cheers!

**Comment by lovelydinosaur** [comment]
It would be worth looking at the wsproto and websockets packages here. Do either of them include a limit by default? (We support either)

**Comment by lovelydinosaur** [comment]
But either way, yes we should definitely have this as a configuration setting.

**Comment by cgarciae** [comment]
Hey, any updates on this?

**Comment by lovelydinosaur** [comment]
@cgarciae Nope - we'd use this ticket if there was any progress.
If anyone wants to take a crack at a pull request for it I'd happily help review & get it in.

**Comment by pgjones** [comment]
> It would be worth looking at the wsproto

I don't think wsproto has something for this (may have forgotten), but I do this in Hypercorn - firstly there is a [config setting](https://github.com/pgjones/hypercorn/blob/master/hypercorn/protocol/ws_stream.py#L147) then it is checked in the [message buffer](https://github.com/pgjones/hypercorn/blob/master/hypercorn/protocol/ws_stream.py#L121). Also see [Some commentary](https://pgjones.gitlab.io/hypercorn/dos_mitigations.html#large-websocket-message)

**Comment by selimb** [comment]
Looks like #538 fixes this, but has been collecting dust? Needing to switch to a different web server just to have control over that option is unfortunate :(

Many thanks for your time spent on this project.

**Comment by untereiner** [comment]
Hello,

I was reading this issue and I am wondering about two size parameters. 
I think there are two sizes who comes into play: 
- the max WebSocket message payload size: the maximum size in bytes allowed for a complete WebSocket message (with multiple frames) which I think is discussed by this issue
- the max WebSocket frame payload size: the maximum size in bytes allowed for a single WebSocket frame.

I don't see the second in wsproto.
I see it in [websockets](https://github.com/aaugustin/websockets/blob/master/src/websockets/legacy/server.py) that has a `max_size` parameter. But, I don't see it in unicorn's [implementation](https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/websockets/websockets_impl.py)

Can someone enlighten me ?
What if a websocket subprotocol wants to negotiate these sizes prior to establishing the WebSocket connection ?
