### ISSUE TITLE
Uvicorn can't get client's ip address, and port when listening to ipv6 address

### ISSUE THREAD

**Issue by Yolley** [Kludex/uvicorn#313]
I have an app, which I need to bind to ipv6 host, so my run.py script looks like this

```
import uvicorn
from app import create_app


if __name__ == '__main__':
    uvicorn.run(create_app(), port=8001, host='::')
```
Also I need access logs from this app. If I look in my logs with this setup, I can see messages like this:
`INFO: None - "GET /docs HTTP/1.1" 200`

So, where client info should be seen (his ip address and port), there is just None value. If I use, for example, hypercorn with command like this
`hypercorn app.main:app --access-log - -b :::8001
`
In logs I can see client's ip address and port
`::1:65427 GET /docs 1.1 200 839 5501`

Is it possible to somehow support ipv6 clien't ip addresses in uvicorn?

**Comment by lovelydinosaur** [comment]
@Yolley Seems like a valid issue yup. If you or anyone else would like to progress this, the best thing would be to start by looking into what differences there are between:

1. How Hypercorn vs. Uvicorn bind the socket.
2. How Hypercorn vs. Uvicorn get the address for logging.

**Comment by Yolley** [comment]
@tomchristie 
I found the row, which causes this
https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/utils.py#L3
So, with ipv6 address length of "info" variable in my case was 4
`('::1', 56937, 0, 0)`
In hypercorn length of address is not checked, but in case of IPV6 they just return first 2 elements of  an address tuple
https://github.com/pgjones/hypercorn/blob/764e0fe967f7fe6abb8baf4787a9609c5be7601b/hypercorn/utils.py#L97

**Comment by lovelydinosaur** [comment]
Okay, so I think we should use `>= 2` there then.

```python
def get_remote_addr(transport):
    info = transport.get_extra_info("peername")
    if info is not None and isinstance(info, (list, tuple)) and len(info) >= 2:  # Here
        return (str(info[0]), int(info[1]))
    return None


def get_local_addr(transport):
    info = transport.get_extra_info("sockname")
    if info is not None and isinstance(info, (list, tuple)) and len(info) >= 2:  # Here
        return (str(info[0]), int(info[1]))
    return None
```

That'd resolve the issue robustly, right?

**Comment by lovelydinosaur** [comment]
Great work tracking this down!

**Comment by Yolley** [comment]
> Okay, so I think we should use `>= 2` there then.
> 
> ```python
> def get_remote_addr(transport):
>     info = transport.get_extra_info("peername")
>     if info is not None and isinstance(info, (list, tuple)) and len(info) >= 2:  # Here
>         return (str(info[0]), int(info[1]))
>     return None
> 
> 
> def get_local_addr(transport):
>     info = transport.get_extra_info("sockname")
>     if info is not None and isinstance(info, (list, tuple)) and len(info) >= 2:  # Here
>         return (str(info[0]), int(info[1]))
>     return None
> ```
> 
> That'd resolve the issue robustly, right?

I am not sure, what is the appropriate way to resolve this, will it create some security issues, if we just check length of an address, without checking socket family? (I believe, we can get socket with command like this `transport.get_extra_info("socket")` and then get `socket.family` like they do in hypercorn https://github.com/pgjones/hypercorn/blob/764e0fe967f7fe6abb8baf4787a9609c5be7601b/hypercorn/asyncio/base.py#L26 ). If not, then ye, it resolves the issue.

**Comment by lovelydinosaur** [comment]
Okay, yeah looks more sensible.

**Comment by Yolley** [comment]
> Okay, yeah looks more sensible.

Do I need to submit a pull request, or will you fix it?

**Comment by lovelydinosaur** [comment]
If you'd like to see it resolved quickly, the best thing to do would be to submit a pull request yes.
