### ISSUE TITLE
File-based configuration

### ISSUE THREAD

**Issue by florimondmanca** [Kludex/uvicorn#322]
Hi there,

Has file-based configuration ever been considered for uvicorn? By that, I mean starting the server via a config file which we contain values for any made available by the `uvicorn` command.

[gunicorn has this feature](http://docs.gunicorn.org/en/stable/configure.html#configuration-file) and I like how the config file is just a plain Python script, which allows to do any sorts of computation (e.g. deriving the number of workers from the number of CPUs). File-based configuration also allows the server config to be version-controlled and written *once and for all* for a given project.

As an illustration, I imagine that file-based configuration would allow to use:

```python
# config.py
import os
import multiprocessing

host = "0.0.0.0"
port = 5050
workers = 2 * multiprocessing.cpu_count() + 1
log_level = "debug"
reload = not os.environ.get("PRODUCTION")
```

```bash
uvicorn -c config.py app:app
```

Instead of:

```bash
uvicorn --host="0.0.0.0" --port=5050 --workers=4 --log-level=debug --reload app:app
```

**Comment by lovelydinosaur** [comment]
It took me a while to dig it, but yeah, we should totally have *exactly* that, as described above.

**Comment by florimondmanca** [comment]
So, do we really want to *not* provide any kind of validation / editor support, then?

As I wrote in #323, using `Config` is more type- and typo-safe, as IDEs have built-in ways of telling us "you passed the wrong parameter", or "it's the incorrect type". And we don't lose the possibility to make intermediary computations.

Or maybe we just want people to not even depend on `Config` as a piece of public API?

**Comment by lovelydinosaur** [comment]
The trade off is that this is just a nicer, more natural style - I *think* I’d prefer it now, even if it mean you need to get the names right.
What do others think?

**Comment by lovelydinosaur** [comment]
I guess I’m on the fence tho.

**Comment by florimondmanca** [comment]
I'll close this, since I've actually been able to do without this very well since I posted this issue. :-)

**Comment by maquino1985** [comment]
Would be great if this was reopened and worked on. I think it's very helpful with my gunicorn apps, not sure how to configure uvicorn at all if its being run from a docker container pointing to an app (e.g. fastapi) and not run explicitly via the backend

**Comment by rusmux** [comment]
@tomchristie Are there any updates on this?

**Comment by noorameera26** [comment]
+1 @tomchristie would love to hear updates as well
