### ISSUE TITLE
uvicorn.org

### ISSUE THREAD

**Issue by isbm** [Kludex/uvicorn#327]
Guys, http://www.thewebsiteisdown.com ... (talking about uvicorn.org which throws at everything 404).

**Comment by lovelydinosaur** [comment]
Okay thanks - I think that ought to resolve shortly (A docs deploy had omitted the CNAME file).

You can use https://www.encode.io/uvicorn/ in the meantime.

Let's leave this ticket open until we know that it's fully resolved.

**Comment by lovelydinosaur** [comment]
Okay looks fixed to me now - thanks for letting me know! :)

**Comment by lovelydinosaur** [comment]
![Screenshot 2019-03-13 at 14 17 25](https://user-images.githubusercontent.com/647359/54285898-be35fc80-459a-11e9-95dc-d685657214ea.png)
