### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS' on Python ,,,3.5.2

### ISSUE THREAD

**Issue by ruanimal** [Kludex/uvicorn#330]
Python 3.5 ssl module has no  attribute 'PROTOCOL_TLS'

![image](https://user-images.githubusercontent.com/14031394/54822018-d87c8280-4cde-11e9-9f36-f38699921ba9.png)

**Comment by ruanimal** [comment]
![image](https://user-images.githubusercontent.com/14031394/54822326-be8f6f80-4cdf-11e9-821d-963f4f4cc1e9.png)

**Comment by lovelydinosaur** [comment]
Okay, thanks. Will try to look into that sometime.
Are you able to upgrade to 3.6+?

**Comment by Hanaasagi** [comment]
I have not see any error message, when run `docker run -it --rm python:3.5-alpine python -c "import ssl;ssl.PROTOCOL_TLS"`.

And in Pyhton 3.5 doc https://docs.python.org/3.5/library/ssl.html#ssl.PROTOCOL_TLS
![屏幕快照 2019-04-04 18 47 11](https://user-images.githubusercontent.com/9482395/55550130-15e30600-570a-11e9-8a5a-e5548abc14b0.png)

More info, see this port pull request https://github.com/python/cpython/commit/598894ff48e9c1171cb2ec1c798235826a75c7e0

**Comment by lovelydinosaur** [comment]
Right, so our minimum version is 3.5.3, then I guess.
@ruanima which *exact* python version are you on?

**Comment by ruanimal** [comment]
@tomchristie  Right, my Python version is  3.5.2.  I will upgrade it to 3.6.

**Comment by simonw** [comment]
I just ran into this one trying to run Uvicorn on https://glitch.com/ - which is a real shame because that would be an amazing environment for demos. They are likely to upgrade Python at some point but it's not clear when.

**Comment by simonw** [comment]
I got my demo working with Daphne instead https://twitter.com/simonw/status/1121572280637595648

**Comment by lovelydinosaur** [comment]
Believe this to now be resolved with 0.7.1

**Comment by simonw** [comment]
Hooray! I now have Uvicorn running on Glitch: https://glitch.com/~asgi-uvicorn
