### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by gogobook** [Kludex/uvicorn#333]
Lack of `assert scope['type'] == 'http'` in the example of document will cause an `AssertionError`

**Comment by lovelydinosaur** [comment]
Make sure you're running the latest version of uvicorn.

I see this...

```python
async def app(scope, receive, send):
    # assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```

```shell
$ uvicorn example:app
INFO: Started server process [57966]
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

**Comment by gogobook** [comment]
May try this again? please.
```py
class EchoBody():
    def __init__(self, scope):
        self.scope = scope

    async def read_body(self, receive):
        """
        Read and return the entire body from an incoming ASGI message.
        """
        body = b''
        more_body = True

        while more_body:
            message = await receive()
            body += message.get('body', b'')
            more_body = message.get('more_body', False)

        return body


    async def __call__(self, receive, send):
        body = await self.read_body(receive)
        await send({
            'type': 'http.response.start',
            'status': 200,
            'headers': [
                [b'content-type', b'text/plain'],
            ]
        })
        await send({
            'type': 'http.response.body',
            'body': body,
        })
```

**Comment by lovelydinosaur** [comment]
Ah thanks. Docs were a bit out of date.
I've updated them to new ASGI-3 versions.

**Comment by anentropic** [comment]
What does:
> ASGI 'lifespan' protocol appears unsupported 

mean?

**Comment by lovelydinosaur** [comment]
ASGI has support for `http`, `websocket`, and `lifespan` message types.
Some servers may not support all message types.

https://asgi.readthedocs.io/en/latest/

**Comment by anentropic** [comment]
I seem to get it when there is an error during start up

e.g. if there is an uncaught exception during Starlette `on_event('startup')` handler I don't see the exception logged but I see "ASGI 'lifespan' protocol appears unsupported" and the server starts up anyway 

if I handle the exception then that message goes away

**Comment by lovelydinosaur** [comment]
Gotcha - you could probably open an issue for that.
It looks like we're not currently using the `lifespan.startup.failed` message anywhere, which we ought to do on startup failures.

**Comment by anentropic** [comment]
would this be a Starlette issue?

**Comment by lovelydinosaur** [comment]
Yup

**Comment by lovelydinosaur** [comment]
Uvicorn will correctly abort if it gets sent that message.
