### ISSUE TITLE
Invoke from command line via python -m uvicorn

### ISSUE THREAD

**Issue by uranusjr** [Kludex/uvicorn#334]
Would this be a good idea? It is as simple as creating a `uvicorn/__main__.py` with:

```python
if __name__ == "__main__":
    from .main import main
    main()
```

**Comment by lovelydinosaur** [comment]
Don't know - is there any concrete benefit to that?

**Comment by lovelydinosaur** [comment]
Vs. running `uvicorn`.

**Comment by lovelydinosaur** [comment]
I'm going to close this off as a "probably not", but could consider it if there's a convincing argument, and also demonstration that other servers or similar are taking this approach.

**Comment by uranusjr** [comment]
The only significant benefit is that it is easier to tell which Python interpreter I’m running against. Uvicorn is by design to be installed into the same environment as the target application, and if there are multiple Python installations on PATH, it may not be immediately apparent what a given `uvicorn` command is tied to, even if I use the absolute path. `/path/to/python -m uvicorn` (or `py -[version] -m uvicorn` on Windows) is by contrast much more obvious. There is also virtually no downside to providing such an entry point, even if the command is preferred.

There seems to be a recent trend in Python packaging to attempt to distinguish between standalone (e.g. mypy and black) and in-environment commands (e.g. pytest and pip), with the difference being whether the installation method matters to how the tool behaves. Tools in the latter category is tightly coupled with the Python environment it is installed in, and `python -m` is thus preferred to make this obvious. This is however only conceptual, and does not have a practical difference at the moment.

As for other servers specifically, [Waitress](https://docs.pylonsproject.org/projects/waitress/en/latest/) supports this invocation method.

**Comment by lovelydinosaur** [comment]
Fair enough.
I'd prefer to pass on it at this point in time.
Perhaps if it gets re-raised at a later date then could reconsider.

**Comment by Diaoul** [comment]
I think its good practice to have a runnable module. In my case it would be useful to run uvicorn from a PyCharm Python Configuration.
As for other libraries using it, I could name a few on the top of my head: [pip](https://pip.pypa.io/en/stable/installing/#upgrading-pip), [venv](https://docs.python.org/dev/library/venv.html#creating-virtual-environments), [gunicorn](http://docs.gunicorn.org/en/stable/2013-news.html#id4)

There is no complexity in this, just another entrypoint.

**Comment by lovelydinosaur** [comment]
Okay, probably happy to accept a pull request for this.

**Comment by retnikt** [comment]
I want to write a PR for this because:
- I tried to use `python -m uvicorn` in a PyCharm Python run configuration, like @Diaoul pointed out
- I found that uvicorn had no `__main__.py`
- I tried to use `python -m uvicorn.main` but encountered this [annoying warning](https://stackoverflow.com/questions/43393764/python-3-6-project-structure-leads-to-runtimewarning)
- I found this issue and want to resolve it

However, I just wanted to check if this is actually open. The last comment says
> Okay, probably happy to accept a pull request for this.

but the issue is closed.
