### ISSUE TITLE
byes_data not working with Channels consumers

### ISSUE THREAD

**Issue by agronick** [Kludex/uvicorn#335]
Uvicorn sends its data like this:

```
        is_text = isinstance(data, str)
        return {
            "type": "websocket.receive",
            "text": data if is_text else None,
            "bytes": None if is_text else data,
        }
```

Channels generic consumers work like this:
```
    def websocket_receive(self, message):
        """
        Called when a WebSocket frame is received. Decodes it and passes it
        to receive().
        """
        if "text" in message:
            self.receive(text_data=message["text"])
        else:
            self.receive(bytes_data=message["bytes"])
```

Since `text` is present but set to none `self.receive` is called with text_data discarding the bytes_data when it is present.

I don't know if this is a bug in Uvicorn or Channels. Its a simple fix either way. Either don't set it on the dict or the channels people should check if its a truthy value and not just present.

**Comment by lovelydinosaur** [comment]
We're following the ASGI spec fine there. https://asgi.readthedocs.io/en/latest/specs/www.html#receive

Channels should really be using `if message.get("text") is not None`

*However* I'd still be perfectly happy to accept a pull request that made a switch on `if is_text`.
