### ISSUE TITLE
Feature request: unix socket owner and permision settings

### ISSUE THREAD

**Issue by em92** [Kludex/uvicorn#337]
By default, uvicorn sets 0755 permission flags to unix socket and using current user and group.
```
srwxr-xr-x 1 eugene eugene 0 мар 28 11:56 /tmp/uvicorn.sock
```

For example, if app is running on user `eugene` and nginx worker is running on user `www-data`, nginx won't be able to access socket and will return 502 error. One of the solutions is to change permission flags and group id of the file.
```
srwxrwxr-x 1 eugene www-data 0 мар 28 12:00 /tmp/uvicorn.sock
```
(assuming `eugene` is in group `www-data`)

Quick patch example:
```diff
diff --git uvicorn/config.py uvicorn/config.py
index 5200032..8f51e69 100644
--- uvicorn/config.py
+++ uvicorn/config.py
@@ -71,6 +71,9 @@ class Config:
         host="127.0.0.1",
         port=8000,
         uds=None,
+        uid=None,
+        gid=None,
+        chmod=None,
         fd=None,
         loop="auto",
         http="auto",
@@ -103,6 +106,9 @@ class Config:
         self.host = host
         self.port = port
         self.uds = uds
+        self.uid = uid
+        self.gid = gid
+        self.chmod = chmod
         self.fd = fd
         self.loop = loop
         self.http = http
diff --git uvicorn/main.py uvicorn/main.py
index ab88499..4d6a986 100644
--- uvicorn/main.py
+++ uvicorn/main.py
@@ -22,6 +22,22 @@ from uvicorn.config import (
 )
 from uvicorn.supervisors import Multiprocess, StatReload
 
+
+class BasedIntParamType(click.ParamType):
+    name = 'integer'
+
+    def convert(self, value, param, ctx):
+        try:
+            if value[:2].lower() == '0x':
+                return int(value[2:], 16)
+            elif value[:1] == '0':
+                return int(value, 8)
+            return int(value, 10)
+        except ValueError:
+            self.fail('%s is not a valid integer' % value, param, ctx)
+
+
+BASED_INT = BasedIntParamType()
 LEVEL_CHOICES = click.Choice(LOG_LEVELS.keys())
 HTTP_CHOICES = click.Choice(HTTP_PROTOCOLS.keys())
 WS_CHOICES = click.Choice(WS_PROTOCOLS.keys())
@@ -52,6 +68,9 @@ HANDLED_SIGNALS = (
     show_default=True,
 )
 @click.option("--uds", type=str, default=None, help="Bind to a UNIX domain socket.")
+@click.option("--uid", type=int, default=-1, help="Owner ID of a UNIX domain socket.")
+@click.option("--gid", type=int, default=-1, help="Group ID of a UNIX domain socket.")
+@click.option("--chmod", type=BASED_INT, default=0o755, help="Mode of a UNIX domain socket.")
 @click.option(
     "--fd", type=int, default=None, help="Bind to socket from this file descriptor."
 )
@@ -196,6 +215,9 @@ def main(
     host: str,
     port: int,
     uds: str,
+    uid: int,
+    gid: int,
+    chmod: int,
     fd: int,
     loop: str,
     http: str,
@@ -228,6 +250,9 @@ def main(
         "host": host,
         "port": port,
         "uds": uds,
+        "uid": uid,
+        "gid": gid,
+        "chmod": chmod,
         "fd": fd,
         "loop": loop,
         "http": http,
@@ -360,6 +385,8 @@ class Server:
         elif config.uds is not None:
             # Create a socket using UNIX domain socket.
             server = await loop.create_unix_server(create_protocol, path=config.uds)
+            os.chmod(config.uds, config.chmod)
+            os.chown(config.uds, config.uid, config.gid)
             message = "Uvicorn running on unix socket %s (Press CTRL+C to quit)"
             self.logger.info(message % config.uds)
             self.servers = [server]
```

**Comment by lovelydinosaur** [comment]
Okay - we could probably consider something along these lines if either daphne or gunicorn provide some kind of similar settings.

**Comment by em92** [comment]
>  we could probably consider something along these lines if either daphne or gunicorn provide some kind of similar settings.

Bump @andrewgodwin and @benoitc

**Comment by lovelydinosaur** [comment]
@em92 - I'd suggest the other way around - if this functionality is something *you're* interested in - then have a look at the docs for those projects, rather than asking for time from their maintainers.

**Comment by em92** [comment]
I see. Checked out daphne. Could not found any settings with chmod and chown, but I have found out, that by running 
```
daphne -u /tmp/daphne.sock example:app
```
we will have:
```
srw-rw-rw- 1 eugene eugene 0 мар 28 20:04 /tmp/daphne.sock
```
which is good, 'cos nginx works fine with it. Then how about setting same permissions in uvicorn?

**Comment by lovelydinosaur** [comment]
Sure thing

**Comment by lovelydinosaur** [comment]
I guess check out if daphne uses chown or chmod next? Or if this works some other way around.

**Comment by em92** [comment]
> I guess check out if daphne uses chown or chmod next? Or if this works some other way around.

- it builds some `endpoints`:
https://github.com/django/daphne/blob/9c574083ff04037cd728bfda351b5ca3327f1fff/daphne/cli.py#L248-L254
- passes to some server_class
- for every endpoint it runs this:
https://github.com/django/daphne/blob/9c574083ff04037cd728bfda351b5ca3327f1fff/daphne/server.py#L120
- `serverFromString` is https://github.com/twisted/twisted/blob/8292869715d9471681ffff32296bc73b946868a3/src/twisted/internet/endpoints.py#L1669
- and finally we have: https://github.com/twisted/twisted/blob/8292869715d9471681ffff32296bc73b946868a3/src/twisted/internet/endpoints.py#L1149-L1153

See mode = 0o666 as `__init__` argument. Daphne does not pass non-default mode arguments

**Comment by lovelydinosaur** [comment]
Okay. Very happy to accept any PRs that set the UDS permissions appropriately.

**Comment by lovelydinosaur** [comment]
Let’s avoid having them as config if possible.
