### ISSUE TITLE
Eventloop running at import time from CLI

### ISSUE THREAD

**Issue by thmsmlr** [Kludex/uvicorn#346]
Thanks for all the great work on uvicorn. This issue is more of a question than a bug. 

Consider the following `run.py`
```python
import asyncio
import uvicorn

print('Event loop running?: ', asyncio.get_event_loop().is_running())

async def app(scope, receive, send):
    pass

if __name__ == '__main__':
    uvicorn.run(app, host='127.0.0.1', port=5000, log_level='info')
```

When we run it programmatically we get,

```
➤ python run.py
Event loop running?:  False
INFO: Started server process [30067]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
```

Where as when we run it through the CLI

```
➤  uvicorn run:app
Event loop running?:  True
INFO: Started server process [29952]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

There seems to be inconsistent behavior here depending on how the application is run. It was my understanding that you don't want the event loop to be running when a module is imported. Since the `await` keyword isn't support at the module level you are forced to run any async code at import by executing `loop.run_until_complete(...)` but that will throw an error in the case of uvicorn running from the CLI with the error `RuntimeError: this event loop is already running.`. 

I dived into the code and it seems like it's happening because in `main.py` you are lazily importing the code via the `Config` object in the `async serve(...)` function. 

https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L310-L311

What do you think about hoisting that call into the `def run(...)` function before the event loop is started, but after the event loop is setup? That way the programmatic and the CLI will have the same behaviour.

Thanks again for the great project!

**Comment by ohmeow** [comment]
I'm having a similar issue.  Ever get any resolution?

**Comment by lovelydinosaur** [comment]
I think a reasonable way to tweak this would be to include config loading in the `run(...)` method.

```python
    config = self.config
    if not config.loaded:
        config.load()
```

However, I'd generally recommend avoiding having to carew about this at all, by using the `lifespan` ASGI event to startup any async services, rather than using `loop.run_until_complete` at import time.

**Comment by lovelydinosaur** [comment]
I'll happily accept a pull request adding early config loading prior to calling into `.start()`
