### ISSUE TITLE
websockets_impl not compatible with django-channels WebsocketConsumer

### ISSUE THREAD

**Issue by Rtik1988** [Kludex/uvicorn#348]
Hello, I use the following setup:
```
django==2.2
channels==2.1.7
uvicorn==0.6.1
protobuf==3.7.1
```
and run the following command:
``` uvicorn --port 8001 --host 0.0.0.0 --workers 1 --log-level debug mysite.asgi:application```

Protobuf is used - the messages are binary.

I have a consumer that inherits from WebsocketConsumer. The consumer don't receive any data. I took a look into the implementation of the WebsocketConsumer and found the following code:
```
    def websocket_receive(self, message):
        """
        Called when a WebSocket frame is received. Decodes it and passes it
        to receive().
        """
        if "text" in message:
            self.receive(text_data=message["text"])
        else:
            self.receive(bytes_data=message["bytes"])
``` 

Even-though the messages themselves are binary the "text" key in the received dictionary still exists.

The code that generates this dictionary is located under `websockets_impl.py` and contains the following code:
```
    async def asgi_receive(self):
        ....
        return {
            "type": "websocket.receive",
            "text": data if is_text else None,
            "bytes": None if is_text else data,
        }
``` 

This issue can be bypassed by using the wsproto instead:
```uvicorn --port 8001 --host 0.0.0.0 --workers 1 --log-level debug --ws wsproto mysite.asgi:application ```

**Comment by lovelydinosaur** [comment]
We're following the ASGI spec correctly here... 

https://asgi.readthedocs.io/en/latest/specs/www.html#receive

"Exactly one of bytes or text must be non-None. One or both keys may be present, however."

It looks to me like this issue needs to be raised against channels instead.

The switch case should probably be `if message.get("text") is not None:`

**Comment by lovelydinosaur** [comment]
I would probably consider merging a pull request which switched us around to *only* populating *either* `bytes` or `text`. (But not going to consider this as an issue otherwise)
