### ISSUE TITLE
Command 'uvicorn' not found

### ISSUE THREAD

**Issue by Legionof7** [Kludex/uvicorn#353]
I installed Uvicorn with pip install uvicorn but I can't run it from command line. I'm on Ubuntu 18.04.2 LTS

**Comment by rbw** [comment]
I'm guessing you mean that the shell you're using is unable to find the uvicorn executable.

If you did a user install, the executable probably ended up in **~/.local/bin/**. If it's there, you'll probably want to add that directory to your *PATH*.

**Comment by pankajPizone** [comment]
Didnt find command uvicorn in macos

**Comment by hkovacs** [comment]
the following worked for me: 

1. create your virtual environment && cd into environment
2. activate environment
3. pip install uvicorn
4. uvicorn --help
it works!

**Comment by darkbluee** [comment]
If you are in a Python virtual environment terminal, try the following (depending on python version)

`python -m uvicorn --help `
`python3 -m uvicorn --help`

If you have a command like `uvicorn main:app --reload` then appending `python -m` or `python3 -m` at the beginning should work

**Comment by rubenslyra** [comment]
run command: 
python3  -m uvicorn main:app --reload

**Comment by Kludex** [comment]
As mentioned on the previous comments, this is not a `uvicorn` issue. In any case, the comments above should be helpful to solve your issue. 

I'm going to lock this issue to avoid comments that may confuse other people. If you have a similar issue, feel free to create a discussion, or talk to us on Gitter.
