### ISSUE TITLE
Json Logger

### ISSUE THREAD

**Issue by jordic** [Kludex/uvicorn#356]
I'm not pretty sure if this is the component where we should add this features, anyway, I explain.
We will deploy our componet, to a k8 pod, and there, the standard log aggregation is in json format.

Do you think makes sense to have this kind of behaviour in uvicorn?

**Comment by lovelydinosaur** [comment]
Possibly related to https://github.com/encode/uvicorn/pull/351

> Do you think makes sense to have this kind of behaviour in uvicorn?

We can adapt what info goes into our logging calls, but *how* the logging is then used is probably beyond the scope of the project itself.

**Comment by rspadim** [comment]
#680
