### ISSUE TITLE
The notify callback is not called on time

### ISSUE THREAD

**Issue by rjwittams** [Kludex/uvicorn#360]
https://github.com/encode/uvicorn/blob/545a2a10859165db016d02a641f0c30d07476af1/uvicorn/main.py#L404

On this line we rely on the 0.1 second ticks that occur to notify gunicorn in time. Jitter or cpu bound or naughty blocking io can cause these ticks to gradually fall behind and the process gets killed.

We should use the call to time that we do a few lines above and store the last time we notified in a member variable rather than the ticks, and make sure we have a margin so we definitely don’t notify too late.

**Comment by lovelydinosaur** [comment]
Sounds reasonable.
Have you observed this behavior in the wild?

**Comment by rjwittams** [comment]
Unfortunately yes!
Call to a bit of cpu intensive but still relatively quick code (~1-2secs). Gradually the ticks get behind.
Took a bit of tracking down. Obviously it can be avoided with executors but its a pretty bad failure mode.

**Comment by lovelydinosaur** [comment]
Gotcha. Pull requests towards resolving this obvs. welcome, but it'll be on my list either way.

**Comment by rjwittams** [comment]
I have a fix, will make a PR later or tomorrow. Just 5 lines or so

**Comment by rjwittams** [comment]
Any chance of taking a look at this PR?
