### ISSUE TITLE
Uvicorn should handle headers as any iterables, not just lists (ASGI spec compliance)

### ISSUE THREAD

**Issue by JerzySpendel** [Kludex/uvicorn#366]
[ASGI Specification](https://asgi.readthedocs.io/en/latest/specs/www.html#response-start) in the `Response Start` says that if I send `http.response.start`, the `headers` part should be of the following form:

(Iterable[[byte string, byte string]])

>  A iterable of [name, value] two-item iterables, where name is the header name, and value is the header value. Order must be preserved in the HTTP response. Header names must be lowercased. Optional; defaults to an empty list.

So let's have an ASGI compliant application of the following form:

```
async def application(scope, receive, send):
    await send(
        {
            "type": "http.response.start",
            "headers": ([b"content-type", b"text/plain"],),
            "status": 200,
        }
    )
    await send({"type": "http.response.body", "body": b"dupa"})
```

After requesting this I get the following in the console:

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/jerzy/venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "./asgi.py", line 9, in application
    "status": 200,
  File "/home/jerzy/venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 427, in send
    headers = self.default_headers + message.get("headers", [])
TypeError: can only concatenate list (not "tuple") to list

```

Looks like the headers have to be list of list, not simple iterable of 2-items iterable. Do you think this is important? If we want to be 100% compliant with ASGI spec uvicorn should handle just any iterables. If you agree, do you think I could prepare a patch?

**Comment by lovelydinosaur** [comment]
Seems reasonable, yup.
I guess `self.default_headers + list(message.get("headers", []))` would do the trick.

**Comment by JerzySpendel** [comment]
Yep, it helps. I've opened PR with the code you suggested.
