### ISSUE TITLE
Secure scheme headers should match Gunicorn more closely.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#369]
Our existing secure scheme behaviors is to only include the middleware if `--proxy-headers` is set. For one thing this means we don't have any way of turning it on when deploying with gunicorn, since there's no equivalent gunicorn setting.

For another thing, it'd probably be nicer behavior to match gunicorn more closely, which uses "secure_scheme_headers" to determine which headers to trust, plus "forwarded_allow_ips" to determine *when* an upstream proxy should be trusted to set the headers correctly: https://docs.gunicorn.org/en/stable/settings.html#secure-scheme-headers

Originally from: https://github.com/encode/starlette-example/issues/6
Related to: https://github.com/encode/uvicorn/issues/343

**Comment by devsetgo** [comment]
What is the mechanism to solve this currently as I've run into it as an issue.

solved my issue here: [https://github.com/encode/starlette/issues/538](https://github.com/encode/starlette/issues/538)

**Comment by lovelydinosaur** [comment]
> What is the mechanism to solve this currently as I've run into it as an issue.

@devsetgo Use `--proxy-headers` in the meantime, or a custom middleware if you need something more complex.

**Comment by lovelydinosaur** [comment]
Related: We should also honor `WEB_CONCURRENCY`

**Comment by lovelydinosaur** [comment]
Now resolved in 0.10 - We support `--forwarded_allow_ips` and default to the value of `$FORWARDED_ALLOW_IPS` or `"127.0.0.1"`.
