### ISSUE TITLE
Include query_string in access logs

### ISSUE THREAD

**Issue by simonw** [Kludex/uvicorn#382]
Uvicorn doesn't currently include the query_string in the logging output.

I need the query_string for my own projects - to analyze what people are searching for on the site for example.

Is there a reason not to include the query_string? Assuming there is, what's the most elegant way for me to reconfigure Uvicorn in my own projects to include this?

**Comment by lovelydinosaur** [comment]
I guess it was either just a stylistic choice, or didn't get considered either ways around.
I'd probably be happy to have it added in there.
We *might* want to have a look at configurable access log styles. (?)

**Comment by simonw** [comment]
Pull request: https://github.com/encode/uvicorn/pull/384

**Comment by lovelydinosaur** [comment]
Resolved in #384
