### ISSUE TITLE
Not respecting Django's CONN_MAX_AGE database setting

### ISSUE THREAD

**Issue by singhravi1** [Kludex/uvicorn#386]
Hi,
I'm using `uvicorn` with `gunicorn`.
I have assigned CONN_MAX_AGE setting a value say 300 but its closing the connection instantly after completing the request.

My gunicorn configuration is like,

> 
> bind = '0.0.0.0:8000'
> workers = 3
> secure_scheme_headers = {'X-FORWARDED-PROTO': 'https'}
> reload = True
> errorlog = '-'
> loglevel = 'debug'
> worker_class = 'uvicorn.workers.UvicornWorker'
> 

And i'm running the following command to start the server,
> gunicorn -c gunicorn.conf.py myproject.asgi:application

**Comment by lovelydinosaur** [comment]
`CONN_MAX_AGE` is a setting that determines the maximum age of the database connection.

Doesn’t appear related to Uvicorn.

**Comment by singhravi1** [comment]
@tomchristie But the connection is persistent when used with wsgi and without uvicorn worker class.

Any reason you can think of?

**Comment by lovelydinosaur** [comment]
Maybe start by trying other ASGI servers: daphne, hypercorn.

If you can isolate this issue to specifically uvicorn, then we should dig further.

**Comment by singhravi1** [comment]
Hey @tomchristie, thanks for your suggestion.

I tried all the ASGI servers, i.e. uvicorn, daphne, hypercorn
Every one of them was disconnecting database connection after the request completion.

But when i try running gunicorn with wsgi application, it does not disconnects the database server just after the request completion (respects the CONN_MAX_AGE).

What is the reason behind ASGI servers not respecting this django setting?

Would you recommend running chat server separate from the web server (that would also be a workaround for this)?

**Comment by lovelydinosaur** [comment]
Not sure, but this needs raising on channels or django or something - its not a uvicorn issue.

**Comment by patrik7** [comment]
I do not think this is a uvicorn issue.

I this this provides some more light: https://github.com/benoitc/gunicorn/issues/996 although I was not able to solve the problem yet.
