### ISSUE TITLE
LICENSE.md installed in the wrong place?

### ISSUE THREAD

**Issue by simonw** [Kludex/uvicorn#392]
I just got the following odd looking error while trying to run `pip3 install -U datasette` on my laptop:

```
Installing collected packages: uvicorn, datasette
  Found existing installation: uvicorn 0.8.3
    Uninstalling uvicorn-0.8.3:
      Successfully uninstalled uvicorn-0.8.3
  Rolling back uninstall of uvicorn
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/LICENSE.md'
```

It looks to me like the `LICENSE.md` from Uvicorn may have been accidentally installed in the wrong place - in `/usr/local/LICENSE.md`

Presumably the cause is this line in setup.py:

https://github.com/encode/uvicorn/blob/15c4e9cfe2d996bd73ed6b542e44160f620b9519/setup.py#L64

I've never quite got my head around how `data_files` is meant to work in `setup.py` - is there something wrong here?

**Comment by mikebobadilla** [comment]
Just ran into this as well

**Comment by Hanaasagi** [comment]
Emm, it's interesting. `LICENSE.md` is installed in my virtualenv home.

**Comment by Hanaasagi** [comment]
It seems that `data_files` is a valid parameter in `distutils.core.setup`. It's a sequence of (directory, files). The directory should be a relative path. It is interpreted relative to the installation prefix (Python’s `sys.prefix` for system installations; `site.USER_BASE` for user installations). I think if the directory is a empty string, files will be moved to `sys.prefix`.

And `setuptools` is built on top of `distutils`. Some parameters are reserved. That is the reason we found `LICENSE.md` is installed in the wrong place.

Ref: https://docs.python.org/3/distutils/setupscript.html#installing-additional-files

**Comment by lovelydinosaur** [comment]
I think I'd like us to remove LICENSE.md from the data files, as we already include license info in the META section. I'm happy to review this, but anything we do should be consistent across the whole range of projects in `encode`.

**Comment by lovelydinosaur** [comment]
One good option here might be to make sure that our long_description includes the license file, rather than using `data_files`.

**Comment by Hanaasagi** [comment]
Some project use `MANIFEST.in` to include their license file, for example https://github.com/python-trio/trio/blob/master/MANIFEST.in

**Comment by euri10** [comment]
Closing this as it seems c14e89e552831e8b4c10e9d6de93834d63f7b97f fixed it
