### ISSUE TITLE
SyntaxError in "Streaming responses" section of usage documentation

### ISSUE THREAD

**Issue by nottheswimmer** [Kludex/uvicorn#394]
https://github.com/encode/uvicorn/blob/329e9669d363f348c93ef62125be386643a715ea/docs/index.md#L307-L328

The above snippet is missing a colon after `for chunk in [b'Hello', b', ', b'world!']` which results in a SyntaxError.

**Comment by lovelydinosaur** [comment]
Resolved in https://github.com/encode/uvicorn/pull/422
