### ISSUE TITLE
Ability to manage the 'max_size' settings for incoming messages.

### ISSUE THREAD

**Issue by hozblok** [Kludex/uvicorn#398]
I am using using Uvicorn with the `websockets`protocol implementation. So the problem is that when I send a large enough message through web sockets (> 1 Mb), the web socket connection is closed. I found that `websockets.server.WebSocketServerProtocol` has the `max_size=1048576` argument:
https://websockets.readthedocs.io/en/stable/api.html?highlight=WebSocketServerProtocol#websockets.protocol.WebSocketCommonProtocol
```
The max_size parameter enforces the maximum size for incoming messages in bytes. The default value is 1 MiB. None disables the limit. If a message larger than the maximum size is received, recv() will raise ConnectionClosedError and the connection will be closed with code 1009.
```

Is it possible to add the ability to manage this setting in Uvicorn?

**Comment by florimondmanca** [comment]
Hi, this might be a duplicate of #306, which suggests controlling max size too.

**Comment by lovelydinosaur** [comment]
Indeed. Very happy to accept a pull request for it. Closing as a duplicate, but appreciated.
