### ISSUE TITLE
Provide access to transport information

### ISSUE THREAD

**Issue by hashbrowncipher** [Kludex/uvicorn#400]
Use case: I would like to access the peer certificate sent by a TLS client.

Issue: As far as I can tell, no information about the transport (including TLS session information) is available to the App.

I have currently implemented a temporary workaround which exposes the full `transport` object as part of the `scope` passed to the app.

```
diff --git a/uvicorn/protocols/http/h11_impl.py b/uvicorn/protocols/http/h11_impl.py
index 240cb35..cf5fd67 100644
--- a/uvicorn/protocols/http/h11_impl.py
+++ b/uvicorn/protocols/http/h11_impl.py
@@ -191,6 +191,7 @@ class H11Protocol(asyncio.Protocol):
                     "raw_path": raw_path,
                     "query_string": query_string,
                     "headers": self.headers,
+                    "transport": self.transport,
                 }
```

Within my code, I use `scope['transport'].get_extra_info("ssl_object").getpeercert(binary_form=True)` to access the relevant information.

Feature request: Provide a way for applications to fetch information about the transport they are communicating over, potentially as an [asgi extension](https://github.com/django/asgiref/blob/master/docs/extensions.rst).

**Comment by lovelydinosaur** [comment]
Interesting. I’d suggest taking a proposal to the ASGI spec first. 👍

**Comment by MohamedAmineOuali** [comment]
Hello,

Are there any update about this feature?

**Comment by MohamedAmineOuali** [comment]
Hello guys,

What do you think about doing a monkey patching of the on_url method instead of changing the source code of uvicorn?

Is there problem if I putting the transport object in the scope ?


```
from uvicorn.protocols.http.httptools_impl import HttpToolsProtocol
 old_on_url = HttpToolsProtocol.on_url

def new_on_url(self,url):
     old_on_url(self, url)
     self.scope['transport'] = self.transport

HttpToolsProtocol.on_url = new_on_url
```



Thank you very much.

**Comment by lattwood** [comment]
@tomchristie this is now a part of the ASGI spec https://asgi.readthedocs.io/en/latest/specs/tls.html
