### ISSUE TITLE
uvicorn seems to not respect the host part of the common lof format

### ISSUE THREAD

**Issue by Lawouach** [Kludex/uvicorn#404]
Hi all,

Running the sample snippet from the home page:

```
async def app(scope, receive, send):
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```

The logs look like this:

```
10:54 $ uvicorn example:app
INFO: Started server process [3152]
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 58964) - "GET / HTTP/1.1" 200
```

I'm wondering if there isn't an issue with the host part of the access log lines? They should simply mention the address by default, not a tuple as is the case now.

Am I misunderstanding something?

**Comment by Lawouach** [comment]
hypercorn display it differently:

```
11:00 $ hypercorn --access-logfile - example:app:app
ASGI Framework Lifespan error, continuing without Lifespan support
Running on 127.0.0.1:8000 over http (CTRL + C to quit)
127.0.0.1:59102 http GET / 1.1 200 - 1000
```

which doesn't look quite right either.

Finally daphne looks as per CLF:
```
$ daphne example:app
2019-08-13 11:02:23,488 INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2019-08-13 11:02:23,489 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-08-13 11:02:23,490 INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2019-08-13 11:02:23,491 INFO     Listening on TCP address 127.0.0.1:8000
127.0.0.1:59138 - - [13/Aug/2019:11:02:28] "GET /" 200 13
```

**Comment by lovelydinosaur** [comment]
Okay - I'd accept a pull request switching the format here.

The relevant lines are:

* https://github.com/encode/uvicorn/blob/dce3f24c82e9948600d9b1c39e14b77ef7e33f67/uvicorn/protocols/http/h11_impl.py#L439
* https://github.com/encode/uvicorn/blob/dce3f24c82e9948600d9b1c39e14b77ef7e33f67/uvicorn/protocols/http/httptools_impl.py#L439

We'd probably want an `addr_as_string(addr: typing.Optional[typing.Tuple[str, int]]) -> str` util function, to convert the two-tuple to an address string. (Perhaps also converting `None` to  `"<host unknown>"`)

**Comment by lovelydinosaur** [comment]
Logging format is cleaner now.
