### ISSUE TITLE
Customising logging

### ISSUE THREAD

**Issue by elyobo** [Kludex/uvicorn#410]
I'd like to customise my logging, but uvicorn [constantly reinitialises the logging config](https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L53) which breaks this (I remove the handler and add my own; the constant reinitialisation seems to add it back again).

I'm not sure whether this has any impact on the performance issue identified in https://github.com/encode/uvicorn/issues/112 but it does seem wasteful, as well as making changes to the logging difficult.

Is there a way to work around this that I'm missing?  Is it worth fixing the underlying issue?

**Comment by elyobo** [comment]
OK, my misunderstanding of python logging, if I adjust the root logger then the repeated calls to `basicConfig` are fine :)

**Comment by lovelydinosaur** [comment]
Grand - any chance you'd be able to update this issue with an example of how customising the logging *should* look?

**Comment by elyobo** [comment]
No, it's fine as it is, this was just my misunderstanding hence the closed
issue.

**Comment by lovelydinosaur** [comment]
A miscommunication...

I meant "could you add a brief example to this issue of how to customize logging with uvicorn" to help out anyone searching for this in the future. 😃

**Comment by elyobo** [comment]
Oh, right!

It really is simple though, my misunderstanding was just in what the "root" logger was.  I assumed it was the logger at the root of _my application_ (e.g. `logging.getLogger('mymodulename')`), but of course external modules accessing a logger aren't going to be accessing one underneath `mymodulename.something` so the root logger is a level up again (e.g. `logging.getLogger()`).

In my case, I wanted to use colours during development to make the logs easier to read.

```python
import logging
import colorlog

logger = logging.getLogger()
handler = colorlog.StreamHandler()                                         
handler.setFormatter(colorlog.ColoredFormatter(                            
    '%(log_color)s%(levelname)s:%(reset)s (%(name)s) %(message)s'          
    ))                                                                     
if logger.hasHandlers():                                              
  logger.handlers.clear()                                             
logger.addHandler(handler)                                            
```
