### ISSUE TITLE
Unstable gunicorn process management on slow route

### ISSUE THREAD

**Issue by kznovo** [Kludex/uvicorn#411]
Thank you for such a wonderful project! It's a joy working with uvicorn.

I have a small issue regarding **the stability of deploying uvicorn server with Gunicorn process management**.

I have a relatively heavy route that takes **around 1sec** to respond.
Say the route looks like below (copied + modified slightly from the original uvicorn sample code):

```python
# server.py
import time

async def app(scope, receive, send):
    time.sleep(1) # simulate computation
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```

Then I deploy the app using gunicorn with 4 uvicorn workers:

```bash
$ gunicorn -w=4 -k=uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 server:app
```

The app works fine but when I do load testing it starts to fail responding in tremendous amounts.

```bash
$ ab -n 100 -c 100 http://localhost:8000/
```
This results in **83/100 failure** to respond.

```bash
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        uvicorn
Server Hostname:        localhost
Server Port:            8000

Document Path:          /
Document Length:        23 bytes

Concurrency Level:      100
Time taken for tests:   24.842 seconds
Complete requests:      100
Failed requests:        83
   (Connect: 0, Receive: 0, Length: 83, Exceptions: 0)
Total transferred:      2550 bytes
HTML transferred:       391 bytes
Requests per second:    4.03 [#/sec] (mean)
Time per request:       24842.069 [ms] (mean)
Time per request:       248.421 [ms] (mean, across all concurrent requests)
Transfer rate:          0.10 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        2    4   1.1      3       6
Processing:  1007 22247 6152.8  24835   24836
Waiting:        0 1634 4241.8      0   13030
Total:       1012 22250 6152.5  24838   24842

Percentage of the requests served within a certain time (ms)
  50%  24838
  66%  24839
  75%  24839
  80%  24840
  90%  24840
  95%  24841
  98%  24842
  99%  24842
 100%  24842 (longest request)
```

The cause seems to be Gunicorn's worker timeout error.

```bash
...
[2019-08-22 14:45:30 +0900] [20382] [INFO] ('127.0.0.1', 44790) - "GET / HTTP/1.0" 200
[2019-08-22 14:45:30 +0900] [20384] [INFO] ('127.0.0.1', 44760) - "GET / HTTP/1.0" 200
[2019-08-22 14:45:31 +0900] [20378] [CRITICAL] WORKER TIMEOUT (pid:20382)
[2019-08-22 14:45:31 +0900] [20378] [CRITICAL] WORKER TIMEOUT (pid:20383)
[2019-08-22 14:45:31 +0900] [20378] [CRITICAL] WORKER TIMEOUT (pid:20384)
[2019-08-22 14:45:31 +0900] [20404] [INFO] Booting worker with pid: 20404
[2019-08-22 14:45:31 +0900] [20404] [INFO] Started server process [20404]
[2019-08-22 14:45:31 +0900] [20404] [INFO] Waiting for application startup.
[2019-08-22 14:45:31 +0900] [20405] [INFO] Booting worker with pid: 20405
[2019-08-22 14:45:31 +0900] [20405] [INFO] Started server process [20405]
[2019-08-22 14:45:31 +0900] [20405] [INFO] Waiting for application startup.
[2019-08-22 14:45:31 +0900] [20406] [INFO] Booting worker with pid: 20406
[2019-08-22 14:45:31 +0900] [20406] [INFO] Started server process [20406]
[2019-08-22 14:45:31 +0900] [20406] [INFO] Waiting for application startup.
[2019-08-22 14:45:32 +0900] [20404] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2019-08-22 14:45:32 +0900] [20405] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2019-08-22 14:45:32 +0900] [20406] [INFO] ASGI 'lifespan' protocol appears unsupported.
```

If I use other process management tools there are no issues. For example, if I use supervisor:

```
; supervisord.conf
[supervisord]

[fcgi-program:uvicorn]
socket=tcp://localhost:8000
command=venv/bin/uvicorn --fd 0 server:app
numprocs=4
process_name=uvicorn-%(process_num)d
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
```

```bash
$ supervisord -c supervisord.conf -n
```

The same test succeeds without any failure.

Uvicorn's native worker management works stably without any issue as well:

```bash
$ uvicorn --workers=4 server:app
```

I haven't been able to look into how Gunicorn process management is implemented, but is there any configurations I must additionally configure in order to achieve stable deployment, or can anyone point to me which part of the implementations to look into?

<hr/>

My environment:
```
$ uname -a
Linux kazuya-ThinkPad-X1-Carbon-6th 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```
<hr/>

Thanks!

**Comment by lovelydinosaur** [comment]
Any idea what the worker timeout period is?

It's also worth noting that you need to be careful with heavy computation in an async context - really you need to run it within a thread pool, otherwise you'll be blocking the event loop for a number of seconds each time, and won't be getting nice finely grained concurrency.

**Comment by kznovo** [comment]
@tomchristie Thanks for the comment. I believe the worker timeout period is the default gunicorn timeout: 30 seconds on the above example.

I might have understood the problem - however I'm not so sure if the below is correct. Could anyone confirm?

The event queue got many items from sending large amount of concurrent requests, and while uvicorn workers are processing them, gunicorn timeout comes and gunicorn kills all the uvicorn workers if there are still items left in the queue.
When I use other synchronous servers such as flask, I don't encounter this worker timeout error since gunicorn receives the signal after each process finishes and resets its timeout timer .

```python
# server.py

import time
from flask import Flask, escape, request

app = Flask(__name__)

@app.route('/')
def hello():
    time.sleep(1)
    name = request.args.get("name", "World")
    return f'Hello, {escape(name)}!'
```

```bash
$ gunicorn -w=4 --bind 0.0.0.0:8000 server:app &
$ ab -n 100 -c 100 http://localhost:8000/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        gunicorn/19.9.0
Server Hostname:        localhost
Server Port:            8000

Document Path:          /
Document Length:        13 bytes

Concurrency Level:      100
Time taken for tests:   25.105 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      17300 bytes
HTML transferred:       1300 bytes
Requests per second:    3.98 [#/sec] (mean)
Time per request:       25105.349 [ms] (mean)
Time per request:       251.053 [ms] (mean, across all concurrent requests)
Transfer rate:          0.67 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        4    8   1.9      8      11
Processing:  1004 13050 7273.6  13050   25090
Waiting:     1003 13050 7273.7  13049   25089
Total:       1015 13058 7271.7  13058   25095

Percentage of the requests served within a certain time (ms)
  50%  13058
  66%  17073
  75%  19081
  80%  21085
  90%  23090
  95%  24092
  98%  25095
  99%  25095
 100%  25095 (longest request)
```

So if gunicorn can receive signals when each request finishes and can reset its timeout timer then the timeout error should not occur - is this correct?

Thanks again!

**Comment by yoonnoon** [comment]
I had the same issue, but moved to using 'await ayncio.sleep' rather than 'time.sleep'.

 The ASGI behavior is that one worker (one process-one thread) improves thread concurrency through coroutines. However, 'time.sleep' blocks the thread, so it cannot handle concurrency and acts like a single thread with lock.

sample code(https://github.com/yoonnoon/nginx-uvicorn-fastapi-container/blob/master/application/service.py)
`
import asyncio
import fastapi
import time

endpoint = fastapi.FastAPI()

@endpoint.get('/anti-pattern')
async def anti_pattern_in_asgi():
    time.sleep(10)
    return "Blocking call like 'time.sleep (10)' in a coroutine " \
           "are anti-patterns because threads can't do anything else."

@endpoint.get('/right-pattern')
async def right_pattern_in_asgi():
    await asyncio.sleep(10)
    return "Non-blocking calls with 'await' in a coroutine, such as 'await asyncio.sleep (10)', " \
           "increase concurrency because the thread can exit and do other things."
 `

**Comment by gvbgduh** [comment]
@kznovo `time.sleep(1)` is the blocking operation, that describes your almost identical throughput, You'd better be using `await asyncio.sleep(1)`, which won't block and allow the scheduler do the job, also because of the overhead of the scheduler itself and the request time coincidently balancing around the timeout limit you might see some discrepancies in comparison to consistent sync operation (as of the lack of the scheduler overhead).

**Comment by gvbgduh** [comment]
Please feel free to reopen if you have any other concerns or please share some other bench results.
