### ISSUE TITLE
Custom Authentication returns None on user

### ISSUE THREAD

**Issue by elkd** [Kludex/uvicorn#413]
I am having a Django project that is using Django channels on some apps and they are served by uvicorn on production. I have implemented a custom Authentication to allow users to login with their phone number. When the user login this way all other pages works perfectly except the pages that are served by uvicorn, it throws 500, with an error message, ModuleNotFoundError: No module named 'users'. What I can tell is that when ASGI request is passed as a parameter on auth.get_user(request) method in Django.contrib.auth.middleware.py it returns None as a user variable. On the local environment it works perfectly, it only behaves this way in production.
Here is the full traceback

```ModuleNotFoundError: No module named 'users'
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "django/contrib/auth/decorators.py", line 44, in <lambda>
    lambda u: u.is_authenticated,
  File "django/utils/functional.py", line 213, in inner
    self._setup()
  File "django/utils/functional.py", line 347, in _setup
    self._wrapped = self._setupfunc()
  File "django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "django/contrib/auth/__init__.py", line 188, in get_user
    backend = load_backend(backend_path)
  File "django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
```

![error](https://user-images.githubusercontent.com/27847245/63579081-66c59f00-c5c4-11e9-9f48-df8e18fe7819.png)

**Comment by lovelydinosaur** [comment]
There's not enough information here to indentify it as an issue with uvicorn itself (rather than some kind of configuration/integration issue). You might want to try swapping uvicorn out for `daphne` or `hypercorn` and see if the issue persists, in order to help you more closely identify where the issue is exactly.

**Comment by elkd** [comment]
Hello, @tomchristie Thank you for your response, I'm replying this late because after using Daphne, I still reproduced the issue, so you were correct that it is not uvicorn itself causing this issue. The reason why I'm bringing this back is that, so far I haven't solved this issue and I have reviewed my code line by line and I can say it is not a configuration issue. I don't know Django well but to my little understanding, Django is failing to get the custom authenticated user object when the request is ASGI request. Can you please give me a suggestion on how to attempt to solve this? Is there any other better place I can open this issue? Here are all of the files that are involved in this.

uvicorn
`ExecStart=/home/my-user/venv/bin/gunicorn \
          -k uvicorn.workers.UvicornWorker \
          --workers 6 \
          --bind unix:/run/gunicorn.sock \
          --log-level critical \
          config.asgi:application`

phone_authentication.py

`from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
​
class PhoneAuthBackend(ModelBackend):
    """
    Authenticate using a phone number.
    """
    def __init__(self, *args, **kwargs):
        self.user_model = get_user_model()
    
    def get_phone_number_data(self, phone):
        """
        Method used for filtering query.
        """
        data = {
            'phone_number': phone
        }
        return data
​
    def authenticate(self, request, username=None, password=None):
        #This is a forgiving code, allow users to login with country code.
        phone = str(username)
        if phone.isalpha() and phone.startswith("+86") == False:
            return None
        if len(phone) == 11 and phone[0] != '1':
            return None
        else:
            #This code only works for Chinese phone numbers.
            if phone.startswith("+86") == False:
                phone = "+86" + phone
            
            user = self.user_model.objects.filter(
                    **self.get_phone_number_data(phone)
                ).first()
            
            if not user:
                # Run the default password hasher once to reduce the timing
                # difference between an existing and a nonexistent user (#20760).
                self.user_model().set_password(password)
            else:
                if user.check_password(password):
                    return user`

settings.py
`​# AUTHENTICATION
AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'users.phone_authentication.PhoneAuthBackend',
]

DJANGO_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'dal',   #Django auto complete has to be before admin
    'dal_select2',
    'django.contrib.admin',
    'django.forms',
    'django.contrib.postgres',
]
THIRD_PARTY_APPS = [
    #Kindly note, these 2 lines below have been moved up and down without success.
    #'users',
    'my-app.users.apps.UsersConfig',
    'crispy_forms',
    'sorl.thumbnail',
    'phonenumber_field',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.amazon',
    # 'allauth.socialaccount.providers.github',
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.linkedin',
    # 'allauth.socialaccount.providers.slack',
    'channels',
    'graphene_django',
    'markdownx',
    'taggit',
    'star_ratings',
    'pwa_webpush',
    'django_elasticsearch_dsl',
]
LOCAL_APPS = [
    # custom apps go here
	# 'my-app.users.apps.UsersConfig',
    'my-app.chat.apps.MessagerConfig',
    'my-app.notifications.apps.NotificationsConfig',
	 # and so on...

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS`

**Comment by lovelydinosaur** [comment]
This is probably the place to try: https://groups.google.com/forum/#!forum/django-users

**Comment by elkd** [comment]
Thank you
