### ISSUE TITLE
NoneType' object has no attribute 'resume_writing' on SSL termination

### ISSUE THREAD

**Issue by zueve** [Kludex/uvicorn#427]
uvicorn == 0.9.0

Running with 
poetry run uvicorn main:app --host 0.0.0.0 --ssl-keyfile certs/
server-key.pem --ssl-certfile /certs/server-crt.pem

When trying to connect from curl:
curl -v -s -k --cert some-wrong-file-path   https://localhost:8000/docs

In uvicorn console log found this lines:
"""
[2019-09-18 06:33:55,853 ERROR] asyncio | Exception in callback <bound method HttpToolsProtocol.connection_lost of <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7fbae32adb10>>
handle: <Handle HttpToolsProtocol.connection_lost>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/home/zenv/.cache/pypoetry/virtualenvs/wl-wallet-py3.7/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 140, in connection_lost
    self.flow.resume_writing()
AttributeError: 'NoneType' object has no attribute 'resume_writing'
"""

**Comment by Hanaasagi** [comment]
I can reproduce this problem. And it also happens in master branch. `connection_made` is not called.

https://github.com/encode/uvicorn/blob/e0a77de6baf436d182868fa280cd5e2f0d66501c/uvicorn/protocols/http/httptools_impl.py#L119-L129

**Comment by Hanaasagi** [comment]
I think if #416 is merged, the problem will be solved.

**Comment by chrisborbidge** [comment]
At risk of sounding impatient - is there a work around that can be implemented with 0.9.0 to enable SSL?

Very much appreciate any help with this error.

**Comment by vanissoft** [comment]
> At risk of sounding impatient - is there a work around that can be implemented with 0.9.0 to enable SSL?
> 
> Very much appreciate any help with this error.

https://github.com/encode/uvicorn/pull/416/files

**Comment by lovelydinosaur** [comment]
This is resolved in 0.9.1 (if you're using the default httptools), and in master (if you're using h11)
