### ISSUE TITLE
UNIX domain socket raises 503 when workers are used

### ISSUE THREAD

**Issue by ivankravets** [Kludex/uvicorn#428]
Is it Ok when a combination of `--workers ` and `--uds` raises 503 error via nginx? For example:
```
--workers 4 --uds /var/run/uvicorn-test.sock
```

it works well when `--workers` is omitted (1 worker). Please note that `gunicorn` works well via Unix socket and multiple workers.

Thanks!

**Comment by Hanaasagi** [comment]
It seems that when combine the `--workers` and `--uds` arguments. uvicorn will ignore `--uds` and create a tcp socket.

https://github.com/encode/uvicorn/blob/e0a77de6baf436d182868fa280cd5e2f0d66501c/uvicorn/main.py#L274-L277
https://github.com/encode/uvicorn/blob/e0a77de6baf436d182868fa280cd5e2f0d66501c/uvicorn/config.py#L220-L228
