### ISSUE TITLE
Quickstart example doesn't comply to protocol

### ISSUE THREAD

**Issue by unc0mm0n** [Kludex/uvicorn#429]
The ASGI protocol specifically mentions that no response should be sent until a request is received:
https://asgi.readthedocs.io/en/latest/specs/www.html
Should probably add something like:
```
    event = await receive()
    if event["type"] != "http.request": #alternatively, event["type"] == "http.disconnect"
        #do something
```

before calling `send()`

**Comment by lovelydinosaur** [comment]
We're already checking that we've got an `http` ASGI message before we send a response.
I'm not sure if there's a misunderstanding here, but it doesn't appear to me that we need to be doing anything else.
