### ISSUE TITLE
Using pdb inside a uvicorn running in docker fails, while it doesn't outside docker.

### ISSUE THREAD

**Issue by joaqo** [Kludex/uvicorn#430]
Hey, I originally reported this issue in the fastapi repository and was informed it would be better suited here. [This is the thread for anyone interested.](https://github.com/tiangolo/fastapi/issues/545)

## Summary of the thread

When running uvicorn inside a `tiangolo/uvicorn-gunicorn:python3.7` docker image with `reload=True` set in `uvicorn.run`, debugging with pdb or any of the similar debuggers is not possible. The `set_trace()` commands trigger a `bdb.BdbQuit` exception instantly. I reduced the bug to those particular conditions after trying to reproduce the error in several environments as detailed in the linked thread. This is a snippet to reproduce the  bug:

```python
from fastapi import FastAPI
from starlette.requests import Request

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.middleware("http")
async def db_session_middleware(request: Request, call_next):
    import pdb; pdb.set_trace()
    return await call_next(request)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run('script_file_name:app', host="0.0.0.0", port=80, reload=True, debug=True)
```

To run it just:
```bash
docker run -v /local_folder_with_script_above/:/test/ -p 80:80 tiangolo/uvicorn-gunicorn:python3.7
```
Then run in another terminal:
```bash
docker exec -it {container_name} bash
```
Finally execute the script using python in that second terminal

**Comment by gvbgduh** [comment]
Hey @joaqo,

I think the problem is in how you run it.

`bdb.BdbQuit` is usually raised when you send a command `q(uit)` to `pdb` explicitly or when it receives EOF or something, running in some background process. Those are not complete specs though.

`uvicorn` with `pdb` will work just fine if you run it straight in the single process, like

```
uvicorn app.api:app
```

And you'll have nice a stable experience.

```
INFO: Started server process [40412]
INFO: Waiting for application startup.
INFO: {'host': ['localhost'], 'port': ['5436']}
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
> /.../middlewares/api_key.py(32)dispatch()
-> api_key = config("API_KEY", cast=str, default=None)
(Pdb)
```

It'll generally work running with `gunicorn`

```
gunicorn --log-level debug --workers 1 --worker-class uvicorn.workers.UvicornWorker app.api:app
```

But it'll be not that convenient as `gunicorn` will be restarting not responding processes and every time it happens you'll need to start from scratch as your breakpoint will" jump" to the beginning (you may try to adjust the timeout settings).

It's becoming really tricky when it runs over a more complex set up, like in the docker environment as the way it handles the processes it will provoke `bdb.BdbQuit` and there's generally no access to interact with code of the app. And `pdb` doesn't work well with multiprocessing out of the box.

The better debugging experience would be to run your code instance in the single process running the plain `uvicorn`.

But there're extreme cases when you have to debug your code in the running processes, like multiple `gunicorn` works or debug `celery` in action.

So, despite old good prints and loggers, you can consider remote debugging options. 

As an example, `celery` comes with a built-in `rdb` solution or you can have a look at [`pudb`](https://documen.tician.de/pudb/). 

There might be other solutions, so it's worth checking if you're going down this path.

**Comment by gvbgduh** [comment]
So, it comes down to the docker level and probably out of the scope of `uvicorn`. I'll close the issue for now, but feel free to re-open if any concerns.

P.S. apparently, you can have a look at some other approaches:
- https://medium.com/@trstringer/debugging-a-python-flask-application-in-a-container-with-docker-compose-fa5be981ec9a
- https://stackoverflow.com/questions/30854967/docker-compose-and-pdb.

**Comment by joaqo** [comment]
Hey @gvbgduh thanks for the answer. I don't think I understood what is happening, is it the way docker handles processes thats the issue? I run the same exact `reload=True`setup in plain macOS/Ubuntu and it works just fine. Also I run the same server on docker with `reload=True` and pdb works perfectly.

Regarding the utility of this debugging setup, I am currently developing using this method just running in macOS and its extremely comfortable, it's the best webdev experience I've had. I can just write the code, save the file and instantly try it in the web browser. If my pdb session raises an exception or something it doesn't matter, new requests to the server get handled by fresh sessions. Basically I can program using my text editor and browser without interacting with console/restarting the server etc.

Nevertheless, running it macOS is not ideal as sooner or later the differences between this environment and the docker environment I use in production is gonna cause me troubles. If I could just run this setup running `docker exec -it container_name bash` it would pretty much be ideal.

But I understand there may be some weird interaction between `reload=True` and docker that may make this not possible.

**Comment by gvbgduh** [comment]
Hey @joaqo, I don't believe `reload=True` is somehow related to this as well as uvicorn in general. It's just a matter of how you communicate with it through docker.

So, I have tried docker-compose that runs nginx that sits in front of gunicorn + uvicorn with https://blog.lucasferreira.org/howto/2017/06/03/running-pdb-with-docker-and-gunicorn.html
and it works fine.

You can also have a look at https://medium.com/@vladyslav.krylasov/how-to-use-pdb-inside-a-docker-container-eeb230de4d11 as another approach.

**Comment by joaqo** [comment]
Hey @gvbgduh the reason why I am saying that `reload=True` is the cause is because pdb works perfectly fine in docker with `reload=False` and crashes with `reload=True`. Keeping everything else exactly the same. So I am not sure what the underlying cause is, but `reload` is certainly the trigger. This has been verified by another commenter in the original fastapi thread I to linked above.

Regarding your test using nginx+gunicorn+uvicon that is not exactly my use case, so I don't see why it applies. If you wan't to reproduce my use case I left the exact steps to reproduce the bug in my original comment. To check that the trigger is `reload` just run the exact steps listed above with and without `reload` activated.

I agree that this doesn't sound like a uvicorn bug, and more like a weird interaction between it and docker. But there seems to be an interesting correlation between `reload` and running pdb in docker which to me seems interesting at least. Also, the ability to develop while using `reload` and pdb inside docker lends itself to a very productive webdev experience for uvicorn users.

**Comment by gvbgduh** [comment]
Interesting. Let me have a deeper look tomorrow.

**Comment by joaqo** [comment]
Hey, @gvbgduh did you have any luck with this?

**Comment by gvbgduh** [comment]
Hi @joaqo, thanks for the reminder!
I wonder how it fails for you as I tried several configurations and seems to be working fine.

I tried `uvicorn`, `uvicorn + gunicorn` and those two with `nginx`.
Once it's up `docker attach <container_id>`.

The app is
`app/app.py`
```
from starlette.applications import Starlette
from starlette.endpoints import HTTPEndpoint
from starlette.responses import JSONResponse

class Endpoint(HTTPEndpoint):
    async def get(self, request):
        import pdb; pdb.set_trace()
        return JSONResponse({"success": True, "method": "GET"})


app = Starlette()
app.debug = True
app.mount("/api", app=Endpoint)
```

`docker-compose.yaml`
```
version: '3.7'

services:
  web:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    # command: gunicorn --log-level debug --bind :8080 --reuse-port --workers 1 --worker-class uvicorn.workers.UvicornWorker app.app:app --timeout 600 --graceful-timeout 500 --capture-output --reload
    command: uvicorn app.app:app --port 8080 --host 0.0.0.0 --reload
    expose:
      - 8080
    environment:
      - DEBUG=1
      - PORT=8080
    volumes:
      - ./:/app
    ports:
      - 8080:8080

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
```

`Dockerfile`
```
FROM gcr.io/google-appengine/python
RUN virtualenv /env -p python3.7
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD . /app
EXPOSE 8080
```

**Comment by lovelydinosaur** [comment]
I'm going to close this off, pending a reproducible case.

**Comment by joaqo** [comment]
Hey @gvbgduh and @tomchristie thanks for the answers. Regrettably the case you posted is not the one I described. My initial post has the exact steps to reproduce the bug, and as far as I can tell no one has been able to make it work yet.

Thanks a lot for the awesome library but I'd be really grateful if you could open the issue again as I don't think you've tried the reproduction steps detailed in my initial post.

Please tell me if you'd like me to add more details to the reproduction steps as this is the second time the issue has been closed citing the need for a reproducible case, so I am starting to think there may be some issues with how I described the steps in my first post.

Again, thanks for the awesome library and for the help.

**Comment by lovelydinosaur** [comment]
Personally I don't have the bandwidth to look into integration issues related to third party environments such as Docker.

If the issue can be reduced specifically into "uvicorn handles signals incorrectly, because X" then sure, we can look into that, but the most feasible assumption given the current info would be that this is some kind of Docker configuration issue, rather than anything to do with uvicorn itself.

There seem to be [a bunch of questions related to using pdb and Docker together](https://www.google.com/search?client=firefox-b-d&q=bdb.BdbQuit+docker), eg
https://stackoverflow.com/questions/58491870/unable-to-debug-or-use-pdb-in-django-bdb-bdbquit - perhaps some other those might help narrow things down?

**Comment by gvbgduh** [comment]
@joaqo yes, some sort of traceback would help. To be honest I find your approach a bit confusing.
The docker image you provided with that command starts its own server, while you want to spin up another one programatically.
Also, while it's a bit tough for me to justify not to use the entrypoint outside the script as it makes it more convenient for deploys across different environments I tried running it programmatically:

```
...

if __name__ == "__main__":
    import uvicorn
    uvicorn.run('app:app', host="0.0.0.0", port=8080, reload=True, debug=True)
```

```
...
command: python app/app.py
...
```

and it seems to be working fine with auto reload.

As of that it seems the problem not in `uvicorn` and not in communicating with `docker`.
So, I would probably recommend to try the plain setup first and/or debug the docker file you use and how it builds the environment.

**Comment by joaqo** [comment]
@gvbgduh very good suggestion. I had assumed that the docker image I was using was the canonical uvicorn docker image (I don't think there is one atm), so I didn't suspect it, but it turns out I was wrong. Tried just using the `python:3` image and just pip installed what I needed inside docker, and my script ran just fine. So I think it was related to the docker image I was using. Will do some further research to try and see what was wrong, and report here if I find anything interesting, but for now it seems that this was my fault and not not uvicorn's.

Thanks again @gvbgduh & @tomchristie .
