### ISSUE TITLE
Question: why do the docs suggest running with Gunicorn in production?

### ISSUE THREAD

**Issue by cetanu** [Kludex/uvicorn#434]
Hello,

Just wondering, [this page](https://www.uvicorn.org/deployment/) says:

> Run gunicorn -k uvicorn.workers.UvicornWorker for production.

In addition there's a recommendation to run NGINX as well.

What are some of the reasons why I would do this? Is Uvicorn unsafe to run as the main server process in prod deployments?

**Comment by Hanaasagi** [comment]
@cetanu Please see this issue https://github.com/encode/uvicorn/issues/303 .

**Comment by cetanu** [comment]
Ah, thanks very much. All clear.

**Comment by lovelydinosaur** [comment]
Wouldn't be a bad idea for our docs to give some more context there.
