### ISSUE TITLE
Support a gunicorn-like config file

### ISSUE THREAD

**Issue by madkote** [Kludex/uvicorn#444]
Hi all,

just few question:
* is there a way to pass a `config.py` like in `gunicorn`?
* how can I override logging in `uvicorn`?
  * in gunicorn I can pass a custom logging dictionary with my custom formatters, etc...

Thanks!

**Comment by lovelydinosaur** [comment]
We don't currently support a config file, no.
If you're running uvicorn programmatically, then we do have a lower-level interface that allows passing a `Config()` instance, but it needs documenting.
You'll need to use Python's standard logging module for configuring the logging display (yup it'd be helpful for us to document this too)

**Comment by madkote** [comment]
Hi @tomchristie thanks! I was able to pass my logger into `Config()`. A configuration (`python`) file would be also very helpful.

**Comment by lovelydinosaur** [comment]
@madkote Good call. Retitled this to reflect that part of the issue specifically.

**Comment by Hanaasagi** [comment]
There is a related PR https://github.com/encode/uvicorn/pull/323 about reading config from a file, though it is not gunicorn-like.

**Comment by lovelydinosaur** [comment]
Let's close this in favor of #323 - we can tackle details of *how* a config file should look/work once we get to that point.

**Comment by lovelydinosaur** [comment]
Having taken a look at this. Yes. And yes, let's make it gunicorn-like - they get it right.
#323 is almost there, just needs a tweak.

**Comment by lovelydinosaur** [comment]
Closing as a duplicate of #322
