### ISSUE TITLE
Process for accept and close keys in ReplyChannel.send() of WebSocket

### ISSUE THREAD

**Issue by 38elements** [Kludex/uvicorn#46]
I think that the process for [accept and close keys](http://channels.readthedocs.io/en/stable/asgi/www.html#send-close-accept) in [ReplyChannel.send()](https://github.com/encode/uvicorn/blob/96a62b3a6e1b5e2eab038ae55ece8e6d5238ae76/uvicorn/protocols/websocket.py#L40-L44) of WebSocket is necessary.

**Comment by lovelydinosaur** [comment]
Agreed, yes!

**Comment by lovelydinosaur** [comment]
Resolved via #49.
Thanks for highlighting this!
