### ISSUE TITLE
uvicorn 启动多线程异常停止问题

### ISSUE THREAD

**Issue by HeywoodKing** [Kludex/uvicorn#463]
我使用uvicorn+启动restful api程序，名命令：
uvicorn run:app --host 127.0.0.1 --port 8080 --workers 10 --limit-concurrency 100 --limit-max-requests 10 --timeout-keep-alive 5 --reload
请求几次之后就会直接进程退出了，cmd显示
INFO: ('192.168.1.xxx', 41820) - "POST /api/v1/xxx/xxx/id2/ HTTP/1.1" 200
INFO: Shutting down
INFO: Waiting for application shutdown.
INFO: Finished server process [14716]
INFO: Stopping reloader process [25216]

然后进程就直接退出了，求大神帮助，感谢万分

**Comment by YangNianYi** [comment]
--limit-max-requests INTEGER    
Maximum number of requests to service before terminating the process.

**Comment by gvbgduh** [comment]
@HeywoodKing I think the @YangNianYi's message should answer your question. Indeed, with those params, the server will terminate after 10 served requests.
Feel free to re-open the issue if you still have concerns.

**Comment by HeywoodKing** [comment]
@YangNianYi @gvbgduh 
--limit-max-requests 10  This parameter is the maximum number of served requests and the process will terminate after 10?Isn't it limiting the maximum request?


I remove --limit-max-requests and use commands：
uvicorn run:app --host 192.168.1.79 --port 8091 --workers 10 --limit-concurrency 100 --timeout-keep-alive 5 --reload

Boot, after a period of time the following error appears

2019-10-28 14:30:51,437 - factory.factory - INFO    : Factory API 运行中...
Factory API 运行中...
INFO: Started server process [28776]
INFO: Waiting for application startup.
ERROR: Accept failed on a socket
socket: <socket.socket fd=832, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.xx', xxxx)>
Traceback (most recent call last):
  File "D:\ProgramData\.pyenv\pyenv-win\versions\3.7.4-amd64\Lib\asyncio\proactor_events.py", line 668, in loop
    f = self._proactor.accept(sock)
  File "D:\ProgramData\.pyenv\pyenv-win\versions\3.7.4-amd64\Lib\asyncio\windows_events.py", line 489, in accept
    self._register_with_iocp(listener)
  File "D:\ProgramData\.pyenv\pyenv-win\versions\3.7.4-amd64\Lib\asyncio\windows_events.py", line 650, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。

**Comment by gvbgduh** [comment]
@HeywoodKing are you able to run the server on localhost or `0.0.0.0`?

**Comment by HeywoodKing** [comment]
@gvbgduh
 (4L6xcK2_) \Flack\Work\xxx\xxx>uvicorn run:app --port 8081 --workers 10 --limit-concurrency 100 --timeout-keep-alive 5 --reload
INFO: Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
INFO: Started reloader process [5556]
2019-10-28 17:04:59,146 - factory.factory - INFO    : Factory API 运行中...
Factory API 运行中...
INFO: Started server process [29368]
INFO: Waiting for application startup.

operational

**Comment by gvbgduh** [comment]
yeah, i see, thanks @HeywoodKing. it seems it can't bind the port to that ip, possibly due to permissions.

**Comment by HeywoodKing** [comment]
@gvbgduh Thank you very much. I'm running it on Windows 10. I'm trying the admin mode command line
