### ISSUE TITLE
Logging ouput is gone in new release

### ISSUE THREAD

**Issue by logileifs** [Kludex/uvicorn#472]
When I run my app with uvicorn version 0.9.1 I get this nice logging output:
```
uvicorn api.app:app --port=8989 --reload
INFO: Uvicorn running on http://127.0.0.1:8989 (Press CTRL+C to quit)
INFO: Started reloader process [13715]
INFO: Started server process [13717]
INFO: Waiting for application startup.
INFO: before_startup
DEBUG: DEBUG: True
INFO: connecting to localhost:28015/test
DEBUG: SECRET_KEY: XXXX
INFO: db connected
^CINFO: Shutting down
INFO: Waiting for application shutdown.
INFO: Finished server process [13717]
INFO: Stopping reloader process [13715]
```

But with the latest uvicorn version (0.10.0) running the same app I only see this:
```
uvicorn api.app:app --port=8989 --reload
INFO:	Uvicorn running on http://127.0.0.1:8989 (Press CTRL+C to quit)
INFO:	Started reloader process [14265]
^CINFO:	Stopping reloader process [14265]
```

**Comment by lovelydinosaur** [comment]
Gotcha - thanks for the report!

There's been a chunk of work on the logging that:

* Adds colours to terminal outputs.
* Uses properly seperate `uvicorn.errors` and `uvicorn.access` loggers.
* No longer passes a logger instance around explicitly, instead just using Python's standard `logging.getLogger(...)`
* Support `--log-config` / `log_config=[dict|str]` to customize log capture.

However, it turns out that in the `--reload` and `--workers` cases we need to reconfigure the logging each time we start up a child process. I'd expect you to need to include `--log-level debug`, unless you're already doing the equivelent of that in your application.

We also need to setup the root logger, so that we're capturing output from *all* loggers, not only `uvicorn.error` and `uvicorn.access`.

Working on this all now in #473.

**Comment by logileifs** [comment]
Thanks for the quick reply,

I noticed those changes and do appreciate the nice colored logging ouput :)

In my case I am configuring logging programmatically in my application and that has worked like a charm until now
```
log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
rh = RedisHandler('logs', host=config.get('REDIS_HOST'), level=logging.DEBUG)
rh.setLevel(logging.DEBUG)
log.addHandler(rh)
```

**Comment by lovelydinosaur** [comment]
Right, I've pushed 0.10.1, which should resolve this. I'd appreciate your feedback, tho.

Uvicorn sets the the default level for the root logger to `INFO`, so you may need to use `--log-level debug` or set the root level to debug in your own codebase.

Incidentally I'm strongly considering a `TRACE` level, and having the raw ASGI messaging only output at trace level. That way we can have something along the lines of...

* INFO: Output for stuff such as Process startup, Database connected, One line access logs.
* DEBUG: Output for stuff such as SQL on database accesses, Outgoing HTTP requests, Cache lookups, SMTP requests, Background tasks. Everything you'd want to see to get a good idea of what I/O the system is performing on each request.
* TRACE: ASGI messages & other low level stuff for when you really need to dig into something obscure, or understand exactly whats happening under the hood.

I'd expect `--log-level debug` to then be pretty useful during development, without presenting an overwhelming amount of info. (Of course there's also the ability to more finely tune *which* bits of logging we want to see.)

**Comment by logileifs** [comment]
I can confirm that it's working now with 0.10.1.
However I noticed some other weird behavior with the logging, if I set up my app the traditional way everything works fine
```
app.add_middleware(RequestIDMiddleware)
app.add_middleware(AuthenticationMiddleware, backend=AuthMiddleware())
app.add_route('/signup', signup_get, methods=["GET"])
app.add_route('/signup', signup_post, methods=["POST"])
router = Router(routes=[
	Route('/', endpoint=Root),
	Route('/users/', endpoint=UsersEndpoint),
	Route('/user/{id}', endpoint=UserEndpoint),
])
app.mount("", router)
```
```
uvicorn api.app:app --port=8989 --reload
INFO:     Uvicorn running on http://127.0.0.1:8989 (Press CTRL+C to quit)
INFO:     Started reloader process [4393]
INFO:     Started server process [4397]
INFO:     Waiting for application startup.
INFO:     before_startup
DEBUG:    DEBUG: True
INFO:     connecting to localhost:28015/test
DEBUG:    SECRET_KEY: -XLxuKa0hRNaMKUaZji8wV88PXI_g2ftSQDJlnl_70E=
INFO:     db connected
INFO:     Application startup complete.
```
But if I change to application factory style
```
def create_app():
	app.add_middleware(RequestIDMiddleware)
	app.add_middleware(AuthenticationMiddleware, backend=AuthMiddleware())
	app.add_route('/signup', signup_get, methods=["GET"])
	app.add_route('/signup', signup_post, methods=["POST"])
	router = Router(routes=[
		Route('/', endpoint=Root),
		Route('/users/', endpoint=UsersEndpoint),
		Route('/user/{id}', endpoint=UserEndpoint),
	])
	app.mount("", router)
	return app
```
I see completely different log output.
```
uvicorn api.app:create_app --port=8989 --reload
INFO:     Uvicorn running on http://127.0.0.1:8989 (Press CTRL+C to quit)
INFO:     Started reloader process [4470]
INFO:     Started server process [4474]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
```
Is this feature perhaps not yet supported?

**Comment by lovelydinosaur** [comment]
You can use app = create_app in that module, but otherwise no, you can’t pass a “function that returns an app” as the app itself.
