### ISSUE TITLE
Bug when run uvicorn with integer log_level parameter

### ISSUE THREAD

**Issue by brunobell** [Kludex/uvicorn#475]
https://github.com/encode/uvicorn/blob/e0fda1fca6e4e2d6399892e329617b8c10dd5817/uvicorn/config.py#L222

When you run uvicorn.run with `log_level=logging.INFO`, which is an integer value, the app won't start successfully. But a string `log_level='info'` will do.

I think this is a bug that can be fixed :)

**Comment by lovelydinosaur** [comment]
Good catch, yup. Now resolved in https://github.com/encode/uvicorn/commit/f846a3514d5c152f300f03b882c05aaf915e73cb - will be sorted when we roll our next release.

Thanks for filing the issue.
