### ISSUE TITLE
Add missing --version flag on cli

### ISSUE THREAD

**Issue by hvdklauw** [Kludex/uvicorn#476]
Would make figuring out which version we have a lot easier.

**Comment by lovelydinosaur** [comment]
Yup, absolutely agreed.
Would certainly accept a pull request implementing this.

**Comment by lovelydinosaur** [comment]
I guess ideally we want something that allows us to print out the Python version, and our dependency versions, to help with filing comprehensive issue reports. Wondering if there's any other Python projects in particular that do a good job of this?

**Comment by hvdklauw** [comment]
flake8 lists it's version, it's dependencies versions and the python version used.

**Comment by lovelydinosaur** [comment]
Good call, yup...

```shell
$ venv/bin/flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.1 on Darwin
```

Also similar...

```shell
$ python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.1"
  },
  "platform": {
    "release": "18.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010009f"
  },
  "urllib3": {
    "version": "1.25.6"
  },
  "using_pyopenssl": false
}
```

**Comment by florimondmanca** [comment]
We have a `--version` flag now:

```console
$ uvicorn --version
Running uvicorn 0.12.0 with CPython 3.8.2 on Darwin
```

So, closing! (Probably we meant to close this via #518 but didn't include a `Fixes` magic keyword there.)
