### ISSUE TITLE
"bad interpreter: No such file or directory" error if virtual env is in a folder with whitespaces

### ISSUE THREAD

**Issue by ulf1** [Kludex/uvicorn#496]
# replicate the error
(1) install a virtual env in a folder with whitespaces

```
mkdir -p "${HOME}/folder with whitespaces/"
cd "${HOME}/folder with whitespaces/"

python3 -m venv .venv
source .venv/bin/activate
pip install uvicorn fastapi
```
(2) main.py

```
from fastapi import FastAPI
app = FastAPI()
@app.get("/")
def read_root():
    return {"Hello": "World"}
```

(3) Try to start server

```
uvicorn main:app --reload
```

Error message

```
-bash: /Users/uh/folder with whitespaces/.venv/bin/uvicorn: "/Users/uh/folder: bad interpreter: No such file or directory
```

# my guess
I guess you are using something like 

```
filepath=${filepath}
```

instead of

```
filepath="${filepath}"
```

somewhere

**Comment by lovelydinosaur** [comment]
This didn't replicate for me.
The "bad interpreter" error makes it look like a shell issue occuring before the python interpreter/uvicorn is even started.

**Comment by ulf1** [comment]
It might depend on the computer used. 
I use MacOS. 

I replicated the error in a debian docker container too. 
https://github.com/ulf1/bugreport-uvicorn

Feel free to try it with any other OS.

**Comment by lovelydinosaur** [comment]
Right, but what you’re showing me there isn’t a Python traceback. Not at all clear that it’s a uvicorn issue rather than some other environment problem. It’d be worth installing other python based command line tools too, and trying those for comparison.

**Comment by ulf1** [comment]
The cause of the problem is a shebang with whitespaces.
If you install a virtual env in a folder with whitespace,
and install `uvicorn` into the this virtual env, 
then the `../bin/uvicorn` script would have shebang like this.

```
#!"/Users/usernamename/folder with whitespaces/venvname/bin/python3"
...
```

It seems that the python project had this issue for years (see [virtualenv, issue 53](https://github.com/pypa/virtualenv/issues/53)) and fixed it somehow.

**Comment by lovelydinosaur** [comment]
Ok, thanks. That script isn’t  related by uvicorn. You might want to make sure you’ve got recent pip and virtual events versions.
