### ISSUE TITLE
Environment variable-based configuration

### ISSUE THREAD

**Issue by Stigjb** [Kludex/uvicorn#500]
## Feature request

I would appreciate the ability to set options for the `uvicorn` script using environment variables, similar to what [Flask enables](https://flask.palletsprojects.com/en/1.1.x/config/#configuring-from-environment-variables).

This would allow setting options using `.env`-files, which are automatically sourced by tools such as Pipenv. The options can easily be overridden on the command line.

Example:

```bash
$ UVICORN_PORT=8080 UVICORN_RELOAD=true uvicorn run app:app
```

`click` could enable large part of the functionality using the `auto_envvar_prefix` option, as described in the [click docs](https://click.palletsprojects.com/en/7.x/options/?highlight=environment%20variables#values-from-environment-variables).

This issue could be tied to the discussion in #322

**Comment by lovelydinosaur** [comment]
Nice idea, but going to have to treat it as out-of-scope at this point in time.
Also potentially fiddly to integrate proprely with our `--env-file` functionality.

**Comment by andrew222651** [comment]
See https://github.com/encode/uvicorn/pull/1279
