### ISSUE TITLE
Closed connections don't cancel tasks

### ISSUE THREAD

**Issue by Xowap** [Kludex/uvicorn#501]
Hi everyone,

Using `uvicorn==0.10.8`, I'm coding something that sends huuuuuge files. It's based on Django Channels.

Here is my router:

```python
application = ProtocolTypeRouter(
    {
        "http": AuthMiddlewareStack(
            URLRouter(
                [
                    url(r"^ah/(?P<file_size>\d+)\.ah$", AhConsumer),
                    url(r"", AsgiHandler),
                ]
            )
        )
    }
)
```

And here is my consumer:

```python
class AhConsumer(AsyncHttpConsumer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._running = True

    async def disconnect(self):
        print("RECEIVED DISCONNECT")
        self._running = False

    async def handle(self, body: AnyStr) -> None:
        try:
            size = int(self.scope["url_route"]["kwargs"]["file_size"])
            print(size)

            await self.send_headers(
                status=200,
                headers=[
                    (b"Content-Length", f"{size}".encode("utf-8")),
                    (b"Content-Type", b"application/octet-stream"),
                    (b"Content-Disposition", b"attachment; file.ah"),
                ],
            )

            bf = BigFile(size)

            for i in range(0, bf.size, 0xffff):
                if not self._running:
                    break

                await self.send_body(await bf.read(0xffff), more_body=True)

            await self.send_body(b'')
        except Exception:
            print_exc()
            raise
```

For reference, `disconnect()` method is called when a `http.disconnect` message is received.

Turns out that `http.disconnect` doesn't seem to be sent because `disconnect()` never gets called.

Also for reference, here is the `BigFile` implementation:

```python
class BigFile(DataStream):
    def __init__(self, size: int):
        self.size = size
        self.read_bytes = 0

    async def read(self, length: int) -> bytes:
        remain = max(0, self.size - self.read_bytes)
        to_read = min(remain, length)
        self.read_bytes += to_read

        return b"a" * to_read
```

Would anyone know if the `http.disconnect` is supposed to be sent? If I'm doing something wrong?

Thanks!

**Comment by Xowap** [comment]
Just a precision: I test by doing a wget to the file and then CTRL+C the wget mid-way.

```
> wget 'http://localhost:8000/ah/1000000000000.ah' -O/dev/null
```

**Comment by lovelydinosaur** [comment]
`uvicorn` won't pre-emptively close off outstanding responses during shutdown, no. It'll wait for them to finish sending first. (Tho it'll eventually hard kill them after a graceful shutdown timeout period)

**Comment by Xowap** [comment]
Soooooo... My use case isn't valid?

**Comment by lovelydinosaur** [comment]
There shouldn't really be an issue here. If uvicorn is shutdown, and you happen to be mid-way through one of these sends, then the application code will still continue to completion unless it takes longer than the hard shutdown period, in which case uvicorn will kill the task.

Which aspect of the behavior would you most want to see changed there, and what is the motivation?

**Comment by Xowap** [comment]
I'm streaming a huge zip file (dozens of Gio) composed of Amazon S3 files and it turns out that this is pretty CPU- and money-intensive. Indeed, my servers are not within the AWS infrastructure so the traffic to get them out is relatively expensive, plus the fact that it's going to keep the CPU busy for no reason.

In case you're interested, I solved my problem with a good old [`StreamingHttpResponse`](https://docs.djangoproject.com/en/3.0/ref/request-response/#streaminghttpresponse-objects) and going from async code (with httpx) to a plain `urlopen()` and synchronous code considerably increased the performance of the solution.

So the use case might be pretty useless (also what's the point of async if your app is CPU-bound?) but maybe it could be documented somewhere. Not sure how nor what though.
