### ISSUE TITLE
Uvicorn started from script as Linux service raises 'Invalid http request'

### ISSUE THREAD

**Issue by rsaleev** [Kludex/uvicorn#503]
And I receive no exceptions when start it by comman `sudo python3 application.py`
```
[Unit]
Description = PythonModule2

After = mysql.service
StartLimitIntervalSec=0

[Service]
Type=simple
PIDFile = /run/pythonservice.pid
Restart=always
RestartSec=1
ExecStart=/usr/bin/python3 /home/myuser/Module2/application.py

[Install]
WantedBy=multi-user.target

```
application.py
```
import uvicorn
import uvicorn.config
from service.service import app

uvicorn.run(app, host=0.0.0.0, port=8087,
            timeout_keep_alive=5)
```
service.py

```
app = Starlette(debug='debug')
@app.route('/api/exemption', methods=['GET'])
async def metro_exemption(request):
    return Response('Ready', status_code=200, media_type='text/plain')
```

Request 
http://192.168.1.3:8087/api/exemption?device=online
                
It happens from time to time and I don't understand what causes it. My code, package or OS.

**Comment by florimondmanca** [comment]
🤷‍♂️ 

Unfortunately I think we're going to need you to review this bug / UX tweak report against the latest version of uvicorn (and Starlete for your example `service.py`) see if anything has improved. Until then, closing for now for housekeeping purposes!

**Comment by JLATORRE89** [comment]
I am assuming this is resolved, but I wanted to post this in case someone else found it useful.
Add this line to your [Service] section, this might help show where the application is getting stuck while running as a service.
StandardError=append:/var/log/appError.log
