### ISSUE TITLE
Uvicorn crashes if ssl_ca_certs is not provided

### ISSUE THREAD

**Issue by jodusan** [Kludex/uvicorn#504]
If I leave out ssl_ca_certs my server crashes upon connection with:

[the following error](https://pastebin.com/D6Ewd2Jx)

Any idea why this happens? I thought only ssl_keyfile and ssl_certfile are required for https

**Comment by lovelydinosaur** [comment]
Not sure on first glace. Does the issue also replicate with `--http h11`?

**Comment by euri10** [comment]
I will close this as stale @dulex123 , feel free to reopen feeding the issue template so that's actionnable.
thanks
