### ISSUE TITLE
FORWARDED_ALLOW_IPS cannot be loaded from ENV

### ISSUE THREAD

**Issue by tomasbedrich** [Kludex/uvicorn#505]
The following two lines together makes impossible to read `FORWARDED_ALLOW_IPS` from env variable.

https://github.com/encode/uvicorn/blob/4da64be4335ba50e43d7ac8c3b5535460a9c1594/uvicorn/config.py#L160
https://github.com/encode/uvicorn/blob/4da64be4335ba50e43d7ac8c3b5535460a9c1594/uvicorn/config.py#L193

**Comment by lovelydinosaur** [comment]
Good catch. How does #507 look to you?
