### ISSUE TITLE
Running uvicorn on a separate thread

### ISSUE THREAD

**Issue by Pedrozena** [Kludex/uvicorn#506]
Hi.
I'm building a microservice that needs to handle both http-API and message-like (amqp) connection.
For this reason, I need, at least, two thread running simultaneously: One for the messaging loop and the second for the api.
I tried all the loops available from the `loop `interface without success:
-asyncio ends in the following exception: `RuntimeError('set_wakeup_fd only works in main thread')`
-uvloop with `RuntimeError("There is no current event loop in thread 'Thread-6'.")`
I then tried to manually create a new event loop in the thread calling uvicorn.run, but I get the same results.
Would it be possible to manually set the event loop object used by uvicorn?

```
from fastapi import FastAPI
import uvicorn
import sys
import threading
import logging
import uvloop
import asyncio

cust_logger = logging.getLogger("ms")

app = FastAPI()

@app.get("/{method}/{param}")
async def f(method):
    return {"method": method}


class HttpRest:
    def __init__(self, comp, settings):
        self.comp = comp
        self.host = settings['host']
        self.port = settings['port']
        self.lifespan = 'on'

    def StartLoop(self, blocking=False):
        def fn(loop):
            asyncio.set_event_loop(loop)
            module_name = vars(sys.modules[__name__])['__package__']
            try:
                uvicorn.run(module_name+":app", host=self.host, port=self.port, access_log=False, log_level='critical', 
                    loop='uvloop', lifespan=self.lifespan)
            except RuntimeError as s:
                cust_logger.error("HttpApi server shut down")
        if not blocking:
            loop = uvloop.new_event_loop()
            self.threadedServer = threading.Thread(target=fn, args=(loop,))
            self.threadedServer.start()
        else:
            fn()
    
    def StopLoop(self):
        self.lifespan = 'off'
		
-----		
		
ms = HttpRest(settings)
ms.StartLoop()
```

**Comment by lovelydinosaur** [comment]
You can use `loop="none"` to explicitly disable uvicorn doing any loop setup itself.

We ought to have some better documentation around this really.

**Comment by Pedrozena** [comment]
Even if I use loop="none", with the explicit creation of a new event loop, I obtain the same results.
This seems to be related to the signal handler installation:
using uvloop I get : `ValueError add_signal_handler() can only be called from the main thread`
while with asyncio:` RuntimeError set_wakeup_fd only works in main thread`
Thanks for the support

**Comment by euri10** [comment]
See https://github.com/tiangolo/fastapi/issues/650 and pr #402
I think unless the latter lands you can't do it

Le mar. 3 déc. 2019 à 10:44 AM, Pedrozena <notifications@github.com> a
écrit :

**Comment by indigoviolet** [comment]
```
class CustomServer(uvicorn.Server):
    def install_signal_handlers(self):
        pass

async def run_uvicorn():
    cfg = uvicorn.Config(api, loop="none", lifespan="off")
    server = CustomServer(cfg)
    await server.serve()
```
Leaving this here for future reference, the docs are lacking around this form of usage, took some digging through (to be fair, very clean) code to figure it out.

**Comment by hpgmiskin** [comment]
I came across this when looking to run FastAPI and uvicon in a thread. I think https://github.com/encode/uvicorn/issues/742#issuecomment-674411676 is a viable solution to running uvicorn in a separate thread. I thought I would cross post incase others reach this issue.
