### ISSUE TITLE
Uvicorn runs app from system interpreter rather than virtual environment

### ISSUE THREAD

**Issue by intrepidOlivia** [Kludex/uvicorn#516]
On Windows 10: I have found that when I run an app that starts the uvicorn.run process, the new process executes from my system's Python install rather than the virtual environment I set up and ran the script from initially. Is this expected behavior? I've reproduced it on two Windows machines, and it seems to be the cause of some import issues I've been having.

**Comment by intrepidOlivia** [comment]
I've created a repro case for this issue: https://github.com/intrepidOlivia/bad-import-repro

**Comment by lovelydinosaur** [comment]
I'm afraid there's not much I can do wrt. environment issues like that. Unless there's some clear indication otherwise it's unlikely to actually be an issue with Uvicorn itself.

Things to start with: Make sure that your virtualenv is activated. Double check that the `uvicorn` executable has installed into the right place. Try installing some other Python executable and see if the results differ.

**Comment by intrepidOlivia** [comment]
Do you have any other suggestions for who to reach out to? I created that repro case after two days of struggling with this. Everything is installed and runs as expected. I only see this with Uvicorn, and I only see it on Windows.

**Comment by lovelydinosaur** [comment]
Can you give an example in the shell so that it's easier to see exactly what you're doing?

Ideally including...

* Creating the virtualenv
* Installing uvicorn
* Running uvicron

**Comment by intrepidOlivia** [comment]
Well, I initially thought this was a PyCharm issue because I was setting up that IDE with the virtual environment's interpreter and it was failing on a run configured specifically to use that interpreter. But as I was getting help with that, someone on the PyCharm forums reproduced the issue on the command line:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006794599-pkg-resources-in-system-install-being-used-instead-of-virtual-environment

I'll see if I can do that as well and get you more details.

**Comment by intrepidOlivia** [comment]
It looks like I can only reproduce the issue reliably with PyCharm after all. So I guess I'll keep chatting with them! Thank you for the responses.

**Comment by FrancescoSaverioZuppichini** [comment]
same here
