### ISSUE TITLE
Bind to unix domain socket instead of ip address

### ISSUE THREAD

**Issue by johandorland** [Kludex/uvicorn#53]
When running applications like uvicorn behind a reverse proxy like NGINX it is best practice to use a unix domain socket instead of binding to an ip address. This has the benefit of improved security and performance.

This could be implemented the same way as [gunicorn](http://docs.gunicorn.org/en/latest/settings.html#server-socket) does it. If the bind parameter starts with ```unix:```, use a unix domain socket. One caveat is that the socket file will have to be created beforehand and cleaned up afterwards.

**Comment by lovelydinosaur** [comment]
Yup, that'd be great.
A pull request would be ace if ya fancy it?

**Comment by audiolion** [comment]
Here is the gunicorn implementation  https://github.com/benoitc/gunicorn/blob/master/gunicorn/sock.py

**Comment by johandorland** [comment]
Ok I'm a partial idiot :man_facepalming: . What I was trying to do already works. I just forgot to put ```unix:``` in my ```--bind``` parameter.

I think what threw me off was that when invoking uvicorn as a library it does only seem to work with host + port

https://github.com/encode/uvicorn/blob/53f728cf2d2946fc616fe1ba08cbd97e9a0ff8af/uvicorn/run.py#L38-L41

The UvicornWorker however already works on the socket level, so it works flawlessly there as gunicorn does the heavy lifting.

It might still be useful to add a way to UvicornServer to use a unix domain socket (or let the calling application supply a sock object?)

**Comment by lovelydinosaur** [comment]
Note: We *do* need to document this. We currently don't have any proper documentation about the available command line arguments.

**Comment by lovelydinosaur** [comment]
Documented this better under 0.2. - http://www.uvicorn.org/#running-with-gunicorn

Also things are more properly split out now - the standard command line tool doesn't depend on gunicorn, but we include a gunicorn worker class, and document using that, as well as running the cli for simpler style.
