### ISSUE TITLE
[question] Why is running multiple workers with an existing app object no longer allowed?

### ISSUE THREAD

**Issue by K900** [Kludex/uvicorn#540]
We're running Uvicorn in a constrained environment at $work, where the configuration for the app is streamed from the orchestrator over the network and delivered exactly once for Complicated Historical Reasons :tm:. Our current approach to spinning up a server is basically:

```python
config = read_config_from_orchestrator()
app = create_app(config)
uvicorn.run(app, host=config.host, port=config.port, workers=config.workers)
```

This worked fine on Uvicorn pre-0.10.6, but has now stopped working with the new worker changes.

There's two tricky parts to this:
1. The configuration for Uvicorn itself is part of the big configuration blob for the app, so the app configuration must be loaded before Uvicorn is brought up.
2. The configuration is streamed exactly once, and can't be reloaded afterwards, so we need to have it in shared memory for all workers. We also have no persistent storage that can be accessed without knowing said configuration, so we can't store it and grab it from the workers later.

Right now we're mostly considering either reverting to a single worker process (not ideal as we'll have a bunch of cores sitting idle) or reverting to an older Uvicorn version (also not ideal for obvious reasons). Is there anything else we can do? Maybe a way to lift the restriction? I'd be happy to write a patch if anyone can give me some direction.

**Comment by euri10** [comment]
Is it still relevant ?
I know it's a very late answer, sorry for that.
The reason I ask is that you can now use a factory flag,does that work for you?

**Comment by euri10** [comment]
closing as stale, feel free to reopen
