### ISSUE TITLE
[QUESTION]How to specify application path when running uvicorn outside of the application directory.

### ISSUE THREAD

**Issue by yezyilomo** [Kludex/uvicorn#549]
I thought there would be an option like `--chdir` in Gunicorn but I didn't find one on the documentation, at first I thought that's what `--root-path` option is used for, turns out I was wrong.

**Comment by fsecada01** [comment]
Would also like to know if this is a thing.  This would make deployments much easier.

**Comment by euri10** [comment]
Using PYTHONPATH maybe, if I understood correctly what you want?

**Comment by fsecada01** [comment]
No, something more like `--chdir backend\src` for deploying uvicorn

**Comment by anandandy139** [comment]
I am also looking for something like this. Could you help ?

**Comment by lovelydinosaur** [comment]
I think we could probably accept a pull request adding that, yup.

**Comment by Sub0X** [comment]
Following this question, is it possible to also have an app-dir kwarg for uvicorn.Config?
