### ISSUE TITLE
PyPy Support

### ISSUE THREAD

**Issue by kgriffs** [Kludex/uvicorn#55]
Hi folks, have you benchmarked this on PyPy? Just curious as to whether using the standard asyncio implementation under PyPy would be faster than uvloop due to thunking across the Cython FFI.

**Comment by lovelydinosaur** [comment]
I did do some experimental stuff, using h11 for a pure python implementation.
I don't have the time to re-assess it at the moment, but short answer was that, no it was slower for the basic "dump some json" case.
For clients with heavy computational workloads it's perfectly possible that a pure python version running under pypy *would* have better performance characteristics, but it's not a priority for me atm.

**Comment by extraymond** [comment]
Hi! Thanks for declaration. I'm a junior developer so if anything I said to be unprofessional I'm sorry. 

I was thinking that, although not directly gaining speed from pypy, it would be nice to support pypy so using uvicorn under pypy as a ASGI server would be a option.

For all the ASGI servers out there, Daphne just isn't as fast and as feature rich as gunicorn. What I really like about uvicorn is that it has the option to specify workers and threads just like gunicorn. This might help performance I guess.
