### ISSUE TITLE
reload option works only with IPv4 host

### ISSUE THREAD

**Issue by toxadx** [Kludex/uvicorn#553]
I can not specify --reload option with IPv6 only --host.
`uvicorn --reload --host="::" example:app`

The server binds only to IPv4 host.

**Comment by koaning** [comment]
Im noticing something similar if I set `--workers 4` on my rpi3.

**Comment by magnusjjj** [comment]
Was about to report the same thing, but with unix sockets.

**Comment by magnusjjj** [comment]
if config.should_reload:
        sock = config.bind_socket()
        supervisor = ChangeReload(config, target=server.run, sockets=[sock])
        supervisor.run()
    elif config.workers > 1:
        sock = config.bind_socket()
        supervisor = Multiprocess(config, target=server.run, sockets=[sock])
        supervisor.run()
    else:
        server.run()

seems to be the offending part.

config.bind_socket() has no code to deal with unix sockets, that's in the Server class.
