### ISSUE TITLE
Automatic pushes to conda-forge

### ISSUE THREAD

**Issue by hingston** [Kludex/uvicorn#554]
Would it be possible to set up automatic pushes to conda-forge when new versions of uvicorn are released?

https://conda-forge.org/docs/maintainer/updating_pkgs.html

**Comment by lovelydinosaur** [comment]
You probably want to talk any conda packaging stuff over with the maintainers of https://github.com/conda-forge/uvicorn-feedstock

I don't have any involvement there.
