### ISSUE TITLE
platform_python_implementation in env markers uses lowercase PyPy

### ISSUE THREAD

**Issue by coderfromhere** [Kludex/uvicorn#558]
Hi everyone,

https://github.com/encode/uvicorn/blob/13094d9c98510237d8db2cf490130a08873ca491/setup.py#L40

AFAIK, examples in https://www.python.org/dev/peps/pep-0508/ suggest that the `platform_python_implementation` marker is not case-insensitive and the current `pypy` marker should actually be `PyPy`.

This was discovered while resolving https://github.com/nix-community/poetry2nix/issues/43

**Comment by lovelydinosaur** [comment]
Thanks! Now resolved... https://github.com/encode/uvicorn/blob/3ae7bd166dbf1f5104753abf3e7fd5ec6904f3b5/setup.py#L40
