### ISSUE TITLE
Error using websockets==4.0.1

### ISSUE THREAD

**Issue by viniciuschiele** [Kludex/uvicorn#56]
Hi,

I was trying to run this example using uvicorn + websockets 4.0.1 (latest version):

```python
async def chat_server(message, channels):
    """
    ASGI-style 'Hello, world' application.
    """
    if message['channel'] == 'websocket.connect':
        await channels['reply'].send({'accept': True})
```

And I get this error after sending the accept message.

```
Starting worker [9001] serving at: 0.0.0.0:8000
Task exception was never retrieved
future: <Task finished coro=<reader() done, defined at /home/vinicius/projects/dealer/venv/lib/python3.6/site-packages/uvicorn/protocols/websocket.py:65> exception=TypeError('An asyncio.Future, a coroutine or an awaitable is required',)>
Traceback (most recent call last):
  File "/home/vinicius/projects/dealer/venv/lib/python3.6/site-packages/uvicorn/protocols/websocket.py", line 72, in reader
    data = await protocol.recv()
  File "/home/vinicius/projects/dealer/venv/lib/python3.6/site-packages/websockets/protocol.py", line 309, in recv
    loop=self.loop, return_when=asyncio.FIRST_COMPLETED)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 311, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/lib/python3.6/asyncio/tasks.py", line 311, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```
It works fine with websockets 3.4.0

I was looking into it and I noticed that in the protocol.py (from websockets) the variable ```transfer_data_task``` is not initialized so a ```None``` is being added to the queue of events causing the error.

It could be a bug in websockets 4.0.* or they have changed the logic and uvicorn is not compatible anymore.

**Comment by jordaneremieff** [comment]
I had this same issue working on my fork - using 3.4.0 allowed websockets to work normally.

**Comment by lovelydinosaur** [comment]
Thanks for the confirmation @erm. Hopefully I’ll get back to this given the renewed work on API Star. Bunch of other work I’ll need to get through first before coming back to websockets, tho.

**Comment by jordaneremieff** [comment]
I discovered the issue. The `.connection_open()` method on the websocket protocol needs to be called after the handshake otherwise the `transfer_data_task` future isn't assigned and causes the `recv()` method on the websocket to fail.
