### ISSUE TITLE
bad practice in logger

### ISSUE THREAD

**Issue by dmig-alarstudios** [Kludex/uvicorn#563]
This is bad: https://github.com/encode/uvicorn/blob/be50ca698b0852320a9b48480c60b34320bcdcf0/uvicorn/logging.py#L47-L53

Better implement it like this:
```python
        if self.use_colors:
            levelname = self.color_level_name(levelname, record.levelno)
            if "color_message" in record.__dict__:
                record.msg = record.__dict__["color_message"]
                record.__dict__["message"] = record.getMessage()
            record.__dict__["colorlevelname"] = levelname  #this might be very useful
        record.__dict__["levelprefix"] = levelname + ":"
```
and use formatters config:
```python
    "formatters": {
        "default": {
            "()": "uvicorn.logging.DefaultFormatter",
            "fmt": "%(levelprefix)-9s %(message)s",
            "use_colors": None,
        },
        "access": {
            "()": "uvicorn.logging.AccessFormatter",
            "fmt": '%(levelprefix)-9s %(client_addr)s - "%(request_line)s" %(status_code)s',
        },
    },
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/563">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/563/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/563/pledge.svg">
</picture>
</a>

**Comment by florimondmanca** [comment]
Hi @dmig-alarstudios, this sounds legit to me. Happy to review any PRs towards improving these practices. :-)

**Comment by euri10** [comment]
I dont think this would work since levelprefix contains the levelname plus all the asni colors codes, right-aligning it with -9s wont have any effect since most likely the length of it will be superior.

**Comment by dmig** [comment]
@euri10 you're definitely right!
I'll close this until I get a better idea.
