### ISSUE TITLE
How to redirect from http to https?

### ISSUE THREAD

**Issue by jodusan** [Kludex/uvicorn#564]
I have a production server which is running on 443 (using starlette framework) and have enabled HTTPSRedirectMiddleware but when i go to http://website.com it doesnt get redirected to https://website.com I guess this is because the server is running on 443 and not 80, so when the request comes in to 80 there is nobody there to handle it. 

Is this possible to do without running two servers?

**Comment by lovelydinosaur** [comment]
You can’t issue redirects from http->https if you don’t have port 80 open, no.

You could look at HSTS which ensures browsers only ever make https requests to your domain.
