### ISSUE TITLE
WebSocketProtocol logged as error

### ISSUE THREAD

**Issue by Pyvonix** [Kludex/uvicorn#568]
**Context**
I will link a [previous issue](https://github.com/Supervisor/supervisor/issues/1325) containing many informations about the current problem. I thought the problem came from the process manager for redirecting errors but after reading the code of **uvicorn** I found the problem. 

**Behavior**
When a **WebSocket request** is received (and accepted), the log is redirected in the **stderr.log** file...
```
INFO:     None - "WebSocket /ws/" [accepted]
```

After the response the supervisor team, I have search the logger used for `websocket` communication...

**uvicorn/protocols/websockets/websockets_impl.py**
```python
class WebSocketProtocol(websockets.WebSocketServerProtocol):
    def __init__(self, config, server_state, _loop=None):
        ...
        self.logger = logging.getLogger("uvicorn.error")
```

**Problem**
Did you have a reason to use `("uvicorn.error")` for WebSocket requests?  
Why we can't use the logger for success requests like HTTP? Because it's seem unicorn correctly understand the communication and accept it, as specified in the log `[accepted]`. So is behavior completely break the logging system to manage errors...

**Comment by Pyvonix** [comment]
Duplicate of #562 with complet context and observed behavior

**Comment by lovelydinosaur** [comment]
Closing in favour of #562
