### ISSUE TITLE
plsease introduce --limit-max-requests-jitter

### ISSUE THREAD

**Issue by kudlatyamroth** [Kludex/uvicorn#574]
As of now, we can define limit_max_requests but if we have 2~4 workes it can quickly go with all workers restarting at the same time.
Gunicorn have something like max request jitter which vary limit per each worker

**Comment by lovelydinosaur** [comment]
I don't have enough time to implement that myself, but I think we could probably accept & review any pull requests introducing that, yup.

**Comment by Stigjb** [comment]
If you are using Gunicorn and have `worker_class = "uvicorn.workers.UvicornWorker"` in your gunicorn_conf.py, max_requests and max_requests_jitter seem to work as expected.

I experimented with a Gunicorn configuration using UvicornWorker, one worker, max_requests=5 and max_requests_jitter=5, and observed that a restart happened after every 5 to 10 requests, as expected.
