### ISSUE TITLE
Incorrect MIME type for templated javascript module imports

### ISSUE THREAD

**Issue by jbsetton** [Kludex/uvicorn#576]
Greetings all,
I cannot seem to find where one explicitly defines mime types for imports. My browser is blocking all javascript module imports due to the server serving them as (“text/plain”). I realize this is a simple configuration issue, but I cannot seem to find where to set it. Any assistance provided is greatly appreciated. The console error shown below with my python 'app'.
I am running Win10 x64, Firefox 73.0 (64-bit), Python 3.7, uvicorn 0.11.2, and starlette 0.13.1. 

![image](https://user-images.githubusercontent.com/40573975/74674149-9ca7a280-5165-11ea-96d7-0b56c76fffe7.png)

```python 
from starlette.applications import Starlette
from starlette.staticfiles import StaticFiles
from starlette.responses import HTMLResponse
from starlette.templating import Jinja2Templates
import uvicorn
from random import randint

port = randint(49152,65535)

templates = Jinja2Templates(directory='templates')

app = Starlette(debug=True)
app.mount('/static', StaticFiles(directory='statics'), name='static')


@app.route('/')
async def homepage(request):
    template = "index.html"
    context = {"request": request}
    return templates.TemplateResponse(template, context)


@app.route('/error')
async def error(request):
    """
    An example error. Switch the `debug` setting to see either tracebacks or 500 pages.
    """
    raise RuntimeError("Oh no")


@app.exception_handler(404)
async def not_found(request, exc):
    """
    Return an HTTP 404 page.
    """
    template = "404.html"
    context = {"request": request}
    return templates.TemplateResponse(template, context, status_code=404)


@app.exception_handler(500)
async def server_error(request, exc):
    """
    Return an HTTP 500 page.
    """
    template = "500.html"
    context = {"request": request}
    return templates.TemplateResponse(template, context, status_code=500)


if __name__ == "__main__":
    uvicorn.run("app-567:app", host='0.0.0.0', port=port, access_log=True, http='h11', loop='asyncio', reload=True)
```

**Comment by jbsetton** [comment]
I think the _mimetypes_ standard library on windows doesn't properly locate the correct dictionary of all known types resulting in some files being mischaracterized as ("text/plain"). To get around this issue, I forcibly imported, initiated and added keys to _mimetypes_ 
```
import mimetypes
mimetypes.init()
```
and here:
```
@app.route('/')
async def homepage(request):
	mimetypes.add_type('application/javascript', '.js')
	mimetypes.add_type('text/css', '.css')
	mimetypes.add_type('image/svg+xml', '.svg')
	template = "index.html"
	context = {"request": request}
	return templates.TemplateResponse(template, context, media_type='text/html')
```
And the resulting web app correctly serves the files as the appropriate MIME content type.

**Comment by lovelydinosaur** [comment]
Closing this, in favour of https://github.com/encode/starlette/issues/829.

(The handling here is a Starlette concern, rather than anything to do with Uvicorn)
