### ISSUE TITLE
HTTP Scope missing fields

### ISSUE THREAD

**Issue by nwalsh1995** [Kludex/uvicorn#578]
https://asgi.readthedocs.io/en/latest/specs/www.html#connection-scope

>The connection scope contains:
    ...
    asgi["version"] (Unicode string) – Version of the ASGI spec.
    asgi["spec_version"] (Unicode string) – Version of the ASGI HTTP spec this server understands; one of "2.0" or "2.1". Optional; if missing assume 2.0.

I sent a request through uvicorn and noticed these fields are missing. Additionally searching the code for "spec_version" does not return any hits so I think these fields are not being handled. Potentially these were added in a later ASGI version that is not supported or I may be misunderstanding what the ASGI docs mean.

**Comment by lovelydinosaur** [comment]
Yup I think they were added later on. Would totally accept PRs adding these.
