### ISSUE TITLE
Log autorestarts caused by max_requests

### ISSUE THREAD

**Issue by Stigjb** [Kludex/uvicorn#579]
UvicornWorker supports the max_requests option in Gunicorn, but restarts due to max_requests are not distinguishable in the server logs from restarts due to other reasons.

The AsyncWorker class in Gunicorn has a log statement covering this:

https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/base_async.py#L98-L101

Is it possible to have this logged in UvicornWorker?

**Comment by lovelydinosaur** [comment]
I think we could accept pull requests around that yup, but we probably don't otherwise have the capacity to prioritse the work ourselves.
