### ISSUE TITLE
Load certificates with custom function

### ISSUE THREAD

**Issue by maxmealy** [Kludex/uvicorn#581]
Is it possible to point Uvicorn to a custom function to load an SSL certificate and keyfile, rather than passing in the filepaths? Or alternatively, point to a function to pass into the password argument when SSLContext.load_cert_chain is called? Thanks.

**Comment by lovelydinosaur** [comment]
Nope there's not anything like that available at the moment - you'd need to do a bit of digging around in the how to change the `.ssl` property on a `Config()` instance.

It's possible that we could accept a pull request adding something along these lines. It'd be interesting to know what kind of control Gunicorn gives you here, as thy've been around far longer than this project and might have already covered this ground.
