### ISSUE TITLE
reloader does not watching sys.path

### ISSUE THREAD

**Issue by voidpp** [Kludex/uvicorn#582]
According to the documentation: https://www.uvicorn.org/settings/ 

> `--reload-dir <path>` - Specify which directories to watch for python file changes. May be used multiple times. If unused, then by default all directories in `sys.path` will be watched.

So if I don't use the `--reload-dir` option the reloader should watch all the dirs in the `sys.path`, but actually it isn't.

**Comment by florimondmanca** [comment]
This is a documentation oversight — https://github.com/encode/uvicorn/pull/479 changed the behavior to watch `os.get_cwd()` to reduce high memory usage (https://github.com/encode/uvicorn/pull/452).

**Comment by florimondmanca** [comment]
Fixed by #625
