### ISSUE TITLE
Uvicorn via gunicorn worker doesn't respect `--forwarded-allow-ips`

### ISSUE THREAD

**Issue by b0g3r** [Kludex/uvicorn#589]
I use uvicorn in docker as uvicorn-worker for gunicorn for my fastapi app. My application needs to know the real client IP of each request, so I use proxy-server with the `X-Forwarded-For` header.

Gunicorn has a special option to change proxy-ip to real-ip, so I running gunicorn like this:
```
gunicorn \
  ppm_telegram_bot.api:app \
  --forwarded-allow-ips="*" 
  --worker-class=uvicorn.workers.UvicornWorker \
  --bind=0.0.0.0:$PORT
```

Because I'm in a container, my WSGI/ASGI server receives requests not from the localhost, but from the docker network.

But uvicorn-worker doesn't respect gunicorn's `forwarded-allow-ips`, so in `ProxyHeadersMiddleware.trusted_hosts` I receive default `127.0.0.1` and proxy-ip instead of real-ip.
https://github.com/encode/uvicorn/blob/9d9f8820a8155e36dcb5e4d4023f470e51aa4e03/uvicorn/middleware/proxy_headers.py#L14-L17

It looks like uvicorn-worker can forward this information to config via `config_kwargs`: https://github.com/encode/uvicorn/blob/9d9f8820a8155e36dcb5e4d4023f470e51aa4e03/uvicorn/workers.py#L28-L35

I could do PR with this change, if required 🙌

**Comment by b0g3r** [comment]
Current workaround — set  `FORWARDED_ALLOW_IPS="*"` as env var before running gunicorn

**Comment by florimondmanca** [comment]
The suggested change sounds legit to me @b0g3r, happy to review PRs. :-)

Edit: oh there's already #592. 🤦

**Comment by PetrShchukin** [comment]
I have kinda similar problem, I'd like actually to put proxy IP as forwarded-allow-ips, but when I do forwarded-allow-ips="mydomain.com" it doesn't work, I suppose that's because requests have proxy ip from the docker network, any suggestions how can I solve this issue? Don't want to leave forwarded-allow-ips="*"

**Comment by merlinz01** [comment]
Try `"userland-proxy": false` in `/etc/docker/daemon.json`, which makes it so the proxy can see the actual IP of the client rather than the Docker bridge.

**Comment by Irfan-wani** [comment]
I tried it with Gunicorn running Uvicorn workers as:
```
CMD ["gunicorn", \
     "--workers=4", \
     "--worker-class=uvicorn.workers.UvicornWorker", \
     "--bind=0.0.0.0:80", \
     "--access-logfile=-", \
     "--error-logfile=-", \
     "--log-level=info", \
     "--forwarded-allow-ips=*", \
     "-c", "gunicorn_config.py", \
     "myapp.main:app"]
```

but it is not working.

**Comment by Irfan-wani** [comment]
Seems it is working fine.
My bad.

In my case, I am using ECS with ALB, so need to check that too.
