### ISSUE TITLE
Proxy Middleware grabs the last IP in `x-forwarded-for`, not the first

### ISSUE THREAD

**Issue by b0g3r** [Kludex/uvicorn#590]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For says the first IP in is a client IP, but ProxyHeadersMiddleware grabs the last IP:
https://github.com/encode/uvicorn/blob/9d9f8820a8155e36dcb5e4d4023f470e51aa4e03/uvicorn/middleware/proxy_headers.py#L41

**Comment by jiamo** [comment]
At now the logic for `x-forwarded-for` are different from gunicorn. After change to uvicorn 0.11.5 my logic depend on  `x-forwarded-for` failed.

**Comment by horseinthesky** [comment]
https://github.com/encode/uvicorn/blob/master/uvicorn/middleware/proxy_headers.py also sets the client port as 0 which is not proper.
```
               if b"x-forwarded-for" in headers:
                    # Determine the client address from the last trusted IP in the
                    # X-Forwarded-For header. We've lost the connecting client's port
                    # information by now, so only include the host.
                    x_forwarded_for = headers[b"x-forwarded-for"].decode("ascii")
                    host = x_forwarded_for.split(",")[-1].strip()
                    port = 0
                    scope["client"] = (host, port)
```
