### ISSUE TITLE
Is there missing close code？

### ISSUE THREAD

**Issue by MisLink** [Kludex/uvicorn#593]
This line: https://github.com/encode/uvicorn/blob/9d9f8820a8155e36dcb5e4d4023f470e51aa4e03/uvicorn/protocols/websockets/wsproto_impl.py#L66

**Comment by lovelydinosaur** [comment]
From https://asgi.readthedocs.io/en/latest/specs/www.html#close

> `code` *(int)* – The WebSocket close code, as per the WebSocket spec. Optional; defaults to `1000`.

So no, not strictly required here.

**Comment by MisLink** [comment]
I asked because I received some `KeyError 'code'` traceback. It shows [django channels](https://github.com/django/channels/blob/c6ea33b8f655cf8f9ac8d563a06a7e457561b9e7/channels/generic/websocket.py#L106) read `code` from message directly.
So the spec says the code is `optional, default to 1000`, does it means setting it to 1000 if not set? If so, Which one of uvicorn, wsproto,channels need setting it to default?

**Comment by lovelydinosaur** [comment]
@MisLink Okay - It's possible that line in Channels should be `message.get("code", 1000)`.
