### ISSUE TITLE
uvicorn.run.run function shadows uvicorn.run module

### ISSUE THREAD

**Issue by sirex** [Kludex/uvicorn#60]
`uvicorn/__init__.py` has this line:

```python
from uvicorn.run import run
```

This line shadows `uvicorn.run` module and for example, I can't import module like this `import uvicorn.run`, because it gives function, not module. But on the other hand, `from uvicorn.run import UvicornServer`.

**Comment by lovelydinosaur** [comment]
Resolved in 0.2.
