### ISSUE TITLE
Should Uvicorn terminate the application instance on exception?

### ISSUE THREAD

**Issue by ackerleytng** [Kludex/uvicorn#601]
In `/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py:387`, uvicorn catches the exception from the client, prints it out, and does not terminate the offending application.

The [ASGI spec](https://asgi.readthedocs.io/en/latest/specs/main.html#error-handling) seem to suggest that  servers "must terminate the application instance and its associated connection if this happens."

Should we terminate the application?

**Comment by lovelydinosaur** [comment]
I think the spec likely needs re-writing there then. You really don't want to terminate the server on an uncaught exception. Logging it to stderr or whatever, and leaving the server running seems a pretty decent policy.
