### ISSUE TITLE
How to log time of response to access log?

### ISSUE THREAD

**Issue by tonal** [Kludex/uvicorn#606]
How to log time of response to access log?

**Comment by lovelydinosaur** [comment]
You'd probably want to look into adding middleware if you want to monitor response timing and similar information.

The chat room is a useful place for usage questions... https://gitter.im/encode/community

**Comment by lambdaq** [comment]
response time in log should be natively supported rather than a user middleware. It's a vital metric in most API services.

**Comment by Kludex** [comment]
Yeah, I'm aware. There are PRs changing our logger setup. In the meantime, you can check the implementation (or use) https://github.com/Kludex/asgi-logger

**Comment by lambdaq** [comment]
https://github.com/encode/uvicorn/issues/527

Found this for the interested.  Should be enough.
