### ISSUE TITLE
Do not hardcode uvloop into UvicornServer.run

### ISSUE THREAD

**Issue by sirex** [Kludex/uvicorn#61]
Currently asyncio event loop is replaced in `UvicornServer.run` method:

```python
    def run(self, app, host, port):
        asyncio.get_event_loop().close()
        asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
        loop = asyncio.get_event_loop()
```

Because of that, there is no way for app to do initialization using uvicorn event loop, because before running the server, existing event loop is closed and replaced by new one.

I thin, event loop policy should be change only if uvicorn is the main entry point, for example `uvicorn.main.run` could do that. Otherwise, app using uvicorn should take care changing event loop policy.

**Comment by lovelydinosaur** [comment]
Happy to take a pull request on this.

I'd suggest adding `loop="asyncio"` as a parameter here... https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L52

**Comment by lovelydinosaur** [comment]
I'd like to keep the default behaviour as "auto-detect", but you *can* now use `loop="asyncio"` to just use whatever `asyncio.get_event_loop()` returns.
