### ISSUE TITLE
If I use pypy,will uvicorn be faster?

### ISSUE THREAD

**Issue by Chise1** [Kludex/uvicorn#613]
I find that pypy can use uvicorn,but I don't know if uvicorn can be fast by jit.?

**Comment by lovelydinosaur** [comment]
Hiya! Let's try to take discussions to https://gitter.im/encode/community as a starting point.

It *might* help if you've got some endpoints that perform some compute-intensive pure python work, but typically probably not, the cpython implementation performed better on benchmarking that I've run.

In either case it's almost certainly a premature maybe-or-maybe-not-optimisation that you don't need to care about unless you're running something at serious scale, across multiple hosts.
