### ISSUE TITLE
Errors when installing dependencies in the virtual environment.

### ISSUE THREAD

**Issue by djbaldey** [Kludex/uvicorn#628]
pip install -r requirements.txt returns
```
ERROR: wsproto 0.13.0 has requirement h11~=0.8.1, but you'll have h11 0.9.0 which is incompatible.
ERROR: flake8 3.7.9 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 2.2.0 which is incompatible.
```

My system:
```
Linux p633 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
Python 3.7.3
pip 20.0.2 from /home/djbaldey/src/uvicorn/venv/lib/python3.7/site-packages/pip (python 3.7)
```

I think need to make a versions adjustment in the dependency file.

**Comment by lovelydinosaur** [comment]
So the `requirements.txt` is only strictly required for development on uvicorn itself, so you ought to be able to install that in a clean virtualenv. Wrt. version clashes in `setup.py`, we'd be happy to accept issue against any lib versions that need updating.

It looks like our *actual* h11 requirements are more loose than listed in `requirements.txt`... https://github.com/encode/uvicorn/blob/b1ee2b86f10e68605d782672e067de204b822b75/setup.py#L45

**Comment by lovelydinosaur** [comment]
Oh right, I see the errors are against a clean setup - not clear what effect they're actually having since it *does* still install all the dependencies, and the tests are running okay, so?

**Comment by florimondmanca** [comment]
Closing tentatively — ran a fresh install myself earlier today, and things were fine, plus we had a bunch of changes to our requirements recently so we'd need to review if this issue still stands as of today. Feel free to reach back if there's any updates!
