### ISSUE TITLE
--log-level ignored for additional loggers?

### ISSUE THREAD

**Issue by sderuiter** [Kludex/uvicorn#640]
Possibly due to me not understanding the logger, but I run `uvicorn app:app --log-level warning`. My app, however, adds it's own loggers like `logger = logging.getLogger("tc.app.join_game")` and I log messages to this (going to a file), mostly .info, some .warning. 

My expectation: running uvicorn with --log-level warning would also silence the .info logs from my app and have them only be visible in the log file (where they are visible, as expected). 

Observed behaviour: I see colorful INFO log messages from my app appear (next to the log file)...

Have I misunderstood the working of log-level?

**Comment by euri10** [comment]
> Possibly due to me not understanding the logger, but I run `uvicorn app:app --log-level warning`. My app, however, adds it's own loggers like `logger = logging.getLogger("tc.app.join_game")` and I log messages to this (going to a file), mostly .info, some .warning.
> 
> My expectation: running uvicorn with --log-level warning would also silence the .info logs from my app and have them only be visible in the log file (where they are visible, as expected).

I think log-level will only set the levels of `uvicorn.error` , `uvicorn.access` and `uvicorn.asgi`

> Observed behaviour: I see colorful INFO log messages from my app appear (next to the log file)...
> 
> Have I misunderstood the working of log-level?

I think this may have been fixed in #645

**Comment by euri10** [comment]
Without further comment let's assume it's fixed :)
