### ISSUE TITLE
Reload Behavior: Documentation != Code, Unnecessary Reloads

### ISSUE THREAD

**Issue by kalzoo** [Kludex/uvicorn#656]
Hey! I upgraded to 0.11.4 shortly after release today, and it has a couple of quirks.

1. The documentation [here](https://github.com/encode/uvicorn/compare/0.11.3...0.11.4#diff-1819b1daaccb3d358620ade9c67e9118R22) says "python file changes" but the code says ["all non-dotfile changes"](https://github.com/encode/uvicorn/compare/0.11.3...0.11.4#diff-b0da863c7164698a2ef0fa805e4a9197R40).
2. That behavior, while from the test cases seems to be intended to roll up things like `.graphql` files, also unfortunately rolls up `.pyc` files, meaning every restart is a double restart:

```
WARNING:  Detected file change in 'app/main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [87024]
INFO:     Started server process [87080]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  Detected file change in 'app/__pycache__/main.cpython-37.pyc'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [87080]
INFO:     Started server process [87093]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

It might be better to use [Path.glob](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob) so users can specify file extensions and paths more explicitly than with `os.walk`, but it's published already so maybe as another flag?

3. A minor point, but worth noting in the docs: `--reload_dir` on the CLI becomes `reload_dirs=['my_dir']` in code: `uvicorn.run('app.main:app', host="0.0.0.0", port=8000, reload=True, reload_dirs=['app'])`

Thanks for making this great library!

**Comment by euri10** [comment]
Can you please paste the output just above what you pasted just to see what reloader it uses?

**Comment by euri10** [comment]
ok it's on statreloader, will send a PR asap

**Comment by lovelydinosaur** [comment]
Thanks for reporting this! 0.11.5 is now published... https://github.com/encode/uvicorn/runs/629310851?check_suite_focus=true
