### ISSUE TITLE
Uvicorn not processing some requests randamly

### ISSUE THREAD

**Issue by hrishikesh-hirlikar** [Kludex/uvicorn#663]
We are running a Fastapi + Uvicorn web application using gunicorn as a process manager and Nginx as the reverse proxy server. The application is running in async mode for most of the i/o operations (DB call, Rest apis). The whole setup is running inside a Docker container on Ubuntu 16.04.

The setup works most of the times but sometimes it does not process a request at all & it gets timed out at Nginx end. We also tried taking Nginx out of the setup and observed that few requests get processed after really long time (like after 15 mins). This is very random but usually happens 2-3 times in an hour.

Below is the gunicorn config that we are using –

`host = os.getenv("HOST", "0.0.0.0")`
`port = os.getenv("PORT", "80")`

`workers = web_concurrency`
`bind = f"{host}:{port}"`
`keepalive = 2`

`timeout = 60  `
`graceful_timeout = 30`
`threads = 2`
`worker_tmp_dir = "/dev/shm"`

`capture_output = True`
`loglevel = os.getenv("LOG_LEVEL", "debug")`

And gunicorn is invoked with command `exec gunicorn -k uvicorn.workers.UvicornWorker -c "$GUNICORN_CONF" "$APP_MODULE"`

We have tried several config changes like –

1. Changing the number of workers, worker timeout
2. Changing the process manager from gunicorn to supervisord
3. Offloading the CPU intensive task to Celery instead of threading
4. Binding uvicorn app to unix socket instead of proxy server

**Comment by erewok** [comment]
Hello, it sounds like there may be too many things in your stack to identify this as an issue with any particular one. For instance, you mention running under Docker: if your application has CPU limits, which are sometimes applied to Docker containers especially in [Kubernetes pods](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718), then it's common to see CPU throttling which results in requests taking an exorbitant amount of time to process. I offer this merely as an example to say that there's so much going on in what you have written that for this to be useful to the uvicorn project as a bug report, you should produce a minimally reproducible example which includes _only_ uvicorn to the greatest extent possible. 

Can you replicate this problem running a minimal uvicorn application only? Can you put together an example that fits inside a comment here that demonstrates this issue?

**Comment by lovelydinosaur** [comment]
I was going to say something similar to @erewok yup, there's too much going on here for us to usefully narrow this down to being an actionable uvicorn issue. Some useful approaches you could try onto this might include...

* Write an ASGI middleware, to monitor if there's any application-level issues.
* Swtich to using `hypercorn` or `daphne` as the ASGI server to see if the issue is still replicating.

You might also want to pay particular attention to any CPU intensive parts that're running inside an async context, since any blocking code like that ought to be run within a thread pool.

**Comment by pacoyang** [comment]
I got the same issue, the `uvicorn` stop process any requests randomly, after about 15 mins the process going back and print out the log message during the blocking, the application have DB call(sqlalchemy sync session) and contains some internal api requests use `httpx(anyio)`. My setup is nginx -> uvicorn single worker with supervisord -> fastapi, all in one docker container. The cpu usage is low, can not replicate this problem in local environment, have you figured out this issue? @hrishikesh-hirlikar
