### ISSUE TITLE
Better host name check for consistency and more idiomatic exc

### ISSUE THREAD

**Issue by hzlmn** [Kludex/uvicorn#664]
Hello, first i would like to thanks for making this library. It is really  🍰.

I have a case where using `FastAPI` i want to run `uvicorn` with auto-reload in debug mode from python code. The following snippet will work
```python
>> main.py
import uvicorn
from fastapi import FastAPI

from .config import Config

app = FastAPI()

@app.get("/")
async def handler():
    return "Hello"

if __name__ == "__main__":
    config = Config()
    uvicorn.run(
        "main:app",
        host=config.HOST,
        port=config.PORT,
        reload=config.DEBUG,
        debug=config.DEBUG,
    )

```  
But when for some reason config.HOST is None i will get
```
Traceback (most recent call last):
  File "/Users/oleg/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/oleg/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/oleg/Projects/leapi-python/api_internal/main.py", line 115, in <module>
    uvicorn.run("api_internal.main:app", host=config.HOST, reload=True,port=config.PORT, debug=True)
  File "/Users/oleg/.local/share/virtualenvs/leapi-python--jMs55TN/lib/python3.6/site-packages/uvicorn/main.py", line 346, in run
    sock = config.bind_socket()
  File "/Users/oleg/.local/share/virtualenvs/leapi-python--jMs55TN/lib/python3.6/site-packages/uvicorn/config.py", line 329, in bind_socket
    sock.bind((self.host, self.port))
```
Because there is not check in bind_socket for falsy values.
```python
 def bind_socket(self):
        sock = socket.socket()
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((self.host, self.port))
        except OSError as exc:
            logger.error(exc)
            sys.exit(1)
        sock.set_inheritable(True)
        ...
```
But in regular mode without debug in reload it will run and will be as expected (use default "127.0.0.1")

Would be nice to make similar behavior in both modes for consistency.

If it is a case i can create small PR.

**Comment by lovelydinosaur** [comment]
I'd suggest that you don't use `None` as the default for the host argument, use `""127.0.0.1"` as the default if it is unset.

Our own default for `host` is `"127.0.0.1"`, rather than `None`.

https://github.com/encode/uvicorn/blob/c30851184c8388253fb08c9cb651dc0ae8be8cf0/uvicorn/config.py#L110

**Comment by hzlmn** [comment]
Yeah, i understand that more verbose default is a better option, but what was my actual confusion is that without debug mode it start server 
```
INFO:     Started server process [54657]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://None:8080 (Press CTRL+C to quit)
```
because internally asyncio handle this case.

But anyway thanks for response!
