### ISSUE TITLE
Support Websocket Denial Response

### ISSUE THREAD

**Issue by abersheeran** [Kludex/uvicorn#667]
https://asgi.readthedocs.io/en/latest/extensions.html#websocket-denial-response

Any support about this? This is helpful in providing clearer tips for websocket errors. For example, return 401, 403, 404.

**Comment by lovelydinosaur** [comment]
We might be able to consider any pull requests implementing this, sure.

**Comment by abersheeran** [comment]
If I don’t have a new appointment this weekend, I can try to achieve it. 😄Although I am not very good at it.

**Comment by ppolewicz** [comment]
@tomchristie what should the PR implementing this be like in order to increase its chances of getting merged? Any hints? I can't find the contributor guide, it was only mentioned in #74.
