### ISSUE TITLE
`timeout_keep_alive` is ignored

### ISSUE THREAD

**Issue by mpekalski** [Kludex/uvicorn#669]
I run `fastAPI` on `Uvicorn`, and in one of the routes I span not so long running subproces (limited by timeout). I wanted to have a graceful shutdown that would not kill the process but wait for execution or catch the timeout.

I hoped that `timeout_keep_alive` config property would make the `Uvicorn` stop receiving any new connection and wait for my processes to finish executing or timeout untill `timeout_keep_alive` is reached, but it seems like this property does not work as advertised. 

What solved my problem was adding a sleep just before closing connections in https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L536

```
logger.info(f"Watiting {self.config.timeout_keep_alive} seconds to finish existing requests")
await asyncio.sleep(self.config.timeout_keep_alive)
```

If I did not do it sometimes my test queries were responding with timeout and sometimes with 
```
$* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

**Comment by euri10** [comment]
I'm closing this @mpekalski for cleaning purposes, the issue is old enough and I'm sorry wasn't properly answered, feel free to reopen if you still face it, just make sure to fill the issue template, thanks
