### ISSUE TITLE
how to deploy a django project using systemd daemon?

### ISSUE THREAD

**Issue by marcossouzadotdev** [Kludex/uvicorn#673]
the documentation looks very poor for a beginner.

So, before I had something like this for the gunicorn:

    [Unit]
    Description=gunicorn daemon
    After=network.target
    
    [Service]
    User=ubuntu
    Group=www-data
    WorkingDirectory=/home/ubuntu/geeknoon_server
    ExecStart=/home/ubuntu/venv/bin/gunicorn --workers 3 --bind unix:/home/ubuntu/geeknoon_server/geeknoon_server.sock config.wsgi:application
    
    [Install]
    WantedBy=multi-user.target

But now I don't know how to do the same for uvicorn, there are no examples using systemd daemon, and I also don't know which parameter to put the values on, since the properties are different.

    [Unit]
    Description=uvicorn daemon
    After=network.target
    
    [Service]
    User=ubuntu
    Group=www-data
    WorkingDirectory=/home/ubuntu/geeknoon_server
    ExecStart=/home/ubuntu/venv/bin/uvicorn --workers 3 --bind unix:/tmp/uvicorn.sock config.asgi:application
    
    [Install]
    WantedBy=multi-user.target

**Comment by lovelydinosaur** [comment]
Heya,

Please don't demand folks time like this.

If you're having problems figuring out how to integrate uvicorn in some particular way we'd happily accept pull requests improving documentation in particular areas, or you're welcome to try asking on the discussion group. https://gitter.im/encode/community
