### ISSUE TITLE
Websocket timeout configuration?

### ISSUE THREAD

**Issue by ChillarAnand** [Kludex/uvicorn#68]
Daphne has config options for websocket timeout

```
  --websocket_timeout WEBSOCKET_TIMEOUT
                        Maximum time to allow a websocket to be connected. -1
                        for infinite.
  --websocket_connect_timeout WEBSOCKET_CONNECT_TIMEOUT
                        Maximum time to allow a connection to handshake. -1
                        for infinite
```

So server never closes connections by default. 

I am trying to use uvicorn to run django asgi with this command.

```
uvicorn foo.asgi --workers 5 --log-level debug --bind 0.0.0.0:9000 --timeout 14400 --graceful-timeout 14400
```

Unfortunately, websockets are getting closed after a minute or so. Is there a way to configure this?

**Comment by matthiask** [comment]
Do you have a nginx between uvicorn and your client? Take a look at proxy_read_timeout and friends then. 60sec sounds like the default value of nginx's timeout settings.

**Comment by ChillarAnand** [comment]
Excellent catch @matthiask. I am using nginx in between. Increasing `proxy_read_timeout` fixed the issue. 

Even with daphne, I was using nginx and it was working without `proxy_read_timeout`. Any idea why it worked in this case?

**Comment by matthiask** [comment]
I think Daphne sends regular pings over websocket connections which act as
keepalives in this case.

**Comment by ChillarAnand** [comment]
I see. Thank you :-)

**Comment by kangelov** [comment]
I am afraid this is closed in error. 
Uvicorn allows websockets to sit open indefinitely, yet some backends for Django Channels (e.g. channels-redis) always need to put an upper bound on how long a websocket will be allowed to be subscribed to events. As a result, when that deadline is reached, a websocket would go silent, never to see traffic again. As there no event when this happens, Uvicorn needs to allow for a way to force websockets to close once they reach a certain age. This is the reason for the Daphne --websocket-timeout parameter. It has nothing to do with pings, or read timeouts.
