### ISSUE TITLE
timeout in uvicorn 0.11.4 vs 0.11.5

### ISSUE THREAD

**Issue by anlaksh88** [Kludex/uvicorn#681]
I have been testing uvicorn with gunicorn. When I use version 0.11.4, I get a lot of "critical worker timeout" errors. I think all the workers are timing out based on the timeout configuration. I do not see this happening with 0.11.5. Was there a bug in 0.11.4 that was fixed in 0.11.5?

**Comment by euri10** [comment]
Correct, 0.11.4 had a wrong fix that was reverted in https://github.com/encode/uvicorn/pull/658
