### ISSUE TITLE
Uvicorn can not start FastAPI APP

### ISSUE THREAD

**Issue by cgi1** [Kludex/uvicorn#687]
```
import uvicorn
from fastapi import FastAPI
app = FastAPI(title='MADS API')
uvicorn.run(app, host='0.0.0.0', port=8127, workers=2)
WARNING:  You must pass the application as an import string to enable 'reload' or 'workers'.
```
(Than it quits with System Code 1)

Versions:
```
$ pip3 list |grep "uvicorn\|fastapi"
fastapi                          0.55.1       
uvicorn                          0.11.5 
```
Ubuntu 20.04; python 3.8.2

**Comment by dhendo** [comment]
I think you need to pass the app as a string, rather than directly, as you've passed the workers argument.

`uvicorn.run("your_module_name:app", host='0.0.0.0', port=8127, workers=2)`

**Comment by euri10** [comment]
yes @dhendo is right !

**Comment by cgi1** [comment]
Understand - But how can I define the name of the module here`?

Uvicorn can not find `your_module_name`:

`ERROR:    Error loading ASGI app. Could not import module "your_module_name".`

**Comment by dhendo** [comment]
It'll depend on the file name - if for example it was called `server.py` then the string you should use is `"server:app"`

**Comment by cgi1** [comment]
@dhendo This finally solved my issue - Thanks!
