### ISSUE TITLE
Server Sent Events (SSE) and send buffer flushing

### ISSUE THREAD

**Issue by bowmanjd** [Kludex/uvicorn#689]
I have a simple ASGI app, seen below. The server appears to be sending the data at the expected intervals, and the headers look right, but the browser does not receive the data until the connection is closed. Is this a buffering issue? How might one flush the buffer so it goes straight to the browser?

Here is the application code:

```python
import asyncio
import datetime


async def app(scope, receive, send):
    headers = [(b"content-type", b"text/html")]
    if scope["path"] == "/":
        body = (
            "<html>"
            "<body>"
            "</body>"
            "<script>"
            "  let eventSource = new EventSource('/sse');"
            "  eventSource.addEventListener('message', (e) => {"
            "    document.body.innerHTML += e.data + '<br>';"
            "  });"
            "</script>"
            "</html>"
        ).encode()

        await send({"type": "http.response.start", "status": 200, "headers": headers})
        await send({"type": "http.response.body", "body": body})
    elif scope["path"] == "/sse":
        headers = [
            (b"content-type", b"text/event-stream"),
            (b"cache-control", b"no-cache"),
            (b"connection", b"keep-alive"),
        ]

        async def body():
            ongoing = True
            while ongoing:
                try:
                    payload = datetime.datetime.now()
                    yield f"data: {payload}\n\n".encode()
                    await asyncio.sleep(10)
                except asyncio.CancelledError:
                    ongoing = False

        await send({"type": "http.response.start", "status": 200, "headers": headers})
        async for chunk in body():
            await send({"type": "http.response.body", "body": chunk, "more_body": True})
        await send({"type": "http.response.body", "body": b""})
    else:
        await send({"type": "http.response.start", "status": 404, "headers": headers})
        await send({"type": "http.response.body", "body": b""})

```

This can be run by naming the file above to `asgi_sse.py`, then using something like
```bash
uvicorn asgi_sse:app
```

The headers:
```bash
$ curl -I http://localhost:8000/sse
HTTP/1.1 200 OK
date: Mon, 01 Jun 2020 09:51:41 GMT
server: uvicorn
content-type: text/event-stream
cache-control: no-cache
connection: keep-alive
```

And the response:
```bash
$ curl http://localhost:8000/sse
data: 2020-06-01 05:52:40.735403

data: 2020-06-01 05:52:50.736378

data: 2020-06-01 05:53:00.736812
```

Weird that curl gets the data immediately...

Is there documentation needed on how to get SSE to work with uvicorn? Or (more likely) am I doing something wrong?

I put the [code above on repl.it][1] To try it out, please fork and run it. Strangely, it works as intended on repl.it.

  [1]: https://repl.it/@jonathanbowman/asgi-sse

**Comment by bowmanjd** [comment]
I changed the above code to send 64k bytes with each event, and that makes things work.

I suspect, then that this is related to the uvloop 64k send buffer.

How do I flush the send buffer, without sending 64 kilobytes of data each time?

**Comment by lovelydinosaur** [comment]
If curl is getting the data immediately then it seems unlikely there there's an issue with the server flushing the data. You might also want to try using something like streaming with `requests` or `httpx` to double check if they're getting the same behaviour.

You might want to start by trying things out on a couple of different browsers, and also by using the network inspector tools to see if you're able to determine when the data arrives.

For now I'm going to close this on the issue that it's a client side problem you're running into one way or another, but I'd be happy to reassess if there's more indicators that it's a problem in uvicorn.

**Comment by bowmanjd** [comment]
Yes, I have just identified that, while all the browsers on my computer (Chrome, Firefox, and Edge) have this issue, it works fine from Chrome on my phone. So, you are right to close this. I will figure out what might be going on with my instance of Windows. Thanks for your help!

**Comment by bowmanjd** [comment]
I wanted to document my resolution here, in case it helps anyone.

It turns out it had to do with Sophos Endpoint Security's "web protection" which was intentionally forcing buffering of the first two megabytes of an event stream. Troubling.

You can find my entire write up [on StackOverflow](https://stackoverflow.com/questions/62129788/on-a-machine-running-sophos-why-do-all-my-browsers-fail-to-receive-server-sent).

I remain perplexed as to why at least some non-Python implementations were working fine, and why ASGI does not expose and document some sort of flush method on an HTTP stream.

**Comment by bokunodev** [comment]
hi, i just tried uvicorn and i'm facing the same issue.
it seems like there is noway to manually flush response buffer, is there a solution for this?
or this is by design and an intended behavior. 
i'm on linux arch 5.10.70-1-lts

**Comment by synodriver** [comment]
```
async def func(scope, receive, send):
    if scope["type"] == "http":
        await send({"type": "http.response.start", "status": 200,
                    "headers": [(b"Content-Type", b"text/event-stream"), (b"Cache-Control", b"no-cache"),
                                (b"X-Accel-Buffering", b"no")]})
        for i in range(10):
            await send({"type": "http.response.body", "body": f"data: {i}\r\n".encode(), "more_body": True})
            await asyncio.sleep(1)
        await send({"type": "http.response.body", "body": b""})
```
Maybe you need anothor header field ```X-Accel-Buffering```.
