### ISSUE TITLE
TypeError while disconnecting socket connections

### ISSUE THREAD

**Issue by ChillarAnand** [Kludex/uvicorn#69]
Uvicorn sometimes throws this error when client tries to disconnect. This doesn't seem to happen when daphne is used.

```
Task exception was never retrieved
future: <Task finished coro=<websocket_session() done, defined at /home/chillar/.virtualenvs/mesh/lib/python3.6/site-packages/uvicorn/protocols/websocket.py:31> exception=TypeError("'<=' not supported between instances of 'int' and 'NoneType'",)>
Traceback (most recent call last):
  File "/home/chillar/.virtualenvs/mesh/lib/python3.6/site-packages/uvicorn/protocols/websocket.py", line 40, in websocket_session
    data = await protocol.recv()
  File "/home/chillar/.virtualenvs/avilpage.com/lib/python3.6/site-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/home/chillar/.virtualenvs/avilpage.com/lib/python3.6/site-packages/websockets/exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

**Comment by jordaneremieff** [comment]
Looks like this is an issue that may be resolved in the next websockets release: https://github.com/aaugustin/websockets/issues/350#issuecomment-386092541.

**Comment by lovelydinosaur** [comment]
> This doesn't seem to happen when daphne is used.

Interesting. I assume `daphne` uses the same websockets package?

**Comment by jordaneremieff** [comment]
Daphne uses `autobahn.twisted.websocket`.

**Comment by lovelydinosaur** [comment]
Okay, I guess the next question is can we work around this prior to the next release of the `websockets` package?

**Comment by jordaneremieff** [comment]
@tomchristie Perhaps. I was intending to PR improved handling of disconnects/timeouts at some point in the nearish future - could be an opportunity then - but I haven't run into this particular issue myself and would need to recreate it.

I noticed in the traceback that it is using the code (current PyPi version) prior to this [commit](https://github.com/encode/uvicorn/commit/24bf63f5c6e1f3fa226e417b89f4e4d32ffa26e4) which includes a few changes to the disconnect/close flow.

@ChillarAnand could you provide more information about how I can recreate this error?

**Comment by ChillarAnand** [comment]
This seems to happen under heavy load. You can run a load test which will trigger this.

```sh
thor -C 100 -A 1000 wss://demo.avilpage.com/posts/223/
```

**Comment by jordaneremieff** [comment]
An update on this, a new version of `websockets` has just been released that should include the fix for the issue I linked - though I have not been able to confirm if that was also the cause of the original issue here.

@ChillarAnand could you try testing against the new version of `websockets` (5.0)?

**Comment by ChillarAnand** [comment]
After updating websockets, this issue seems fixed.

Thanks @erm.
