### ISSUE TITLE
[question] how uvicorn deal with logging

### ISSUE THREAD

**Issue by flapili** [Kludex/uvicorn#691]
Hi,

I come from Tornado world and I don't know a lot about the  uvicorn/Guvicorn ecosystem.

I have some questions about logging, how deal with blocking loggings handlers in uvicorn and also how workers work in gunicorn (spawn new process ? thread ?), this question is probably XY so I'll expose my current solution with Tornado:

I need to write logs in files and I currently use [start(0)](https://www.tornadoweb.org/en/stable/tcpserver.html#tornado.tcpserver.TCPServer.start) in Tornado, that fork the process, so I can't write to the file directly even if fd are shared  via the fork.
I have to send all logs to an another process [Sending and receiving logging events across a network
](https://docs.python.org/3/howto/logging-cookbook.html#sending-and-receiving-logging-events-across-a-network) with a queue in each Tornado process and also a queue in the logger process.

Now I had exposed my current context I would need some advice on some point.

- does uvicorn handle logging in a thread ? or rather does blocking handlers still block the event loop (I want to use SMTPhandler) ? if it does I still have to use a queue + queueHandler + queueListener

- the [settings ](https://www.uvicorn.org/settings/) page say about log config 
> --log-config <path> - Logging configuration file.
but does uvicorn can work with dict or yaml config file or only [that](https://docs.python.org/3/library/logging.config.html#configuration-file-format)?

> Run gunicorn -k uvicorn.workers.UvicornWorker for production.
Does that spawn multiple process to bypass the GIL or only create a threadpool ?

- this question is not really related to uvicorn but do you know how I can join the log queue if I have to use config file ? 

PS: sorry for my english

**Comment by lovelydinosaur** [comment]
Hiya. You might have more luck with questions in the chat space... https://gitter.im/encode/community
We're trying to avoid using GitHub for usage questions and discussions, since it simply introduces too much maintainer burden.
