### ISSUE TITLE
Include a environment variable to change arg commands

### ISSUE THREAD

**Issue by rspadim** [Kludex/uvicorn#693]
Hello,

I'm testing the FASTAPI (https://fastapi.tiangolo.com/) and there's a nice environment variable when running with gunicorn (https://docs.gunicorn.org/en/stable/settings.html#settings) `GUNICORN_CMD_ARGS`, it include command line args using enviroment variables

this is very usefull when using docker compose, or k8s. without rebuild the container i can change how it starts (more debug messages instead of only critical)

could be possible include a enviroment at uvicorn? `UVICORN_CMD_ARGS`

the gunicorn_cmd_args implementation can be saw here:

https://github.com/benoitc/gunicorn/blob/ee685e197b3f7cf899dc7d6e0688ff169e9d10df/gunicorn/app/base.py#L171

https://github.com/benoitc/gunicorn/blob/6aab4decde5735fc77daf4fecaf9ef3632189f62/gunicorn/config.py#L79

thanks!

**Comment by rspadim** [comment]
reading click pypi, maybe something could be done here:

https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables

**Comment by rspadim** [comment]
https://github.com/encode/uvicorn/blob/d9d7bc6b38d07a4187882a2d49d92f1640c2446c/uvicorn/__main__.py#L4


maybe instead of:

```
    uvicorn.main()
```

use 
```
    uvicorn.main(auto_envvar_prefix='UVICORN')
```

**Comment by kolypto** [comment]
+1 to this!
