### ISSUE TITLE
Consider Splitting into Uvicorn-Core and Uvicorn-HTTP for generalized TCP Workers

### ISSUE THREAD

**Issue by hansonkd** [Kludex/uvicorn#695]
For some context on this ticket, I have used uvicorn to load-balance the redis protocol across workers: https://github.com/hansonkd/Tino it still needs some work, but Uvicorn almost worked right out of the box for my use case.

Basically all we need to do to let this happen is to remove the HTTP dependencies from setup.py and allow us to set the server and protocol names in the config. Thats it! And part of it is already done and working: https://github.com/encode/uvicorn/pull/694, The current `uvicorn` repo would become `uvicorn-core`. `uvicorn` repo would import `uvicorn-core` and define the `protocol_class` in Config to be the HTTP protocol.

Obviously this would be a very large change. Another alternative that would be a breaking change would be to do this to `setup.py` and add `http` as extra requires:
```
http_requirements = [
    "h11>=0.8,<0.10",
    "websockets==8.*",
    "httptools==0.1.* ;" + env_marker
]

extras_require = {"watchgodreload": ["watchgod>=0.6,<0.7"], "http": http_requirements}
```

If there is some other way to specify 2 packages in one repo, this would be very simple.

Relavent PR: https://github.com/encode/uvicorn/pull/694

**Comment by euri10** [comment]
sorry if there's something I dont get here but you can already set the protocol using `--http`

**Comment by hansonkd** [comment]
> sorry if there's something I dont get here but you can already set the protocol using `--http`

Exactly! That's why the project is already so close. Basically the only problem that my PR https://github.com/encode/uvicorn/pull/694 is solving is to rename some things to be more general since protocol might not be HTTP and for the logs to not display HTTP.  Besides changing how the logs are formatting, essentially if we rename `http_protocol_class` -> `protocol_class` and `http` -> `protocol` everything becomes nice and generic.

The only other thing that is missing is that perhaps Uvicorn is installing too many dependencies. It is installing http protocols when you might not need them if you are going to use Uvicorn for something other than HTTP.

This might be a lot of work to save time not installing stuff we don't need, but I wanted to at least open the conversation about generalizing Uvicorn.

So what needs to happen to make this a better generalized TCP Project:
* Allow you to set protocol name in logs
* Maybe rename `http` kwarg to `protocol`
* Maybe rename `http_protocol_class` to just `protocol_class`
* Remove extra dependencies on HTTP libs

And thats it, uvicorn would be an even better general TCP server.

**Comment by florimondmanca** [comment]
@hansonkd Hi — Thanks for sharing your experimentations here. :-) It's nice to hear that Uvicorn can be hacked upon and useful in ways that weren't expected in the first place.

However, I don't think Uvicorn is meant to become a "generalized TCP server" anytime soon. Its primary focus is Python ASGI, and that means HTTP and WebSocket as first-class, out-of-the-box citizens. So I hope you'll understand that what you're suggesting would be a pretty fundamental leap I don't think we're ready to consider.

If its architecture is useful to you, feel free to extract it and repackage it up as something else, perhaps for your own use. But for now we need Uvicorn to serve the Python ASGI space for the foreseeable future.

Thanks!
