### ISSUE TITLE
Possibility to install without uvloop

### ISSUE THREAD

**Issue by mojimi** [Kludex/uvicorn#702]
So, uvicorn automatically installs uvloop as a dep, but you can run without it.

Can we have a version/fork without uvloop? In Docker, Uvloop takes the majority of the build time, its really slow to build, so being able to skip it would really streamline it.

**Comment by erewok** [comment]
Most of the value of uvicorn in my own projects is that _it is based on uvloop_. If I didn't want something built on uvloop, I would probably opt for one of gunicorn's asyncio workers.

**Comment by euri10** [comment]
that's what  https://github.com/encode/uvicorn/pull/666 intends to do @mojimi so once a reviewer will have time I think you'll get what you want
