### ISSUE TITLE
How to get uvicorn event loop?

### ISSUE THREAD

**Issue by diachkow** [Kludex/uvicorn#706]
I run uvicorn server programmatically:
```
if __name__ == '__main__':
    uvicorn.run(
        'app:app',
        host='127.0.0.1',
        port=8000,
        log_level='info',
        loop='asyncio'
    )
```

How can I get the created asyncio loop to reuse it for aiogram bot?

I have `bot.py` file for telegram bot and `app.py` file for starlette application running on uvicorn. When I'm trying to call `asyncio.get_running_loop()` in `bot.py` I gets the error that says that there is no running event loops at this time.

Is it even able to create asyncio loop manually and pass it to `uvicorn.run` function?

**Comment by useless-null** [comment]
`asyncio.get_event_loop()`?

**Comment by diachkow** [comment]
> `asyncio.get_event_loop()`?

That can only work in a functions that is called after the `uvicorn.run()` has been executed. If you'd use `asyncio.get_event_loop()` in the module scope it would resolve into error. Using the `asyncio.new_event_loop()` will create a second loop among with `uvicorn.run()` function.

The solution of this problem may be an option to pass the existing loop into `uvicorn.run` function rather that creating it in it like it does.

**Comment by euri10** [comment]
cant access the source right now but check in the tests how it's done.
on top of my mind you'd do something like

config = Config(app=app, loop=loop_instance)
server = Server(config=config)
server.run()


On Wed, Jul 1, 2020 at 8:03 AM Vitaliy Diachkov
<notifications@github.com> wrote:
>
> asyncio.get_event_loop()?
>
> That is only working in a functions that is called after the uvicorn.run() has been executed. If you'd use asyncio.get_event_loop() in the module scope it would resolve into error. Using the asyncio.new_event_loop() will create a second loop among with uvicorn.run() function.
>
> The solution of this problem may be an option to pass the existing loop into uvicorn.run function rather that creating it in it like it does.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
benoit barthelet
http://pgp.mit.edu/pks/lookup?op=get&search=0xF150E01A72F6D2EE

**Comment by diachkow** [comment]
As I've mentioned, you can only pass the loop parameter as a string that indicates the type of the loop to be craeted (e.g. asyncio, uvloop or other). I think I've tried to pass the loop instance in the Config, but it had not resolve the problem.

https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L310

**Comment by diachkow** [comment]
I've actually find the solution by getting loop instance in `on_startup()` method of my Starlette application, but making user able to pass his loop instance can be a good impovement.

**Comment by euri10** [comment]
```
import asyncio
from uvicorn import Config, Server


async def app(scope, receive, send):
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })


loop = asyncio.new_event_loop()

config = Config(app=app, loop=loop)
server = Server(config)
loop.run_until_complete(server.serve())
```

**Comment by useless-null** [comment]
> I've actually find the solution by getting loop instance in `on_startup()` method of my Starlette application, but making user able to pass his loop instance can be a good impovement.

I think a good idea to using lifespan for this, but in current specs ASGI doesn't support transfer server environment to app, like server_stats, current loop and more.

**Comment by lovelydinosaur** [comment]
Closing this as an open-ended discussion, rather than a uvicorn "issue".

**Comment by useless-null** [comment]
> I've actually find the solution by getting loop instance in `on_startup()` method of my Starlette application, but making user able to pass his loop instance can be a good impovement.

This work too:
```
#!/usr/bin/python3
# # -*- coding: utf-8 -*-
import asyncio

loop = None

async def asgi_handler(scope, receiver, sender):
  global loop
  if scope['type'] == 'lifespan':
    message = await receiver()
    if message['type'] == 'lifespan.startup':
      loop = asyncio.get_running_loop()
      loop.create_task(cron())
      await sender({'type': 'lifespan.startup.complete'})
    elif message['type'] == 'lifespan.shutdown':
      print("Shutdown received!")
      await sender({'type': 'lifespan.shutdown.complete'})
    return

  await sender({'type': 'http.response.start', 'status': 200, 'headers': [[b'content-type', b'text-plain']] })
  await sender({'type': 'http.response.body', 'body': b'fine test'})
  print(f"Request to {scope['path']} complete")


async def cron():
  while True:
    print("Cron tick")
    await asyncio.sleep(1)
  return None


if __name__ == '__main__':
  import uvicorn
  uvicorn.run("test:asgi_handler",
                host = '0.0.0.0',
                port = 8080,
                lifespan = 'on',
                workers = 1,
                log_level = "warning",
                interface = 'asgi3',
                timeout_keep_alive = 5)

```

**Comment by rafaellehmkuhl** [comment]
> ```
> import asyncio
> from uvicorn import Config, Server
> 
> 
> async def app(scope, receive, send):
>     await send({
>         'type': 'http.response.start',
>         'status': 200,
>         'headers': [
>             [b'content-type', b'text/plain'],
>         ]
>     })
>     await send({
>         'type': 'http.response.body',
>         'body': b'Hello, world!',
>     })
> 
> 
> loop = asyncio.new_event_loop()
> 
> config = Config(app=app, loop=loop)
> server = Server(config)
> loop.run_until_complete(server.serve())
> ```

Adding that if you want to run two async-functions/coroutines concurrently just use this same code, changing last line with:

```python
loop.create_task(server.serve())
loop.create_task(second_infinite_async_function())
loop.run_forever()
```

**Comment by scoutinhobh** [comment]
@useless-null with the example you have shown is it possible to share a queue between the 2 coroutines?

**Comment by stevstrong** [comment]
> I've actually find the solution by getting loop instance in `on_startup()` method of my Starlette application, but making user able to pass his loop instance can be a good improvement.
https://github.com/encode/uvicorn/issues/706#issuecomment-652216443

@diachkow , can you please share your code how did you do that?
