### ISSUE TITLE
[Question] How to start a service with long loading time?

### ISSUE THREAD

**Issue by FrontMage** [Kludex/uvicorn#711]
I'm trying to use fastapi to serve my TensorFlow model, the thing is that on a crapy machine the model took about a minute to load, uvicorn just kills the process after 30s loading time, I can't find any options to bypass this limit.

Is there a way to do this?

Thanks for the help!

**Comment by euri10** [comment]
This is not a uvicorn question, would make more sense to get help in Starlette or FastAPI.
That said, you could for instance use the Starlette built-in lifespan kwarg to run your initialization, something like that if it's a sync function should work

```
import time

from starlette.applications import Starlette

import uvicorn

def lifespan(app):
    # do your tensorflow stuff
    time.sleep(10)
    yield

app = Starlette(lifespan=lifespan)


if __name__ == '__main__':
    uvicorn.run(app=app)
```

**Comment by FrontMage** [comment]
@euri10 Thanks for the help!
I tried to use lifespan and startup functions, but it did not work.
It turns out that my machine is so crapy, that its memory ran out while loading the model.
I originally thought the process is killed by uvicorn, but the truth is that Linux has an out of memory killer which kills processes if they use up to a certain amount of memory.
