### ISSUE TITLE
kill -15 (SIGTERM) doesn't restart the uvicorn server?

### ISSUE THREAD

**Issue by est** [Kludex/uvicorn#712]
Hi, I am running `uvicorn --host 0.0.0.0 --port 9000 --access-log main:app --workers 2` and want to restart the server manually with `kill -15 $pid` but it just made the server stop without restart. 

The `restart()` method https://github.com/encode/uvicorn/blob/7e55554a9f32a127ea3511fa2f55d1b47b66029d/uvicorn/supervisors/basereload.py#L63  works internally. how can I manually trigger a restart?

**Comment by euri10** [comment]
you cant
that method is used by the reloader (`--reload`) and its use is mutually exclusive of `--workers`

**Comment by est** [comment]
@euri10 I skimmed the docs several times, seems that there is no way to restart the server manually?
