### ISSUE TITLE
Docs: clarify how to use proxy-headers with unix sockets

### ISSUE THREAD

**Issue by PeterJCLaw** [Kludex/uvicorn#713]
It would be great if it could be documented that when using a unix socket the client address which `ProxyHeadersMiddleware` gets will be `None` and that you therefore need to pass `*` as the trusted hosts to get the proxy headers to work.

Even better would be for the proxy headers to "just work" when using a unix socket, in the same way that `ProxyHeadersMiddleware` trusts localhost by default, though I suspect that may be more involved.

**Comment by euri10** [comment]
would be a good addition yes, PR welcome @PeterJCLaw :)

**Comment by PeterJCLaw** [comment]
So I had a quick look into the internals here and I can't see an easy way to be confident in the middleware that the connection is a unix socket.

I think that ideally we'd get something in `scope['client']` which would tell us that, however the ASGI spec defines that value to be either a 2-tuple (`host`, `port`) or `None` which kinda rules that out.
While `uvicorn` does pass `None` there for a unix socket, it seems to also be the case that various error conditions in `uvicorn.protocols.utils.get_remote_addr` could cause it to be `None` for other reasons. Certainly as this is somewhat security sensitive I think I'd want to have actively determined that we're looking at a unix socket, rather than merely not a happy-path network socket.

`scope['server']` might hold more promise, though `uvicorn.protocols.utils.get_local_addr` also seems to have some soft fallback logic which I'm unsure of.

Is there something I'm missing here which might make this possible, or is documenting the behaviour the only solution? (I'm happy to look at doing that anyway, just would be nice for it to work automatically)
