### ISSUE TITLE
Logging does not work

### ISSUE THREAD

**Issue by bryanapperson** [Kludex/uvicorn#72]
None of my apistar app's access logging or other logging in application code that works with daphne or gunicorn works here. It seems like logging may not be implemented. Please advise.

**Comment by jordaneremieff** [comment]
Do you have an example of the logging calls? I suspect that this is occurring because `uvicorn` doesn't specify a log level, so it will only display `<logger>.warning()` messages by default.

You may be able to confirm this by using the following logging config:

```
logging.basicConfig(
    level=2,
    format="%(asctime)-15s %(levelname)-8s %(message)s"
)
```

**Comment by bryanapperson** [comment]
I am running uvicorn as follows:

`uvicorn app:app -b 127.0.0.1:5000 --log-level debug`

There was no logging before, however after adding:

```
logging.basicConfig(
    level=2,
    format="%(asctime)-15s %(levelname)-8s %(message)s"
)
```

To app.py logging is now functioning with regular calls to the module logger object.

**Comment by cglacet** [comment]
A solution that works with the current version is:

```python
logger = logging.getLogger("My logs")
logger.setLevel(logging.DEBUG)
logger.debug("TEST")
```

It doesn't require to modify the `uvicorn` command and is probably the expected use of `logging`.
