### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by jordaneremieff** [Kludex/uvicorn#74]
It may be a good idea to establish contribution guidelines for this project in order to help anyone that is interested in improving things but unsure of how to actually engage the process of proposing changes or submitting PRs.

I am a bit unclear on how to approach some of the existing issues, and it would be helpful if there were a process in place to organize/prioritize tasks that need to be done as well as to identify potential blockers.

Perhaps something similar to what [Channels](https://channels.readthedocs.io/en/latest/contributing.html) does? It seems like a good example of how this could be handled.

**Comment by lovelydinosaur** [comment]
I’ll go through the issues again once 0.2 is out. The structure is cleaner, and the proper separation out from gunicorn should also help make things a bit more obvious.

I think there’ll be some decent tickets for contributors to get stuck into, too.
