### ISSUE TITLE
uvicorn flagged as vulnerable (all version) on pyup.io

### ISSUE THREAD

**Issue by MarioElstner** [Kludex/uvicorn#741]
Since the latest update to the pyup DB (Aug 2nd), all existing versions of uvicorn have been flagged as vulnerable. https://pyup.io/changelogs/uvicorn/

**Comment by euri10** [comment]
thanks, this has already been reported here and on their db site, not sure how long it takes for them to correct the incorrect information.

see https://github.com/pyupio/safety-db/issues/2314
