### ISSUE TITLE
Catch `HttpParserInvalidMethodError` exception

### ISSUE THREAD

**Issue by ChillarAnand** [Kludex/uvicorn#75]
`uvicorn==0.1.1` is throwing these errors

```
uvicorn[7423]: Unhandled exception in event loop
uvicorn[7423]: Traceback (most recent call last):
uvicorn[7423]:   File "uvloop/handles/stream.pyx", line 784, in uvloop.loop.__uv_stream_on_read_impl
uvicorn[7423]:   File "uvloop/handles/stream.pyx", line 563, in uvloop.loop.UVStream._on_read
uvicorn[7423]:   File "/home/web/.virtualenvs/mesh/lib/python3.5/site-packages/uvicorn/protocols/http.py", line 212, in data_received
uvicorn[7423]:     self.request_parser.feed_data(data)
uvicorn[7423]:   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
uvicorn[7423]: httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
```

**Comment by zeromake** [comment]
@ChillarAnand you use method is not in [parser](https://github.com/nodejs/http-parser/blob/master/http_parser.c#L954) , but uvicorn should catch this error.

**Comment by jordaneremieff** [comment]
@ChillarAnand how can I reproduce this?

**Comment by ChillarAnand** [comment]
These errors are showing up in production. I am not sure why that is happening. I couldn't reproduce it locally.

**Comment by jordaneremieff** [comment]
@ChillarAnand The exception could be explicitly handled, but the underlying issue is what @zeromake said. If you could debug the information associated with the request and the data that is being received by the protocol then it may indicate the cause.

**Comment by ChillarAnand** [comment]
I will log the data and see what is happening. Thanks @erm @zeromake

**Comment by lovelydinosaur** [comment]
Should be easy enough to resolve:

* Catch the exception in `data_received` (If httptools has a base class for all parser exceptions then that's what we should be catching)
* Run `self.transport.close()` when exception occurs, and log a warning-level message.
* Add test case.
