### ISSUE TITLE
Programatic access to the port Uvicorn is running on if started with port 0

### ISSUE THREAD

**Issue by simonw** [Kludex/uvicorn#761]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [x] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

If you start Uvicorn on port 0, it will be assigned a port at random. https://github.com/encode/uvicorn/commit/a75fe1381f6b1f78901691c71894f3cf487b5d30 is a change related to this.

I'd like a way to programatically access that port after calling `uvicorn.run()` so I can display it back to the user - for this issue: https://github.com/simonw/datasette/issues/873

## Describe the solution you would like.

I'm not sure what would work best here. I don't want to have to wait for an HTTP request to arrive (because I want to show a message on startup), but calling `uvicorn.run()` as [I do here](https://github.com/simonw/datasette/blob/86aefc39c5aca01b00dbc57ba386a6743c21fb46/datasette/cli.py#L445) is a blocking call.

I really want to be able to say "start the server running and then call this callback function with enough information that it can tell what port the server has been assigned". Is there another mechanism I could use for that?

**Comment by Kludex** [comment]
Not really.

After a year, do still have interest on this or did you have ideas for it? @simonw

**Comment by ehiggs** [comment]
Hi, i saw this issue come up on the fastapi discord.

Make a kwarg that takes an open socket. Use this for listening and applications tht make the socket can know the port.

This has other nice properties like being able to define the socket as SO_REUSEPORT (which I'd expect a Python server always wants).

Is that a workable plan? It's a common pattern that I've used and seen in the wild in C++, Go, and Rust.

**Comment by Kludex** [comment]
> It's a common pattern that I've used and seen in the wild in C++, Go, and Rust.

@ehiggs do you have references?

**Comment by Kludex** [comment]
This should be enough:

```python
import asyncio

import uvicorn


async def app(scope, receive, send):
    ...


async def main():
    config = uvicorn.Config("main:app", port=0, log_level="info")
    server = uvicorn.Server(config)
    asyncio.create_task(server.serve())

    while not server.started:
        await asyncio.sleep(0.1)

    for server in server.servers:
        for socket in server.sockets:
            print(socket.getsockname())


if __name__ == "__main__":
    asyncio.run(main())
```

If it's not, please let me know, and I'll reopen it.

**Comment by iudeen** [comment]
I tried this, and I get 
```
AttributeError: 'uvloop.loop.PseudoSocket' object has no attribute 'getsocketname'
```

**Comment by colinpalmer** [comment]
I had the same problem of needing to get the port from the Uvicorn server after start up. The discussion above and @Kludex's suggestion was very helpful, but I ended up using a slightly different solution so I could still call the normal `server.run()` method and allow Uvicorn to set up its event loop in the normal way rather than setting up the asyncio task myself.

I thought I'd post some example code here in case it's useful for anyone. The idea is to use a monkey patch to override the `server._log_started_message()` method, which is called once the server is running and so acts as a hook to tell us when the server has started. Of course, the leading underscore means this is an internal method so this approach could break if the Uvicorn implementation changes in future, but it seems to work nicely for now. This code should do the same as @Kludex's example:

```python
import uvicorn


async def app(scope, receive, send):
    ...


def server_started(server):
    for server in server.servers:
        for socket in server.sockets:
            print(socket.getsockname())


def main():
    config = uvicorn.Config("main:app", port=0)
    server = uvicorn.Server(config)

    orig_log_started_message = server._log_started_message

    def patch_log_started_message(listeners):
        orig_log_started_message(listeners)
        server_started(server)

    server._log_started_message = patch_log_started_message

    server.run()


if __name__ == "__main__":
    main()
```

**Comment by king-of-poppk** [comment]
@Kludex The equivalent using `anyio` seems to be using a [task group](https://anyio.readthedocs.io/en/stable/tasks.html) with `tg.start_soon`. Any idea how to make it work with `await tg.start` instead? I've tried but it seems to hang forever.
