### ISSUE TITLE
uvicorn ssl issue

### ISSUE THREAD

**Issue by MarshalOfficial** [Kludex/uvicorn#765]
I have a problem with using SSL, in documents said I need SSL key.pem and cert.pem, I am running on a windows server and use let's encrypt, now it does not give me pem format, I had adjusted in win-acme utility to create an SSL certificate with the key exportable flag, when it creates I export it and got .pfx format of the certificate that located in cert-manager of windows, then use OpenSSL to get out pem format of certificate and key, but when running Uvicorn, it is insecure in the browser and my frontend request missed with a mixed content error.
how and which files do I set in uvicorn run command?
what is my fault in what I did?
thanks,

**Comment by euri10** [comment]
hello @MarshalOfficial there is a question template to fill and part of it is

- [ ] I asked the [community chat](https://gitter.im/encode/community) for help.

so send your usage question there first if possible, thanks
