### ISSUE TITLE
Relative import to app (e.g. using '..' in app path) results in a TypeError

### ISSUE THREAD

**Issue by SimonCockx** [Kludex/uvicorn#766]
### Checklist

- [ OK ] The bug is reproducible against the latest release and/or `master`.
- [ OK ] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I have a Django application with the following structure.

    root/
        my_app/
            __init__.py
            asgi.py
        some_other_folder/

When I'm in the root folder, I can start the uvicorn server perfectly with `uvicorn my_app.asgi:application`. However, when trying to reference the asgi application from withing a subfolder (e.g. `some_other_folder`), uvicorn throws a TypeError ` the 'package' argument is required to perform a relative import for '..my_app.asgi'`.

### To reproduce

1. Create an application with the structure as described above.
2. `cd some_other_folder`
3. `uvicorn ..my_app.asgi:application`

### Expected behavior

It should run without problem.

### Actual behavior

A type error is thrown: `TypeError: the 'package' argument is required to perform a relative import for '..my_app.asgi'`

### Environment

- Windows 10
- Python 3.8.5
- Uvicorn 0.11.8

**Comment by euri10** [comment]
2 options, both from some_other_folder:

1. `PYTHONPATH=.. uvicorn my_app.asgi:application`
2. `uvicorn --app-dir=.. my_app.asgi:application`
