### ISSUE TITLE
Ability to log the HTTP referer

### ISSUE THREAD

**Issue by simonw** [Kludex/uvicorn#773]
Unless I've missed something, it looks like it isn't currently possible to configure Uvicorn to output the HTTP Referer header in the access logs:

https://github.com/encode/uvicorn/blob/e77e59612ecae4ac10f9be18f18c47432be7909a/uvicorn/logging.py#L109-L132

This would be really useful for me because I'm trying to figure out where traffic to my sites comes from without running Google Analytics!

**Comment by euri10** [comment]
you're correct, it should be in the socpe["headers"] if I'm not mistaken so that sounds feasible

**Comment by Kludex** [comment]
I recommend using a middleware to create the access logs, and disable the `uvicorn.access` logger.

This project can be used as inspiration: https://github.com/Kludex/asgi-logger.

PR is welcome to improve the documentation here. About the access logger formatter discussion, we'll continue on #527.
