### ISSUE TITLE
Support Hyper (the rust one)

### ISSUE THREAD

**Issue by alippai** [Kludex/uvicorn#779]
Curl is experimenting wtih supporting it thus they are developing a C API: https://github.com/hyperium/hyper/issues/2265

Would this be usable by uvicorn for HTTP/2 support?

**Comment by florimondmanca** [comment]
Hello!

Not something I'd personally see us doing anytime soon, given the rather tight resources constraints on Uvicorn for the moment, and how Uvicorn has been focusing on providing a simple, as-pure-Python-as-it-can-be as possible (hence the recent switch to optional installs for `uvloop` and other C-optimized components).

Hope this answers your question! Happy to have other maintainers' thoughts on this too, but for now going to close this off. :-)
