### ISSUE TITLE
Timezone is inconsistent with localtime and gunicorn log.

### ISSUE THREAD

**Issue by stevechenzy** [Kludex/uvicorn#783]
### Checklist

- [ ] The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet.

### Describe the bug
using gunicorn + uvicorn worker to run asgi django project. in the log file the output form gunicorn is localtime, while the output from uvicorn looks like alway the timezone-0. 

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.

**Comment by euri10** [comment]
can you include a precise example of what you expect please, I'm not sure we're doing anything fancy on that side.
also is it the access logs you're talking about ?

**Comment by stevechenzy** [comment]
Thanks euro10 for looking into this issue. 

With some investigations, I found the solution. The time zone in setting.py of Django project is not same as the server local time setting. After correcting that, the time of logging is consistent now. 

It indicates that django is using system time zone setting and ignores its own settings, while uvicorn is using django setting.

**Comment by euri10** [comment]
thanks for the explanation, that should not be easy to spot !

**Comment by stevechenzy** [comment]
Yes but that’s life. :-)
