### ISSUE TITLE
Stack Trace not printing with debug enabled

### ISSUE THREAD

**Issue by cclloyd** [Kludex/uvicorn#785]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Even with `debug=True` and `log_level='debug'` set in the server, when my application raises an exception, which results in a 500 error, all the dev server does is print the 500 error, and nothing about the exception.

### To reproduce

    async def start_asgi_server():
        config = uvicorn.Config("api.asgi:application",
                                host="0.0.0.0",
                                port=8000,
                                log_level="debug",
                                loop='asyncio',
                                debug=True,
                                reload=True
                                )
        server = uvicorn.Server(config=config)
        await server.serve()

    loop.create_task(start_asgi_server())

    future = loop.create_future()
    loop.run_until_complete(future)

Gives the error

> INFO:     127.0.0.1:54540 - "POST /social/discord/ HTTP/1.1" 500 Internal Server Error

But no other info.

### Expected behavior

It prints the stack trace when debug=True

### Actual behavior

Only the server error is printed.

### Debugging material

The above example code is used so that I can have Uvicorn share the event loop with another library.  There is a second task added before the loop is started, and they both run indefinitely until stopped.

Full logs:

```
INFO:     Started server process [3481]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:54538 - "POST /social/oauth/token/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:54540 - "POST /social/discord/ HTTP/1.1" 500 Internal Server Error
```

NOTE:
- Please list tracebacks in full (don't truncate them).
- If relevant, consider turning on DEBUG or TRACE logs for additional details (see the Logging section on https://www.uvicorn.org/settings/ specifically the `log-level` flag).
- Consider using `<details>` to make tracebacks/logs collapsible if they're very large (see https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d).
-->

### Environment

- Running uvicorn 0.11.8 with CPython 3.8.2 on Darwin
- Code use to programmatically run uvicorn shown above.

**Comment by euri10** [comment]
a minimal reproducible example would help, can't reprpoduce using the below which seems quite close to what you're doing

```
import asyncio
from uvicorn import Config, Server


async def app(scope, receive, send):
    raise RuntimeError("Something wewwnt wrong")


async def printl(start=0):
    while True:
        await asyncio.sleep(1)
        start+=1
        print(start)
        

async def main():
    loop = asyncio.new_event_loop()
    config = Config(app=app, loop=loop, log_level='debug', debug=True, reload=True)
    server = Server(config)
    await asyncio.gather(server.serve(), printl(0) )

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by euri10** [comment]
closing as stale, feel free to reopen

**Comment by Stargateur** [comment]
It's hard to make an MCVE when the bug appear to be totally random and that have just error doesn't help to fix a scripting language like python..., but I can confirm this on windows.

**Comment by euri10** [comment]
> It's hard to make an MCVE when the bug appear to be totally random and that have just error doesn't help to fix a scripting language like python..., but I can confirm this on windows.

happy to help with something to chew !

**Comment by Stargateur** [comment]
sorry, I ragequit python and return to Rust, the package management nightmare of python. Having try every single one of them and failing each time to make thing just work make me going crazy when a simple `cargo run` just work. plus the problem I get with python (no strong typed, etc..)

Anyway, I'm not even sure it's come from uvicorn after some time I think maybe it's a falcon bug on its ASGI side. It's unclear and something the exception is correctly show, sometime not. Need to warp all my route implementation with a giant `try` block to see the exception.

**Comment by euri10** [comment]
rust docs and package management is superior in every way yes :) !
