### ISSUE TITLE
Response without body gets transfer-encoding: chunked header

### ISSUE THREAD

**Issue by sverkera** [Kludex/uvicorn#787]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

On a response without a body a header transfer-encoding: chunked will be added, like in this example:

[root@srv-1]# curl -v http://localhost:8088/Content/d3bc31df-4a14-4be5-b176-6ffdf6d0ef15/Status
* About to connect() to localhost port 8088 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8088 (#0)
> GET /Content/d3bc31df-4a14-4be5-b176-6ffdf6d0ef15/Status HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8088
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Fri, 25 Sep 2020 22:15:00 GMT
< server: uvicorn
< transfer-encoding: chunked
<
* Connection #0 to host localhost left intact

In our case the calling client gets confused and expects body content to appear. This happens on all responses which does not have status code 204 or 304.

### To reproduce

Do a request which will give the following return:
        return Response(status_code=404)

Workaround to resolve the issue is to include a content-lenght: 0 header:
        return Response(status_code=404, headers={"content-length": "0"})

### Expected behavior

Responses without a body, like a 404 in the example above, should not get a transfer-encoding header added.

### Actual behavior

Responses without a body gets a transfer-encoding header added

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.

**Comment by florimondmanca** [comment]
I'm able to reproduce the behavior you're seeing…

```python
# app.py
from starlette.responses import PlainTextResponse

app = PlainTextResponse(status_code=404)
```

```bash
uvicorn app:app
```

```console
$ curl -v localhost:8000
* Rebuilt URL to: localhost:8000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Mon, 28 Sep 2020 19:37:10 GMT
< server: uvicorn
< content-type: text/plain; charset=utf-8
< transfer-encoding: chunked
< 
* Connection #0 to host localhost left intact
```

However, it's not immediately clear to me that this should be considered as a bug. Tested against Hypercorn and Daphne, and they're both returning an empty chunked response.

How is this behavior affecting you? That is, what do you mean *exactly* by…?

> In our case the calling client gets confused and expects body content to appear.

**Comment by euri10** [comment]
closing as stale, feel free to reopen
