### ISSUE TITLE
UvicornWorker 'auto' loop and http implementations don't work on Linux without extras installed

### ISSUE THREAD

**Issue by mdgilene** [Kludex/uvicorn#816]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

After #666 , uvloop and and httptools are no longer installed unless you specify to install the 'standard' extra. Because of this when running with `loop='auto'` and `http='auto'` the application fails to start due to 'uvloop' and 'httptools' being selected. NOTE: This only happens when running the `uvicorn.workers.UvicornWorker` through something like Gunicorn.

### To reproduce

```bash
pip install uvicorn gunicorn
```

```python
#main.py
async def app(scope, receive, send):
    assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```

```bash
gunicorn -k uvicorn.workers.UvicornWorker main:app
```

### Expected behavior

'auto' should pick 'asyncio' and 'h11' for their respective settings on Linux if the 'standard' extra is not installed.

### Actual behavior

Application starts up but immediately throws `ModuleNotFoundError: No module named 'uvloop'`. If you install uvloop it then complains about not finding httptools. After installing both, no more issues occur.

### Environment

- Running uvicorn 0.12.1 with CPython 3.7.6 on Linux

**Comment by euri10** [comment]
Yep, we should be selecting good defaults

**Comment by florimondmanca** [comment]
For anyone passing by a looking for a workaround…

https://www.uvicorn.org/deployment/#gunicorn

```python
# myproject/workers.py
class MyUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {"loop": "auto", "http": "auto"}
```

```console
$ gunicorn -w myproject.workers.MyUvicornWorker app:app
```

See #266
