### ISSUE TITLE
examples of https configuration

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [Kludex/uvicorn#819]
Hi.
I have been trying to implement Uvicorn in my Django project.
It works excelent except https support. From docs it's not quite obviose how to implement it. 
Could you please add some examples maybe?

```
import uvicorn
import os
from pathlib import Path


#  Uvicorn server settings
if __name__ == '__main__':
    uvicorn.run(
        'entropy.asgi:application',
        host='localhost',
        port=8000,
        log_level='info',
        reload=True,
        workers=os.cpu_count(),
        env_file=Path(r'entropy\.env'),
        use_colors=True,
        ssl_keyfile=Path(r'rootCA-key.pem'),
        ssl_certfile=Path(r'rootCA.pem'),
    )
```

Basically doesnt want to work via https, but all works fine via http. Cant comprehend why...

**Comment by euri10** [comment]
I think you're right, we could add something in the docs, @AlekseiKhatkevich 

In the meantime, the test suite might put you on the way, especially the `test_ssl.py`.

I don't see anything obviously wrong in what you're doing above, hence filling the issue template is helpful

> Basically doesnt want to work via https, but all works fine via http. Cant comprehend why...

there's not enough info here to help you

**Comment by euri10** [comment]
for instance this works, this goes with all the [trustme](https://github.com/python-trio/trustme) caveats of course mostly this one: 

> Should I use these certs for anything real? Certainly not.

app.py
```python
import trustme

import uvicorn


async def read_body(receive):
    """
    Read and return the entire body from an incoming ASGI message.
    """
    body = b''
    more_body = True

    while more_body:
        message = await receive()
        body += message.get('body', b'')
        more_body = message.get('more_body', False)

    return body


async def app(scope, receive, send):
    """
    Echo the request body back in an HTTP response.
    """
    body = await read_body(receive)
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': body,
    })


if __name__ == '__main__':
    with trustme.CA().issue_server_cert("localhost","127.0.0.1","::1").private_key_and_cert_chain_pem.tempfile() as ssl_certfile:
        uvicorn.run("app:app", ssl_certfile=ssl_certfile)
```

**Comment by AlekseiKhatkevich** [comment]
@euri10. Thanks for explanation. You probably should include it as example in docs. Usefull for development
