### ISSUE TITLE
client port is always 0,after set environment variable FORWARDED_ALLOW_IPS

### ISSUE THREAD

**Issue by zffocussss** [Kludex/uvicorn#830]
#531 # Describe the bug

### Expected behavior

the real client ip and port should be displayed on the logs

### Actual behavior

the real client ip is right now.but the port is zero always

### Debugging material

2020-10-23 03:58:19 [INFO] uvicorn: ('public ip', 0) - "WebSocket " [accepted]

NOTE:
- Please list tracebacks in full (don't truncate them).
- If relevant, consider turning on DEBUG or TRACE logs for additional details (see the Logging section on https://www.uvicorn.org/settings/ specifically the `log-level` flag).
- Consider using `<details>` to make tracebacks/logs collapsible if they're very large (see https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d).
-->

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
```
Running uvicorn 0.11.8 with CPython 3.8.2 on Linux
```
- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.
```
uvicorn.run(
        "main:app", host="0.0.0.0", port=8088, log_level="debug", reload=True,reload=True)
```

### Additional context
I use helm to install a websocket application behind ingress-nginx

**Comment by euri10** [comment]
Hi @zffocussss I'm gonna close this as non-reproducible on my end, see the screen below, the port is not 0.
I see you're using an old uvicorn version, maybe you should try with it.
We'll gladly reopen if you provide actionnable info, thanks

![20201023_0921_1374x994_1603437719](https://user-images.githubusercontent.com/1104190/96968577-72d32680-1511-11eb-95f7-e8070bcfa8c8.png)
