### ISSUE TITLE
aiortc example fails with uvloop but works with asyncio loop

### ISSUE THREAD

**Issue by joseph-long** [Kludex/uvicorn#840]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When negotiating a WebRTC connection, the ICE transport is closed when aiortc tries to start sending data. It's not clear what's happening, but adding `--loop asyncio` makes the example work.

### To reproduce

Adapted from upstream, https://github.com/joseph-long/starlette-aiortc-example/blob/main/webcam2.py uses aiortc + Starlette to stream a video of a scrolling pattern. `webcam.py` is closer to the upstream version using aiohttp (but changed to show a flag instead of streaming the webcam). Requires starlette/uvicorn, aiortc, and NumPy (if not already brought in by aiortc?)

Start with `$ uvicorn webcam2:app`, navigate to http://localhost:8080/, check the "Use STUN" box, click Start and watch the console.

### Expected behavior

Demo video shown in the `<video>` element on that page.
![image](https://user-images.githubusercontent.com/31168267/97888150-09f56680-1ce8-11eb-9b04-6f919954a101.png)

Should work with uvloop as well as asyncio.

### Actual behavior

Works with asyncio loop, connection fails and aiortc is in an invalid state with uvloop.

### Debugging material

<details><summary>Output from `$ uvicorn webcam2:app`</summary>
<pre>$ uvicorn webcam2:app
INFO:     Started server process [34540]
INFO:uvicorn.error:Started server process [34540]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:60209 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:60209 - "GET /client.js HTTP/1.1" 200 OK
{<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7ff050d36690>}
DEBUG:ice:controlled - new -> closed
DEBUG:ice:Connection(0) protocol(0) connection_made(<UDPTransport closed=False 0x7ff050d68ef0>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<UDPTransport closed=False 0x7ff050d68e20>)
DEBUG:ice:Connection(0) protocol(2) connection_made(<UDPTransport closed=False 0x7ff050e96050>)
DEBUG:ice:Connection(0) protocol(3) connection_made(<UDPTransport closed=False 0x7ff050e96120>)
DEBUG:ice:Connection(0) protocol(4) connection_made(<UDPTransport closed=False 0x7ff050e961f0>)
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'$\xceo\xbcM\xa2)\xe6\xf87\x91 ')
DEBUG:ice:Connection(0) protocol(0) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xe1|\xfcw\x0b|,\xb2E\x91\xd8\xbb')
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x90\xe5\x8a\xe2\xb3\xef\x93\xd1\xfch\xc7\xb8')
DEBUG:ice:Connection(0) protocol(4) connection_lost([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(3) connection_lost([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(0) < ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xe1|\xfcw\x0b|,\xb2E\x91\xd8\xbb')
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'$\xceo\xbcM\xa2)\xe6\xf87\x91 ')
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x90\xe5\x8a\xe2\xb3\xef\x93\xd1\xfch\xc7\xb8')
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'$\xceo\xbcM\xa2)\xe6\xf87\x91 ')
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x90\xe5\x8a\xe2\xb3\xef\x93\xd1\xfch\xc7\xb8')
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'$\xceo\xbcM\xa2)\xe6\xf87\x91 ')
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x90\xe5\x8a\xe2\xb3\xef\x93\xd1\xfch\xc7\xb8')
INFO:     127.0.0.1:60268 - "POST /offer HTTP/1.1" 200 OK
DEBUG:ice:controlled - new -> checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.113', 54645) -> ('67.1.30.246', 63505)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.28.128.1', 53106) -> ('67.1.30.246', 63505)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('169.254.0.1', 61201) -> ('67.1.30.246', 63505)) State.FROZEN -> State.WAITING
ICE connection state is checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.113', 54645) -> ('67.1.30.246', 63505)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(0) > ('67.1.30.246', 63505) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xa7\x95w)\xcd\xeb\xc5\xca5e\xe2\x90')
DEBUG:ice:Connection(0) protocol(1) < ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 63506) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xcf\xab+i\xe1\x9b7\xcc\x9dC\x00\x1f')
DEBUG:ice:Connection(0) protocol(1) > ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 63506) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xcf\xab+i\xe1\x9b7\xcc\x9dC\x00\x1f')
INFO:ice:Connection(0) Discovered peer reflexive candidate Candidate(he8WNFKKme 1 udp 1853817087 fd53:c25c:318f:0:e945:1e01:5d5f:c269 63506 typ prflx)
INFO:ice:Connection(0) Check CandidatePair(('fd53:c25c:318f:0:c35:a820:78d8:8e14', 54646) -> ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 63506)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(1) > ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 63506) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'yh\x8e\x01\xcbW\x17\xb5iFh\x13')
DEBUG:ice:Connection(0) protocol(1) < ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 63506) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'yh\x8e\x01\xcbW\x17\xb5iFh\x13')
INFO:ice:Connection(0) Check CandidatePair(('fd53:c25c:318f:0:c35:a820:78d8:8e14', 54646) -> ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 63506)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) Check CandidatePair(('172.28.128.1', 53106) -> ('67.1.30.246', 63505)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('169.254.0.1', 61201) -> ('67.1.30.246', 63505)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) ICE completed
DEBUG:ice:controlled - checking -> completed
DEBUG:dtls:client - State.NEW -> State.CONNECTING
ICE connection state is completed
DEBUG:ice:controlled - completed -> failed
ICE connection state is failed
DEBUG:dtls:client - DTLS shutdown complete
DEBUG:ice:controlled - failed -> closed
ICE connection state is closed
DEBUG:dtls:client x DTLS handshake failed (connection error)
DEBUG:dtls:client - State.CONNECTING -> State.FAILED
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /Users/josephlong/devel/aiortc/src/aiortc/rtcpeerconnection.py:912> exception=InvalidStateError('RTCIceTransport is closed')>
Traceback (most recent call last):
  File "/Users/josephlong/devel/aiortc/src/aiortc/rtcpeerconnection.py", line 920, in __connect
    await iceTransport.start(self.__remoteIce[transceiver])
  File "/Users/josephlong/devel/aiortc/src/aiortc/rtcicetransport.py", line 301, in start
    raise InvalidStateError("RTCIceTransport is closed")
aiortc.exceptions.InvalidStateError: RTCIceTransport is closed
DEBUG:ice:Connection(0) protocol(0) connection_lost(None)
DEBUG:ice:Connection(0) protocol(1) connection_lost(None)
DEBUG:ice:Connection(0) protocol(2) connection_lost(None)</pre>
</details>

<details><summary>Output from `$ uvicorn --loop asyncio webcam2:app`</summary>
<pre>$ uvicorn --loop asyncio webcam2:app
INFO:     Started server process [34505]
INFO:uvicorn.error:Started server process [34505]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:59688 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:59688 - "GET /client.js HTTP/1.1" 200 OK
{<aiortc.rtcpeerconnection.RTCPeerConnection object at 0x7fd1f8d061d0>}
DEBUG:ice:controlled - new -> closed
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=25 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=26 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(2) connection_made(<_SelectorDatagramTransport fd=27 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(3) connection_made(<_SelectorDatagramTransport fd=28 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(4) connection_made(<_SelectorDatagramTransport fd=29 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdf\n_\xf8|\x959p\xbd\xacI\x7f')
DEBUG:ice:Connection(0) protocol(3) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xc2F\xdd7\x1aS=!\xd7g\xfa8')
DEBUG:ice:Connection(0) protocol(4) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(0) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xc7\x8ci|\x06\xab\xffXI*r\x9e')
DEBUG:ice:Connection(0) protocol(0) < ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xc7\x8ci|\x06\xab\xffXI*r\x9e')
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdf\n_\xf8|\x959p\xbd\xacI\x7f')
DEBUG:ice:Connection(0) protocol(3) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xc2F\xdd7\x1aS=!\xd7g\xfa8')
DEBUG:ice:Connection(0) protocol(4) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdf\n_\xf8|\x959p\xbd\xacI\x7f')
DEBUG:ice:Connection(0) protocol(3) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xc2F\xdd7\x1aS=!\xd7g\xfa8')
DEBUG:ice:Connection(0) protocol(4) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(3) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdf\n_\xf8|\x959p\xbd\xacI\x7f')
DEBUG:ice:Connection(0) protocol(3) error_received([Errno 65] No route to host)
DEBUG:ice:Connection(0) protocol(4) > ('172.253.117.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xc2F\xdd7\x1aS=!\xd7g\xfa8')
DEBUG:ice:Connection(0) protocol(4) error_received([Errno 65] No route to host)
INFO:     127.0.0.1:59750 - "POST /offer HTTP/1.1" 200 OK
DEBUG:ice:controlled - new -> checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.113', 63726) -> ('67.1.30.246', 49768)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.28.128.1', 51496) -> ('67.1.30.246', 49768)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('169.254.0.1', 63674) -> ('67.1.30.246', 49768)) State.FROZEN -> State.WAITING
ICE connection state is checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.113', 63726) -> ('67.1.30.246', 49768)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(0) > ('67.1.30.246', 49768) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x9c>[\xb5#\x99m\x8b{\x04Q\xfa')
DEBUG:ice:Connection(0) protocol(1) < ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 49769) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf5U\xf7\x90\xe5\x9e\x1d\xeeJ\xe5\x0b\xdc')
DEBUG:ice:Connection(0) protocol(1) > ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 49769) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xf5U\xf7\x90\xe5\x9e\x1d\xeeJ\xe5\x0b\xdc')
INFO:ice:Connection(0) Discovered peer reflexive candidate Candidate(izNIEY7Mce 1 udp 1853817087 fd53:c25c:318f:0:e945:1e01:5d5f:c269 49769 typ prflx)
INFO:ice:Connection(0) Check CandidatePair(('fd53:c25c:318f:0:c35:a820:78d8:8e14', 63727) -> ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 49769)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(1) > ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 49769) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xb5_\xcf)-\x98\xccl\xb0\x8a.\x0e')
DEBUG:ice:Connection(0) protocol(1) < ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 49769) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xb5_\xcf)-\x98\xccl\xb0\x8a.\x0e')
INFO:ice:Connection(0) Check CandidatePair(('fd53:c25c:318f:0:c35:a820:78d8:8e14', 63727) -> ('fd53:c25c:318f:0:e945:1e01:5d5f:c269', 49769)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) Check CandidatePair(('172.28.128.1', 51496) -> ('67.1.30.246', 49768)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('169.254.0.1', 63674) -> ('67.1.30.246', 49768)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) ICE completed
DEBUG:ice:controlled - checking -> completed
DEBUG:dtls:client - State.NEW -> State.CONNECTING
ICE connection state is completed
DEBUG:dtls:client - DTLS handshake complete
DEBUG:dtls:client - State.CONNECTING -> State.CONNECTED
DEBUG:rtp:sender(video) - RTP started
DEBUG:rtp:sender(video) - RTCP started
DEBUG:rtp:sender(video) > RtpPacket(seq=5635, ts=649129322, marker=1, payload=120, 844 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=5636, ts=649132322, marker=1, payload=120, 368 bytes)
</pre>
</details>

### Environment

- OS / Python / Uvicorn version: `Running uvicorn 0.12.2 with CPython 3.7.8 on Darwin`

### Additional context

https://github.com/aiortc/aiortc/issues/429

**Comment by euri10** [comment]
closing as stale, dont hesitate to reopen with a clear explanation on how to reproduce this !
