### ISSUE TITLE
h11 - Content-Length issue

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#841]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

An error is raised when running `uvicorn` with the `h11` HTTP protocol implementation.

### To reproduce

I've found the issue running a FastAPI app:

```python
from fastapi import FastAPI

app = FastAPI()

@app.put("/", status_code=204)
def put_nothing():
    pass
```
With a simple curl request the problem raises:
```bash
curl -X PUT "http://localhost:8000/" -H  "accept: application/json" -H  "Content-Type: application/json -v"
```

### Expected behavior

Logs shouldn't show any errors.

### Actual behavior

This error appears in the log on each call:
```bash
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

### Debugging material
You should run `uvicorn` with:
```bash
uvicorn test:app --port 8000 --reload --http h11
```
Then you'll see the below behavior (after calling the `curl` command):

![image](https://user-images.githubusercontent.com/7353520/98186118-57ebb380-1f0e-11eb-893d-0e8318913d12.png)

On the curl command you'll get:

![image](https://user-images.githubusercontent.com/7353520/98186767-c11ff680-1f0f-11eb-9f88-4a32615ddb41.png)

**THIS IS USING `HTTPTOOLS`:** (no problems in the logs with it)
![image](https://user-images.githubusercontent.com/7353520/98186888-09d7af80-1f10-11eb-9548-318e3f7bb100.png)

### Environment

- Python: 3.8.5
- Uvicorn: 0.12.2
- FastAPI: 0.61.1

### Additional context

This error only happens with `uvicorn==0.12.2`. The other versions work just fine. But the problem relies on the `h11` upgrade. On `uvicorn==0.12.2` the `h11` was upgraded to `0.11.0`. This can be verified just downgrading the `h11` to `0.10.0` and maintaining the `uvicorn` version.

**Comment by euri10** [comment]
Can you reproduce without FastAPI ?
https://github.com/tiangolo/fastapi/issues/717

**Comment by Kludex** [comment]
@euri10 Thank you for the reference. But the thing is that changing the `h11` version makes it work...

**Comment by euri10** [comment]
> @euri10 Thank you for the reference. But the thing is that changing the `h11` version makes it work...

no it doesnt

**Comment by Kludex** [comment]
You're right. My information was incorrect. I probably made a mistake reproducing the issue with `h11==0.10.0`... 

I'm closing this as the information on the description was incorrect... sry
