### ISSUE TITLE
Hot-reloading gets stuck after interacting with multiprocessing / Twisted signals

### ISSUE THREAD

**Issue by desprit** [Kludex/uvicorn#850]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Launched with `--reload` option gets stuck after executing code that interacts with multiprocessing. More details below.

### To reproduce

I prepared a minimal build to reproduce this error:
https://github.com/desprit/uvicorn_reload_test

### Expected behavior

Uvicorn restarts.

### Actual behavior

Uvicorn get's stuck with message `WARNING:  Detected file change in...`

### Environment

`v0.12.2`
`uvicorn main:app --reload`

### Additional context

I tested it with [hypercorn](https://pgjones.gitlab.io/hypercorn/) and hot reloading doesn't break there. Did also tests with Flask + Gunicorn, works well there as well.

**Comment by florimondmanca** [comment]
@desprit Hi!

Quickly looked at the code over https://github.com/desprit/uvicorn_reload_test/blob/master/src/runner.py

Could you clarify which bits "interact with multiprocessing"?

Right now I'm seeing something interesting here:

```python
@app.get("/run", response_model=dict)
async def handler():
    """
    Parse request payload and run Scrapy spider.
    """

    result = run_spider()
    return {
        "status": result["status"],
        "data": result.get("results"),
        "message": result.get("message"),
    }
```

The `run_spider()` function is synchronous (it runs a twisted reactor — is this what does multiprocessing?), but you're calling it inside a Starlette view, which must remain non-blocking. I wouldn't be surprised that this causes some issues further down the line, including perhaps an issue with reloading.

Have you tried running it from a thread…?

```python
from starlette.concurrency import run_in_threadpool

@app.get("/run", response_model=dict)
async def handler():
    """
    Parse request payload and run Scrapy spider.
    """

    result = await run_in_threadpool(run_spider)
    return {
        "status": result["status"],
        "data": result.get("results"),
        "message": result.get("message"),
    }
```

**Comment by desprit** [comment]
@florimondmanca 

Thanks for the answer!
I tried running it with `run_in_threadpool` which threw an error from `twisted` saying:
```
builtins.ValueError: signal only works in main thread
```
which after some googling took me to https://mail.python.org/pipermail/python-list/2003-June/184406.html

I followed Andrew's advice and changed this line:
https://github.com/desprit/uvicorn_reload_test/blob/master/src/runner.py#L35
to be
```
reactor.run(installSignalHandlers=0)
```
Uvicorn doesn't stuck anymore. I don't have any good explanation yet (haven't had time to check the source code), maybe cleanup for signal handlers isn't getting called somewhere. I also don't know whether disabling `installSignalHandlers`  will affect anything. I have a cluster of several hundreds of Scrapy spiders, will test the fix there and let you know.
Twisted signals somehow break uvicorn reloading.

update: working good for me

**Comment by florimondmanca** [comment]
@desprit Nice, sure let us know how this behaves in production. :-)

As for Twisted, not an expert of Twisted myself, though [this FAQ](https://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions#Igetexceptions.ValueError:signalonlyworksinmainthreadwhenItrytorunmyTwistedprogramWhatswrong) indicates that the `installSignalHandlers` option is meant for this kind of use case (disable signal handling when running a reactor in a thread). I _assume_ the default signal handling is just there for convenience (eg making the reactor catch a `Ctrl-C` and return, instead of raising a `KeyboardInterrupt`) and dropping it won't cause much trouble. Let's see! :-)

**Comment by desprit** [comment]
@florimondmanca 

Do you, by any chance, have a better name for this ticket? I think multiprocessing is misleading and I want this thread to be discoverable in future since the issue is very niche and you don't find many references in google.

**Comment by florimondmanca** [comment]
@desprit I updated the issue title slightly, to me it looks like it contains appropriate keywords for a variety of entry points into this issue (hot reload being blocked, multiprocessing code, signals, Twisted...).

**Comment by euri10** [comment]
seems like this is solved, closing for now !
