### ISSUE TITLE
Support a concurrency ceiling without returning 503, like gunicorn's worker_connections

### ISSUE THREAD

**Issue by AlexHill** [Kludex/uvicorn#865]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I haven't dug deep into how gunicorn/uvicorn/channels work before now, so I'm mostly looking for a bit of clarity around what's expected and what's possible. This isn't a bug as such more question of architecture and configuration. It also might be more of a Django Channels issue than a Uvicorn issue. That said...

In wsgi gunicorn, multiple sync workers share a single queue - the incoming socket's backlog. This means that incoming connections are accepted and handled only when a worker is available and in the order they arrived - there is no "per-worker" queue. Any available worker is free to handle the next that is not currently being worked on.

This is the default behaviour with the `sync` worker, and can be achieved with the `gthread` worker type by setting `worker_connections` equal to `threads` - each worker will then only accept as many connections as there are threads doing work, so again the only queue it at the global level.

I'm wondering how to achieve this kind of behaviour with uvicorn/Channels. The uvicorn workers simply `accept` as fast as they can, creating an internal queue of async tasks inside each worker process, waiting to be run on the event loop. This would be fine in a fully async web application, but Django is not that - Channels runs synchronous Django views in a threadpool behind an async interface. The result is that requests can end up effectively queued inside a worker behind long-running requests, even if another worker process is idle. This effect is worse the lower the value of ASGI_THREADS.

Looking at the code, it looks like what might work here is some other worker class which accepts connections in a similar way to Gunicorn's gthread and then uses loop.connect_accepted_socket, rather than using loop.create_server...but then if you have true async views, or websockets, then you don't want those connections to "count" towards this limit! Any advice or help here would be very welcome.

### To reproduce

I've made the simplest Django project I can at https://github.com/AlexHill/django_channels_test. It has one endpoint, `/delay/<ms>/` which simply sleeps for the specified about of time. A load_test.py script hits this endpoint with random delays of `random.random() ** 2` seconds. The RNG is seeded so that subsequent runs are comparable.

Run the following commands:
1. `make env` to make the virtual environment
2. `env/bin/pip install "asgiref<3.3" "django<3" "channels<3"` to avoid some outstanding bugs
3. `make asgi-threads/wsgi-fair` to run gunicorn with four threads and four workers with either the uvicorn or gthread worker respectively.
3. `env/bin/python load_test.py 20 500` to make 500 requests with a max of 20 in-flight at a time.

Results:

With uvicorn:
```
Elapsed:  17.05116295814514
Mean:     0.62664039
Median:   0.5439335
Stddev:   0.48723392956708245
Variance: 0.23739690212138065
```

With gthread using --worker-connections:
```
Elapsed:  11.54984188079834
Mean:     0.43470821
Median:   0.361935
Stddev:   0.30666966777163374
Variance: 0.09404628513116423
```

All of these numbers are much better.

With gthread without --worker-connections:
```
Elapsed:  16.559799194335938
Mean:     0.641835746
Median:   0.56931
Stddev:   0.516759295760383
Variance: 0.267040169754767
```

Without limiting worker connections we effectively have the same setup as uvicorn - the gthread worker accepts many connections which go into a queue which the threadpool works through.

Thanks if you made it this far. Any advice greatly appreciated.

**Comment by florimondmanca** [comment]
@AlexHill Hello!

Just seeing this now. There was a somewhat related discussion on the `aiohttp` repo: https://github.com/aio-libs/aiohttp/issues/675 As well as this SO thread: https://stackoverflow.com/questions/56320850/aiohttp-server-max-connections

What's the behavior of Gunicorn when using `gthread`/`--worker-connections` — does it queue connections when the limit is reached, or does it reject the socket connection?

From my POV I don't think we're going to implement very highly sophisticated connection pooling / limit behavior in Uvicorn itself. As mentioned in the aiohttp issue, if you'd like more sophisticated options, putting Uvicorn behind a reverse proxy like Nginx which has those options (and many more :-)) would probably be a fair solution.

I'm not familiar enough with the Django Channels ecosystem to say if there are any recommendations on this front. Maybe some folks there have had to deal with this "limit sync views, but not async ones" thing? Does Django 3 help at all?

I'll close this for now because I don't think we'll be providing more options in Uvicorn at this time, but feel free to continue some discussion. :-) Thanks!

**Comment by AlexHill** [comment]
Fair enough!

> What's the behavior of Gunicorn when using gthread/--worker-connections — does it queue connections when the limit is reached, or does it reject the socket connection?

It queues, using the socket backlog as passed to `listen`. That's what gives the nice behaviour of there being a single, global queue which is always serviced by the next available worker thread across all worker processes.

Requests are handled by a `futures.ThreadPoolExecutor` and scheduled with `ThreadPoolExecutor.submit()`, in almost exactly the same way as they're handled in uvicorn by being scheduled on the event loop. `worker-connections` just allows you to limit how oversubscribed the threadpool is allowed to be. That's managed by literally just incrementing a number on accept and decrementing when each request finishes. If you don't allow it to be oversubscribed at all, by setting `worker-connections` and `threads` to the same value, connections remain queued on the socket waiting to be `accept`ed until a thread on any of the worker processes is actually available to process the work.

I think it might be possible to write a Uvicorn worker class that does something similar. If I get any time I'll give it a go. For now we've reverted to serving our sync views from Gunicorn and leaving uvicorn to just serve the websocket views.

**Comment by Meidan** [comment]
hey @AlexHill , did end up implementing a custom Uvicorn worker that allows specifying something like `worker_connections`? any tips would be appreciated

**Comment by AlexHill** [comment]
Unfortunately not, I just split my our app into one service handling
traditional requests with uwsgi and a sidecar handling websockets with
uvicorn.

**Comment by SHxKM** [comment]
Hey @AlexHill - this solved a mystery to me on why Uvicorn with Gunicorn were as slow/slower than Daphne…one thing I’m wondering about: 

> The result is that requests can end up effectively queued inside a worker behind long-running requests, even if another worker process is idle. This effect is worse the lower the value of ASGI_THREADS.

why is it worse when ASGI_THREADS is lower? Intuitively, I’d expect the opposite..

**Comment by AlexHill** [comment]
ASGI_THREADS determines the size of the threadpool in which sync views are run, but it doesn't have any effect on how many requests a worker pulls off the queue. So with a smaller ASGI_THREADS, you'd end up with a similar amount of requests queued inside each worker, but with a smaller threadpool servicing the queue of tasks, meaning tasks are more likely to be blocked behind a long-running request.

(Note: I've just seen that in the latest asgiref, [ASGI_THREADS support is removed](https://github.com/django/asgiref/commit/6a0cae060c0d96d7bf0d5a3dc38dbde090ab3e1a))

**Comment by AndresPinerosZen** [comment]
Is it actually possible to have an nginx configuration that caps the synchronous requests that consume the threadpool while allowing asynchronous requests to be handle normally?

It seems like the sane way would be to have a backend for the synchronous endpoints. That backend should have a `max_conns=<max-threads>` and a `queue`. Then also create an async nginx backend for the async stuff and don't add any connection limit.

Seems like having this out of the box would be a much better user experience, but it's understandable it isn't implemented. It's just a big gotcha for people moving from UWSGI or Gunicorn to Uvicorn.
