### ISSUE TITLE
multiworkers support for programming mode

### ISSUE THREAD

**Issue by zqbake** [Kludex/uvicorn#872]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

**Comment by florimondmanca** [comment]
@zhqu1148980644 This issue is empty. Please be considerate of other people's time and attention, and provide a description and fill in the template appropriately if there's anything you'd like to discuss. Thanks.
