### ISSUE TITLE
cannot import name 'Server' from 'uvicorn.main'

### ISSUE THREAD

**Issue by dirkliebich** [Kludex/uvicorn#879]
EDIT: this error happens when working with user: ubuntu (although in admin group).

after switching and re-installing under root, using **sudo su -** all works fine.
________

installed all parts as per documentation on Ubuntu 20.x
created example file main.py

when I run **uvicorn main:app --reload** from ssh console I get the follwing error. Any help is appreciated.

> uvicorn main:app --reload
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/uvicorn", line 5, in <module>
    from uvicorn.main import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/__init__.py", line 2, in <module>
    from uvicorn.main import Server, main, run
ImportError: cannot import name 'Server' from 'uvicorn.main' (/home/ubuntu/.local/lib/python3.8/site-packages/uvicorn/main.py)

**Comment by euri10** [comment]
Feel free to fill the issue template :)
thanks

**Comment by florimondmanca** [comment]
Closing for now, feel free to report back with your Uvicorn version if you'd like us to look into it — upgrading to the latest version should do the trick, though.
