### ISSUE TITLE
uvicorn worker hangs after client interrupt connection

### ISSUE THREAD

**Issue by Enormoss** [Kludex/uvicorn#882]
I'm reading data from fastapi FileResponse thru uvicorn, using curl.
When I interrupt curl, uvicron is still running eating CPU

with trace enabled, uvicorn sending still 

`ASGI [2] Send {'type': 'http.response.body', 'body': '<4096 bytes>', 'more_body': True}`

uvicorn is in version 0.13.0

Runnign uvicorn behind ngix is the same situation.

**Comment by euri10** [comment]
Feel free to fill the issue template :)
thanks

**Comment by Enormoss** [comment]
probably I found it
I rewrited code to StreamingResponse with 
`await request.is_disconnected()`
inside generator

**Comment by euri10** [comment]
ok closing it if you found what went wrong, feel free to raise an issue with the template filled if not the case, that saves us time ;)

**Comment by Enormoss** [comment]
Ok, thank you for your time.
