### ISSUE TITLE
Gunicorn+UvicornWorker,access log not working after logrotate access log file.

### ISSUE THREAD

**Issue by yinkh** [Kludex/uvicorn#896]
### Checklist

- [ YES ] The bug is reproducible against the latest release and/or `master`.
- [ YES ] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Use FastAPI+Uvicorn+Gunicorn to deploy the production environment, When use logrotate to compressed log, access.log file will be reopen, but UvicornWorker not write access log to access.log.

### To reproduce
1.  start server with gunicorn+UvicornWorker
```
(venv) [root@localhost task_registry_center]# gunicorn -w 2 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --access-logfile log/access.log main:app
[2020-12-16 17:09:41 +0800] [3330] [INFO] Starting gunicorn 20.0.4
[2020-12-16 17:09:41 +0800] [3330] [INFO] Listening at: http://0.0.0.0:8000 (3330)
[2020-12-16 17:09:41 +0800] [3330] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2020-12-16 17:09:41 +0800] [3332] [INFO] Booting worker with pid: 3332
[2020-12-16 17:09:41 +0800] [3333] [INFO] Booting worker with pid: 3333
```
2.  now access log file is empty
```
[root@localhost log]# pwd
/data/task_registry_center/log
[root@localhost log]# ll
total 20
-rw-r--r--. 1 root root    0 Dec 16 16:56 access.log
-rw-r--r--. 1 root root    0 Dec 16 16:41 client.log
-rw-r--r--. 1 root root    0 Dec 16 16:56 debug.log
-rw-r--r--. 1 root root    0 Dec 16 16:41 elk_client.log
-rw-r--r--. 1 root root 5402 Dec 16 17:08 error.log
-rw-r--r--. 1 root root    0 Dec 16 16:41 id_server.log
-rw-r--r--. 1 root root 4029 Dec 16 17:09 main.log
-rw-r--r--. 1 root root 4480 Dec 16 17:10 tasks.log
```
3.  call one api 10 times, now log path is :

```
[root@localhost log]# ll
total 24
-rw-r--r--. 1 root root  720 Dec 16 17:11 access.log

```
access.log context is 
```
192.168.11.1:60477 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60478 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60479 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60480 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60481 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60482 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60483 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60484 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60485 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60486 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
```
4. manual call logrotate

```
[root@localhost ~]# /usr/sbin/logrotate -f /etc/logrotate.d/task_registry_center
```
logrotate config is :
```
[root@localhost ~]# cat /etc/logrotate.d/task_registry_center                                                                                                                                                   
/data/task_registry_center/log/*.log {                                                                                                                                  
        size 1M                                                                                                                                                         
        rotate 20                                                                                                                                                       
        compress                                                                                                                                                        
        nodelaycompress                                                                                                                                                 
        dateformat -%Y-%m-%d-%s                                                                                                                                         
        dateext                                                                                                                                                         
        missingok                                                                                                                                                       
        notifempty                                                                                                                                                      
        postrotate                                                                                                                                                      
            killall -s USR1 gunicorn                                                                                                                  13,9          All
        endscript
}

```

5.  gunicorn receive USR1 signal to reopen access log file and log this
```
[2020-12-16 17:12:16 +0800] [3330] [INFO] Handling signal: usr1
[2020-12-16 17:12:16 +0800] [3330] [INFO] Handling signal: usr1
[2020-12-16 17:12:16 +0800] [3330] [INFO] Handling signal: usr1
[2020-12-16 17:12:16 +0800] [3330] [INFO] Handling signal: usr1
```

6. now log path is:
```
[root@localhost log]# ll
total 20
-rw-r--r--. 1 root root   0 Dec 16 17:12 access.log
-rw-r--r--. 1 root root 125 Dec 16 17:11 access.log-2020-12-16-1608109936.gz
```
7. then call one api 10 times, log path is:
```
[root@localhost log]# ll
total 20
-rw-r--r--. 1 root root   0 Dec 16 17:12 access.log
-rw-r--r--. 1 root root 125 Dec 16 17:11 access.log-2020-12-16-1608109936.gz
```
access.log-2020-12-16-1608109936.gz context still is 
```
192.168.11.1:60477 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60478 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60479 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60480 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60481 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60482 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60483 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60484 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60485 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
192.168.11.1:60486 - "GET /api/client?page_size=10&page=1 HTTP/1.1" 200
```

this 10 times does not log to any access log.

### Expected behavior

the lastest 10 times api call will log access log to reopened access.log file.

### Actual behavior

the lastest 10 times api call does not log to any access log file.

### Debugging material

I have manual send USR1 signal instead of call logrotate, the result is same , new log file is created,but no access record log to it.

### Environment

- OS is centos7
- Python 3.8.3
- gunicorn          20.0.4
- uvicorn           0.13.1
- fastapi           0.62.0

### Additional context

I have find someone has same issue as me on so,see 
https://stackoverflow.com/questions/61794303/why-doesnt-gunicorn-write-log-to-reopened-file-while-rotating-a-log-file

I have try to rewirte UvicornWorker like:
```
class RequestUvicornWorker(UvicornWorker):

    def __init__(self, *args, **kwargs):
        super(RequestUvicornWorker, self).__init__(*args, **kwargs)
        logger = logging.getLogger("uvicorn.access")
        handler = WatchedFileHandler(filename='log/access.log')
        logger.handlers = self.log.access_log.handlers
        logger.setLevel(self.log.access_log.level)
```
change log handler to WatchedFileHandler, still not working.
And i have a flask app deploy with gunicorn, this will correctly log access log to new access log file after logrotate.

Hope for reply,THANK YOU!

**Comment by yinkh** [comment]
logrotate copytruncate option works for me!

**Comment by yinkh** [comment]
But use `copytruncate` instead of  `create`  for logrotate, has the risk of lost log record, hope someone can find the real reason cause this issue!

**Comment by yinkh** [comment]
In gunicorn(version 20.0.4 ), has some code related to USR1 singles, here is the key code:

`venv/Lib/site-packages/gunicorn/workers/base.py line 165`

```
    def init_signals(self):
        # reset signaling
        for s in self.SIGNALS:
            signal.signal(s, signal.SIG_DFL)
        # init new signaling
        signal.signal(signal.SIGQUIT, self.handle_quit)
        signal.signal(signal.SIGTERM, self.handle_exit)
        signal.signal(signal.SIGINT, self.handle_quit)
        signal.signal(signal.SIGWINCH, self.handle_winch)
        signal.signal(signal.SIGUSR1, self.handle_usr1)
        signal.signal(signal.SIGABRT, self.handle_abort)

        # Don't let SIGTERM and SIGUSR1 disturb active requests
        # by interrupting system calls
        signal.siginterrupt(signal.SIGTERM, False)
        signal.siginterrupt(signal.SIGUSR1, False)

        if hasattr(signal, 'set_wakeup_fd'):
            signal.set_wakeup_fd(self.PIPE[1])

```

```
    # line 185 in same file
    def handle_usr1(self, sig, frame):
        self.log.reopen_files()
```

`venv/Lib/site-packages/gunicorn/glogging.py` line 352
```
    def reopen_files(self):
        if self.cfg.capture_output and self.cfg.errorlog != "-":
            for stream in sys.stdout, sys.stderr:
                stream.flush()

            with self.lock:
                if self.logfile is not None:
                    self.logfile.close()
                self.logfile = open(self.cfg.errorlog, 'a+')
                os.dup2(self.logfile.fileno(), sys.stdout.fileno())
                os.dup2(self.logfile.fileno(), sys.stderr.fileno())


        for log in loggers():
            for handler in log.handlers:
                if isinstance(handler, logging.FileHandler):
                    handler.acquire()
                    try:
                        if handler.stream:
                            handler.close()
                            handler.stream = handler._open()
                    finally:
                        handler.release()
```

**Comment by yinkh** [comment]
`venv/Lib/site-packages/gunicorn/arbiter.py` line 196:
```

    def run(self):
        "Main master loop."
        self.start()
        util._setproctitle("master [%s]" % self.proc_name)

        try:
            self.manage_workers()

            while True:
                self.maybe_promote_master()

                sig = self.SIG_QUEUE.pop(0) if self.SIG_QUEUE else None
                if sig is None:
                    self.sleep()
                    self.murder_workers()
                    self.manage_workers()
                    continue

                if sig not in self.SIG_NAMES:
                    self.log.info("Ignoring unknown signal: %s", sig)
                    continue

                signame = self.SIG_NAMES.get(sig)
                handler = getattr(self, "handle_%s" % signame, None)
                if not handler:
                    self.log.error("Unhandled signal: %s", signame)
                    continue
                self.log.info("Handling signal: %s", signame)
                handler()
                self.wakeup()
```

```

    def handle_usr1(self):
        """\
        SIGUSR1 handling.
        Kill all workers by sending them a SIGUSR1
        """
        self.log.reopen_files()
        self.kill_workers(signal.SIGUSR1)
```

 I notice uviocrn only handle this two signal?

```
HANDLED_SIGNALS = (
    signal.SIGINT,  # Unix signal 2. Sent by Ctrl+C.
    signal.SIGTERM,  # Unix signal 15. Sent by `kill <pid>`.
)
```

**Comment by yinkh** [comment]
If i comment code inside `venv/Lib/site-packages/uvicorn/workers.py` line 63 like this:

```
    def init_process(self):
        self.config.setup_event_loop()
        super(UvicornWorker, self).init_process()

    '''
    def init_signals(self):
        pass
    '''

    def run(self):
        self.config.app = self.wsgi
        server = Server(config=self.config)
        loop = asyncio.get_event_loop()
        loop.run_until_complete(server.serve(sockets=self.sockets))
```
this problem is gone!

so the code inside `gunicorn/workers/base.py class Worker` function init_signals, `signal.signal(signal.SIGUSR1, self.handle_usr1)` is need！

**Comment by yinkh** [comment]
change code inside `venv/Lib/site-packages/uvicorn/workers.py` line 63 form:
```
    def init_signals(self):
        pass
```

to

```
    def init_signals(self):
        signal.signal(signal.SIGUSR1, self.handle_usr1)
```

will solve this problem.should i push a PR?

**Comment by euri10** [comment]
Have you tried on master ?
If that doesn't work then the latest pr on that part of the code here
https://github.com/encode/uvicorn/pull/895 was likely not enough and we may
have to consider removing entirely the init_signals override which I
thought initially was the right move.

**Comment by euri10** [comment]
Related https://github.com/encode/uvicorn/issues/464

**Comment by yinkh** [comment]
the code inside branch master works like charm!
```
    def init_signals(self):
        # Reset signals so Gunicorn doesn't swallow subprocess return codes
        # other signals are set up by Server.install_signal_handlers()
        # See: https://github.com/encode/uvicorn/issues/894
        for s in self.SIGNALS:
            signal.signal(s, signal.SIG_DFL)

```

**Comment by euri10** [comment]
I'm glad it's working now for you, in fact you can already use it in 0.13.3 !

**Comment by yinkh** [comment]
I will upgrade to 0.13.3 ! thank you

**Comment by otsuka** [comment]
I wrote a very simple Starlette app to test the log rotate behavior.

###### umain.py

```py
import logging

from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route

logging.basicConfig(level=logging.DEBUG, filename='./log.txt')

logger = logging.getLogger(__name__)


async def some_startup_task():
    logger.info("startup")


async def some_shutdown_task():
    logger.info("shutdown")


async def homepage(request):
    logger.debug("homepage()")
    return JSONResponse({'hello': 'world'})


app = Starlette(debug=False,
                routes=[Route('/', homepage)],
                on_startup=[some_startup_task],
                on_shutdown=[some_shutdown_task])
```

Start this Starlette app with Gunicorn and UvicornWorker.

```
$ gunicorn -w 2 -k uvicorn.workers.UvicornWorker umain:app

[2021-01-12 17:26:17 +0900] [287] [INFO] Starting gunicorn 20.0.4
[2021-01-12 17:26:17 +0900] [287] [INFO] Listening at: http://127.0.0.1:8000 (287)
[2021-01-12 17:26:17 +0900] [287] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-01-12 17:26:17 +0900] [289] [INFO] Booting worker with pid: 289
[2021-01-12 17:26:17 +0900] [290] [INFO] Booting worker with pid: 290
[2021-01-12 17:26:17 +0900] [289] [INFO] Started server process [289]
[2021-01-12 17:26:17 +0900] [290] [INFO] Started server process [290]
[2021-01-12 17:26:17 +0900] [289] [INFO] Waiting for application startup.
[2021-01-12 17:26:17 +0900] [290] [INFO] Waiting for application startup.
[2021-01-12 17:26:17 +0900] [290] [INFO] Application startup complete.
[2021-01-12 17:26:17 +0900] [289] [INFO] Application startup complete.
```

Invoking `kill -USR1 287` in order to rotate the log file, then the console log is as follows:

```
[2021-01-12 17:26:33 +0900] [287] [INFO] Handling signal: usr1
[2021-01-12 17:26:33 +0900] [300] [INFO] Booting worker with pid: 300
[2021-01-12 17:26:33 +0900] [311] [INFO] Booting worker with pid: 311
[2021-01-12 17:26:33 +0900] [300] [INFO] Started server process [300]
[2021-01-12 17:26:33 +0900] [300] [INFO] Waiting for application startup.
[2021-01-12 17:26:33 +0900] [300] [INFO] Application startup complete.
[2021-01-12 17:26:33 +0900] [311] [INFO] Started server process [311]
[2021-01-12 17:26:33 +0900] [311] [INFO] Waiting for application startup.
[2021-01-12 17:26:33 +0900] [311] [INFO] Application startup complete.
```

Worker processes were restarted.

The `log.txt` indicates that the on_startup task were called but the on_shutdown task were not called.

```
$ cat log.txt
INFO:umain:startup
INFO:umain:startup
INFO:umain:startup
INFO:umain:startup
```

How can we reopen a log file without restarting worker processes for log rotation?
And, on restarting worker processes, why the on_shutdown task are not called?

#### Environment 

- macOS 10.15.7
- Python 3.8.6
- uvicorn 0.13.3
- gunicorn 20.0.4
- starlette 0.13.6

**Comment by euri10** [comment]
> How can we reopen a log file without restarting worker processes for log rotation?

no idea, someone more familiar with gunicorn internals might have a clue

> And, on restarting worker processes, why the on_shutdown task are not called?

it's because, _**I suppose**_, we have a SIGTERM issue (see #852) , I just tested your snippet on #853 and I have the shutdown logrotate in files

**Comment by yinkh** [comment]
> I wrote a very simple Starlette app to test the log rotate behavior.
> 
> ###### umain.py
> ```python
> import logging
> 
> from starlette.applications import Starlette
> from starlette.responses import JSONResponse
> from starlette.routing import Route
> 
> logging.basicConfig(level=logging.DEBUG, filename='./log.txt')
> 
> logger = logging.getLogger(__name__)
> 
> 
> async def some_startup_task():
>     logger.info("startup")
> 
> 
> async def some_shutdown_task():
>     logger.info("shutdown")
> 
> 
> async def homepage(request):
>     logger.debug("homepage()")
>     return JSONResponse({'hello': 'world'})
> 
> 
> app = Starlette(debug=False,
>                 routes=[Route('/', homepage)],
>                 on_startup=[some_startup_task],
>                 on_shutdown=[some_shutdown_task])
> ```
> 
> Start this Starlette app with Gunicorn and UvicornWorker.
> 
> ```
> $ gunicorn -w 2 -k uvicorn.workers.UvicornWorker umain:app
> 
> [2021-01-12 17:26:17 +0900] [287] [INFO] Starting gunicorn 20.0.4
> [2021-01-12 17:26:17 +0900] [287] [INFO] Listening at: http://127.0.0.1:8000 (287)
> [2021-01-12 17:26:17 +0900] [287] [INFO] Using worker: uvicorn.workers.UvicornWorker
> [2021-01-12 17:26:17 +0900] [289] [INFO] Booting worker with pid: 289
> [2021-01-12 17:26:17 +0900] [290] [INFO] Booting worker with pid: 290
> [2021-01-12 17:26:17 +0900] [289] [INFO] Started server process [289]
> [2021-01-12 17:26:17 +0900] [290] [INFO] Started server process [290]
> [2021-01-12 17:26:17 +0900] [289] [INFO] Waiting for application startup.
> [2021-01-12 17:26:17 +0900] [290] [INFO] Waiting for application startup.
> [2021-01-12 17:26:17 +0900] [290] [INFO] Application startup complete.
> [2021-01-12 17:26:17 +0900] [289] [INFO] Application startup complete.
> ```
> 
> Invoking `kill -USR1 287` in order to rotate the log file, then the console log is as follows:
> 
> ```
> [2021-01-12 17:26:33 +0900] [287] [INFO] Handling signal: usr1
> [2021-01-12 17:26:33 +0900] [300] [INFO] Booting worker with pid: 300
> [2021-01-12 17:26:33 +0900] [311] [INFO] Booting worker with pid: 311
> [2021-01-12 17:26:33 +0900] [300] [INFO] Started server process [300]
> [2021-01-12 17:26:33 +0900] [300] [INFO] Waiting for application startup.
> [2021-01-12 17:26:33 +0900] [300] [INFO] Application startup complete.
> [2021-01-12 17:26:33 +0900] [311] [INFO] Started server process [311]
> [2021-01-12 17:26:33 +0900] [311] [INFO] Waiting for application startup.
> [2021-01-12 17:26:33 +0900] [311] [INFO] Application startup complete.
> ```
> 
> Worker processes were restarted.
> 
> The `log.txt` indicates that the on_startup task were called but the on_shutdown task were not called.
> 
> ```
> $ cat log.txt
> INFO:umain:startup
> INFO:umain:startup
> INFO:umain:startup
> INFO:umain:startup
> ```
> 
> How can we reopen a log file without restarting worker processes for log rotation?
> And, on restarting worker processes, why the on_shutdown task are not called?
> 
> #### Environment
> * macOS 10.15.7
> * Python 3.8.6
> * uvicorn 0.13.3
> * gunicorn 20.0.4
> * starlette 0.13.6

I has same question. uvicorn 0.13.3 will restart gunicorn worker for USR1 signal,which is different from gunicorn. Change `init_signals` to original will work:

```
    def init_signals(self):
        # reset signaling
        for s in self.SIGNALS:
            signal.signal(s, signal.SIG_DFL)
        # init new signaling
        signal.signal(signal.SIGQUIT, self.handle_quit)
        signal.signal(signal.SIGTERM, self.handle_exit)
        signal.signal(signal.SIGINT, self.handle_quit)
        signal.signal(signal.SIGWINCH, self.handle_winch)
        signal.signal(signal.SIGUSR1, self.handle_usr1)
        signal.signal(signal.SIGABRT, self.handle_abort)

        # Don't let SIGTERM and SIGUSR1 disturb active requests
        # by interrupting system calls
        signal.siginterrupt(signal.SIGTERM, False)
        signal.siginterrupt(signal.SIGUSR1, False)

        if hasattr(signal, 'set_wakeup_fd'):
            signal.set_wakeup_fd(self.PIPE[1])
```
