### ISSUE TITLE
Cythonised protocol implementation

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#92]
Provide a cythonised version of the `httptools` protocol implementation.

May also want to drop header lowercasing (they should already be) and provide dict-like objects for the known message types.

**Comment by lovelydinosaur** [comment]
Not that I especially *want* to do this, but we need to bash folks over the head with fast ASGI implementations, because it's important for making the case. 💥😎

**Comment by RobertoPrevato** [comment]
Hi @tomchristie, I started working on the Cythonized version of httptools protocol for uvicorn, I just pushed it here (feature branch inside my fork of uvicorn): [https://github.com/RobertoPrevato/uvicorn/tree/feature/cyhttptools](https://github.com/RobertoPrevato/uvicorn/tree/feature/cyhttptools).

Unit tests for protocols are passing.

I needed to change a couple of things:
* I needed to rename the file 'httptools.py' to something else, otherwise the compiled Cython protocol would use it instead of the intended `httptools` library
* I think there is an error in the arrangement of some of the unit tests you prepared, and assertions are succeeding just by coincidence; in some arrangements header values of type `int` are then used like they were `str`, calling `decode()` method that doesn't exist on `int` - I changed these arrangements like this:

```py
    def app(scope):
        return Response(b"xxx", headers={"content-length": "10"})  # <-- 10 to "10"
```
* since asyncio classes cannot be used as base classes for `cdef` classes, the Cythonized HttpToolsProtocol class cannot inherit from asyncio.Protocol; it works by duck typing

Since I am new to Cython, there are for sure many things to improve in what I did (more optimizations to do), if somebody could give recommendations I would be happy.

**Comment by lovelydinosaur** [comment]
Amazing!

I managed to get it working, but I needed to use `ext_modules=cythonize("uvicorn/protocols/http/cyhttptools.pyx"),` in the `setup.py`. I'm not sure how I should be installing it otherwise?

Saw a bit of a throughput bump. Everything working well, except Ctrl-C didn't seem to quit, and needed `kill -9` (Do you see the same behavior there?)

Good catch on the `int`/`str` cases.

> the Cythonized HttpToolsProtocol class cannot inherit from asyncio.Protocol; it works by duck typing

That's fine, yup. That's what I'd expected to see.

We've got a couple of options here:

* Allow uvicorn to use a third-party protocol class, and have the cythonised variant be packaged up seperately (just providing the protocol class, which can then be referenced by something like `uvicorn --http cyhttptools:CyHttpToolsProtocol ...`
* Provide the cythonised variant as a built-in option, like this.

Also, what's the best way to see what's being turned into C and what's being left as plain Python?

Any thoughts on how best to profile this?

**Comment by RobertoPrevato** [comment]
Sorry for coming back so late :)
I answer in order:
1. about cythonizing, in my branch I modified the [`setup.py` file](https://github.com/RobertoPrevato/uvicorn/blob/feature/cyhttptools/setup.py) to include extension configuration, and added a Makefile that works on my Ubuntu 18.04. 
```python
    ext_modules=[
        Extension('uvicorn.protocols.http.cyhttptools',
                  ['uvicorn/protocols/http/cyhttptools.c'],
                  extra_compile_args=['-O2'])
    ],
```
First we need to cythonize, then run setup.py to build extensions; example:
```shell
	cython uvicorn/protocols/http/cyhttptools.pyx
	python3 setup.py build_ext --inplace
```
I looked at how `httptools` code was configured and did the same as there.

2. I didn't try yet with keyboard interrupt, I will take a look asap if it works. I have the same problem with aiohttp under Windows, I don't know if it can be related.

3. I think that packing the Cythonized protocol in a dedicated library would make sense the most. Not everybody is interested in different kinds of protocols. The only problem I see is that, in this scenario, we should also put the unit tests in a dedicated package, to avoid having to copy-paste the tests for protocols in many repositories. I never packed unit tests in a dedicated library, it looks a bit exotic but doable. Another option maybe is to use `.gitmodules` file referencing another repository; I don't know what is the best option.

4. About seeing which code is turned into C and what's left in Python, I recommend to use `cython` command with annotations (for example: _cython -a uvicorn/protocols/http/cyhttptools.pyx_) which generates an HTML page with Python parts highlighted in yellow and expandable to see generated code. I described this in the README of my fork.

5. About profiling, as I mentioned in my first email, I think we should have a dedicated repository with benchmarks-related code. I think it's necessary to have a CI job that runs these benchmarks periodically and publishes results somewhere, to detect degradations in performance as the framework evolves. I would setup email notifications to be notified when performance degradation is detected (in speed, CPU or RAM consumption). It's not easy but I know how to set up something like this with VSTS and Azure, it would cost time but ~0 in money.

**Comment by lovelydinosaur** [comment]
3. I'd be fine with that. We could perfectly well include any custom protocol classes in our our test cases here, to ensure that they're compliant. You might want to duplicate the tests for the repo that the protocol class is in. (Honestly I'd *initially* just keep it simple and duplicate the test cases in your own repo.)
5. I'd suggest just making sure we keep the TechEmpower benchmarks up to date with the latest version of uvicorn, and the latest version of whichever protocol class we use. (See also https://github.com/encode/uvicorn/issues/94) Techempower now run continuous benchmarking, so any version updates will give us historical comparisons, for a decent range of test types. https://tfb-status.techempower.com/

There's been some updates to the http protocols, that you might want to sync up to. In particular they'll now handle pipelining properly, which is a pre-requisite for techempower's "plaintext" test type, which uses HTTP pipelining.

**Comment by imbolc** [comment]
@tomchristie do you want to leave main implementation pure-python? Can't we cythonise a little parts and merge it into main branch? I have some time I'd spend on this task, but I'm afraid to waste it on huge never-merged branch :)

**Comment by lovelydinosaur** [comment]
What I’d like is for it to be an optional dependency that’s installed and used by default. Similar to `uvloop` - not strictly required or part of the main package, but used in the default case.

**Comment by lovelydinosaur** [comment]
Actually thinking about it, for the purposes of testing etc maybe it is helpful to have it in the core package - not sure. Would that introduce issues installing with pypy or on windows?

**Comment by imbolc** [comment]
> optional dependency that’s installed and used by default

I agree in the ideal world it's probably the best way, but if you range your priorities would maintaining these additional versions somewhere on the top?

> Would that introduce issues installing with pypy or on windows?

I'm not an expert in Cython, but if it will, would it change anything? I mean what the goal of uvicorn? What would you prefer to achieve first - better performance or universality?

I think people using windows mostly for development and I don't see why daphne any worse for this purposes. The same thoughts on pypy, uvicorn isn't a single option here, they can use another pure-python asgi server. It doesn't look like if uvicorn stop support those, some people lose whole asgi-world :)

**Comment by lovelydinosaur** [comment]
100% want uvicorn to continue supporting pypy and windows, yup. I’ve no problem maintaining a cythonised protocol package, under the `encode` organisation if needed. It’d be high enough priority since performance *is* one of the key drivers towards async.

**Comment by imbolc** [comment]
> I’ve no problem maintaining a cythonised protocol package

So you've decided to make it optional?

> Would that introduce issues installing with pypy or on windows?

I read a bit about it. Cython suggesting distribute as well `.c` files and disable compilation of `.pyx` by default. Pypy and windows both can compile c-extensions. So there's probably a way to cythonise anything we want without loosing compatibility and creating optional packages.

> is one of the key drivers towards async

If we're talking about performance in general it's probably the only reason :)

What the next steps we can make it this direction? It's probably would be creating a testing routine for each platform? Is there a place (like apistar forum?) we can look for experienced people willing to help in this narrow area?

**Comment by lovelydinosaur** [comment]
> If we're talking about performance in general it's probably the only reason

Throughput performance is the most obvious driver, yes, but not the only one. There's a whole bunch of stuff that it makes possible that you can't really do in a thread-blocking context. WebSocket Support, Server Sent Events, In-process background tasks. etc.

> What the next steps we can make it this direction?

All we need to start with is a package that includes a cythonised protocol class.
