### ISSUE TITLE
Httptools trims long urls

### ISSUE THREAD

**Issue by euri10** [Kludex/uvicorn#924]
Prompted as part of the discussion in #344 , it seems httptools doenst handle well long url, see #925 for a failing test

I can say that for my case the issue is not URLs longer than 65,535 characters, but rather that `on_url` is being called multiple times for whatever reason: https://github.com/nodejs/http-parser#parsing-urls.

_Originally posted by @malthejorgensen in https://github.com/encode/uvicorn/issues/344#issuecomment-752074479_

**Comment by victoraugustolls** [comment]
@euri10 There is a [pr](https://github.com/MagicStack/httptools/pull/56) to move httptools from http-parser tô llhttp. If the bug is in http-parser, this might help!

**Comment by euri10** [comment]
Cool, I subscribed to it thanks for the heads up @victoraugustolls !

**Comment by Kludex** [comment]
jfyk, @victoraugustolls PR was merged, and we have a PR using the new httptools version: https://github.com/encode/uvicorn/pull/1024

**Comment by euri10** [comment]
url parsing in httptools is still handled by http-parser and llhttp has a long standing enhancement request to provide a way to do it, so using the new httptools version in fact does not change anything to this issue

**Comment by euri10** [comment]
closing this a wontfix since it's an issue upstream > upstream (httptools using http-parse for url parsing)
