### ISSUE TITLE
SCRIPT_NAME does not respect ASGI spec

### ISSUE THREAD

**Issue by NargiT** [Kludex/uvicorn#937]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The root path cannot be modified.

### Expected behavior

I expect logs to match the real request, in other words `curl localhost:8000/foo` must log `INFO:     127.0.0.1:34100 - "GET foo/ HTTP/1.1" 200 OK` where as in this case `curl localhost:8000` must logs `not found` as uvicorn is configured to use foo context `INFO:     127.0.0.1:34100 - "GET / HTTP/1.1" 404 OK` 

### Actual behavior

Currently the logging does not match to the real call.

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
```bash
uvicorn --version
Running uvicorn 0.13.3 with CPython 3.6.9 on Linux
```

- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.
```bash
export SCRIPT_NAME=foo; uvicorn --log-level trace test:app
```

### Additional context

Everything is inside docker and the application is a python package.

some references: https://github.com/tiangolo/fastapi/issues/1207#issuecomment-611683608

**Comment by euri10** [comment]
see https://github.com/django/asgiref/pull/230

**Comment by Kludex** [comment]
PR to continue @CoolSpring8 's work is welcome.

**Comment by Kludex** [comment]
As we want to remove `WSGIMiddleware` from `uvicorn`, and use [`a2wsgi`](https://pypi.org/project/a2wsgi/) package, I'll close this issue.

@abersheeran Can you confirm we don't have this issue on `a2wsgi`?

**Comment by abersheeran** [comment]
> As we want to remove `WSGIMiddleware` from `uvicorn`, and use [`a2wsgi`](https://pypi.org/project/a2wsgi/) package, I'll close this issue.
> 
> @abersheeran Can you confirm we don't have this issue on `a2wsgi`?

I had a quick recap of `a2wsgi`'s code and it doesn't seem like it handles this, I'll be submitting a PR soon to fix it (based on [PEP3333's code](https://peps.python.org/pep-3333/#the-server-gateway-side), which is easy).

**Comment by Kludex** [comment]
Great! Thanks @abersheeran 🙇
