### ISSUE TITLE
Error Python3.9

### ISSUE THREAD

**Issue by vBlackOut** [Kludex/uvicorn#938]
### Describe the bug

i run uvicorn on python3.9 but console return 

OSError: [Errno 88] Socket operation on non-socket

full output:
INFO:     Started server process [6652]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
Traceback (most recent call last):
  File "/var/www/html/cubydock/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 65, in serve
    await self.startup(sockets=sockets)
  File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 116, in startup
    sock = socket.fromfd(config.fd, socket.AF_UNIX, socket.SOCK_STREAM)
  File "/usr/lib/python3.9/socket.py", line 545, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket

you are more information for this error ? thank you i use Manjaro Linux python3.9 thank

**Comment by euri10** [comment]
please fill the bug report template with all info, thanks

**Comment by vBlackOut** [comment]
i found one problem it's for --fd
sudo /var/www/html/cubydock/.venv/bin/uvicorn --fd $(circus.sockets.web) cuby.asgi:application
but it's work
sudo /var/www/html/cubydock/.venv/bin/uvicorn cuby.asgi:application

**Comment by vBlackOut** [comment]
it's my systemd return

● cubydock.service - CubyDock servie webpanel
     Loaded: loaded (/etc/systemd/system/cubydock.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-01-19 13:30:59 CET; 2s ago
   Main PID: 18782 (python3.9)
      Tasks: 8 (limit: 38402)
     Memory: 33.5M
     CGroup: /system.slice/cubydock.service
             ├─18782 /var/www/html/cubydock/.venv/bin/python3.9 /var/www/html/cubydock/.venv/bin/circusd /var/www/html/cubydock/circus.ini --log-output /var/www/html/cubydock/debugservice.log --pidfile /var/run/cubydock.pid
             └─18787 /var/www/html/cubydock/.venv/bin/python3.9 -c from circus import stats; stats.main() --endpoint tcp://127.0.0.1:5555 --pubsub tcp://127.0.0.1:5556 --statspoint tcp://127.0.0.1:5557

janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:     await self.startup(sockets=sockets)
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:   File "/var/www/html/cubydock/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 116, in startup
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:     sock = socket.fromfd(config.fd, socket.AF_UNIX, socket.SOCK_STREAM)
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:   File "/usr/lib/python3.9/socket.py", line 545, in fromfd
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:     return socket(family, type, proto, nfd)
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:   File "/usr/lib/python3.9/socket.py", line 232, in __init__
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]:     _socket.socket.__init__(self, family, type, proto, fileno)
janv. 19 13:30:59 mjd-systemproductname python3.9[18789]: OSError: [Errno 88] Socket operation on non-socket
janv. 19 13:30:59 mjd-systemproductname sudo[18785]: pam_unix(sudo:session): session closed for user root
janv. 19 13:30:59 mjd-systemproductname sudo[18786]: pam_unix(sudo:session): session closed for user root


version uvicorn 
Running uvicorn 0.13.3 with CPython 3.9.1 on Linux

**Comment by vBlackOut** [comment]
weird it's pip version uviron return 0.13.3

Collecting uvicorn
  Using cached uvicorn-0.13.3-py3-none-any.whl (45 kB)
Requirement already satisfied: h11>=0.8 in ./.venv/lib/python3.9/site-packages (from uvicorn) (0.12.0)
Requirement already satisfied: click==7.* in ./.venv/lib/python3.9/site-packages (from uvicorn) (7.1.2)
Installing collected packages: uvicorn
Successfully installed uvicorn-0.13.3

**Comment by vBlackOut** [comment]
i found this problem it's for socket used by other program thank
