### ISSUE TITLE
Docs: workers = 1 when WEB_CONCURRENCY is not set

### ISSUE THREAD

**Issue by pawamoy** [Kludex/uvicorn#940]
Hello, thanks for this great ASGI server 🙂 

I have an application that must use only one worker (it's not thread-safe), and so I wanted to confirm that, by default, uvicorn only uses one worker. But I had to read the source code

https://github.com/encode/uvicorn/blob/afb2d565c8dae859bcef4c76b3c6dc3f3077314d/uvicorn/config.py#L177

...to confirm that when `WEB_CONCURRENCY` is not defined, and `workers` is not specified, 1 is used.

Would you accept a PR adding that information to the docs (there are 4-5 places where this can be added)?

**Comment by euri10** [comment]
> I have an application that must use only one worker (it's not thread-safe), and so I wanted to confirm that, by default, uvicorn only uses one worker. But I had to read the source code

`workers` set the number of processes not threads, just to be clear

> ...to confirm that when `WEB_CONCURENCY` is not defined, and `workers` is not specified, 1 is used.
> 
> Would you accept a PR adding that information to the docs (there are 4-5 places where this can be added)?

sure why not, I edited your title to put 2 Rs though, easier to find

**Comment by pawamoy** [comment]
Thanks!

> workers set the number of processes not threads, just to be clear

Oh yes, I used "thread-safe" because I'm not sure there's a "process-safe" term? 😅 

OK I'll try to send a PR soon 🙂

**Comment by euri10** [comment]
seems like there is :_)

Queues are thread and process safe.


in https://docs.python.org/3/library/multiprocessing.html#exchanging-objects-between-processes


On Thu, Jan 21, 2021 at 3:06 PM Timothée Mazzucotelli
<notifications@github.com> wrote:
>
> Thanks!
>
> workers set the number of processes not threads, just to be clear
>
> Oh yes, I used "thread-safe" because I'm not sure there's a "process-safe" term?
>
> OK I'll try to send a PR soon
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
benoit barthelet
http://pgp.mit.edu/pks/lookup?op=get&search=0xF150E01A72F6D2EE
