### ISSUE TITLE
uvicorn.error logs supressed when using custom log config

### ISSUE THREAD

**Issue by mvolfik** [Kludex/uvicorn#944]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet. -- There are some old, dead and I'm not sure how much related are they

### Describe the bug

When you use `--log-config config_file` (I tested both JSON and YAML), no logs from `uvicorn.error` are ever shown (on any level - errors, startup info, anything). This is likely caused by not inheriting settings from the `root` "logger" (not `logger.root` config, but the top-level `root` key).

It can be fixed by manually setting `loggers:uvicorn.error:propagate` to `true`, or by specifying the handlers for this logger. However, in the second case, all logs from this logger show twice.

### To reproduce

`log-config.yaml`:

```yaml
version: 1

formatters:
  console:
    format: "%(levelname)s\t%(name)s\t%(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stderr
    level: 0

root:
  handlers: [ console ]
  level: 0
```

`app.py`:

```python
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route
import logging

logger = logging.getLogger(__name__)


async def test(request):
    logger.debug("debug test")
    logger.error("log error test")
    return PlainTextResponse("passed")


app = Starlette(routes=[Route("/", test)])
```
`pip install uvicorn[standard]==0.13.3 starlette==0.14.1`
`uvicorn app:app --log-config log-config.yaml`

### Expected behavior

Standard logs appear, like this:

```
INFO	uvicorn.error	Started server process [111942]
INFO	uvicorn.error	Waiting for application startup.
TRACE	uvicorn.asgi	ASGI [1] Started scope={'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}}
TRACE	uvicorn.asgi	ASGI [1] Receive {'type': 'lifespan.startup'}
TRACE	uvicorn.asgi	ASGI [1] Send {'type': 'lifespan.startup.complete'}
INFO	uvicorn.error	Application startup complete.
INFO	uvicorn.error	Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
TRACE	uvicorn.error	127.0.0.1:59012 - Connection made
TRACE	uvicorn.asgi	127.0.0.1:59012 - ASGI [2] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'client': ('127.0.0.1', 59012), 'scheme': 'http', 'method': 'GET', 'root_path': '', 'path': '/', 'raw_path': b'/', 'query_string': b'', 'headers': '<...>'}
DEBUG	app	debug test
ERROR	app	log error test
TRACE	uvicorn.asgi	127.0.0.1:59012 - ASGI [2] Send {'type': 'http.response.start', 'status': 200, 'headers': '<...>'}
INFO	uvicorn.access	127.0.0.1:59012 - "GET / HTTP/1.1" 200
TRACE	uvicorn.asgi	127.0.0.1:59012 - ASGI [2] Send {'type': 'http.response.body', 'body': '<6 bytes>'}
TRACE	uvicorn.asgi	127.0.0.1:59012 - ASGI [2] Completed
```

This can be achieved by adding the following at the end of the `log-config.yaml` file:

```yaml
loggers:
  uvicorn.error:
    propagate: true
```

If this is desired behavior, it should be 100% noted in docs!

### Actual behavior

Only ASGI TRACE messages and logs from my application appear:

```
TRACE	uvicorn.asgi	ASGI [1] Started scope={'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}}
TRACE	uvicorn.asgi	ASGI [1] Receive {'type': 'lifespan.startup'}
TRACE	uvicorn.asgi	ASGI [1] Send {'type': 'lifespan.startup.complete'}
TRACE	uvicorn.asgi	127.0.0.1:59102 - ASGI [2] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'client': ('127.0.0.1', 59102), 'scheme': 'http', 'method': 'GET', 'root_path': '', 'path': '/', 'raw_path': b'/', 'query_string': b'', 'headers': '<...>'}
DEBUG	app	debug test
ERROR	app	log error test
TRACE	uvicorn.asgi	127.0.0.1:59102 - ASGI [2] Send {'type': 'http.response.start', 'status': 200, 'headers': '<...>'}
INFO	uvicorn.access	127.0.0.1:59102 - "GET / HTTP/1.1" 200
TRACE	uvicorn.asgi	127.0.0.1:59102 - ASGI [2] Send {'type': 'http.response.body', 'body': '<6 bytes>'}
TRACE	uvicorn.asgi	127.0.0.1:59102 - ASGI [2] Completed
```

### Environment

Running uvicorn 0.13.3 with CPython 3.8.5 on Linux

#### Why is this important

The `uvicorn.error` messages are not only the informational ones about server startup, but also errors that happen when server (the starlette in my case) startup fails. Modify `app.py` like this:

```python
async def fail_startup():
    return 3/0
app = Starlette(routes=[Route("/", test)], on_startup=[fail_startup])
```

The Startup error appears only in the TRACE (logging level 5; DEBUG is 10!!) message.

#### Related (?) issues and PRs

#934 could be related?
#644 could be related?

There's quite a lot of issues and PRs related to logging config, but I don't have much insight into how it works in uvicorn and my efforts lead nowhere. Sorry if I'm duplicating something.

I tried bisecting, but this seems to be present since `yaml` config was allowed. Interestingly enough, the issue doesn't happen in current version when I transcribe the exact same settings into `setup.cfg`, so it's probably related to how the configuration is loaded.

**Comment by euri10** [comment]
you logging config is missing `disable_existing_loggers: False`

**Comment by mvolfik** [comment]
Ahh, thanks, sorry. This is a pretty important setting hidden the Python docs. Could you maybe mention this in the docs for the `--log-config` option?
