### ISSUE TITLE
uvicorn.run with debug=True results in multiprocessing RuntimeError

### ISSUE THREAD

**Issue by echap1** [Kludex/uvicorn#949]
When trying to call `uvicorn.run` with `debug=True`, I get a runtime error.

```  
File "/usr/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
INFO:     Stopping reloader process [12137]

Process finished with exit code 0
```

Code used to run:
```python
uvicorn.run(
    "backend.app:app",
    host="127.0.0.1",
    port=8000,
    debug=True,
)
```

When `debug=True` is not passed, the app runs normally.

**Comment by euri10** [comment]
Can you fill the template with all the info asked and give us more insight about the code you're running, there's not much we can do here with what's presented.

**Comment by gitgithan** [comment]
Not sure if my suggestion helps. 
I had an analogous problem with adding reload=True.

The solution that worked for me is to wrap the unicorn.run code inside `def main():`, then add 
```
if __name__ == "__main__":
    main()
```
This RuntimeError seems not specific to uvicorn, but general to all multiprocessing in Windows. 
https://docs.python.org/2/library/multiprocessing.html#windows

**Comment by raccoon641** [comment]
> When trying to call `uvicorn.run` with `debug=True`, I get a runtime error.
> 
> ```
> File "/usr/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
>     raise RuntimeError('''
> RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> INFO:     Stopping reloader process [12137]
> 
> Process finished with exit code 0
> ```
> 
> Code used to run:
> 
> ```python
> uvicorn.run(
>     "backend.app:app",
>     host="127.0.0.1",
>     port=8000,
>     debug=True,
> )
> ```
> 
> When `debug=True` is not passed, the app runs normally.

ye wala nahi chal rha
