### ISSUE TITLE
Difficulty in understanding Uvicorn logs

### ISSUE THREAD

**Issue by gautamsinghania95** [Kludex/uvicorn#950]
I am facing an issue in Uvicorn where a background process is crashing the whole application intermittently. I want to understand the logs thrown by Uvicorn, as I am not able to reproduce this issue reliably.

Logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 184, in main_loop
    should_exit = await self.on_tick(counter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runner.py", line 8, in <module>
    uvicorn.run(
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    await self.main_loop()
RuntimeError: coroutine raised StopIteration
```

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`: `Running uvicorn 0.13.3 with CPython 3.8.5 on Linux`
- The exact command you're running uvicorn with, all flags you passed included: Programatically running Uvicorn, 
```py
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=4000,
        http="h11",
        # Maintaining logging at application instead of uvicorn
        access_log=False,
        log_config=None
    )
```

### Additional context
* Application is using FastAPI, see http://fastapi.tiangolo.com/
* Started noticing this when I upgraded Couchbase SDK 3.0.8
* Have seen this site while debugging this issue: https://www.gitmemory.com/issue/coleifer/python-lsm-db/20/758081515
* My application starts a background scheduler before starting the Uvicorn application. See https://apscheduler.readthedocs.io/en/stable/

**Comment by gautamsinghania95** [comment]
Hey, I am actively tracking this request. Pinging so that it does not get auto closed by the bot.

**Comment by euri10** [comment]
there is not closing bot
without seeing the relevant code it's hard to guess what is happening, we'd need more info

**Comment by gautamsinghania95** [comment]
I am facing this issue in an enterprise code, and as I said before I was not able to reproduce this issue in an example. I was more looking into some insights of the logs, so I could understand the error better. See if you can help me out in this, like for example what is happening in the logs.

**Comment by euri10** [comment]
the error log you'r seeing makes no sense to me, without seeing what's going on there's no chance I'll be able to help.

**Comment by gautamsinghania95** [comment]
ok, let me see if i can provide more details or make this issue reproducible. closing this ticket for now.
