### ISSUE TITLE
BUG: Uvicorn not detecting file changes in Apple Silicon M1 Chip

### ISSUE THREAD

**Issue by merrcury** [Kludex/uvicorn#955]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug
Unicorn is not detecting file changes in my python code on my M1 mac. I had to restart the server again and again. 

### To reproduce
1. Make a demo FastAPI code on M1 Machine. 
2. Run it through uvicorn. 
3.  Make some change in the code while the server is running. 

### Expected behavior

It should detect change as it does on Intel x86 processors. 

### Actual behavior

It wasn’t able to detect the change on apple arm64 chip. 

### Debugging material

Nothing as such. 

### Environment

- OS / Python / Uvicorn version: Running uvicorn 0.13.3 with CPython 3.8.2 on Darwin
- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce : `uvicorn qentry.main:app --host=0.0.0.0 --port=8080`

**Comment by euri10** [comment]
you dont use the `--reload` flag ?

**Comment by merrcury** [comment]
Not working every time though. I have tried in main of python code as well. 
IDE = PyCharm

**Comment by merrcury** [comment]
> you dont use the `--reload` flag ?

Not on my intel machine

**Comment by euri10** [comment]
the reload flag is what tells uvicorn to reload, if you dont use it as the command you pasted above suggests there nothing we can do !
