### ISSUE TITLE
StreamingResponse with a set content-length header

### ISSUE THREAD

**Issue by thenewguy** [Kludex/uvicorn#956]
I am swapping a Django project that runs with wsgi using gunicorn process workers to asgi.

One view that fails to serve through the `uvicorn.workers.UvicornWorker` worker is returning a StreamingResponse with a known Content-Length.  I.e. the view sets `response["Content-Length"] = size`. The rest of the test suite is passing

Tests pass with the default gunicorn worker in wsgi mode.  When swapped to `uvicorn.workers.UvicornWorker` in ASGI curl fails with exit code 18.

[This is the summary of curl exit code 18](https://everything.curl.dev/usingcurl/returns):

> Partial file. Only a part of the file was transferred. When the transfer is considered complete, curl will verify that it actually received the same amount of data that it was told before-hand that it was going to get. If the two numbers do not match, this is the error code. It could mean that curl got fewer bytes than advertised or that it got more. curl itself cannot know which number that is wrong or which is correct. If any.

I am not getting any useful logs so not sure how to provide better information at this time.  I observed the same issue attempting to browse with Chrome - but there isn't any helpful error output here either.

**Comment by euri10** [comment]
2 things: 

1. is it an issue with gunicorn/uvicorn worker only or it's that same when using bare uvicorn ?
2. it's going to be difficult with no example, you got tests, why dont you try trim down the one that fails to give us a mrc ?

**Comment by thenewguy** [comment]
Ok - I will close for now and re-open if I can provide something more actionable

**Comment by thenewguy** [comment]
After further digging I believe this will turn out to be unrelated to uvicorn and more of an issue with the view being incompatible with ASGI under the hood at the moment

**Comment by euri10** [comment]
Dont hesitate to reopen if anything changes !
