### ISSUE TITLE
Add `--workers` flag

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#96]
Support multi-process from the cli, not just from running with gunicorn

**Comment by lovelydinosaur** [comment]
On reflection... https://github.com/encode/uvicorn/pull/141

Let's not have `--workers`.
Instead use `gunicorn` or another process manager in production.

**Comment by alimcmaster** [comment]
Did you end up removing --workers @tomchristie docs still seem to mention it. I'm happy to submit a PR myself to fix :)

https://www.uvicorn.org/deployment/

**Comment by lovelydinosaur** [comment]
It's been re-introduced now. More cleanly this time.

**Comment by alimcmaster** [comment]
Interestingly when increasing workers to 2 -> line 60 in reduction.py in multiprocessing seems to throw:

```
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'request_response.<locals>.app'
```

Let me attempt to provide a minimal repo/raise an issue

**Comment by lovelydinosaur** [comment]
Okay, windows, linux or mac?
Running programmatically or from the command line?

There's some limitations to how we can use Python's multiprocessing - will just need to trash these out carefully.
