### ISSUE TITLE
Constant CPU load when being idle (--reload might be the issue here)

### ISSUE THREAD

**Issue by srkunze** [Kludex/uvicorn#960]
#338 already refers to it, and my observation is with `--reload` the fans of my laptop are always up which gets on my nerves little bit. Besides from the that the reloading works decently.

It's roughly 25% constant load (similar to what https://github.com/encode/uvicorn/issues/338#issuecomment-642298366 says):

![image](https://user-images.githubusercontent.com/1389648/108594088-1f1a0200-7378-11eb-9e69-62352ca9c3e8.png)

Django runserver uses `StatReloader` to reload when code changes happen without any CPU load when being idle.

Do you think it would be possible to use `StatReloader` in uvicorn?

**Comment by euri10** [comment]
I havent looked closely at Django StatReloader mechanism for quite a long time but iirc ours is just a clone.

You can try using the other reloader watchgod.
You can also increase `reload_delay` or even restrict you watched files with `reload_dirs` if the cwd is large enough

**Comment by guettli** [comment]
1: Try installing `watchgod` (yes "god", not "dog")
2: Typos in `--reload-dir` are silently ignored up to now: https://github.com/encode/uvicorn/issues/969

**Comment by asdfMaciej** [comment]
I've been able to reproduce this `--reload` issue on Docker for Windows - both with and without Watchgod installed. Constant CPU idle load and a memory leak.

```
uvicorn app.main:app --reload --reload-dir=/app/ --host 0.0.0.0 --port 8000
uvicorn==0.29.0
```

This issue appears to be related: https://github.com/docker/for-win/issues/13745
