### ISSUE TITLE
Modify watchgod ignored_file_regexes to exlude emacs lock file

### ISSUE THREAD

**Issue by n-arakawa** [Kludex/uvicorn#963]
### Checklist

- [ X ] The bug is reproducible against the latest release and/or `master`.
- [ X ] There are no similar issues or pull requests to fix it yet.

### To reproduce
When emacs editor generates lock file  like .#test.py', 

### Expected behavior

Just ignore .#* files!

### Actual behavior

The uvicon generates the following error repeatedly
```shell
error walking file system: FileNotFoundError [Errno 2] No such file or directory:  '/dir/.#test.py'
```

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
Running uvicorn 0.13.3 with CPython 3.8.5 on Linux

### Additional context

`uvicorn/supervisors/watchgodreload.py`

```python
class CustomWatcher(DefaultWatcher):
    ignore_dotted_file_regex = r"^\/?(?:\w+\/)*(\.\w+)"
    ignored = []
````
How about  `ignore_dotted_file_regex = r"^\/?(?:\w+\/)*(\.[\#\w]+)"`

**Comment by euri10** [comment]
Latest uvicorn relaxed watchgod and I think it was fixed there,
https://github.com/samuelcolvin/watchgod/issues/71
Can you upgrade and tell us if that's ok?

**Comment by n-arakawa** [comment]
Thanks.
It's fine with watchgod V0.7(Released: Jan 31, 2021)
