### ISSUE TITLE
typo in `--reload-dir` is passed silently (watchgod)

### ISSUE THREAD

**Issue by guettli** [Kludex/uvicorn#969]
### Describe the bug
if I supply a directory to `--reload-dir` which does not exist, the server starts.

```
./bin/uvicorn --host localhost --port 8000 --reload  --reload-dir asdfasfsrc foo.asgi:application
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [123571] using watchgod
INFO:     Started server process [123573]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```
```
./bin/uvicorn  --version
Running uvicorn 0.13.4 with CPython 3.8.5 on Linux
```

### Expected behavior

I want the server to not start, if the reload-dir does not exist.

### Actual behavior

The server starts.

**Comment by euri10** [comment]
Why is it an issue for you ? iirc we don't add that unexisting directory to watched ones so there's no perf penalty or stuff that is looked at unnecessarily.

**Comment by max-l** [comment]
@euri10 not starting with an error message gives a better user (developer) experience !
