### ISSUE TITLE
improve user experience by complaining when reload_dirs is given a string instead of a list

### ISSUE THREAD

**Issue by max-l** [Kludex/uvicorn#976]
Passing a string to reload_dirs as in the following, causes reload to silently not work :

```
    uvicorn.run(
        "dp.server:app",
        host="127.0.0.1", port=5000,
        log_level="info",
        reload=True,
        reload_dirs="/home/maxou/dev/proj",
        reload_delay=2.0
    )
```

Giving reload_dirs an array : ["/home/maxou/dev/proj"]  fixes the problem

It's not really a bug, but complaining with an error message would improve the user experience.

**Comment by euri10** [comment]
definitely something that could be improved and that would have been detected by mypy I think.
