### ISSUE TITLE
Add `--reload` flag

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#98]
Auto-reloading when code changes

**Comment by lovelydinosaur** [comment]
We now have auto-reloading when `--debug` is used.

**Comment by abhyudayasrinet** [comment]
How can I force an auto-reload if I make code changes are deployed in production?
I'm currently setting up an API endpoint using fastapi and deploying it with uvicorn + nginx

**Comment by euri10** [comment]
You can't,
The reload mode is more intended to be used in development.

**Comment by abhyudayasrinet** [comment]
@euri10 how could one automate a deployment for such a case then?

**Comment by euri10** [comment]
I would subscribe to https://github.com/encode/uvicorn/pull/853

If this lands then we may add another signal, SIGUSR1 comes to mind, for
the restart method of MultiProcess that could be triggered with a kill -1
pid

**Comment by abhyudayasrinet** [comment]
Thanks, will watch it. Meanwhile, I guess I will have to go with restarting the gunicorn service when code deployments are triggered.
